/* =========================================================
   CHAPTER 12 · LIMITS AND DERIVATIVES — every exercise question as a sim
   Every derivative question carries f and the answer df; the test page checks df against a numeric derivative of f.
   Questions with letters (a, b, c, …) are graphed with a = 2, b = 3, c = 1, d = 4, p = 1, q = 2, r = 3, s = 4, m = 2, n = 3.
   ========================================================= */
const K12 = { a: 2, b: 3, c: 1, d: 4, p: 1, q: 2, r: 3, s: 4, m: 2, n: 3 };
const PI = Math.PI;
/* limit question: optional working steps, then the value; the stage slides points into x = a */
function limQ(n, q, f, a, L, o = {}) {
  const v = o.view || [a - 2.5, a + 2.5];
  return { ex: 'Ex 12.1', n, q, scene: 'calc', kim: o.kim, f, a0: a, L,
    setup: (W) => { calcView(W, f, v[0], v[1], { y: o.y }); if (o.hole !== false && isFinite(L) && !isFinite(f(a))) W.holes.push([a, L]); if (o.cap) W.pl.caption = o.cap; if (o.setup) o.setup(W); },
    parts: [...(o.steps || []), o.mcq ? { k: 'mcq', q: o.mq || 'The limit is', o: o.mcq, a: 0, x: o.x, act: async () => approach(W, a) } : { k: 'num', q: o.nq || 'Limit = ?', a: L, show: o.show, keys: o.keys, tol: o.tol, x: o.x || (o.show || fmtN(L, 4)) + '.', act: async () => approach(W, a) }, ...(o.after || [])],
    w: [o.w || 'Limit = ' + (o.show || fmtN(L, 4))] };
}
/* derivative question: pick the formula, then read the tangent slope at x0 and type it */
function dQ(ex, n, q, f, df, opts, x0, o = {}) {
  const v = o.view || [x0 - 2.5, x0 + 2.5];
  return { ex, n, q, scene: 'calc', kim: o.kim, f, df,
    setup: (W) => { calcView(W, f, v[0], v[1], { y: o.y }); W.a = v[0] + (v[1] - v[0]) * 0.2; W.tan = true; W.read = true; grabCalc(W); if (o.cap) W.pl.caption = o.cap; },
    parts: [...(o.steps || []), { k: 'mcq', q: o.mq || "f′(x) = ?", o: opts, a: 0, x: o.x || opts[0] + '.' }, { k: 'task', q: 'Drag P to x = ' + fmtN(x0, 3) + ' and read the tangent slope', todo: 'The green dashed line is the tangent.', check: (W) => Math.abs(W.a - x0) < 0.026, auto: (W) => (W.a = x0), reveal: (W) => (W.a = x0) }, { k: 'num', q: "f′(" + fmtN(x0, 3) + ") = ? (2 decimals are enough)", a: df(x0), tol: Math.max(0.011, Math.abs(df(x0)) * 0.002), show: fmtN(df(x0), 3), x: 'From the formula: ' + fmtN(df(x0), 4) + '.' }],
    w: [o.w || "f′(x) = " + opts[0]] };
}
const prfP = (s) => ({ k: 'order', q: 'Order the first-principle steps', s });

/* ===================== EXERCISE 12.1 ===================== */
const EX121 = [
  limQ('Q1', 'lim (x→3) (x + 3)', (x) => x + 3, 3, 6),
  limQ('Q2', 'lim (x→π) (x − 22/7)', (x) => x - 22 / 7, PI, PI - 22 / 7, { show: 'π − 22/7', keys: 'π', tol: 1e-4, x: 'π − 22/7 ≈ −0.00126.' }),
  limQ('Q3', 'lim (r→1) πr²', (x) => PI * x * x, 1, PI, { show: 'π', keys: 'π', tol: 1e-3 }),
  limQ('Q4', 'lim (x→4) (4x + 3)/(x − 2)', (x) => (4 * x + 3) / (x - 2), 4, 19 / 2, { show: '19/2', view: [2.5, 6.5] }),
  limQ('Q5', 'lim (x→−1) (x¹⁰ + x⁵ + 1)/(x − 1)', (x) => (x ** 10 + x ** 5 + 1) / (x - 1), -1, -1 / 2, { show: '−1/2', view: [-2, 0.5], y: [-3, 1] }),
  limQ('Q6', 'lim (x→0) [(x + 1)⁵ − 1]/x', (x) => ((x + 1) ** 5 - 1) / x, 0, 5, { steps: [{ k: 'mcq', q: 'Put y = x + 1: this is (y⁵ − 1⁵)/(y − 1) as y → 1, which is', o: ['5 · 1⁴', '1⁵', '0/0 forever', '5 · 1⁵⁻²'], a: 0 }], y: [0, 12], view: [-1.5, 1] }),
  limQ('Q7', 'lim (x→2) (3x² − x − 10)/(x² − 4)', (x) => (3 * x * x - x - 10) / (x * x - 4), 2, 11 / 4, { show: '11/4', steps: [{ k: 'mcq', q: 'Factor and cancel (x − 2):', o: ['(3x + 5)/(x + 2)', '(3x − 5)/(x + 2)', '(3x + 5)/(x − 2)', '3'], a: 0 }], y: [0, 5] }),
  limQ('Q8', 'lim (x→3) (x⁴ − 81)/(2x² − 5x − 3)', (x) => (x ** 4 - 81) / (2 * x * x - 5 * x - 3), 3, 108 / 7, { show: '108/7', steps: [{ k: 'mcq', q: 'After cancelling (x − 3):', o: ['(x + 3)(x² + 9)/(2x + 1)', '(x + 3)/(2x + 1)', '(x² + 9)/(2x − 1)', 'x³/(2x + 1)'], a: 0 }], y: [5, 25], view: [1.5, 4.5] }),
  limQ('Q9', 'lim (x→0) (ax + b)/(cx + 1)', (x) => (2 * x + 3) / (x + 1), 0, 3, { mcq: ['b', 'a', 'a/c', 'b/c'], cap: 'graph with a = 2, b = 3, c = 1', w: 'Limit = b', view: [-0.8, 2] }),
  limQ('Q10', 'lim (z→1) (z^⅓ − 1)/(z^⅙ − 1)', (x) => (Math.cbrt(x) - 1) / (x ** (1 / 6) - 1), 1, 2, { steps: [{ k: 'mcq', q: 'Divide top and bottom by (z − 1): (⅓)·1^(−⅔) ÷ (⅙)·1^(−⅚)', o: ['(1/3)/(1/6)', '(1/6)/(1/3)', '1/3', '1/6'], a: 0 }], view: [0.05, 3], y: [1, 3] }),
  limQ('Q11', 'lim (x→1) (ax² + bx + c)/(cx² + bx + a), a + b + c ≠ 0', (x) => (2 * x * x + 3 * x + 1) / (x * x + 3 * x + 2), 1, 1, { cap: 'graph with a = 2, b = 3, c = 1', x: '(a + b + c)/(c + b + a) = 1.', view: [-0.5, 3] }),
  limQ('Q12', 'lim (x→−2) (1/x + 1/2)/(x + 2)', (x) => (1 / x + 0.5) / (x + 2), -2, -1 / 4, { show: '−1/4', steps: [{ k: 'mcq', q: '(1/x + 1/2) = (x + 2)/(2x), so the expression becomes', o: ['1/(2x)', '2x', '(x + 2)/2', '1/x'], a: 0 }], view: [-4, -0.6], y: [-1, 0.2] }),
  limQ('Q13', 'lim (x→0) sin ax / bx', (x) => Math.sin(2 * x) / (3 * x), 0, 2 / 3, { mcq: ['a/b', 'b/a', '1', 'ab'], cap: 'graph with a = 2, b = 3', x: '(sin ax/ax)·(a/b) → a/b.', w: 'Limit = a/b', view: [-2, 2], y: [-0.4, 1] }),
  limQ('Q14', 'lim (x→0) sin ax / sin bx, a, b ≠ 0', (x) => Math.sin(2 * x) / Math.sin(3 * x), 0, 2 / 3, { mcq: ['a/b', 'b/a', '1', '0'], cap: 'graph with a = 2, b = 3', w: 'Limit = a/b', view: [-0.9, 0.9], y: [-1, 2] }),
  limQ('Q15', 'lim (x→π) sin(π − x)/[π(π − x)]', (x) => Math.sin(PI - x) / (PI * (PI - x)), PI, 1 / PI, { show: '1/π', keys: 'π', tol: 1e-3, x: 'Put y = π − x → 0: (1/π)(sin y / y) → 1/π.', y: [-0.1, 0.4] }),
  limQ('Q16', 'lim (x→0) cos x/(π − x)', (x) => Math.cos(x) / (PI - x), 0, 1 / PI, { show: '1/π', keys: 'π', tol: 1e-3, x: 'Just plug in: 1/π.', y: [-0.2, 0.6] }),
  limQ('Q17', 'lim (x→0) (cos 2x − 1)/(cos x − 1)', (x) => (Math.cos(2 * x) - 1) / (Math.cos(x) - 1), 0, 4, { steps: [{ k: 'mcq', q: 'Use 1 − cos θ = 2 sin²(θ/2):', o: ['sin² x / sin²(x/2)', 'sin x / sin(x/2)', 'cos² x', '2 sin x'], a: 0 }], x: '≈ x²/(x²/4) = 4.', y: [0, 5] }),
  limQ('Q18', 'lim (x→0) (ax + x cos x)/(b sin x)', (x) => (2 * x + x * Math.cos(x)) / (3 * Math.sin(x)), 0, 1, { mcq: ['(a + 1)/b', 'a/b', '(a − 1)/b', '1/b'], cap: 'graph with a = 2, b = 3', x: '(x/sin x)·(a + cos x)/b → (a + 1)/b.', w: 'Limit = (a + 1)/b', y: [0, 2] }),
  limQ('Q19', 'lim (x→0) x sec x', (x) => x / Math.cos(x), 0, 0, { view: [-1.2, 1.2] }),
  limQ('Q20', 'lim (x→0) (sin ax + bx)/(ax + sin bx), a, b, a + b ≠ 0', (x) => (Math.sin(2 * x) + 3 * x) / (2 * x + Math.sin(3 * x)), 0, 1, { cap: 'graph with a = 2, b = 3', x: 'Divide by x: (a + b)/(a + b) = 1.', view: [-1, 1], y: [0, 2] }),
  limQ('Q21', 'lim (x→0) (cosec x − cot x)', (x) => 1 / Math.sin(x) - Math.cos(x) / Math.sin(x), 0, 0, { x: '(1 − cos x)/sin x = tan(x/2) → 0.', view: [-2, 2] }),
  limQ('Q22', 'lim (x→π/2) tan 2x / (x − π/2)', (x) => Math.tan(2 * x) / (x - PI / 2), PI / 2, 2, { x: 'y = x − π/2: tan(2y + π)/y = tan 2y / y → 2.', view: [PI / 2 - 0.7, PI / 2 + 0.7], y: [0, 4] }),
  limQ('Q23', 'f(x) = 2x + 3 (x ≤ 0), 3(x + 1) (x > 0). Find lim at x → 0 and x → 1.', (x) => (x <= 0 ? 2 * x + 3 : 3 * (x + 1)), 1, 6, { hole: false, view: [-2, 2.5], steps: [{ k: 'fields', q: 'At 0', f: [{ l: 'LHL', a: 3 }, { l: 'RHL', a: 3 }], x: 'Both 3, so lim (x→0) f(x) = 3.', act: async () => approach(W, 0) }], nq: 'lim (x→1) f(x) = ?', x: '3(1 + 1) = 6.', w: 'lim (x→0) = 3, lim (x→1) = 6' }),
  limQ('Q24', 'f(x) = x² − 1 (x ≤ 1), −x² − 1 (x > 1). Find lim (x→1) f(x).', (x) => (x <= 1 ? x * x - 1 : -x * x - 1), 1, NaN, { hole: false, setup: (W) => W.holes.push([1, -2]), steps: [{ k: 'fields', q: 'One-sided limits', f: [{ l: 'LHL', a: 0 }, { l: 'RHL', a: -2 }] }], mcq: ['does not exist', '0', '−2', '−1'], x: '0 ≠ −2.', w: 'LHL = 0, RHL = −2: no limit' }),
  limQ('Q25', 'f(x) = |x|/x (x ≠ 0), 0 (x = 0). Evaluate lim (x→0) f(x).', (x) => (x === 0 ? 0 : Math.abs(x) / x), 0, NaN, { hole: false, setup: (W) => { W.holes.push([0, 1], [0, -1]); W.dotsF.push([0, 0]); }, steps: [{ k: 'fields', q: 'One-sided limits', f: [{ l: 'LHL', a: -1 }, { l: 'RHL', a: 1 }] }], mcq: ['does not exist', '0', '1', '−1'], y: [-2, 2], w: 'LHL = −1, RHL = 1: no limit' }),
  limQ('Q26', 'f(x) = x/|x| (x ≠ 0), 0 (x = 0). Find lim (x→0) f(x).', (x) => (x === 0 ? 0 : x / Math.abs(x)), 0, NaN, { hole: false, setup: (W) => { W.holes.push([0, 1], [0, -1]); W.dotsF.push([0, 0]); }, steps: [{ k: 'fields', q: 'One-sided limits', f: [{ l: 'LHL', a: -1 }, { l: 'RHL', a: 1 }] }], mcq: ['does not exist', '0', '1', '−1'], y: [-2, 2], w: 'LHL = −1, RHL = 1: no limit' }),
  limQ('Q27', 'f(x) = |x| − 5. Find lim (x→5) f(x).', (x) => Math.abs(x) - 5, 5, 0, { view: [-1, 8] }),
  limQ('Q28', 'f(x) = a + bx (x < 1), 4 (x = 1), b − ax (x > 1), and lim (x→1) f(x) = f(1). Find a and b.', (x) => (x < 1 ? 4 * x : x > 1 ? 4 : 4), 1, 4, { hole: false, cap: 'graph with a = 0, b = 4', steps: [{ k: 'mcq', q: 'The conditions are', o: ['a + b = 4 and b − a = 4', 'a + b = 4 only', 'a = b', 'a − b = 4'], a: 0 }, { k: 'fields', q: 'Solve', f: [{ l: 'a', a: 0 }, { l: 'b', a: 4 }], x: 'a = 0, b = 4.' }], nq: 'Then lim (x→1) f(x) = ?', w: 'a = 0, b = 4', view: [-1, 3] }),
  limQ('Q29', 'f(x) = (x − a₁)(x − a₂)…(x − aₙ). Find lim (x→a₁) f(x) and lim (x→a) f(x) for a ≠ a₁, …, aₙ.', (x) => (x - 1) * (x - 2) * (x - 3), 1, 0, { cap: 'graph with a₁, a₂, a₃ = 1, 2, 3', nq: 'lim (x→a₁) f(x) = ?', after: [{ k: 'mcq', q: 'For a ≠ any aᵢ:', o: ['(a − a₁)(a − a₂)…(a − aₙ)', '0', 'does not exist', 'a₁a₂…aₙ'], a: 0, x: 'A polynomial: just plug in.' }], view: [0, 4], y: [-1, 1], w: '0, and (a − a₁)(a − a₂)…(a − aₙ)' }),
  limQ('Q30', 'f(x) = |x| + 1 (x < 0), 0 (x = 0), |x| − 1 (x > 0). For which a does lim (x→a) f(x) exist?', (x) => (x < 0 ? -x + 1 : x > 0 ? x - 1 : 0), 0, NaN, { hole: false, setup: (W) => { W.holes.push([0, 1], [0, -1]); W.dotsF.push([0, 0]); }, steps: [{ k: 'fields', q: 'At 0', f: [{ l: 'LHL', a: 1 }, { l: 'RHL', a: -1 }] }], mcq: ['every a ≠ 0', 'only a = 0', 'every a', 'no a'], x: 'Away from 0, f is a line on each side.', w: 'Exists for all a ≠ 0' }),
  limQ('Q31', 'If lim (x→1) [f(x) − 2]/(x² − 1) = π, evaluate lim (x→1) f(x).', (x) => 2 + PI * (x * x - 1), 1, 2, { cap: 'one such f: 2 + π(x² − 1)', steps: [{ k: 'mcq', q: 'The denominator → 0 but the ratio stays finite, so the numerator must', o: ['→ 0', '→ π', '→ ∞', '→ 2'], a: 0 }], x: 'lim [f(x) − 2] = π · 0 = 0 ⇒ lim f(x) = 2.', view: [-0.5, 2.5] }),
  limQ('Q32', 'f(x) = mx² + n (x < 0), nx + m (0 ≤ x ≤ 1), nx³ + m (x > 1). For which integers m, n do both lim (x→0) and lim (x→1) exist?', (x) => (x < 0 ? 2 * x * x + 2 : x <= 1 ? 2 * x + 2 : 2 * x ** 3 + 2), 1, 4, { hole: false, cap: 'graph with m = n = 2', steps: [{ k: 'mcq', q: 'At x = 0: LHL = n and RHL = m. The limit exists when', o: ['m = n', 'm = −n', 'always', 'never'], a: 0, act: async () => approach(W, 0) }, { k: 'mcq', q: 'At x = 1: LHL = n + m and RHL = n + m. The limit exists', o: ['for all integers m, n', 'only if m = n', 'only if m = 0', 'never'], a: 0 }], mcq: ['lim at 0 needs m = n; lim at 1 exists for all m, n', 'both need m = n', 'm = n = 0 only', 'never'], mq: 'So, overall', w: 'x → 0: m = n.  x → 1: any integers m, n.', view: [-1.5, 1.8], y: [0, 8] }),
];

/* ===================== EXERCISE 12.2 ===================== */
const EX122 = [
  dQ('Ex 12.2', 'Q1', 'Find the derivative of x² − 2 at x = 10.', (x) => x * x - 2, (x) => 2 * x, ['2x', 'x²', '2x − 2', 'x'], 10, { view: [6, 12], steps: [prfP(['[(10 + h)² − 2 − (100 − 2)]/h', '= (20h + h²)/h', '= 20 + h → 20'])] }),
  dQ('Ex 12.2', 'Q2', 'Find the derivative of x at x = 1.', (x) => x, () => 1, ['1', 'x', '0', '2'], 1),
  dQ('Ex 12.2', 'Q3', 'Find the derivative of 99x at x = 100.', (x) => 99 * x, () => 99, ['99', '99x', '9900', '1'], 100, { view: [98, 102] }),
  dQ('Ex 12.2', 'Q4 (i)', 'From first principles: x³ − 27.', (x) => x ** 3 - 27, (x) => 3 * x * x, ['3x²', 'x²', '3x² − 27', '3x'], 1, { steps: [prfP(['[(x + h)³ − 27 − (x³ − 27)]/h', '= (3x²h + 3xh² + h³)/h', '= 3x² + 3xh + h² → 3x²'])], view: [-2, 3] }),
  dQ('Ex 12.2', 'Q4 (ii)', 'From first principles: (x − 1)(x − 2).', (x) => (x - 1) * (x - 2), (x) => 2 * x - 3, ['2x − 3', '2x + 3', 'x − 3', '(x − 1) + (x − 2) + 1'], 2, { steps: [prfP(['f(x) = x² − 3x + 2', '[f(x + h) − f(x)]/h = (2xh + h² − 3h)/h', '= 2x + h − 3 → 2x − 3'])] }),
  dQ('Ex 12.2', 'Q4 (iii)', 'From first principles: 1/x².', (x) => 1 / (x * x), (x) => -2 / x ** 3, ['−2/x³', '2/x³', '−1/x²', '−2/x²'], 1, { steps: [prfP(['[1/(x + h)² − 1/x²]/h', '= (x² − (x + h)²)/(h x²(x + h)²)', '= −(2x + h)/(x²(x + h)²) → −2/x³'])], view: [0.4, 3] }),
  dQ('Ex 12.2', 'Q4 (iv)', 'From first principles: (x + 1)/(x − 1).', (x) => (x + 1) / (x - 1), (x) => -2 / (x - 1) ** 2, ['−2/(x − 1)²', '2/(x − 1)²', '−2/(x − 1)', '1'], 2, { steps: [prfP(['[(x + h + 1)/(x + h − 1) − (x + 1)/(x − 1)]/h', '= −2h/(h(x − 1)(x + h − 1))', '→ −2/(x − 1)²'])], view: [1.3, 4] }),
  { ex: 'Ex 12.2', n: 'Q5', q: 'For f(x) = x¹⁰⁰/100 + x⁹⁹/99 + … + x²/2 + x + 1, prove f′(1) = 100 f′(0).', scene: 'board', parts: [{ k: 'mcq', q: "f′(x) = ?", o: ['x⁹⁹ + x⁹⁸ + … + x + 1', '100x⁹⁹ + 99x⁹⁸ + … + 1', 'x¹⁰⁰ + … + x', '1 + 2x + … + 100x⁹⁹'], a: 0 }, { k: 'fields', q: 'Evaluate', f: [{ l: "f′(1)", a: 100 }, { l: "f′(0)", a: 1 }], x: '100 = 100 × 1 ✓' }], w: ["f′(1) = 100, f′(0) = 1 ⇒ f′(1) = 100 f′(0)"], f: (x) => { let s = 1; for (let k = 1; k <= 100; k++) s += x ** k / k; return s; }, df: (x) => { let s = 0; for (let k = 0; k <= 99; k++) s += x ** k; return s; } },
  dQ('Ex 12.2', 'Q6', 'Derivative of xⁿ + axⁿ⁻¹ + a²xⁿ⁻² + … + aⁿ⁻¹x + aⁿ (fixed a).', (x) => x ** 3 + 2 * x * x + 4 * x + 8, (x) => 3 * x * x + 4 * x + 4, ['nxⁿ⁻¹ + a(n − 1)xⁿ⁻² + … + aⁿ⁻¹', 'nxⁿ⁻¹ + naxⁿ⁻² + … + naⁿ⁻¹', 'xⁿ⁻¹ + axⁿ⁻² + …', 'nxⁿ⁻¹ + aⁿ'], 1, { cap: 'graph with n = 3, a = 2' }),
  dQ('Ex 12.2', 'Q7 (i)', 'Derivative of (x − a)(x − b).', (x) => (x - 2) * (x - 3), (x) => 2 * x - 5, ['2x − a − b', '2x − ab', 'x − a − b', '2x + a + b'], 1, { cap: 'graph with a = 2, b = 3' }),
  dQ('Ex 12.2', 'Q7 (ii)', 'Derivative of (ax² + b)².', (x) => (2 * x * x + 3) ** 2, (x) => 8 * x * (2 * x * x + 3), ['4ax(ax² + b)', '2(ax² + b)', '2ax(ax² + b)', '4a²x³'], 0.5, { cap: 'graph with a = 2, b = 3', view: [-1.2, 1.2] }),
  dQ('Ex 12.2', 'Q7 (iii)', 'Derivative of (x − a)/(x − b).', (x) => (x - 2) / (x - 3), (x) => (2 - 3) / (x - 3) ** 2, ['(a − b)/(x − b)²', '(b − a)/(x − b)²', '1/(x − b)', '(a − b)/(x − b)'], 1, { cap: 'graph with a = 2, b = 3', view: [-1, 2.7] }),
  dQ('Ex 12.2', 'Q8', 'Derivative of (xⁿ − aⁿ)/(x − a).', (x) => (x ** 3 - 8) / (x - 2), (x) => (3 * x ** 3 - 2 * 3 * x * x - x ** 3 + 8) / (x - 2) ** 2, ['[nxⁿ − anxⁿ⁻¹ − xⁿ + aⁿ]/(x − a)²', 'nxⁿ⁻¹', '[nxⁿ⁻¹ − aⁿ]/(x − a)', 'naⁿ⁻¹'], 1, { cap: 'graph with n = 3, a = 2', view: [-1, 1.8] }),
  dQ('Ex 12.2', 'Q9 (i)', 'Derivative of 2x − 3/4.', (x) => 2 * x - 0.75, () => 2, ['2', '2x', '2 − 3/4', '0'], 1),
  dQ('Ex 12.2', 'Q9 (ii)', 'Derivative of (5x³ + 3x − 1)(x − 1).', (x) => (5 * x ** 3 + 3 * x - 1) * (x - 1), (x) => 20 * x ** 3 - 15 * x * x + 6 * x - 4, ['20x³ − 15x² + 6x − 4', '15x² + 3', '20x³ + 6x − 4', '(15x² + 3)(x − 1)'], 1, { view: [-1, 1.6] }),
  dQ('Ex 12.2', 'Q9 (iii)', 'Derivative of x⁻³(5 + 3x).', (x) => x ** -3 * (5 + 3 * x), (x) => -15 * x ** -4 - 6 * x ** -3, ['x⁻⁴(−15 − 6x)', 'x⁻⁴(15 + 6x)', '−3x⁻⁴ · 3', '−15x⁻⁴'], 1, { view: [0.6, 3] }),
  dQ('Ex 12.2', 'Q9 (iv)', 'Derivative of x⁵(3 − 6x⁻⁹).', (x) => x ** 5 * (3 - 6 * x ** -9), (x) => 15 * x ** 4 + 24 * x ** -5, ['15x⁴ + 24x⁻⁵', '15x⁴ − 24x⁻⁵', '15x⁴ + 54x⁻¹⁰', '5x⁴(3 − 6x⁻⁹)'], 1, { view: [0.7, 1.8] }),
  dQ('Ex 12.2', 'Q9 (v)', 'Derivative of x⁻⁴(3 − 4x⁻⁵).', (x) => x ** -4 * (3 - 4 * x ** -5), (x) => -12 * x ** -5 + 36 * x ** -10, ['−12x⁻⁵ + 36x⁻¹⁰', '12x⁻⁵ − 36x⁻¹⁰', '−12x⁻⁵ + 20x⁻¹⁰', '−4x⁻⁵(3 − 4x⁻⁵)'], 1, { view: [0.8, 2.5] }),
  dQ('Ex 12.2', 'Q9 (vi)', 'Derivative of 2/(x + 1) − x²/(3x − 1).', (x) => 2 / (x + 1) - (x * x) / (3 * x - 1), (x) => -2 / (x + 1) ** 2 - (x * (3 * x - 2)) / (3 * x - 1) ** 2, ['−2/(x + 1)² − x(3x − 2)/(3x − 1)²', '2/(x + 1)² − 2x/3', '−2/(x + 1)² + x(3x − 2)/(3x − 1)²', '−2/(x + 1) − 2x/(3x − 1)'], 1, { view: [0.5, 3] }),
  dQ('Ex 12.2', 'Q10', 'Derivative of cos x from first principles.', Math.cos, (x) => -Math.sin(x), ['−sin x', 'sin x', '−cos x', 'cos x'], 1, { steps: [prfP(['[cos(x + h) − cos x]/h', '= [cos x (cos h − 1) − sin x sin h]/h', '= cos x · (cos h − 1)/h − sin x · (sin h)/h', '→ cos x · 0 − sin x · 1 = −sin x'])], view: [-1, 4] }),
  dQ('Ex 12.2', 'Q11 (i)', 'Derivative of sin x cos x.', (x) => Math.sin(x) * Math.cos(x), (x) => Math.cos(2 * x), ['cos 2x', 'sin 2x', 'cos² x', '−sin x cos x'], 1, { view: [-1, 3] }),
  dQ('Ex 12.2', 'Q11 (ii)', 'Derivative of sec x.', (x) => 1 / Math.cos(x), (x) => Math.tan(x) / Math.cos(x), ['sec x tan x', 'sec² x', '−sec x tan x', 'tan x'], 1, { view: [-1.3, 1.3] }),
  dQ('Ex 12.2', 'Q11 (iii)', 'Derivative of 5 sec x + 4 cos x.', (x) => 5 / Math.cos(x) + 4 * Math.cos(x), (x) => (5 * Math.tan(x)) / Math.cos(x) - 4 * Math.sin(x), ['5 sec x tan x − 4 sin x', '5 sec² x − 4 sin x', '5 sec x tan x + 4 sin x', '5 tan x − 4 sin x'], 1, { view: [-1.3, 1.3] }),
  dQ('Ex 12.2', 'Q11 (iv)', 'Derivative of cosec x.', (x) => 1 / Math.sin(x), (x) => -Math.cos(x) / Math.sin(x) ** 2, ['−cosec x cot x', 'cosec x cot x', '−cosec² x', 'cot x'], 1, { view: [0.3, 2.8] }),
  dQ('Ex 12.2', 'Q11 (v)', 'Derivative of 3 cot x + 5 cosec x.', (x) => 3 / Math.tan(x) + 5 / Math.sin(x), (x) => -3 / Math.sin(x) ** 2 - (5 * Math.cos(x)) / Math.sin(x) ** 2, ['−3 cosec² x − 5 cosec x cot x', '3 cosec² x + 5 cosec x cot x', '−3 cosec² x + 5 cosec x cot x', '−3 cot x − 5 cosec x'], 1, { view: [0.4, 2.8] }),
  dQ('Ex 12.2', 'Q11 (vi)', 'Derivative of 5 sin x − 6 cos x + 7.', (x) => 5 * Math.sin(x) - 6 * Math.cos(x) + 7, (x) => 5 * Math.cos(x) + 6 * Math.sin(x), ['5 cos x + 6 sin x', '5 cos x − 6 sin x', '−5 cos x + 6 sin x', '5 cos x + 6 sin x + 7'], 1, { view: [-2, 4] }),
  dQ('Ex 12.2', 'Q11 (vii)', 'Derivative of 2 tan x − 7 sec x.', (x) => 2 * Math.tan(x) - 7 / Math.cos(x), (x) => 2 / Math.cos(x) ** 2 - (7 * Math.tan(x)) / Math.cos(x), ['2 sec² x − 7 sec x tan x', '2 sec² x + 7 sec x tan x', '2 sec x tan x − 7 sec² x', '2 tan² x − 7 sec x'], 1, { view: [-1.3, 1.3] }),
];

/* ===================== MISCELLANEOUS ===================== */
const mq = (n, q, f, df, opts, x0, o = {}) => dQ('Misc', n, q, f, df, opts, x0, Object.assign({ cap: o.cap === undefined ? 'graph with a = 2, b = 3, c = 1, d = 4, p = 1, q = 2, r = 3, s = 4, m = 2, n = 3' : o.cap }, o));
const S = Math.sin, Co = Math.cos, Tn = Math.tan;
const EX12M = [
  mq('Q1 (i)', 'From first principles: −x.', (x) => -x, () => -1, ['−1', '1', '−x', '0'], 1, { cap: null, steps: [prfP(['[−(x + h) − (−x)]/h', '= −h/h', '= −1'])] }),
  mq('Q1 (ii)', 'From first principles: (−x)⁻¹.', (x) => -1 / x, (x) => 1 / (x * x), ['1/x²', '−1/x²', '1/x', '−1/x'], 1, { cap: null, view: [0.4, 3] }),
  mq('Q1 (iii)', 'From first principles: sin(x + 1).', (x) => S(x + 1), (x) => Co(x + 1), ['cos(x + 1)', '−cos(x + 1)', 'sin(x + 1)', 'cos x'], 1, { cap: null }),
  mq('Q1 (iv)', 'From first principles: cos(x − π/8).', (x) => Co(x - PI / 8), (x) => -S(x - PI / 8), ['−sin(x − π/8)', 'sin(x − π/8)', '−cos(x − π/8)', '−sin x'], 1, { cap: null }),
  mq('Q2', 'Derivative of x + a.', (x) => x + 2, () => 1, ['1', 'a', '1 + a', '0'], 1),
  mq('Q3', 'Derivative of (px + q)(r/x + s).', (x) => (x + 2) * (3 / x + 4), (x) => 1 * 4 - (2 * 3) / (x * x), ['ps − qr/x²', 'ps + qr/x²', 'p(r/x + s)', 'pr/x − qr/x²'], 1, { view: [0.4, 3] }),
  mq('Q4', 'Derivative of (ax + b)(cx + d)².', (x) => (2 * x + 3) * (x + 4) ** 2, (x) => (x + 4) * (3 * 2 * 1 * x + 2 * 4 + 2 * 3 * 1), ['(cx + d)(3acx + ad + 2bc)', 'a(cx + d)² + 2c(ax + b)', '2ac(cx + d)', '(cx + d)(acx + 2bc)'], 0, { view: [-5, 1] }),
  mq('Q5', 'Derivative of (ax + b)/(cx + d).', (x) => (2 * x + 3) / (x + 4), (x) => (2 * 4 - 3 * 1) / (x + 4) ** 2, ['(ad − bc)/(cx + d)²', '(bc − ad)/(cx + d)²', 'a/c', '(ad + bc)/(cx + d)²'], 1, { view: [-3, 3] }),
  mq('Q6', 'Derivative of (1 + 1/x)/(1 − 1/x), x ≠ 0, 1.', (x) => (1 + 1 / x) / (1 - 1 / x), (x) => -2 / (x - 1) ** 2, ['−2/(x − 1)²', '2/(x − 1)²', '−2/(x + 1)²', '−1/x²'], 2, { cap: null, view: [1.3, 4] }),
  mq('Q7', 'Derivative of 1/(ax² + bx + c).', (x) => 1 / (2 * x * x + 3 * x + 1), (x) => -(4 * x + 3) / (2 * x * x + 3 * x + 1) ** 2, ['−(2ax + b)/(ax² + bx + c)²', '(2ax + b)/(ax² + bx + c)²', '−1/(ax² + bx + c)²', '−(2ax + b)/(ax² + bx + c)'], 1, { view: [0, 2.5] }),
  mq('Q8', 'Derivative of (ax + b)/(px² + qx + r).', (x) => (2 * x + 3) / (x * x + 2 * x + 3), (x) => (-2 * 1 * x * x - 2 * 3 * 1 * x + 2 * 3 - 3 * 2) / (x * x + 2 * x + 3) ** 2, ['(−apx² − 2bpx + ar − bq)/(px² + qx + r)²', '(apx² + 2bpx + bq − ar)/(px² + qx + r)²', 'a/(2px + q)', '(a − 2px − q)/(px² + qx + r)²'], 1),
  mq('Q9', 'Derivative of (px² + qx + r)/(ax + b).', (x) => (x * x + 2 * x + 3) / (2 * x + 3), (x) => (2 * 1 * x * x + 2 * 3 * 1 * x + 3 * 2 - 2 * 3) / (2 * x + 3) ** 2, ['(apx² + 2bpx + bq − ar)/(ax + b)²', '(−apx² − 2bpx + ar − bq)/(ax + b)²', '(2px + q)/a', '(2px + q)(ax + b) − a'], 1, { view: [-1, 2] }),
  mq('Q10', 'Derivative of a/x⁴ − b/x² + cos x.', (x) => 2 / x ** 4 - 3 / (x * x) + Co(x), (x) => -8 / x ** 5 + 6 / x ** 3 - S(x), ['−4a/x⁵ + 2b/x³ − sin x', '4a/x⁵ − 2b/x³ − sin x', '−4a/x³ + 2b/x − sin x', '−4a/x⁵ − 2b/x³ + sin x'], 1.5, { view: [0.9, 3] }),
  mq('Q11', 'Derivative of 4√x − 2.', (x) => 4 * Math.sqrt(x) - 2, (x) => 2 / Math.sqrt(x), ['2/√x', '4/√x', '2√x', '1/(2√x)'], 1, { cap: null, view: [0.2, 4] }),
  mq('Q12', 'Derivative of (ax + b)ⁿ.', (x) => (2 * x + 3) ** 3, (x) => 3 * 2 * (2 * x + 3) ** 2, ['na(ax + b)ⁿ⁻¹', 'n(ax + b)ⁿ⁻¹', 'a(ax + b)ⁿ', 'na(ax + b)ⁿ'], -1, { view: [-2.5, 0] }),
  mq('Q13', 'Derivative of (ax + b)ⁿ(cx + d)ᵐ.', (x) => (2 * x + 3) ** 3 * (x + 4) ** 2, (x) => (2 * x + 3) ** 2 * (x + 4) * (2 * 1 * (2 * x + 3) + 3 * 2 * (x + 4)), ['(ax + b)ⁿ⁻¹(cx + d)ᵐ⁻¹[mc(ax + b) + na(cx + d)]', 'nm a c (ax + b)ⁿ⁻¹(cx + d)ᵐ⁻¹', '(ax + b)ⁿ⁻¹(cx + d)ᵐ⁻¹[na(ax + b) + mc(cx + d)]', 'na(ax + b)ⁿ⁻¹ + mc(cx + d)ᵐ⁻¹'], -1, { view: [-2.2, 0] }),
  mq('Q14', 'Derivative of sin(x + a).', (x) => S(x + 2), (x) => Co(x + 2), ['cos(x + a)', '−cos(x + a)', 'cos x', 'sin a cos x'], 1),
  mq('Q15', 'Derivative of cosec x cot x.', (x) => Co(x) / S(x) ** 2, (x) => -(1 / S(x)) * (Co(x) ** 2 / S(x) ** 2 + 1 / S(x) ** 2), ['−cosec x (cot² x + cosec² x)', 'cosec x (cot² x + cosec² x)', '−cosec² x cot x', '−cosec³ x'], 1, { cap: null, view: [0.5, 2.6] }),
  mq('Q16', 'Derivative of cos x/(1 + sin x).', (x) => Co(x) / (1 + S(x)), (x) => -1 / (1 + S(x)), ['−1/(1 + sin x)', '1/(1 + sin x)', '−sin x/(1 + sin x)', '−1/(1 + sin x)²'], 1, { cap: null, view: [-1, 3] }),
  mq('Q17', 'Derivative of (sin x + cos x)/(sin x − cos x).', (x) => (S(x) + Co(x)) / (S(x) - Co(x)), (x) => -2 / (S(x) - Co(x)) ** 2, ['−2/(sin x − cos x)²', '2/(sin x − cos x)²', '−1/(sin x − cos x)²', '0'], 1.5, { cap: null, view: [1, 3] }),
  mq('Q18', 'Derivative of (sec x − 1)/(sec x + 1).', (x) => (1 / Co(x) - 1) / (1 / Co(x) + 1), (x) => (2 * Tn(x) / Co(x)) / (1 / Co(x) + 1) ** 2, ['2 sec x tan x/(sec x + 1)²', '−2 sec x tan x/(sec x + 1)²', 'sec x tan x/(sec x + 1)', '2/(sec x + 1)²'], 1, { cap: null, view: [-1.3, 1.3] }),
  mq('Q19', 'Derivative of sinⁿ x.', (x) => S(x) ** 3, (x) => 3 * S(x) ** 2 * Co(x), ['n sinⁿ⁻¹ x cos x', 'n sinⁿ⁻¹ x', 'n cosⁿ⁻¹ x', 'sinⁿ⁻¹ x cos x'], 1, { cap: 'graph with n = 3' }),
  mq('Q20', 'Derivative of (a + b sin x)/(c + d cos x).', (x) => (2 + 3 * S(x)) / (1 + 4 * Co(x)), (x) => (3 * 1 * Co(x) + 2 * 4 * S(x) + 3 * 4) / (1 + 4 * Co(x)) ** 2, ['(bc cos x + ad sin x + bd)/(c + d cos x)²', '(bc cos x − ad sin x + bd)/(c + d cos x)²', 'b cos x/(−d sin x)', '(bc cos x + ad sin x)/(c + d cos x)'], 0.5, { view: [-1, 1.2] }),
  mq('Q21', 'Derivative of sin(x + a)/cos x.', (x) => S(x + 2) / Co(x), (x) => Co(2) / Co(x) ** 2, ['cos a/cos² x', 'sin a/cos² x', 'cos(x + a)/sin x', '−cos a/cos² x'], 0.5, { view: [-1.3, 1.3] }),
  mq('Q22', 'Derivative of x⁴(5 sin x − 3 cos x).', (x) => x ** 4 * (5 * S(x) - 3 * Co(x)), (x) => 4 * x ** 3 * (5 * S(x) - 3 * Co(x)) + x ** 4 * (5 * Co(x) + 3 * S(x)), ['4x³(5 sin x − 3 cos x) + x⁴(5 cos x + 3 sin x)', '4x³(5 cos x + 3 sin x)', '4x³(5 sin x − 3 cos x) + x⁴(5 cos x − 3 sin x)', 'x⁴(5 cos x + 3 sin x)'], 1, { cap: null, view: [-0.5, 2] }),
  mq('Q23', 'Derivative of (x² + 1) cos x.', (x) => (x * x + 1) * Co(x), (x) => 2 * x * Co(x) - (x * x + 1) * S(x), ['2x cos x − (x² + 1) sin x', '2x cos x + (x² + 1) sin x', '−2x sin x', '2x − sin x'], 1, { cap: null }),
  mq('Q24', 'Derivative of (ax² + sin x)(p + q cos x).', (x) => (2 * x * x + S(x)) * (1 + 2 * Co(x)), (x) => (4 * x + Co(x)) * (1 + 2 * Co(x)) - 2 * S(x) * (2 * x * x + S(x)), ['(2ax + cos x)(p + q cos x) − q sin x (ax² + sin x)', '(2ax + cos x)(p + q cos x) + q sin x (ax² + sin x)', '(2ax + cos x)(−q sin x)', '2ax p − q sin x cos x'], 1),
  mq('Q25', 'Derivative of (x + cos x)(x − tan x).', (x) => (x + Co(x)) * (x - Tn(x)), (x) => (1 - S(x)) * (x - Tn(x)) - (x + Co(x)) * Tn(x) ** 2, ['(1 − sin x)(x − tan x) − (x + cos x) tan² x', '(1 − sin x)(x − tan x) + (x + cos x) tan² x', '(1 − sin x)(1 − sec² x)', '(1 + sin x)(x − tan x) − (x + cos x) sec² x'], 0.5, { cap: null, view: [-1.2, 1.2] }),
  mq('Q26', 'Derivative of (4x + 5 sin x)/(3x + 7 cos x).', (x) => (4 * x + 5 * S(x)) / (3 * x + 7 * Co(x)), (x) => (15 * x * Co(x) + 28 * Co(x) + 28 * x * S(x) - 15 * S(x) + 35) / (3 * x + 7 * Co(x)) ** 2, ['(15x cos x + 28 cos x + 28x sin x − 15 sin x + 35)/(3x + 7 cos x)²', '(4 + 5 cos x)/(3 − 7 sin x)', '(15x cos x + 28 cos x − 28x sin x + 15 sin x + 35)/(3x + 7 cos x)²', '(28 cos x + 35)/(3x + 7 cos x)²'], 0.5, { cap: null, view: [-0.5, 1.4] }),
  mq('Q27', 'Derivative of x² cos(π/4)/sin x.', (x) => (x * x * Co(PI / 4)) / S(x), (x) => (Co(PI / 4) * (2 * x * S(x) - x * x * Co(x))) / S(x) ** 2, ['cos(π/4)(2x sin x − x² cos x)/sin² x', 'cos(π/4)(2x sin x + x² cos x)/sin² x', '2x cos(π/4)/cos x', '−sin(π/4) · 2x/sin x'], 1, { cap: null, view: [0.4, 2.6] }),
  mq('Q28', 'Derivative of x/(1 + tan x).', (x) => x / (1 + Tn(x)), (x) => (1 + Tn(x) - x / Co(x) ** 2) / (1 + Tn(x)) ** 2, ['(1 + tan x − x sec² x)/(1 + tan x)²', '(1 + tan x + x sec² x)/(1 + tan x)²', '1/sec² x', '(1 − x sec² x)/(1 + tan x)'], 0.5, { cap: null, view: [-0.6, 1.3] }),
  mq('Q29', 'Derivative of (x + sec x)(x − tan x).', (x) => (x + 1 / Co(x)) * (x - Tn(x)), (x) => (1 + Tn(x) / Co(x)) * (x - Tn(x)) + (x + 1 / Co(x)) * (1 - 1 / Co(x) ** 2), ['(1 + sec x tan x)(x − tan x) + (x + sec x)(1 − sec² x)', '(1 + sec x tan x)(1 − sec² x)', '(1 + sec x tan x)(x − tan x) − (x + sec x)(1 − sec² x)', '(1 + sec² x)(x − tan x)'], 0.5, { cap: null, view: [-1.2, 1.2] }),
  mq('Q30', 'Derivative of x/sinⁿ x.', (x) => x / S(x) ** 3, (x) => (S(x) - 3 * x * Co(x)) / S(x) ** 4, ['(sin x − n x cos x)/sinⁿ⁺¹ x', '(sin x + n x cos x)/sinⁿ⁺¹ x', '1/(n sinⁿ⁻¹ x cos x)', '(1 − n x cos x)/sinⁿ x'], 1, { cap: 'graph with n = 3', view: [0.6, 2.6] }),
];

const BOSS12 = [['lim (x→2) (x² − 4)/(x − 2)', ['4', '0', '2', 'undefined'], 0], ['lim (x→0) sin 5x / x', ['5', '1', '0', '1/5'], 0], ['d/dx x⁷', ['7x⁶', 'x⁶', '7x⁷', '6x⁷'], 0], ['d/dx cos x', ['−sin x', 'sin x', 'cos x', '−cos x'], 0], ['LHL = 2, RHL = 3: the limit', ['does not exist', 'is 2.5', 'is 2', 'is 3'], 0], ['d/dx (uv)', ["u′v + uv′", "u′v′", "u′v − uv′", "uv′"], 0], ['lim (x→1) (x¹⁰ − 1)/(x − 1)', ['10', '1', '0', '9'], 0], ['Slope of y = x² at x = 3', ['6', '9', '3', '2'], 0], ['d/dx tan x', ['sec² x', 'cot x', '−cosec² x', 'sec x tan x'], 0], ['lim (x→0) (1 − cos x)/x', ['0', '1', '1/2', '∞'], 0]];

LESSONS.splice(3, 0, exLesson({ id: 'ex121', title: 'Exercise 12.1', blurb: 'All 32 limits: plug in, factor, sandwich, one-sided.', face: 'kimmy-playful', qs: EX121 }));
LESSONS.splice(6, 0, exLesson({ id: 'ex122', title: 'Exercise 12.2', blurb: 'All 11 (25 parts): first principles and the rules, checked on the graph.', face: 'jess-happy', qs: EX122 }));
LESSONS.push(exLesson({ id: 'misc', title: 'Miscellaneous', blurb: 'All 30 Miscellaneous derivatives, each read off its tangent.', face: 'jess-thinking', qs: EX12M }));
LESSONS.push(lesson({ id: 'boss', title: 'Boss Battle', blurb: 'Ten fast questions. Speed points. Beat Kimmy.', face: 'jess-excited', steps: [async function () { enterScene('board', (W) => { W.tag = 'BOSS'; W.sub = 'Chapter 12'; }); await slam('BOSS BATTLE', '10 questions · speed counts'); await K('play', 'h → 0!'); await cont('Fight'); }, ...BOSS12.map(([q, o, a], i) => async function () { enterScene('board', (W) => { W.tag = 'Q' + (i + 1); W.sub = 'Boss Battle'; }); await quiz(q, o, a, plain(o[a]) + '.', null, 15); await cont(); }), async function () { enterScene('board', (W) => { W.tag = 'K.O.!'; W.sub = 'Chapter 12'; }); await summary(['Chapter 12 complete!', { t: "f′(x) = lim [f(x + h) − f(x)]/h", eq: true }]); }] }));
LESSONS.forEach((l) => { if (l.kind === 'ex') l.short = l.id === 'misc' ? 'M' : l.title.replace('Exercise ', ''); });
