/* =========================================================
   CHAPTER 14 · PROBABILITY — every exercise question as a sim
   Probabilities are computed by counting (nCk) where possible.
   ========================================================= */
const fq = (l, v) => ({ l, a: v, show: FR(v), tol: 1e-6 });
const B14 = (ex, n, q, parts, w, o = {}) => Object.assign({ ex, n, q, scene: 'board', parts, w: [w] }, o);
const SUMS = { A: (a, b) => a % 2 === 0, B: (a, b) => a % 2 === 1, C: (a, b) => a + b <= 5 };

/* ===================== EXERCISE 14.1 ===================== */
const EX141 = [
  B14('Ex 14.1', 'Q1', 'A die is rolled. E: “shows 4”, F: “shows an even number”. Are E and F mutually exclusive?', [{ k: 'pick', q: 'E ∩ F', pool: DIE, a: ['4'] }, { k: 'tf', q: 'Mutually exclusive?', o: ['Yes', 'No'], a: 1, x: 'E ∩ F = {4} ≠ φ.' }], 'No: E ∩ F = {4}'),
  B14('Ex 14.1', 'Q2', 'A die is thrown. A: < 7, B: > 7, C: multiple of 3, D: < 4, E: even and > 4, F: not less than 3. Find A ∪ B, A ∩ B, B ∪ C, E ∩ F, D ∩ E, A − C, D − E, E ∩ F′, F′.', [
    { k: 'pick', q: 'C: a multiple of 3', pool: DIE, a: ['3', '6'] }, { k: 'pick', q: 'F: not less than 3', pool: DIE, a: ['3', '4', '5', '6'] },
    { k: 'match', q: 'Match the event to its set', L: ['A ∪ B', 'A ∩ B', 'B ∪ C', 'E ∩ F'], R: ['{6}', '{3, 6}', 'φ', '{1, 2, 3, 4, 5, 6}'], a: [3, 2, 1, 0] },
    { k: 'pick', q: 'A − C', pool: DIE, a: ['1', '2', '4', '5'] }, { k: 'pick', q: 'D ∩ E (tap nothing if it is φ)', pool: DIE, a: [] }, { k: 'match', q: 'Match', L: ['D − E', 'F′'], R: ['{1, 2}', '{1, 2, 3}'], a: [1, 0] }, { k: 'pick', q: 'E ∩ F′', pool: DIE, a: [] }],
    'A = S, B = φ, C = {3, 6}, D = {1, 2, 3}, E = {6}, F = {3, 4, 5, 6}; A ∪ B = S, A ∩ B = φ, B ∪ C = {3, 6}, E ∩ F = {6}, D ∩ E = φ, A − C = {1, 2, 4, 5}, D − E = {1, 2, 3}, E ∩ F′ = φ, F′ = {1, 2}'),
  { ex: 'Ex 14.1', n: 'Q3', q: 'Two dice. A: sum > 8, B: a 2 on either die, C: sum ≥ 7 and a multiple of 3. Which pairs are mutually exclusive?', scene: 'dice36', parts: [dicePart('Build A: sum greater than 8', (a, b) => a + b > 8), dicePart('Build B: 2 on either die', (a, b) => a === 2 || b === 2), dicePart('Build C: sum ≥ 7 and a multiple of 3', (a, b) => a + b >= 7 && (a + b) % 3 === 0), { k: 'mcq', q: 'Mutually exclusive pairs', o: ['A, B and B, C', 'A, C only', 'A, B only', 'all three pairs'], a: 0, x: 'A die showing 2 caps the sum at 8, so B misses A and C.', act: async () => { W.ev = [ev('A', C['sora-tint'], (a, b) => a + b > 8), ev('B', C.sakura, (a, b) => a === 2 || b === 2), ev('C', C['matcha-tint'], (a, b) => a + b >= 7 && (a + b) % 3 === 0)]; W.sel = new Set(); } }], w: ['A and B, B and C are mutually exclusive; A and C are not'] },
  B14('Ex 14.1', 'Q4', 'Three coins. A: three heads, B: two heads one tail, C: three tails, D: head on the first coin. Which are (i) mutually exclusive (ii) simple (iii) compound?', [{ k: 'pick', q: 'D: head on the first coin', pool: COINS3, a: ['HHH', 'HHT', 'HTH', 'HTT'] }, { k: 'mcq', q: '(i) Mutually exclusive pairs', o: ['A & B, A & C, B & C, C & D', 'A & D only', 'all pairs', 'B & D, C & D'], a: 0, x: 'A ∩ D = {HHH} and B ∩ D ≠ φ.' }, { k: 'mcq', q: '(ii) simple and (iii) compound', o: ['simple: A, C · compound: B, D', 'simple: A · compound: B, C, D', 'simple: B, D · compound: A, C', 'all simple'], a: 0 }], '(i) A & B, A & C, B & C, C & D  (ii) A, C  (iii) B, D'),
  B14('Ex 14.1', 'Q5', 'Three coins: describe events that are (i) mutually exclusive (ii) mutually exclusive and exhaustive (iii) not mutually exclusive (iv) mutually exclusive but not exhaustive (v) three mutually exclusive, not exhaustive.', [{ k: 'tf', q: '(i) “three heads” and “three tails” are mutually exclusive', o: ['True', 'False'], a: 0 }, { k: 'mcq', q: '(ii) Mutually exclusive and exhaustive', o: ['no head, exactly one head, at least two heads', 'three heads, three tails', 'one head, two heads', 'at least one head, at least one tail'], a: 0 }, { k: 'mcq', q: '(iii) Not mutually exclusive', o: ['at least one head, at least one tail', 'three heads, three tails', 'no head, three heads', 'exactly one head, exactly two heads'], a: 0 }, { k: 'mcq', q: '(iv)/(v) Mutually exclusive but not exhaustive', o: ['three heads, three tails (+ exactly two heads)', 'no head, at least one head', 'any event and its complement', 'S and φ'], a: 0, x: 'Many answers are possible; these are examples.' }], 'One possible set of answers (many are correct)'),
  { ex: 'Ex 14.1', n: 'Q6', q: 'Two dice. A: first die even, B: first die odd, C: sum ≤ 5. Describe A′, not B, A or B, A and B, A but not C, B or C, B and C, A ∩ B′ ∩ C′.', scene: 'dice36', parts: [dicePart('Build C: sum ≤ 5', SUMS.C), { k: 'match', q: 'Match', L: ['A′', 'not B', 'A or B', 'A and B'], R: ['S', 'A', 'φ', 'B'], a: [3, 1, 0, 2] }, dicePart('Build “A but not C”', (a, b) => SUMS.A(a, b) && !SUMS.C(a, b)), dicePart('Build “B and C”', (a, b) => SUMS.B(a, b) && SUMS.C(a, b)), { k: 'fields', q: 'Counts', f: [{ l: 'n(B or C)', a: PAIRS.filter(([a, b]) => SUMS.B(a, b) || SUMS.C(a, b)).length }, { l: 'n(A ∩ B′ ∩ C′)', a: PAIRS.filter(([a, b]) => SUMS.A(a, b) && !SUMS.C(a, b)).length }], x: 'A ∩ B′ ∩ C′ = A − C.' }], w: ['A′ = B, not B = A, A or B = S, A and B = φ, A but not C has 14 outcomes, B or C has 22, B and C has 6, A ∩ B′ ∩ C′ = A − C'] },
  B14('Ex 14.1', 'Q7', 'For Q6, true or false: (i) A, B mutually exclusive (ii) A, B mutually exclusive and exhaustive (iii) A = B′ (iv) A, C mutually exclusive (v) A, B′ mutually exclusive (vi) A′, B′, C mutually exclusive and exhaustive.', [{ k: 'tf', q: '(i)', a: true }, { k: 'tf', q: '(ii)', a: true }, { k: 'tf', q: '(iii)', a: true }, { k: 'tf', q: '(iv) A, C mutually exclusive — e.g. (2, 1) is in both', a: false }, { k: 'tf', q: '(v) A, B′ mutually exclusive — B′ = A', a: false }, { k: 'tf', q: '(vi) A′, B′, C mutually exclusive and exhaustive', a: false, x: 'A′ ∩ C ≠ φ, e.g. (1, 1).' }], 'T, T, T, F, F, F'),
];

/* ===================== EXERCISE 14.2 ===================== */
const EX142 = [
  B14('Ex 14.2', 'Q1', 'Which assignments for ω₁, …, ω₇ are NOT valid? (a) 0.1, 0.01, 0.05, 0.03, 0.01, 0.2, 0.6 (b) 1/7 each (c) 0.1, …, 0.7 (d) −0.1, 0.2, 0.3, 0.4, −0.2, 0.1, 0.3 (e) 1/14, 2/14, …, 6/14, 15/14', [{ k: 'num', q: 'Sum of (a) = ?', a: 1, x: '1.00: valid.' }, { k: 'tf', q: '(b) valid?', a: true }, { k: 'num', q: 'Sum of (c) = ?', a: 2.8, x: '2.8 > 1: invalid.' }, { k: 'tf', q: '(d) valid?', a: false, x: 'Negative probabilities.' }, { k: 'tf', q: '(e) valid?', a: false, x: '15/14 > 1.' }], '(c), (d), (e) are not valid'),
  B14('Ex 14.2', 'Q2', 'A coin is tossed twice. Probability of at least one tail?', [{ k: 'pick', q: 'At least one tail', pool: COINS2, a: ['HT', 'TH', 'TT'] }, { k: 'num', q: 'P = ?', a: 0.75, show: '3/4' }], '3/4'),
  { ex: 'Ex 14.2', n: 'Q3', q: 'A die is thrown: P(prime), P(≥ 3), P(≤ 1), P(> 6), P(< 6).', scene: 'roll', setup: (W) => Object.assign(W, { kind: 'die', faces: [1, 2, 3, 4, 5, 6], counts: [0, 0, 0, 0, 0, 0] }), parts: [{ k: 'fields', q: 'Probabilities', f: [fq('prime', 1 / 2), fq('≥ 3', 2 / 3), fq('≤ 1', 1 / 6), fq('> 6', 0), fq('< 6', 5 / 6)] }], w: ['1/2, 2/3, 1/6, 0, 5/6'] },
  { ex: 'Ex 14.2', n: 'Q4', q: 'A card from 52: (a) points in S (b) P(ace of spades) (c) P(ace), P(black).', scene: 'deck', setup: (W) => { W.hl = (s, r) => r === 'A'; W.capName = 'aces'; }, parts: [{ k: 'num', q: '(a) n(S) = ?', a: 52 }, { k: 'fields', q: 'Probabilities', f: [fq('ace of spades', 1 / 52), fq('an ace', 1 / 13), fq('black', 1 / 2)] }], w: ['52; 1/52; 1/13; 1/2'] },
  B14('Ex 14.2', 'Q5', 'A coin marked 1 and 6 and a fair die are tossed. P(sum = 3), P(sum = 12)?', [{ k: 'num', q: 'n(S) = 2 × 6 = ?', a: 12 }, { k: 'fields', q: 'Probabilities', f: [fq('sum 3: (1, 2)', 1 / 12), fq('sum 12: (6, 6)', 1 / 12)] }], '1/12 and 1/12'),
  B14('Ex 14.2', 'Q6', '4 men and 6 women on a council. P(a random member is a woman)?', [{ k: 'num', q: 'P = 6/10 = ?', a: 0.6, show: '3/5' }], '3/5'),
  B14('Ex 14.2', 'Q7', 'A coin is tossed 4 times: win ₹1 per head, lose ₹1.50 per tail. Possible amounts and their probabilities?', [{ k: 'fields', q: 'Amounts (₹) for 4, 3, 2, 1, 0 heads', f: [{ l: '4H', a: 4 }, { l: '3H', a: 1.5 }, { l: '2H', a: -1 }, { l: '1H', a: -3.5 }, { l: '0H', a: -6 }], x: 'Heads − 1.5 × tails.' }, { k: 'fields', q: 'Their probabilities (out of 16)', f: [0, 1, 2, 3, 4].map((t) => fq(4 - t + 'H', nCk(4, t) / 16)) }], 'Win ₹4 (1/16), ₹1.50 (1/4), lose ₹1 (3/8), lose ₹3.50 (1/4), lose ₹6 (1/16)'),
  B14('Ex 14.2', 'Q8', 'Three coins: P(3 heads), P(2 heads), P(≥ 2 heads), P(≤ 2 heads), P(no head), P(3 tails), P(exactly 2 tails), P(no tail), P(≤ 2 tails).', [{ k: 'fields', q: 'Heads', f: [fq('3 H', 1 / 8), fq('2 H', 3 / 8), fq('≥ 2 H', 1 / 2), fq('≤ 2 H', 7 / 8), fq('no head', 1 / 8)] }, { k: 'fields', q: 'Tails', f: [fq('3 T', 1 / 8), fq('exactly 2 T', 3 / 8), fq('no tail', 1 / 8), fq('≤ 2 T', 7 / 8)] }], '1/8, 3/8, 1/2, 7/8, 1/8, 1/8, 3/8, 1/8, 7/8'),
  B14('Ex 14.2', 'Q9', 'P(A) = 2/11. Find P(not A).', [{ k: 'num', q: '1 − 2/11 = ?', a: 9 / 11, show: '9/11' }], '9/11'),
  B14('Ex 14.2', 'Q10', 'A letter is chosen at random from ASSASSINATION. P(vowel), P(consonant)?', [{ k: 'fields', q: 'Count: 13 letters; A×3, I×2, O×1 are vowels', f: [fq('vowel', 6 / 13), fq('consonant', 7 / 13)] }], '6/13 and 7/13'),
  B14('Ex 14.2', 'Q11', 'A lottery: choose 6 different numbers from 1 to 20. P(matching the fixed six)?', [{ k: 'num', q: '²⁰C₆ = ?', a: nCk(20, 6) }, { k: 'num', q: 'P = 1/²⁰C₆ = ? (type 1/38760)', a: 1 / nCk(20, 6), show: '1/38760', tol: 1e-9 }], '1/38760'),
  B14('Ex 14.2', 'Q12', 'Consistent? (i) P(A) = 0.5, P(B) = 0.7, P(A ∩ B) = 0.6 (ii) P(A) = 0.5, P(B) = 0.4, P(A ∪ B) = 0.8', [{ k: 'tf', q: '(i) consistent? (A ∩ B ⊂ A)', a: false, x: 'P(A ∩ B) = 0.6 > P(A) = 0.5.' }, { k: 'tf', q: '(ii) consistent? (gives P(A ∩ B) = 0.1)', a: true }], '(i) No  (ii) Yes'),
  { ex: 'Ex 14.2', n: 'Q13', q: 'Fill the blanks: (i) 1/3, 1/5, 1/15, ? (ii) 0.35, ?, 0.25, 0.6 (iii) 0.5, 0.35, ?, 0.7', scene: 'pvenn', setup: (W) => Object.assign(W, { a: 1 / 3, b: 1 / 5, ab: 1 / 15 }), parts: [{ k: 'num', q: '(i) P(A ∪ B) = ?', a: 7 / 15, show: '7/15' }, { k: 'num', q: '(ii) P(B) = ?', a: 0.5, pre: async () => Object.assign(W, { a: 0.35, b: NaN, ab: 0.25 }) }, { k: 'num', q: '(iii) P(A ∩ B) = ?', a: 0.15, pre: async () => Object.assign(W, { a: 0.5, b: 0.35, ab: NaN }) }], w: ['7/15, 0.5, 0.15'] },
  B14('Ex 14.2', 'Q14', 'P(A) = 3/5, P(B) = 1/5, A and B mutually exclusive. P(A or B)?', [{ k: 'num', q: '3/5 + 1/5 = ?', a: 0.8, show: '4/5' }], '4/5'),
  { ex: 'Ex 14.2', n: 'Q15', q: 'P(E) = 1/4, P(F) = 1/2, P(E and F) = 1/8. Find (i) P(E or F) (ii) P(not E and not F).', scene: 'pvenn', setup: (W) => Object.assign(W, { a: 0.25, b: 0.5, ab: 0.125, labA: 'E', labB: 'F' }), parts: [{ k: 'num', q: '(i) = ?', a: 5 / 8, show: '5/8', act: async () => (W.lit = ['a-b', 'ab', 'b-a']) }, { k: 'num', q: '(ii) = ?', a: 3 / 8, show: '3/8', act: async () => (W.lit = ['out']) }], w: ['5/8 and 3/8'] },
  B14('Ex 14.2', 'Q16', 'P(not E or not F) = 0.25. Are E and F mutually exclusive?', [{ k: 'num', q: 'P(E ∩ F) = 1 − 0.25 = ?', a: 0.75 }, { k: 'tf', q: 'Mutually exclusive?', o: ['Yes', 'No'], a: 1, x: 'P(E ∩ F) ≠ 0.' }], 'No: P(E ∩ F) = 0.75'),
  { ex: 'Ex 14.2', n: 'Q17', q: 'P(A) = 0.42, P(B) = 0.48, P(A and B) = 0.16. Find P(not A), P(not B), P(A or B).', scene: 'pvenn', setup: (W) => Object.assign(W, { a: 0.42, b: 0.48, ab: 0.16 }), parts: [{ k: 'fields', q: 'Probabilities', f: [{ l: 'not A', a: 0.58 }, { l: 'not B', a: 0.52 }, { l: 'A or B', a: 0.74 }] }], w: ['0.58, 0.52, 0.74'] },
  { ex: 'Ex 14.2', n: 'Q18', q: '40% study Maths, 30% Biology, 10% both. P(Maths or Biology)?', scene: 'pvenn', setup: (W) => Object.assign(W, { a: 0.4, b: 0.3, ab: 0.1, labA: 'M', labB: 'B' }), parts: [{ k: 'num', q: '0.4 + 0.3 − 0.1 = ?', a: 0.6, act: async () => (W.lit = ['a-b', 'ab', 'b-a']) }], w: ['0.6'] },
  { ex: 'Ex 14.2', n: 'Q19', q: 'P(pass 1st) = 0.8, P(pass 2nd) = 0.7, P(pass at least one) = 0.95. P(pass both)?', scene: 'pvenn', setup: (W) => Object.assign(W, { a: 0.8, b: 0.7, ab: NaN }), parts: [{ k: 'num', q: '0.8 + 0.7 − 0.95 = ?', a: 0.55, act: async () => { W.ab = 0.55; W.lit = ['ab']; } }], w: ['0.55'] },
  { ex: 'Ex 14.2', n: 'Q20', q: 'P(both English and Hindi) = 0.5, P(neither) = 0.1, P(English) = 0.75. P(Hindi)?', scene: 'pvenn', setup: (W) => Object.assign(W, { a: 0.75, b: NaN, ab: 0.5, labA: 'E', labB: 'H' }), parts: [{ k: 'num', q: 'P(E ∪ H) = 1 − 0.1 = ?', a: 0.9 }, { k: 'num', q: 'P(H) = 0.9 − 0.75 + 0.5 = ?', a: 0.65, act: async () => (W.b = 0.65) }], w: ['P(Hindi) = 0.65'] },
  { ex: 'Ex 14.2', n: 'Q21', q: '60 students: 30 NCC, 32 NSS, 24 both. P(NCC or NSS), P(neither), P(NSS but not NCC)?', scene: 'pvenn', setup: (W) => Object.assign(W, { a: 0.5, b: 32 / 60, ab: 0.4, labA: 'NCC', labB: 'NSS' }), parts: [{ k: 'fields', q: 'Probabilities', f: [fq('NCC or NSS', 19 / 30), fq('neither', 11 / 30), fq('NSS not NCC', 2 / 15)] }], w: ['19/30, 11/30, 2/15'] },
];

/* ===================== MISCELLANEOUS ===================== */
const EX14M = [
  B14('Misc', 'Q1', 'A box has 10 red, 20 blue, 30 green marbles; 5 are drawn. P(all blue)? P(at least one green)?', [{ k: 'mcq', q: '(i) all blue', o: ['²⁰C₅/⁶⁰C₅', '20/60', '⁵C₂₀/⁶⁰C₅', '(1/3)⁵'], a: 0 }, { k: 'mcq', q: '(ii) at least one green', o: ['1 − ³⁰C₅/⁶⁰C₅', '³⁰C₅/⁶⁰C₅', '1 − (1/2)⁵', '³⁰C₁/⁶⁰C₅'], a: 0, x: 'Complement: no green means all 5 from the 30 non-green.' }, { k: 'num', q: 'Value of (i) ≈ ? (4 decimals)', a: nCk(20, 5) / nCk(60, 5), tol: 0.0001, show: fmtN(nCk(20, 5) / nCk(60, 5), 4) }], '²⁰C₅/⁶⁰C₅ and 1 − ³⁰C₅/⁶⁰C₅'),
  B14('Misc', 'Q2', '4 cards from 52: P(3 diamonds and 1 spade)?', [{ k: 'mcq', q: 'P = ?', o: ['¹³C₃ · ¹³C₁ / ⁵²C₄', '¹³C₄ / ⁵²C₄', '(¹³C₃ + ¹³C₁)/⁵²C₄', '¹³C₃ · ³⁹C₁ / ⁵²C₄'], a: 0 }, { k: 'num', q: 'Value ≈ ? (4 decimals)', a: (nCk(13, 3) * 13) / nCk(52, 4), tol: 0.0001, show: fmtN((nCk(13, 3) * 13) / nCk(52, 4), 4) }], '¹³C₃ · ¹³C₁ / ⁵²C₄'),
  { ex: 'Misc', n: 'Q3', q: 'A die has two 1s, three 2s and one 3. P(2), P(1 or 3), P(not 3)?', scene: 'roll', setup: (W) => Object.assign(W, { kind: 'die', faces: [1, 1, 2, 2, 2, 3], counts: Array(6).fill(0) }), parts: [{ k: 'fields', q: 'Probabilities', f: [fq('P(2)', 1 / 2), fq('P(1 or 3)', 1 / 2), fq('P(not 3)', 5 / 6)] }], w: ['1/2, 1/2, 5/6'] },
  B14('Misc', 'Q4', '10,000 tickets, 10 prizes. P(no prize) with (a) 1 (b) 2 (c) 10 tickets?', [{ k: 'num', q: '(a) 9990/10000 = ?', a: 0.999, show: '999/1000' }, { k: 'mcq', q: '(b) and (c)', o: ['⁹⁹⁹⁰C₂/¹⁰⁰⁰⁰C₂ and ⁹⁹⁹⁰C₁₀/¹⁰⁰⁰⁰C₁₀', '(0.999)² and (0.999)¹⁰', '0.998 and 0.99', '¹⁰C₂/¹⁰⁰⁰⁰C₂ and ¹⁰C₁₀/¹⁰⁰⁰⁰C₁₀'], a: 0 }], '999/1000, ⁹⁹⁹⁰C₂/¹⁰⁰⁰⁰C₂, ⁹⁹⁹⁰C₁₀/¹⁰⁰⁰⁰C₁₀'),
  B14('Misc', 'Q5', '100 students split into sections of 40 and 60. P(you and your friend are in the same section)? Different sections?', [{ k: 'num', q: 'Same: (⁹⁸C₃₈ + ⁹⁸C₅₈)/¹⁰⁰C₄₀ = (40·39 + 60·59)/(100·99) = ?', a: 17 / 33, show: '17/33', tol: 1e-6 }, { k: 'num', q: 'Different = ?', a: 16 / 33, show: '16/33', tol: 1e-6 }], '17/33 and 16/33'),
  B14('Misc', 'Q6', 'Three letters go into three addressed envelopes at random. P(at least one letter in its proper envelope)?', [{ k: 'num', q: 'Arrangements with NO letter right (derangements of 3) = ?', a: 2, x: 'BCA and CAB.' }, { k: 'num', q: 'P(at least one right) = 1 − 2/6 = ?', a: 2 / 3, show: '2/3' }], '2/3'),
  { ex: 'Misc', n: 'Q7', q: 'P(A) = 0.54, P(B) = 0.69, P(A ∩ B) = 0.35. Find P(A ∪ B), P(A′ ∩ B′), P(A ∩ B′), P(B ∩ A′).', scene: 'pvenn', setup: (W) => Object.assign(W, { a: 0.54, b: 0.69, ab: 0.35 }), parts: [{ k: 'fields', q: 'Read the regions', f: [{ l: 'A ∪ B', a: 0.88 }, { l: 'A′ ∩ B′', a: 0.12 }, { l: 'A ∩ B′', a: 0.19 }, { l: 'B ∩ A′', a: 0.34 }], act: async () => (W.lit = ['a-b']) }], w: ['0.88, 0.12, 0.19, 0.34'] },
  B14('Misc', 'Q8', 'Harish (M, 30), Rohan (M, 33), Sheetal (F, 46), Alis (F, 28), Salim (M, 41). P(spokesperson is male or over 35)?', [{ k: 'pick', q: 'Male or over 35', pool: ['Harish', 'Rohan', 'Sheetal', 'Alis', 'Salim'], a: ['Harish', 'Rohan', 'Sheetal', 'Salim'] }, { k: 'num', q: 'P = ?', a: 0.8, show: '4/5' }], '4/5'),
  B14('Misc', 'Q9', '4-digit numbers > 5000 from 0, 1, 3, 5, 7. P(divisible by 5) (i) with repetition (ii) without?', [{ k: 'fields', q: '(i) With repetition: count (5000 itself is not > 5000)', f: [{ l: 'all', a: 2 * 125 - 1 }, { l: 'divisible by 5', a: 2 * 5 * 5 * 2 - 1 }], x: '249 and 99.' }, { k: 'num', q: '(i) P = 99/249 = ?', a: 33 / 83, show: '33/83', tol: 1e-6 }, { k: 'fields', q: '(ii) Without repetition', f: [{ l: 'all', a: 48 }, { l: 'divisible by 5', a: 18 }], x: 'First 5: last 0 (6 ways); first 7: last 0 or 5 (12 ways).' }, { k: 'num', q: '(ii) P = 18/48 = ?', a: 3 / 8, show: '3/8' }], '(i) 33/83  (ii) 3/8'),
  B14('Misc', 'Q10', 'A 4-wheel lock (digits 0–9) opens with a sequence of four different digits. P(right sequence at random)?', [{ k: 'num', q: '¹⁰P₄ = ?', a: 5040 }, { k: 'num', q: 'P = 1/5040 (type it)', a: 1 / 5040, show: '1/5040', tol: 1e-9 }], '1/5040'),
];

const BOSS14 = [['P(head) for a fair coin', ['1/2', '1', '0', '1/4'], 0], ['P(sure event)', ['1', '0', '1/2', '∞'], 0], ['P(impossible event)', ['0', '1', '−1', '1/2'], 0], ['P(not A) when P(A) = 0.3', ['0.7', '0.3', '1.3', '0'], 0], ['Mutually exclusive means', ['A ∩ B = φ', 'A ∪ B = S', 'A = B', 'P(A) = P(B)'], 0], ['Two dice: P(sum = 7)', ['1/6', '1/12', '7/36', '1/36'], 0], ['P(A ∪ B) =', ['P(A) + P(B) − P(A ∩ B)', 'P(A) + P(B)', 'P(A)P(B)', '1 − P(A ∩ B)'], 0], ['P(king) from 52 cards', ['1/13', '1/52', '1/4', '4/13'], 0], ['3 coins: n(S)', ['8', '6', '3', '9'], 0], ['A die: P(even)', ['1/2', '1/3', '1/6', '2/3'], 0]];
LESSONS.splice(1, 0, exLesson({ id: 'ex141', title: 'Exercise 14.1', blurb: 'All 7: build events by tapping dice, coins and faces.', face: 'kimmy-playful', qs: EX141 }));
LESSONS.splice(4, 0, exLesson({ id: 'ex142', title: 'Exercise 14.2', blurb: 'All 21: axioms, counting and the addition rule.', face: 'jess-happy', qs: EX142 }));
LESSONS.push(exLesson({ id: 'misc', title: 'Miscellaneous', blurb: 'All 10: marbles, cards, lotteries, envelopes and locks.', face: 'jess-thinking', qs: EX14M }));
LESSONS.push(lesson({ id: 'boss', title: 'Boss Battle', blurb: 'Ten fast questions. Speed points. Beat Kimmy.', face: 'jess-excited', steps: [async function () { enterScene('board', (W) => { W.tag = 'BOSS'; W.sub = 'Chapter 14'; }); await slam('BOSS BATTLE', '10 questions · speed counts'); await K('play', 'Roll the dice!'); await cont('Fight'); }, ...BOSS14.map(([q, o, a], i) => async function () { enterScene('board', (W) => { W.tag = 'Q' + (i + 1); W.sub = 'Boss Battle'; }); await quiz(q, o, a, plain(o[a]) + '.', null, 15); await cont(); }), async function () { enterScene('board', (W) => { W.tag = 'K.O.!'; W.sub = 'Chapter 14'; }); await summary(['Chapter 14 complete!', { t: 'P(A ∪ B) = P(A) + P(B) − P(A ∩ B)', eq: true }]); }] }));
LESSONS.forEach((l) => { if (l.kind === 'ex') l.short = l.id === 'misc' ? 'M' : l.title.replace('Exercise ', ''); });
