/* =========================================================
   CHAPTER 4 · COMPLEX NUMBERS — every exercise question as a sim
   Answers come from the Cx arithmetic helper (checked again by the test page).
   ========================================================= */
const S5 = Math.sqrt(5), S2 = Math.SQRT2, S3 = Math.sqrt(3);
/* standard a + ib question: optional Argand animation */
function cxQ(ex, n, q, z, o = {}) {
  return {
    ex, n, q, cz: z, scene: 'argand', setup: (W) => argView(W, o.view || Math.max(2, Math.ceil(Math.max(Math.abs(z[0]), Math.abs(z[1]), ...(o.show || []).flat().map(Math.abs)) * 1.1))), kim: o.kim,
    parts: [...(o.pre || []), { k: 'fields', q: (o.ask || 'Write it as a + ib') + '   (a = real part, b = imaginary part)', f: abF(z, o), keys: o.keys || '', x: o.x || '= ' + (o.str || Cx.str(z)) + '.', act: o.act || (async () => { W.zs.push(zObj(z, { col: C.beni, w: 4.5, t: o.str || null })); SFX.snap(); }) }],
    w: o.w || [q.replace(/^Express |^Find /, '') + ' = ' + (o.str || Cx.str(z))],
  };
}
const EX41 = [
  cxQ('Ex 4.1', 'Q1', 'Express (5i)(−[[3|5]]i) in the form a + ib.', Cx.mul([0, 5], [0, -3 / 5]), { pre: [{ k: 'mcq', q: '(5i)(−3/5 i) = −3i². And i² = ?', o: ['1', '−1', 'i', '−i'], a: 1, x: 'So −3(−1) = 3.' }], act: async () => { await animMul(W, [0, 5], [0, -0.6]); }, w: ['(5i)(−3/5 i) = −3i² = 3 = 3 + i0'] }),
  { ex: 'Ex 4.1', n: 'Q2', q: 'Express i⁹ + i¹⁹ in the form a + ib.', scene: 'argand', setup: (W) => argView(W, 1.6), parts: [{ k: 'mcq', q: 'i⁹ = ?', o: ['1', 'i', '−1', '−i'], a: 1, x: '9 = 8 + 1.', act: async () => ipowSpin(W, 9) }, { k: 'mcq', q: 'i¹⁹ = ?', o: ['1', 'i', '−1', '−i'], a: 3, x: '19 = 16 + 3.', act: async () => ipowSpin(W, 19) }, { k: 'fields', q: 'So i⁹ + i¹⁹ = a + ib', f: abF([0, 0]), x: 'i + (−i) = 0 = 0 + i0.' }], w: ['i⁹ + i¹⁹ = i + (−i) = 0 = 0 + i0'] },
  { ex: 'Ex 4.1', n: 'Q3', q: 'Express i⁻³⁹ in the form a + ib.', scene: 'argand', setup: (W) => argView(W, 1.6), parts: [{ k: 'mcq', q: 'i³⁹ = ?', o: ['1', 'i', '−1', '−i'], a: 3, x: '39 = 36 + 3.' }, { k: 'fields', q: 'i⁻³⁹ = 1/(−i) = a + ib', f: abF([0, 1]), x: '1/(−i) = i.', act: async () => ipowSpin(W, -39) }], w: ['i⁻³⁹ = 1/i³⁹ = 1/(−i) = i = 0 + i1'] },
  cxQ('Ex 4.1', 'Q4', 'Express 3(7 + i7) + i(7 + i7) in the form a + ib.', Cx.add(Cx.mul([3, 0], [7, 7]), Cx.mul(I, [7, 7])), { view: 30, x: '21 + 21i + 7i − 7 = 14 + 28i.', act: async () => { await animAdd(W, [21, 21], [-7, 7]); } }),
  cxQ('Ex 4.1', 'Q5', 'Express (1 − i) − (−1 + i6) in the form a + ib.', Cx.sub([1, -1], [-1, 6]), { view: 8, x: '1 + 1 − i − 6i = 2 − 7i.', act: async () => { await animAdd(W, [1, -1], [1, -6]); } }),
  cxQ('Ex 4.1', 'Q6', 'Express ([[1|5]] + i[[2|5]]) − (4 + i[[5|2]]) in the form a + ib.', Cx.sub([1 / 5, 2 / 5], [4, 5 / 2]), { view: 5, x: '(1/5 − 4) + (2/5 − 5/2)i = −19/5 − 21/10 i.', act: async () => { await animAdd(W, [0.2, 0.4], [-4, -2.5]); } }),
  cxQ('Ex 4.1', 'Q7', 'Express [([[1|3]] + i[[7|3]]) + (4 + i[[1|3]])] − (−[[4|3]] + i) in the form a + ib.', Cx.sub(Cx.add([1 / 3, 7 / 3], [4, 1 / 3]), [-4 / 3, 1]), { view: 6, x: 'Real: 1/3 + 4 + 4/3 = 17/3. Imag: 7/3 + 1/3 − 1 = 5/3.' }),
  cxQ('Ex 4.1', 'Q8', 'Express (1 − i)⁴ in the form a + ib.', Cx.pow([1, -1], 4), { view: 4.5, pre: [{ k: 'fields', q: 'First (1 − i)² = a + ib', f: abF([0, -2]), x: '1 − 2i + i² = −2i.' }], x: '(−2i)² = 4i² = −4.', act: async () => { await animMul(W, [0, -2], [0, -2]); } }),
  cxQ('Ex 4.1', 'Q9', 'Express ([[1|3]] + 3i)³ in the form a + ib.', Cx.pow([1 / 3, 3], 3), { view: 30, x: '1/27 + 3(1/9)(3i) + 3(1/3)(9i²) + 27i³ = 1/27 + i − 9 − 27i = −242/27 − 26i.' }),
  cxQ('Ex 4.1', 'Q10', 'Express (−2 − [[1|3]]i)³ in the form a + ib.', Cx.pow([-2, -1 / 3], 3), { view: 8, x: '−(2 + i/3)³ = −[8 + 4i − 2/3 − i/27] = −22/3 − 107/27 i.' }),
  cxQ('Ex 4.1', 'Q11', 'Find the multiplicative inverse of 4 − 3i.', Cx.inv([4, -3]), { view: 5, ask: '1/(4 − 3i) = (4 + 3i)/25', x: '|4 − 3i|² = 25.', act: async () => { W.zs.push(zObj([4, -3], { col: C.sora }), zObj([0.16, 0.12], { col: C.beni, t: '4/25 + 3/25 i' })); }, w: ['(4 − 3i)⁻¹ = (4 + 3i)/(16 + 9) = 4/25 + (3/25)i'] }),
  cxQ('Ex 4.1', 'Q12', 'Find the multiplicative inverse of √5 + 3i.', Cx.inv([S5, 3]), { view: 4, tol: 1e-3, sa: '√5/14', sb: '−3/14', str: '√5/14 − (3/14)i', keys: ' √', ask: '|√5 + 3i|² = 5 + 9 = 14, so the inverse is (√5 − 3i)/14', w: ['(√5 + 3i)⁻¹ = (√5 − 3i)/(5 + 9) = √5/14 − (3/14)i'] }),
  cxQ('Ex 4.1', 'Q13', 'Find the multiplicative inverse of −i.', Cx.inv([0, -1]), { view: 1.6, x: '1/(−i) = i.', w: ['(−i)⁻¹ = 1/(−i) = i/(−i·i) = i/1 = i'] }),
  {
    ex: 'Ex 4.1', n: 'Q14', q: 'Express [(3 + i√5)(3 − i√5)] / [(√3 + √2 i) − (√3 − i√2)] in the form a + ib.', scene: 'argand', setup: (W) => argView(W, 6),
    parts: [{ k: 'num', q: 'Numerator = 9 − (i√5)² = ?', a: 14, x: '9 + 5 = 14.' }, { k: 'mcq', q: 'Denominator = ?', o: ['2√2 i', '2√3', '0', '2√2'], a: 0, x: 'The √3 cancels: √2 i + √2 i.' }, { k: 'fields', q: '14/(2√2 i) = a + ib', f: abF([0, -7 / S2], { tol: 1e-3, sb: '−7√2/2' }), keys: ' √', x: '7/(√2 i) = −7i/√2 = −(7√2/2) i.', act: async () => { W.zs.push(zObj([0, -7 / S2], { col: C.beni, t: '−(7√2/2) i' })); } }],
    w: ['= 14/(2√2 i) = 7/(√2 i) = −7i/√2 = 0 − (7√2/2) i'],
  },
];
const EX4M = [
  { ex: 'Misc', n: 'Q1', q: 'Evaluate [i¹⁸ + (1/i)²⁵]³.', scene: 'argand', setup: (W) => argView(W, 2.5), parts: [{ k: 'mcq', q: 'i¹⁸ = ?', o: ['1', 'i', '−1', '−i'], a: 2, x: '18 = 16 + 2.' }, { k: 'mcq', q: '(1/i)²⁵ = (−i)²⁵ = ?', o: ['i', '−i', '1', '−1'], a: 1, x: '−i²⁵ = −i.' }, { k: 'fields', q: '(−1 − i)³ = a + ib', f: abF([2, -2]), x: '−(1 + i)³ = −(1 + 3i − 3 − i) = 2 − 2i.', act: async () => { W.zs.push(zObj([-1, -1], { col: C.sora }), zObj([2, -2], { col: C.beni })); } }], w: ['i¹⁸ = −1, (1/i)²⁵ = −i. [−1 − i]³ = −(1 + i)³ = −(−2 + 2i) = 2 − 2i'] },
  { ex: 'Misc', n: 'Q2', q: 'For any two complex numbers z₁ and z₂, prove that Re(z₁z₂) = Re z₁ Re z₂ − Im z₁ Im z₂.', scene: 'argand', setup: (W) => argView(W, 4), parts: [{ k: 'order', q: 'Order the proof', s: ['Let z₁ = x₁ + iy₁ and z₂ = x₂ + iy₂', 'z₁z₂ = x₁x₂ + i x₁y₂ + i y₁x₂ + i² y₁y₂', '= (x₁x₂ − y₁y₂) + i(x₁y₂ + x₂y₁)', 'Re(z₁z₂) = x₁x₂ − y₁y₂ = Re z₁ Re z₂ − Im z₁ Im z₂'] }], w: ['z₁z₂ = (x₁x₂ − y₁y₂) + i(x₁y₂ + x₂y₁), so Re(z₁z₂) = x₁x₂ − y₁y₂ = Re z₁ Re z₂ − Im z₁ Im z₂'] },
  (() => { const d = Cx.sub(Cx.inv([1, -4]), Cx.div([2, 0], [1, 1])), m = Cx.div([3, -4], [5, 1]), z = Cx.mul(d, m); return { ex: 'Misc', n: 'Q3', q: 'Reduce ([[1|1 − 4i]] − [[2|1 + i]])([[3 − 4i|5 + i]]) to the standard form.', cz: z, scene: 'argand', setup: (W) => argView(W, 2), parts: [{ k: 'fields', q: 'Bracket 1: 1/(1 − 4i) − 2/(1 + i)', f: abF(d), x: '(1 + 4i)/17 − (1 − i) = (−16 + 21i)/17.' }, { k: 'fields', q: 'Bracket 2: (3 − 4i)/(5 + i)', f: abF(m), x: '(3 − 4i)(5 − i)/26 = (11 − 23i)/26.' }, { k: 'fields', q: 'Product = a + ib', f: abF(z), x: '(−16 + 21i)(11 − 23i)/442 = (307 + 599i)/442.', act: async () => { W.zs.push(zObj(z, { col: C.beni })); } }], w: ['= [(−16 + 21i)/17] × [(11 − 23i)/26] = (307 + 599i)/442 = 307/442 + (599/442)i'] }; })(),
  { ex: 'Misc', n: 'Q4', q: 'If x − iy = √[(a − ib)/(c − id)], prove that (x² + y²)² = (a² + b²)/(c² + d²).', scene: 'argand', setup: (W) => argView(W, 3), parts: [{ k: 'order', q: 'Order the proof', s: ['(x − iy)² = (a − ib)/(c − id)', 'Take modulus: |x − iy|² = |a − ib| / |c − id|', '(x² + y²) = √(a² + b²)/√(c² + d²)', 'Square both sides: (x² + y²)² = (a² + b²)/(c² + d²)'] }], w: ['Squaring, (x − iy)² = (a − ib)/(c − id). Taking modulus, x² + y² = √(a² + b²)/√(c² + d²). Squaring again gives the result.'] },
  { ex: 'Misc', n: 'Q5', q: 'If z₁ = 2 − i, z₂ = 1 + i, find |(z₁ + z₂ + 1)/(z₁ − z₂ + 1)|.', scene: 'argand', setup: (W) => argView(W, 4.5), parts: [{ k: 'fields', q: 'z₁ + z₂ + 1 = ?', f: abF([4, 0]), x: '4.', act: async () => { W.zs.push(zObj([4, 0], { col: C.sora })); } }, { k: 'fields', q: 'z₁ − z₂ + 1 = ?', f: abF([2, -2]), x: '2 − 2i.', act: async () => { W.zs.push(zObj([2, -2], { col: C.khaki })); } }, { k: 'num', q: '|4| / |2 − 2i| = ?   (√ key allowed)', a: '√2', show: '√2', keys: '√', x: '4/(2√2) = √2.' }], w: ['|4 / (2 − 2i)| = 4/√8 = √2'] },
  { ex: 'Misc', n: 'Q6', q: 'If a + ib = (x + i)²/(2x² + 1), prove that a² + b² = (x² + 1)²/(2x² + 1)².', scene: 'argand', setup: (W) => argView(W, 2), parts: [{ k: 'order', q: 'Order the proof', s: ['Take modulus: |a + ib| = |x + i|² / (2x² + 1)', '√(a² + b²) = (x² + 1)/(2x² + 1)', 'Square: a² + b² = (x² + 1)²/(2x² + 1)²'] }], w: ['|a + ib| = |x + i|²/(2x² + 1) = (x² + 1)/(2x² + 1); square both sides.'] },
  { ex: 'Misc', n: 'Q7', q: 'Let z₁ = 2 − i, z₂ = −2 + i. Find (i) Re(z₁z₂ / z̄₁) (ii) Im(1/(z₁z̄₁)).', scene: 'argand', setup: (W) => argView(W, 4.5), parts: [{ k: 'fields', q: 'z₁z₂ = ?', f: abF(Cx.mul([2, -1], [-2, 1])), x: '−4 + 2i + 2i − i² = −3 + 4i.' }, { k: 'num', q: '(i) (−3 + 4i)/(2 + i) = (−2 + 11i)/5. Real part = ?', a: '-2/5', show: '−2/5', x: 'Re = −2/5.', act: async () => { W.zs.push(zObj(Cx.div(Cx.mul([2, -1], [-2, 1]), [2, 1]), { col: C.beni })); } }, { k: 'num', q: '(ii) z₁z̄₁ = |z₁|² = 5. Im(1/5) = ?', a: 0, x: '1/5 is real: imaginary part 0.' }], w: ['(i) z₁z₂/z̄₁ = (−3 + 4i)/(2 + i) = (−2 + 11i)/5, so Re = −2/5', '(ii) 1/(z₁z̄₁) = 1/5, so Im = 0'] },
  { ex: 'Misc', n: 'Q8', q: 'Find the real numbers x and y if (x − iy)(3 + 5i) is the conjugate of −6 − 24i.', scene: 'argand', setup: (W) => argView(W, 26), parts: [{ k: 'mcq', q: '(x − iy)(3 + 5i) = ?', o: ['(3x + 5y) + i(5x − 3y)', '(3x − 5y) + i(5x + 3y)', '3x + 5yi', '(3x + 5y) − i(5x − 3y)'], a: 0, x: '3x + 5xi − 3yi − 5y i².' }, { k: 'fields', q: '3x + 5y = −6 and 5x − 3y = 24', f: [{ l: 'x', a: 3 }, { l: 'y', a: -3, show: '−3' }], x: 'x = 3, y = −3.', act: async () => { await animMul(W, [3, 3], [3, 5]); } }], w: ['(3x + 5y) + i(5x − 3y) = −6 + 24i ⇒ 3x + 5y = −6, 5x − 3y = 24 ⇒ x = 3, y = −3'] },
  { ex: 'Misc', n: 'Q9', q: 'Find the modulus of [[1 + i|1 − i]] − [[1 − i|1 + i]].', scene: 'argand', setup: (W) => argView(W, 2.5), parts: [{ k: 'mcq', q: '(1 + i)/(1 − i) = ?', o: ['i', '−i', '1', '2i'], a: 0, x: '(1 + i)²/2 = 2i/2 = i.' }, { k: 'num', q: 'i − (−i) = 2i, so the modulus = ?', a: 2, x: '|2i| = 2.', act: async () => { W.zs.push(zObj([0, 2], { col: C.beni })); W.circ = { r: 2, t: '|z| = 2' }; } }], w: ['(1 + i)/(1 − i) = i and (1 − i)/(1 + i) = −i, so the modulus is |2i| = 2'] },
  { ex: 'Misc', n: 'Q10', q: 'If (x + iy)³ = u + iv, show that u/x + v/y = 4(x² − y²).', scene: 'argand', setup: (W) => argView(W, 3), parts: [{ k: 'mcq', q: '(x + iy)³ = ?', o: ['(x³ − 3xy²) + i(3x²y − y³)', '(x³ + 3xy²) + i(3x²y + y³)', 'x³ − iy³', '(x³ − y³) + 3ixy'], a: 0, x: 'Binomial expansion with i² = −1, i³ = −i.' }, { k: 'order', q: 'Finish', s: ['u = x³ − 3xy², v = 3x²y − y³', 'u/x = x² − 3y², v/y = 3x² − y²', 'u/x + v/y = 4x² − 4y² = 4(x² − y²)'] }], w: ['u = x³ − 3xy², v = 3x²y − y³; u/x + v/y = x² − 3y² + 3x² − y² = 4(x² − y²)'] },
  { ex: 'Misc', n: 'Q11', q: 'If α and β are different complex numbers with |β| = 1, then find |(β − α)/(1 − ᾱβ)|.', scene: 'argand', setup: (W) => { argView(W, 1.6); W.circ = { r: 1, t: '|β| = 1' }; }, parts: [{ k: 'order', q: 'Order the steps', s: ['|β| = 1 ⇒ ββ̄ = 1', '1 − ᾱβ = ββ̄ − ᾱβ = β(β̄ − ᾱ)', '|1 − ᾱβ| = |β|·|conj(β − α)| = |β − α|', 'So the ratio has modulus 1'] }, { k: 'num', q: '|(β − α)/(1 − ᾱβ)| = ?', a: 1, x: '1.' }], w: ['1 − ᾱβ = β(β̄ − ᾱ), so |1 − ᾱβ| = |β||β − α| = |β − α|. Hence the value is 1.'] },
  { ex: 'Misc', n: 'Q12', q: 'Find the number of non-zero integral solutions of the equation |1 − i|ˣ = 2ˣ.', scene: 'plane', setup: (W) => { planeView(W, -3, 3, -0.5, 6); W.curves.push(curve((x) => Math.SQRT2 ** x, C.sora, { p: 1, t: '(√2)ˣ' }), curve((x) => 2 ** x, C.beni, { p: 1, t: '2ˣ' })); }, parts: [{ k: 'mcq', q: '|1 − i| = ?', o: ['√2', '2', '0', '1'], a: 0, x: '√(1 + 1).' }, { k: 'num', q: '(√2)ˣ = 2ˣ only at x = 0. Number of NON-ZERO integral solutions = ?', a: 0, x: 'The curves meet only at x = 0.', act: async () => { W.pts.push({ x: 0, y: 1, t: 'only x = 0' }); } }], w: ['(√2)ˣ = 2ˣ ⇒ 2^{x/2} = 2ˣ ⇒ x/2 = x ⇒ x = 0. So there are 0 non-zero integral solutions.'] },
  { ex: 'Misc', n: 'Q13', q: 'If (a + ib)(c + id)(e + if)(g + ih) = A + iB, show that (a² + b²)(c² + d²)(e² + f²)(g² + h²) = A² + B².', scene: 'argand', setup: (W) => argView(W, 3), parts: [{ k: 'order', q: 'Order the proof', s: ['Take modulus of both sides', '|a + ib||c + id||e + if||g + ih| = |A + iB|', '√(a² + b²)·√(c² + d²)·√(e² + f²)·√(g² + h²) = √(A² + B²)', 'Square both sides'] }], w: ['|z₁z₂z₃z₄| = |z₁||z₂||z₃||z₄|; take moduli and square.'] },
  { ex: 'Misc', n: 'Q14', q: 'If ([[1 + i|1 − i]])ᵐ = 1, then find the least positive integral value of m.', scene: 'argand', setup: (W) => argView(W, 1.6), parts: [{ k: 'mcq', q: '(1 + i)/(1 − i) = ?', o: ['i', '−i', '1', '2'], a: 0, x: 'As in Q9.' }, { k: 'num', q: 'iᵐ = 1. Least positive m = ?', a: 4, x: 'i⁴ = 1.', act: async () => ipowSpin(W, 4) }], w: ['(1 + i)/(1 − i) = i, and iᵐ = 1 first happens at m = 4.'] },
];
const BOSS4 = [
  ['i² = ?', ['1', '−1', 'i', '0'], 1], ['i⁴⁵ = ?', ['1', 'i', '−1', '−i'], 1], ['(2 + i)(2 − i) = ?', ['3', '5', '4 − i', '4'], 1], ['|−6 + 8i| = ?', ['10', '14', '2', '√28'], 0], ['Conjugate of 4 − 7i', ['−4 + 7i', '4 + 7i', '7 − 4i', '−4 − 7i'], 1],
  ['1/i = ?', ['i', '−i', '1', '−1'], 1], ['Multiplying by i rotates by…', ['45°', '90°', '180°', '0°'], 1], ['√−9 = ?', ['3i', '−3', '9i', '±3'], 0], ['Re[(1 + i)²] = ?', ['0', '2', '1', '−2'], 0], ['(1 + i)/(1 − i) = ?', ['1', 'i', '−i', '2i'], 1],
];
LESSONS.push(exLesson({ id: 'ex41', title: 'Exercise 4.1', blurb: 'All 14: a + ib forms, powers of i, inverses.', face: 'kimmy-curious', qs: EX41 }));
LESSONS.push(exLesson({ id: 'misc', title: 'Miscellaneous', blurb: 'All 14 Miscellaneous Exercise questions.', face: 'jess-thinking', qs: EX4M }));
LESSONS.push(lesson({
  id: 'boss', title: 'Boss Battle', blurb: 'Ten fast questions. Speed points. Beat Kimmy.', face: 'jess-excited',
  steps: [async function () { enterScene('board', (W) => { W.tag = 'BOSS'; W.sub = 'Chapter 4'; }); await slam('BOSS BATTLE', '10 questions · speed counts'); await K('play', 'Imaginary boss, real points!'); await cont('Fight'); }, ...BOSS4.map(([q, o, a], i) => async function () { enterScene('board', (W) => { W.tag = 'Q' + (i + 1); W.sub = 'Boss Battle'; }); await quiz(q, o, a, plain(o[a]) + '.', null, 15); await cont(); }), async function () { enterScene('board', (W) => { W.tag = 'K.O.!'; W.sub = 'Chapter 4'; }); await summary(['Chapter 4 complete!', 'i · Argand plane · Algebra · Conjugates', { t: 'z·z̄ = |z|²', eq: true }]); }],
}));
LESSONS.forEach((l) => { if (l.kind === 'ex') l.short = l.id === 'misc' ? 'M' : l.title.replace('Exercise ', ''); });
