/* =========================================================
   CLASS 12 · CHAPTER 6 · APPLICATION OF DERIVATIVES — every exercise question as a sim
   Increasing/decreasing answers are computed from the sign of a numeric f′; optimum points are checked by the test page.
   ========================================================= */
const { sin, cos, tan, log, exp, sqrt, abs, atan, cbrt } = Math;
const sayJ = (t, m = 'think') => ({ k: 'say', who: 'jess', m, t });
const xs6 = (ex, n, q, parts, w, o = {}) => ({ ex, n, q, scene: o.scene || 'board', setup: o.setup, parts, w: [w] });
/* related-rates question on the rate scene */
const rateQ = (ex, n, q, kind, v, parts, w, o = {}) => ({ ex, n, q, scene: 'rate', setup: (W) => rateSet(W, kind, v, o.lines || [], o.set || {}), parts: [...(o.play ? [{ k: 'run', run: async (W) => { const to = o.play; SFX.whoosh(); await tw(W, { v: to, duration: AUTO ? 0.05 : 1.1, ease: 'power1.inOut' }); } }] : []), ...parts], w: [w] });
const numP = (q, a, x, o = {}) => ({ k: 'num', q, a, x, ...o });
const pis = (a, show) => ({ a, show, keys: 'π', tol: 1e-3 });
/* max/min question on the mono scene: optional sign strip, then fields */
const extQ = (ex, n, q, f, view, crit, parts, w, o = {}) => ({ ex, n, q, scene: 'mono', f, crit, setup: (W) => monoSet(W, f, view[0], view[1], { y: view.length > 2 ? [view[2], view[3]] : undefined, crit, critLab: o.critLab, strip: 0, dom: o.dom, cap: o.cap }), parts: [{ k: 'run', run: async (W) => { await stripRun(W); W.marks = crit.map((x) => ({ x, kind: turn(f, x) })).filter((m) => m.kind !== 'neither' || o.flat); SFX.chime(); } }, ...parts], w: [w] });
const fld = (q, f, x, o = {}) => ({ k: 'fields', q, f, x, ...o });

/* ===================== EXERCISE 6.1 ===================== */
const EX61 = [
  rateQ('Ex 6.1', 'Q1', 'Rate of change of the area of a circle with respect to r when (a) r = 3 cm (b) r = 4 cm', 'circle', 3, [fld('dA/dr = 2πr', [{ l: '(a) r = 3', ...pis(6 * PI, '6π') }, { l: '(b) r = 4', ...pis(8 * PI, '8π') }], '6π and 8π cm²/cm.', { keys: 'π' })], '(a) 6π (b) 8π', { set: { scale: 0.6 }, play: 4 }),
  rateQ('Ex 6.1', 'Q2', 'A cube’s volume grows at 8 cm³/s. How fast is the surface area increasing when the edge is 12 cm?', 'cube', 12, [numP('dx/dt = 8/(3x²); dS/dt = 12x · dx/dt = 32/x = ?', 8 / 3, '8/3 cm²/s.', { show: '8/3' })], '8/3 cm²/s', { set: { scale: 0.2 } }),
  rateQ('Ex 6.1', 'Q3', 'The radius of a circle grows at 3 cm/s. How fast is the area increasing when r = 10 cm?', 'circle', 10, [numP('dA/dt = 2πr · 3 = ? (with π)', 60 * PI, '60π cm²/s.', pis(60 * PI, '60π'))], '60π cm²/s', { set: { scale: 0.22 } }),
  rateQ('Ex 6.1', 'Q4', 'An edge of a cube grows at 3 cm/s. How fast is the volume increasing when the edge is 10 cm?', 'cube', 10, [numP('dV/dt = 3x² · 3 = ?', 900, '900 cm³/s.')], '900 cm³/s', { set: { scale: 0.22 } }),
  rateQ('Ex 6.1', 'Q5', 'Waves move out at 5 cm/s. How fast is the enclosed area increasing when r = 8 cm?', 'circle', 8, [numP('dA/dt = 2π · 8 · 5 = ? (with π)', 80 * PI, '80π cm²/s.', pis(80 * PI, '80π'))], '80π cm²/s', { set: { scale: 0.26 }, play: 8 }),
  rateQ('Ex 6.1', 'Q6', 'The radius grows at 0.7 cm/s. What is the rate of increase of the circumference?', 'circle', 4, [numP('dC/dt = 2π · 0.7 = ? (with π)', 1.4 * PI, '1.4π cm/s, whatever the radius.', pis(1.4 * PI, '1.4π'))], '1.4π cm/s', { set: { scale: 0.45 } }),
  rateQ('Ex 6.1', 'Q7', 'x shrinks at 5 cm/min and y grows at 4 cm/min. When x = 8, y = 6, find the rates of change of (a) the perimeter (b) the area', 'rect', 8, [fld('At x = 8, y = 6', [{ l: 'dP/dt', a: -2 }, { l: 'dA/dt', a: 2 }], 'dP/dt = 2(−5 + 4) = −2 cm/min; dA/dt = −5·6 + 8·4 = 2 cm²/min.')], '(a) −2 cm/min (b) 2 cm²/min', { set: { v2: 6, scale: 0.3 } }),
  rateQ('Ex 6.1', 'Q8', 'A balloon is inflated at 900 cm³/s. Find the rate at which the radius increases when r = 15 cm', 'sphere', 15, [numP('dr/dt = 900/(4πr²) = ? (with π)', 1 / PI, '1/π cm/s.', { show: '1/π', keys: 'π', tol: 1e-3 })], '1/π cm/s', { set: { scale: 0.15 }, play: 15 }),
  rateQ('Ex 6.1', 'Q9', 'Find the rate of change of the volume of a sphere with respect to r when r = 10 cm', 'sphere', 10, [numP('dV/dr = 4πr² = ? (with π)', 400 * PI, '400π cm³/cm.', pis(400 * PI, '400π'))], '400π cm³ per cm', { set: { scale: 0.2 } }),
  rateQ('Ex 6.1', 'Q10', 'A 5 m ladder: its foot moves away at 2 cm/s. How fast is the top coming down when the foot is 4 m from the wall?', 'ladder', 2, [numP('x² + y² = 25 ⇒ dy/dt = −(x/y) dx/dt. At x = 4, y = 3: dy/dt = ?', -8 / 3, 'The top slides down at 8/3 cm/s.', { show: '−8/3' })], 'decreasing at 8/3 cm/s', { set: { L: 5 }, play: 4 }),
  xs6('Ex 6.1', 'Q11', 'A particle moves along 6y = x³ + 2. Find the points where y changes 8 times as fast as x', [fld('6 dy/dt = 3x² dx/dt and dy/dt = 8 dx/dt give x² = 16', [{ l: 'x₁', a: 4 }, { l: 'y₁', a: 11 }, { l: 'x₂', a: -4 }, { l: 'y₂', a: -31 / 3, show: '−31/3' }], '(4, 11) and (−4, −31/3).')], '(4, 11) and (−4, −31/3)', { scene: 'calc', setup: (W) => { calcView(W, (x) => (x ** 3 + 2) / 6, -5, 5, { y: [-14, 14] }); W.a = 4; W.tan = true; grabCalc(W); } }),
  rateQ('Ex 6.1', 'Q12', 'The radius of an air bubble grows at 1/2 cm/s. How fast is the volume increasing when r = 1 cm?', 'sphere', 1, [numP('dV/dt = 4πr² · ½ = ? (with π)', 2 * PI, '2π cm³/s.', pis(2 * PI, '2π'))], '2π cm³/s', { set: { scale: 1.6 } }),
  xs6('Ex 6.1', 'Q13', 'A balloon has diameter (3/2)(2x + 1). Find the rate of change of its volume with respect to x', [{ k: 'mcq', q: 'r = (3/4)(2x + 1), V = (4/3)πr³ = (9π/16)(2x + 1)³, so dV/dx =', o: ['(27π/8)(2x + 1)²', '(9π/8)(2x + 1)²', '(27π/16)(2x + 1)²', '(9π/16)(2x + 1)²'], a: 0, x: 'Chain rule: 3·2 = 6 times 9π/16.' }], '(27π/8)(2x + 1)²'),
  rateQ('Ex 6.1', 'Q14', 'Sand pours at 12 cm³/s into a cone with height = radius/6. How fast is the height increasing when h = 4 cm?', 'sand', 4, [{ k: 'mcq', q: 'r = 6h, so V = ⅓π(6h)²h =', o: ['12πh³', '36πh³', '4πh³', '2πh³'], a: 0, x: '⅓π·36h²·h.' }, numP('dh/dt = 12/(36πh²) = ? (with π)', 1 / (48 * PI), '1/(48π) cm/s.', { show: '1/(48π)', keys: 'π', tol: 1e-5 })], '1/(48π) cm/s', { set: { scale: 0.9 }, play: 4 }),
  xs6('Ex 6.1', 'Q15', 'C(x) = 0.007x³ − 0.003x² + 15x + 4000. Find the marginal cost when x = 17', [numP('C′(17) = 0.021(289) − 0.006(17) + 15 = ?', 20.967, '₹20.967 (about ₹20.97).', { tol: 0.0006, pre: '₹' })], '₹20.967', { scene: 'calc', setup: (W) => { calcView(W, (x) => 0.007 * x ** 3 - 0.003 * x * x + 15 * x + 4000, 10, 22); W.a = 17; W.tan = true; grabCalc(W); W.fLab = 'C'; } }),
  xs6('Ex 6.1', 'Q16', 'R(x) = 13x² + 26x + 15. Find the marginal revenue when x = 7', [numP('R′(7) = 26(7) + 26 = ?', 208, '₹208.', { pre: '₹' })], '₹208'),
  xs6('Ex 6.1', 'Q17', 'The rate of change of the area of a circle w.r.t. r at r = 6 cm is (A) 10π (B) 12π (C) 8π (D) 11π', [{ k: 'mcq', q: '2πr at r = 6', o: ['(B) 12π', '(A) 10π', '(C) 8π', '(D) 11π'], a: 0, x: '12π.' }], '(B)'),
  xs6('Ex 6.1', 'Q18', 'R(x) = 3x² + 36x + 5. The marginal revenue when x = 15 is (A) 116 (B) 96 (C) 90 (D) 126', [numP('6x + 36 at 15 = ?', 126, '126.'), { k: 'mcq', q: 'Answer', o: ['(D) 126', '(A) 116', '(B) 96', '(C) 90'], a: 0, x: '(D).' }], '(D)'),
];

/* ===================== EXERCISE 6.2 ===================== */
const inf = Infinity;
const EX62 = [
  monoQ('Ex 6.2', 'Q1', 'Show that f(x) = 3x + 17 is increasing on ℝ', (x) => 3 * x + 17, [-6, 4], [-inf, inf], ['ℝ'], { only: 'inc', iq: 'f′ = 3 > 0. Increasing on', w: 'f′ = 3 > 0: increasing on ℝ' }),
  monoQ('Ex 6.2', 'Q2', 'Show that f(x) = e²ˣ is increasing on ℝ', (x) => exp(2 * x), [-2, 1.2], [-inf, inf], ['ℝ'], { only: 'inc', iq: 'f′ = 2e²ˣ > 0. Increasing on', w: 'f′ = 2e²ˣ > 0: increasing on ℝ' }),
  monoQ('Ex 6.2', 'Q3', 'Show that sin x is (a) increasing in (0, π/2) (b) decreasing in (π/2, π) (c) neither in (0, π)', sin, [0, PI, -0.3, 1.3], [0, PI / 2, PI], ['(0, π/2)', '(π/2, π)'], { critLab: (c) => (c > 2 ? 'π' : c > 1 ? 'π/2' : '0'), dom: [0, PI], post: [{ k: 'tf', q: '(c) So on the whole of (0, π) it is neither increasing nor decreasing', a: true, x: 'It rises then falls.' }] }),
  monoQ('Ex 6.2', 'Q4', 'Find the intervals in which f(x) = 2x² − 3x is (a) increasing (b) decreasing', (x) => 2 * x * x - 3 * x, [-1.5, 3], [-inf, 0.75, inf], ['(−∞, 3/4)', '(3/4, ∞)']),
  monoQ('Ex 6.2', 'Q5', 'Find the intervals in which f(x) = 2x³ − 3x² − 36x + 7 is (a) increasing (b) decreasing', (x) => 2 * x ** 3 - 3 * x * x - 36 * x + 7, [-5, 6], [-inf, -2, 3, inf], ['(−∞, −2)', '(−2, 3)', '(3, ∞)']),
  monoQ('Ex 6.2', 'Q6 (a)', 'Strictly increasing or decreasing: x² + 2x − 5', (x) => x * x + 2 * x - 5, [-4, 2], [-inf, -1, inf], ['(−∞, −1)', '(−1, ∞)']),
  monoQ('Ex 6.2', 'Q6 (b)', 'Strictly increasing or decreasing: 10 − 6x − 2x²', (x) => 10 - 6 * x - 2 * x * x, [-5, 2], [-inf, -1.5, inf], ['(−∞, −3/2)', '(−3/2, ∞)']),
  monoQ('Ex 6.2', 'Q6 (c)', 'Strictly increasing or decreasing: −2x³ − 9x² − 12x + 1', (x) => -2 * x ** 3 - 9 * x * x - 12 * x + 1, [-3.5, 0.5], [-inf, -2, -1, inf], ['(−∞, −2)', '(−2, −1)', '(−1, ∞)']),
  monoQ('Ex 6.2', 'Q6 (d)', 'Strictly increasing or decreasing: 6 − 9x − x²', (x) => 6 - 9 * x - x * x, [-9, 1], [-inf, -4.5, inf], ['(−∞, −9/2)', '(−9/2, ∞)']),
  monoQ('Ex 6.2', 'Q6 (e)', 'Strictly increasing or decreasing: (x + 1)³(x − 3)³', (x) => (x + 1) ** 3 * (x - 3) ** 3, [-1.8, 3.8, -80, 40], [-inf, -1, 1, 3, inf], ['(−∞, −1)', '(−1, 1)', '(1, 3)', '(3, ∞)'], { pre: [{ k: 'mcq', q: 'f′(x) =', o: ['6(x + 1)²(x − 3)²(x − 1)', '3(x + 1)²(x − 3)²', '6(x + 1)(x − 3)(x − 1)', '(x + 1)²(x − 3)²'], a: 0, x: 'Product rule, then factor.' }] }),
  monoQ('Ex 6.2', 'Q7', 'Show that y = log(1 + x) − 2x/(2 + x), x > −1, is increasing throughout its domain', (x) => log(1 + x) - (2 * x) / (2 + x), [-0.95, 4], [-1, 0, inf], ['(−1, 0)', '(0, ∞)'], { dom: [-1, 99], pre: [{ k: 'mcq', q: 'dy/dx =', o: ['x²/((1 + x)(2 + x)²)', '1/(1 + x)', '−x²/(2 + x)²', 'x/(1 + x)'], a: 0, x: '≥ 0 for x > −1, zero only at x = 0.' }], only: 'inc', w: 'y′ = x²/((1 + x)(2 + x)²) ≥ 0: increasing on (−1, ∞)' }),
  monoQ('Ex 6.2', 'Q8', 'Find the values of x for which y = [x(x − 2)]² is increasing', (x) => (x * (x - 2)) ** 2, [-1, 3, -0.5, 3], [-inf, 0, 1, 2, inf], ['(−∞, 0)', '(0, 1)', '(1, 2)', '(2, ∞)'], { only: 'inc', pre: [{ k: 'mcq', q: 'y′ =', o: ['4x(x − 1)(x − 2)', '2x(x − 2)', '4x(x − 2)', '2(x − 1)(x − 2)'], a: 0, x: 'Chain rule.' }] }),
  monoQ('Ex 6.2', 'Q9', 'Prove that y = 4 sin θ/(2 + cos θ) − θ is increasing in [0, π/2]', (t) => (4 * sin(t)) / (2 + cos(t)) - t, [0, PI / 2, -0.1, 0.35], [0, PI / 2], ['[0, π/2]'], { critLab: (c) => (c ? 'π/2' : '0'), dom: [0, PI / 2], only: 'inc', pre: [{ k: 'mcq', q: 'dy/dθ =', o: ['cos θ(4 − cos θ)/(2 + cos θ)²', '4 cos θ/(2 + cos θ)', '−sin θ/(2 + cos θ)²', '(4 − cos θ)/(2 + cos θ)'], a: 0, x: '≥ 0 on [0, π/2].' }] }),
  monoQ('Ex 6.2', 'Q10', 'Prove that the logarithmic function is increasing on (0, ∞)', log, [0.05, 5], [0, inf], ['(0, ∞)'], { only: 'inc', dom: [0, 99], iq: '(log x)′ = 1/x > 0. Increasing on' }),
  monoQ('Ex 6.2', 'Q11', 'Prove that f(x) = x² − x + 1 is neither strictly increasing nor decreasing on (−1, 1)', (x) => x * x - x + 1, [-1, 1, 0.5, 3.2], [-1, 0.5, 1], ['(−1, 1/2)', '(1/2, 1)'], { dom: [-1, 1], post: [{ k: 'tf', q: 'So on all of (−1, 1) f is neither', a: true, x: 'f′ = 2x − 1 changes sign at 1/2.' }] }),
  xs6('Ex 6.2', 'Q12', 'Which of these are decreasing on (0, π/2)? (A) cos x (B) cos 2x (C) cos 3x (D) tan x', [{ k: 'pick', q: 'Pick every decreasing one', pool: ['(A) cos x', '(B) cos 2x', '(C) cos 3x', '(D) tan x'], a: ['(A) cos x', '(B) cos 2x'], brace: false, x: 'cos 3x turns around at x = π/3; tan x increases.' }], '(A) and (B)', { scene: 'mono', setup: (W) => { monoSet(W, (x) => cos(3 * x), 0, PI / 2, { dom: [0, PI / 2], crit: [PI / 3], critLab: () => 'π/3', cap: 'cos 3x on (0, π/2)' }); } }),
  xs6('Ex 6.2', 'Q13', 'On which interval is f(x) = x¹⁰⁰ + sin x − 1 decreasing? (A) (0, 1) (B) (π/2, π) (C) (0, π/2) (D) none of these', [{ k: 'mcq', q: 'f′ = 100x⁹⁹ + cos x. On (0, 1) and (0, π/2) both terms are positive; on (π/2, π) 100x⁹⁹ is huge. So', o: ['(D) None of these', '(A)', '(B)', '(C)'], a: 0, x: 'f′ > 0 on every listed interval.' }], '(D)', { scene: 'mono', setup: (W) => monoSet(W, (x) => x ** 100 + sin(x) - 1, 0, 1.05, { dom: [0, 1.05], y: [-1.2, 1.5] }) }),
  xs6('Ex 6.2', 'Q14', 'For what values of a is f(x) = x² + ax + 1 increasing on [1, 2]?', [
    { k: 'task', q: 'Slide a down until the bottom of the parabola touches x = 1', pre: async (W) => { W.av = 0; W.F = (x) => (x * x + W.av * x + 1) / (W.ys || 1); W.asl = slider('a', -4, 1, 0.5, 0, (v) => 'a = ' + v, (v) => (W.av = v)); }, check: (W) => W.av === -2, auto: (W) => { W.av = -2; if (W.asl) W.asl.value = -2; } },
    { k: 'mcq', q: 'f′ = 2x + a ≥ 0 on [1, 2] needs 2 + a ≥ 0, so', o: ['a ≥ −2', 'a > −2 only', 'a ≤ −2', 'a = −2 only'], a: 0, x: 'At a = −2, f = (x − 1)² is still strictly increasing on [1, 2].' },
    sayJ('Answer-key check: the book’s answer is a > −2, but a = −2 also works, since f′(x) = 2x − 2 > 0 everywhere inside (1, 2). The full answer is a ≥ −2.'),
  ], 'a ≥ −2', { scene: 'mono', setup: (W) => { monoSet(W, (x) => x * x + 1, -2, 4, { y: [-4, 12], dom: [1, 2], crit: [1, 2] }); } }),
  monoQ('Ex 6.2', 'Q15', 'If I is any interval disjoint from [−1, 1], prove that f(x) = x + 1/x is increasing on I', (x) => x + 1 / x, [-4, 4, -6, 6], [-inf, -1, 0, 1, inf], ['(−∞, −1)', '(−1, 0)', '(0, 1)', '(1, ∞)'], { only: 'inc', iq: 'f′ = 1 − 1/x². Where is f increasing?' }),
  monoQ('Ex 6.2', 'Q16', 'Prove that log sin x is increasing on (0, π/2) and decreasing on (π/2, π)', (x) => log(sin(x)), [0.05, PI - 0.05, -3, 0.5], [0, PI / 2, PI], ['(0, π/2)', '(π/2, π)'], { critLab: (c) => (c > 2 ? 'π' : c > 1 ? 'π/2' : '0'), dom: [0, PI] }),
  monoQ('Ex 6.2', 'Q17', 'Prove that log|cos x| is decreasing on (0, π/2) and increasing on (3π/2, 2π)', (x) => log(abs(cos(x))), [0.05, 2 * PI - 0.05, -3, 0.5], [0, PI / 2, 3 * PI / 2, 2 * PI], ['(0, π/2)', '(π/2, 3π/2)', '(3π/2, 2π)'], { critLab: (c) => ['0', 'π/2', '3π/2', '2π'][[0, PI / 2, 3 * PI / 2, 2 * PI].findIndex((v) => Math.abs(v - c) < 1e-9)], dom: [0, 2 * PI], cap: 'f′ = −tan x' }),
  monoQ('Ex 6.2', 'Q18', 'Prove that f(x) = x³ − 3x² + 3x − 100 is increasing in ℝ', (x) => x ** 3 - 3 * x * x + 3 * x - 100, [-1, 3], [-inf, 1, inf], ['(−∞, 1)', '(1, ∞)'], { only: 'inc', iq: 'f′ = 3(x − 1)² ≥ 0. Increasing on', post: [{ k: 'tf', q: 'So f is increasing on all of ℝ (f′ = 0 only at the single point 1)', a: true, x: 'A lone zero of f′ does not stop it increasing.' }] }),
  monoQ('Ex 6.2', 'Q19', 'The interval in which y = x²e⁻ˣ is increasing is (A) (−∞, ∞) (B) (−2, 0) (C) (2, ∞) (D) (0, 2)', (x) => x * x * exp(-x), [-1, 6, -0.2, 1], [-inf, 0, 2, inf], ['(−∞, 0)', '(0, 2)', '(2, ∞)'], { only: 'inc', post: [{ k: 'mcq', q: 'Answer', o: ['(D) (0, 2)', '(A)', '(B)', '(C)'], a: 0, x: 'y′ = x(2 − x)e⁻ˣ.' }] }),
];

/* ===================== EXERCISE 6.3 ===================== */
const f53 = (x) => 3 * x ** 4 - 8 * x ** 3 + 12 * x * x - 48 * x + 25;
const EX63 = [
  extQ('Ex 6.3', 'Q1 (i)', 'Max and min values, if any: f(x) = (2x − 1)² + 3', (x) => (2 * x - 1) ** 2 + 3, [-1, 2], [0.5], [{ k: 'mcq', q: 'f has', o: ['minimum 3, no maximum', 'maximum 3', 'min 3 and max 4', 'neither'], a: 0, x: 'At x = 1/2.' }], 'Min 3, no max'),
  extQ('Ex 6.3', 'Q1 (ii)', 'Max and min values, if any: f(x) = 9x² + 12x + 2', (x) => 9 * x * x + 12 * x + 2, [-2, 1], [-2 / 3], [{ k: 'mcq', q: '9x² + 12x + 2 = (3x + 2)² − 2, so f has', o: ['minimum −2, no maximum', 'maximum −2', 'minimum 2', 'neither'], a: 0, x: 'At x = −2/3.' }], 'Min −2, no max', { critLab: () => '−2/3' }),
  extQ('Ex 6.3', 'Q1 (iii)', 'Max and min values, if any: f(x) = −(x − 1)² + 10', (x) => -((x - 1) ** 2) + 10, [-2, 4], [1], [{ k: 'mcq', q: 'f has', o: ['maximum 10, no minimum', 'minimum 10', 'both', 'neither'], a: 0, x: 'At x = 1.' }], 'Max 10, no min'),
  extQ('Ex 6.3', 'Q1 (iv)', 'Max and min values, if any: g(x) = x³ + 1', (x) => x ** 3 + 1, [-2, 2], [0], [{ k: 'mcq', q: 'g has', o: ['neither max nor min', 'min 1', 'max 1', 'both'], a: 0, x: 'It runs from −∞ to ∞.' }], 'Neither', { flat: true }),
  extQ('Ex 6.3', 'Q2 (i)', 'Max and min values, if any: f(x) = |x + 2| − 1', (x) => abs(x + 2) - 1, [-5, 1], [-2], [{ k: 'mcq', q: 'f has', o: ['minimum −1, no maximum', 'maximum −1', 'minimum 1', 'neither'], a: 0, x: 'At x = −2.' }], 'Min −1, no max'),
  extQ('Ex 6.3', 'Q2 (ii)', 'Max and min values, if any: g(x) = −|x + 1| + 3', (x) => -abs(x + 1) + 3, [-4, 2], [-1], [{ k: 'mcq', q: 'g has', o: ['maximum 3, no minimum', 'minimum 3', 'both', 'neither'], a: 0, x: 'At x = −1.' }], 'Max 3, no min'),
  extQ('Ex 6.3', 'Q2 (iii)', 'Max and min values, if any: h(x) = sin 2x + 5', (x) => sin(2 * x) + 5, [-3.2, 3.2, 3.5, 6.5], [], [fld('Values', [{ l: 'max', a: 6 }, { l: 'min', a: 4 }], '5 ± 1.')], 'Max 6, min 4'),
  extQ('Ex 6.3', 'Q2 (iv)', 'Max and min values, if any: f(x) = |sin 4x + 3|', (x) => abs(sin(4 * x) + 3), [-1.6, 1.6, 1.5, 4.5], [], [fld('Values', [{ l: 'max', a: 4 }, { l: 'min', a: 2 }], 'sin 4x + 3 is between 2 and 4, always positive.')], 'Max 4, min 2'),
  extQ('Ex 6.3', 'Q2 (v)', 'Max and min values, if any: h(x) = x + 1, x ∈ (−1, 1)', (x) => (x <= -1 || x >= 1 ? NaN : x + 1), [-1.5, 1.5, -0.5, 2.5], [], [{ k: 'mcq', q: 'On the open interval h has', o: ['neither max nor min', 'max 2', 'min 0', 'both'], a: 0, x: 'The ends 0 and 2 are never reached.' }], 'Neither', { dom: [-1, 1] }),
  extQ('Ex 6.3', 'Q3 (i)', 'Local maxima/minima and values: f(x) = x²', (x) => x * x, [-2, 2], [0], [fld('Local minimum', [{ l: 'at x', a: 0 }, { l: 'value', a: 0 }], 'Local min 0 at x = 0.')], 'Local min 0 at x = 0'),
  extQ('Ex 6.3', 'Q3 (ii)', 'Local maxima/minima and values: g(x) = x³ − 3x', (x) => x ** 3 - 3 * x, [-2.5, 2.5], [-1, 1], [fld('g′ = 3(x² − 1)', [{ l: 'local max at x', a: -1 }, { l: 'value', a: 2 }, { l: 'local min at x', a: 1 }, { l: 'value ', a: -2 }], 'Max 2 at −1, min −2 at 1.')], 'Local max 2 at x = −1; local min −2 at x = 1'),
  extQ('Ex 6.3', 'Q3 (iii)', 'Local maxima/minima and values: h(x) = sin x + cos x, 0 < x < π/2', (x) => sin(x) + cos(x), [0, PI / 2, 0.8, 1.6], [PI / 4], [fld('Local maximum (type with π, √)', [{ l: 'at x', a: PI / 4, show: 'π/4', tol: 1e-3 }, { l: 'value', a: R2, show: '√2', tol: 1e-3 }], 'Max √2 at π/4.', { keys: 'π √' })], 'Local max √2 at x = π/4', { critLab: () => 'π/4', dom: [0, PI / 2] }),
  extQ('Ex 6.3', 'Q3 (iv)', 'Local maxima/minima and values: f(x) = sin x − cos x, 0 < x < 2π', (x) => sin(x) - cos(x), [0, 2 * PI, -1.6, 1.6], [3 * PI / 4, 7 * PI / 4], [fld('f′ = cos x + sin x = 0 (type with π, √)', [{ l: 'local max at x', a: (3 * PI) / 4, show: '3π/4', tol: 1e-3 }, { l: 'value', a: R2, show: '√2', tol: 1e-3 }, { l: 'local min at x', a: (7 * PI) / 4, show: '7π/4', tol: 1e-3 }, { l: 'value ', a: -R2, show: '−√2', tol: 1e-3 }], 'Max √2 at 3π/4, min −√2 at 7π/4.', { keys: 'π √' })], 'Local max √2 at 3π/4; local min −√2 at 7π/4', { critLab: (c) => (c < 3 ? '3π/4' : '7π/4'), dom: [0, 2 * PI] }),
  extQ('Ex 6.3', 'Q3 (v)', 'Local maxima/minima and values: f(x) = x³ − 6x² + 9x + 15', (x) => x ** 3 - 6 * x * x + 9 * x + 15, [-0.5, 4.5], [1, 3], [fld('f′ = 3(x − 1)(x − 3)', [{ l: 'local max value f(1)', a: 19 }, { l: 'local min value f(3)', a: 15 }], 'Max 19 at 1, min 15 at 3.')], 'Local max 19 at x = 1; local min 15 at x = 3'),
  extQ('Ex 6.3', 'Q3 (vi)', 'Local maxima/minima and values: g(x) = x/2 + 2/x, x > 0', (x) => x / 2 + 2 / x, [0.3, 6, 1, 5], [2], [fld('g′ = 1/2 − 2/x²', [{ l: 'local min at x', a: 2 }, { l: 'value', a: 2 }], 'Min 2 at x = 2.')], 'Local min 2 at x = 2', { dom: [0, 99] }),
  extQ('Ex 6.3', 'Q3 (vii)', 'Local maxima/minima and values: g(x) = 1/(x² + 2)', (x) => 1 / (x * x + 2), [-3, 3, -0.1, 0.7], [0], [fld('Local maximum', [{ l: 'at x', a: 0 }, { l: 'value', a: 0.5, show: '1/2' }], 'Max 1/2 at x = 0.')], 'Local max 1/2 at x = 0'),
  extQ('Ex 6.3', 'Q3 (viii)', 'Local maxima/minima and values: f(x) = x√(1 − x), 0 < x < 1', (x) => x * sqrt(1 - x), [0, 1, -0.05, 0.5], [2 / 3], [fld('f′ = (2 − 3x)/(2√(1 − x))', [{ l: 'local max at x', a: 2 / 3, show: '2/3' }, { l: 'value', a: (2 * R3) / 9, show: '2√3/9', tol: 1e-3 }], 'Max 2√3/9 at x = 2/3.', { keys: '√' })], 'Local max 2√3/9 at x = 2/3', { critLab: () => '2/3', dom: [0, 1] }),
  xs6('Ex 6.3', 'Q4', 'Prove that eˣ, log x and x³ + x² + x + 1 have no maxima or minima', [{ k: 'match', q: 'Match each function with why f′ never vanishes', L: ['eˣ', 'log x', 'x³ + x² + x + 1'], R: ['f′ = 1/x > 0 for x > 0', 'f′ = 3x² + 2x + 1 > 0 (discriminant < 0)', 'f′ = eˣ > 0'], a: [2, 0, 1] }], 'f′ never changes sign, so there are no extrema'),
  extQ('Ex 6.3', 'Q5 (i)', 'Absolute max and min: f(x) = x³ on [−2, 2]', (x) => x ** 3, [-2, 2], [-2, 0, 2], [fld('Check 0 and both ends', [{ l: 'max', a: 8 }, { l: 'min', a: -8 }], 'Max 8 at x = 2, min −8 at x = −2.')], 'Max 8, min −8', { dom: [-2, 2], flat: true }),
  extQ('Ex 6.3', 'Q5 (ii)', 'Absolute max and min: f(x) = sin x + cos x on [0, π]', (x) => sin(x) + cos(x), [0, PI, -1.2, 1.6], [0, PI / 4, PI], [fld('Values at 0, π/4, π (type with √)', [{ l: 'max', a: R2, show: '√2', tol: 1e-3 }, { l: 'min', a: -1 }], 'Max √2 at π/4, min −1 at π.', { keys: '√' })], 'Max √2, min −1', { dom: [0, PI], critLab: (c) => (c > 3 ? 'π' : c > 0.5 ? 'π/4' : '0') }),
  extQ('Ex 6.3', 'Q5 (iii)', 'Absolute max and min: f(x) = 4x − x²/2 on [−2, 9/2]', (x) => 4 * x - (x * x) / 2, [-2, 4.5], [-2, 4, 4.5], [fld('f′ = 4 − x = 0 at 4', [{ l: 'max', a: 8 }, { l: 'min', a: -10 }], 'f(4) = 8, f(−2) = −10, f(9/2) = 63/8.')], 'Max 8, min −10', { dom: [-2, 4.5] }),
  extQ('Ex 6.3', 'Q5 (iv)', 'Absolute max and min: f(x) = (x − 1)² + 3 on [−3, 1]', (x) => (x - 1) ** 2 + 3, [-3, 1], [-3, 1], [fld('Decreasing on the whole interval', [{ l: 'max', a: 19 }, { l: 'min', a: 3 }], 'f(−3) = 19, f(1) = 3.')], 'Max 19, min 3', { dom: [-3, 1] }),
  xs6('Ex 6.3', 'Q6', 'Find the maximum profit if p(x) = 41 − 72x − 18x²', [numP('p′ = −72 − 36x = 0 at x = −2. Maximum profit p(−2) = ?', 113, '113 (p″ = −36 < 0).')], 'Maximum profit 113', { scene: 'mono', setup: (W) => monoSet(W, (x) => 41 - 72 * x - 18 * x * x, -5, 1, { crit: [-2] }) }),
  extQ('Ex 6.3', 'Q7', 'Find the max and min values of 3x⁴ − 8x³ + 12x² − 48x + 25 on [0, 3]', f53, [0, 3, -45, 30], [0, 2, 3], [{ k: 'mcq', q: 'f′ = 12(x − 2)(x² + 2), so the only critical point is', o: ['x = 2', 'x = 0', 'x = ±√2', 'none'], a: 0, x: 'x² + 2 never vanishes.' }, fld('Compare f(0), f(2), f(3)', [{ l: 'max', a: 25 }, { l: 'min', a: -39 }], 'f(0) = 25, f(2) = −39, f(3) = 16.')], 'Max 25, min −39', { dom: [0, 3] }),
  xs6('Ex 6.3', 'Q8', 'At what points in [0, 2π] does sin 2x attain its maximum?', [{ k: 'pick', q: 'Pick every point', pool: ['π/4', '3π/4', '5π/4', '7π/4', 'π/2'], a: ['π/4', '5π/4'], brace: false, x: '2x = π/2 or 5π/2.' }], 'x = π/4 and 5π/4', { scene: 'mono', setup: (W) => monoSet(W, (x) => sin(2 * x), 0, 2 * PI, { dom: [0, 2 * PI] }) }),
  xs6('Ex 6.3', 'Q9', 'What is the maximum value of sin x + cos x?', [numP('√2 sin(x + π/4) has maximum ? (type with √)', R2, '√2.', { show: '√2', keys: '√', tol: 1e-3 })], '√2', { scene: 'mono', setup: (W) => monoSet(W, (x) => sin(x) + cos(x), -PI, PI) }),
  extQ('Ex 6.3', 'Q10', 'Max of 2x³ − 24x + 107 on [1, 3], and on [−3, −1]', (x) => 2 * x ** 3 - 24 * x + 107, [-3.5, 3.5], [-2, 2], [fld('f′ = 6(x² − 4)', [{ l: 'max on [1, 3]', a: 89 }, { l: 'max on [−3, −1]', a: 139 }], 'f(1) = 85, f(2) = 75, f(3) = 89; f(−3) = 125, f(−2) = 139, f(−1) = 129.')], '89 on [1, 3]; 139 on [−3, −1]'),
  xs6('Ex 6.3', 'Q11', 'x⁴ − 62x² + ax + 9 attains its maximum on [0, 2] at x = 1. Find a', [numP('f′(1) = 4 − 124 + a = 0, so a = ?', 120, 'a = 120.')], 'a = 120', { scene: 'mono', setup: (W) => monoSet(W, (x) => x ** 4 - 62 * x * x + 120 * x + 9, 0, 2, { dom: [0, 2], crit: [1] }) }),
  extQ('Ex 6.3', 'Q12', 'Find the max and min values of x + sin 2x on [0, 2π]', (x) => x + sin(2 * x), [0, 2 * PI], [PI / 3, (2 * PI) / 3, (4 * PI) / 3, (5 * PI) / 3], [{ k: 'mcq', q: 'f′ = 1 + 2 cos 2x = 0 at π/3, 2π/3, 4π/3, 5π/3. Comparing with the ends:', o: ['max 2π at x = 2π, min 0 at x = 0', 'max 4π/3 + √3/2, min π/3 − √3/2', 'max 2π, min 2π/3 − √3/2', 'max 5π/3, min 0'], a: 0, x: 'f(2π) = 2π ≈ 6.28 beats f(4π/3) ≈ 5.05; f(0) = 0 is below f(2π/3) ≈ 1.23.' }], 'Max 2π, min 0', { dom: [0, 2 * PI], critLab: (c) => ({ 1: 'π/3', 2: '2π/3', 4: '4π/3', 5: '5π/3' })[Math.round((c * 3) / PI)] }),
  optQ('Ex 6.3', 'Q13', 'Find two numbers whose sum is 24 and whose product is as large as possible', (x) => x * (24 - x), 0, 24, 12, (W, x) => PIC.split(W, x, 24, 'x', '24 − x'), { step: 0.5, flab: 'x(24 − x)', fields: [{ l: 'x', a: 12 }, { l: '24 − x', a: 12 }], x: '12 and 12.' }),
  optQ('Ex 6.3', 'Q14', 'Find positive x, y with x + y = 60 and xy³ maximum', (x) => x * (60 - x) ** 3, 0, 60, 15, (W, x) => PIC.split(W, x, 60, 'x', 'y'), { step: 0.5, flab: 'xy³', fields: [{ l: 'x', a: 15 }, { l: 'y', a: 45 }], x: 'f′ = (60 − x)²(60 − 4x) = 0.' }),
  optQ('Ex 6.3', 'Q15', 'Find positive x, y with x + y = 35 and x²y⁵ maximum', (x) => x * x * (35 - x) ** 5, 0, 35, 10, (W, x) => PIC.split(W, x, 35, 'x', 'y'), { step: 0.5, flab: 'x²y⁵', fields: [{ l: 'x', a: 10 }, { l: 'y', a: 25 }], x: 'x(35 − x)⁴(70 − 7x) = 0.' }),
  optQ('Ex 6.3', 'Q16', 'Find two positive numbers whose sum is 16 and the sum of whose cubes is minimum', (x) => x ** 3 + (16 - x) ** 3, 0, 16, 8, (W, x) => PIC.split(W, x, 16, 'x', '16 − x'), { min: true, step: 0.5, flab: 'x³ + (16 − x)³', fields: [{ l: 'x', a: 8 }, { l: '16 − x', a: 8 }], x: '3x² − 3(16 − x)² = 0.' }),
  optQ('Ex 6.3', 'Q17', 'An 18 cm square of tin: cut equal squares from the corners to make the largest open box. Side of the cut square?', (x) => x * (18 - 2 * x) ** 2, 0, 9, 3, (W, x) => PIC.box(W, x, 18, 18), { step: 0.1, fields: [{ l: 'cut', a: 3, post: 'cm' }], x: 'V′ = (18 − 2x)(18 − 6x) = 0 ⇒ x = 3.' }),
  optQ('Ex 6.3', 'Q18', 'A 45 cm × 24 cm sheet: cut equal corner squares for the largest open box. Side of the cut square?', (x) => x * (45 - 2 * x) * (24 - 2 * x), 0, 12, 5, (W, x) => PIC.box(W, x, 24, 45), { step: 0.1, fields: [{ l: 'cut', a: 5, post: 'cm' }], x: 'V′ = 12(x − 5)(x − 18); x = 18 is too big.' }),
  optQ('Ex 6.3', 'Q19', 'Show that of all rectangles inscribed in a fixed circle, the square has the maximum area', (t) => 4 * cos(t) * sin(t), 0.05, PI / 2 - 0.05, PI / 4, (W, t) => PIC.rectCircle(W, t), { step: 0.01, xlab: 'angle θ', flab: 'area/R²', x0: 0.3, post: [{ k: 'mcq', q: 'Area = 2R² sin 2θ is largest at θ = π/4, where width = height. So the rectangle is', o: ['a square', 'twice as wide as tall', 'degenerate', 'any rectangle'], a: 0, x: 'Width = height = √2 R.' }], w: 'Area 2R² sin 2θ is greatest at θ = π/4: a square' }),
  optQ('Ex 6.3', 'Q20', 'Show that the closed cylinder of given surface area and maximum volume has height equal to the diameter', (r) => r * (6 * PI - 2 * PI * r * r) / 2, 0.1, 1.7, 1, (W, r) => { const { cx, cy } = LP(); const k = Math.min(SW * 0.08, SH * 0.12), h = (6 * PI - 2 * PI * r * r) / (2 * PI * r); ctx.fillStyle = C['sora-tint']; ctx.strokeStyle = C.ink; ctx.lineWidth = 2; ctx.fillRect(cx - r * k, cy - (h / 2) * k * 0.5, 2 * r * k, h * k * 0.5); ctx.strokeRect(cx - r * k, cy - (h / 2) * k * 0.5, 2 * r * k, h * k * 0.5); D.text('h = ' + fmtN(h, 2) + ', 2r = ' + fmtN(2 * r, 2), cx, cy + 3 * k * 0.5 + 18, { size: 12, w: 800 }); }, { step: 0.01, xlab: 'r', flab: 'V (S = 6π)', post: [{ k: 'tf', q: 'At the best r, h = 2r', a: true, x: 'With S fixed, V = (Sr − 2πr³)/2; V′ = 0 gives S = 6πr², so h = 2r.' }], w: 'h = 2r (the diameter)' }),
  optQ('Ex 6.3', 'Q21', 'Of all closed cylindrical cans of volume 100 cm³, find the dimensions with the least surface area', (r) => 2 * PI * r * r + 200 / r, 1, 6, cbrt(50 / PI), (W, r) => { const { cx, cy } = LP(); const k = Math.min(SW * 0.03, SH * 0.05), h = 100 / (PI * r * r); ctx.fillStyle = C['kin-tint']; ctx.strokeStyle = C.ink; ctx.lineWidth = 2; ctx.fillRect(cx - r * k, cy - (h / 2) * k, 2 * r * k, h * k); ctx.strokeRect(cx - r * k, cy - (h / 2) * k, 2 * r * k, h * k); D.text('r = ' + fmtN(r, 2) + ', h = ' + fmtN(h, 2), cx, cy + 6 * k + 10, { size: 12, w: 800 }); }, { min: true, step: 0.01, xlab: 'r', flab: 'surface S', fields: [{ l: 'r ≈', a: cbrt(50 / PI), tol: 0.01, show: fmtN(cbrt(50 / PI), 3) }, { l: 'h = 2r ≈', a: 2 * cbrt(50 / PI), tol: 0.02, show: fmtN(2 * cbrt(50 / PI), 3) }], x: 'r = (50/π)^(1/3) ≈ 2.52 cm, h = 2(50/π)^(1/3) ≈ 5.03 cm.', w: 'r = (50/π)^(1/3) cm, h = 2(50/π)^(1/3) cm' }),
  optQ('Ex 6.3', 'Q22', 'A 28 m wire is cut into a square and a circle. Where to cut for the least combined area?', (x) => (x * x) / 16 + (28 - x) ** 2 / (4 * PI), 0, 28, 112 / (PI + 4), (W, x) => { PIC.split(W, x, 28, 'square', 'circle'); const { cx, cy } = LP(); const k = Math.min(SW * 0.006, SH * 0.01) * 1.4; ctx.strokeStyle = C.ink; ctx.lineWidth = 2; ctx.fillStyle = C.kin; ctx.fillRect(cx - 60 - (x / 4) * k, cy + 50, (x / 4) * k * 2, (x / 4) * k * 2); ctx.fillStyle = C['sora-tint']; ctx.beginPath(); ctx.arc(cx + 60, cy + 50 + ((28 - x) / (2 * PI)) * k, ((28 - x) / (2 * PI)) * k * 2, 0, 7); ctx.fill(); ctx.stroke(); }, { min: true, step: 0.05, xlab: 'square piece', flab: 'total area', fields: [{ l: 'square piece', a: 112 / (PI + 4), show: '112/(π + 4)', keys: 'π', tol: 1e-3 }, { l: 'circle piece', a: (28 * PI) / (PI + 4), show: '28π/(π + 4)', tol: 1e-3 }], keys: 'π', x: 'x/8 − (28 − x)/(2π) = 0.', w: 'Square piece 112/(π + 4) m, circle piece 28π/(π + 4) m' }),
  optQ('Ex 6.3', 'Q23', 'Prove that the largest cone inscribed in a sphere of radius R has volume 8/27 of the sphere', (h) => (PI / 3) * h * h * (2 - h), 0.05, 2, 4 / 3, (W, h) => PIC.coneIn(W, h, 1), { step: 0.01, xlab: 'height h (R = 1)', flab: 'cone volume', post: [numP('Largest volume ÷ sphere volume (4π/3) = ?', 8 / 27, 'At h = 4R/3: V = (32/81)πR³ = (8/27)(4/3)πR³.', { show: '8/27' })], w: 'V_max = (8/27)·(4/3)πR³ at h = 4R/3' }),
  optQ('Ex 6.3', 'Q24', 'Show that the cone of least curved surface and given volume has altitude √2 × radius', (r) => PI * r * sqrt(r * r + (9 / (PI * r * r)) ** 2), 0.5, 3, Math.pow(9 / (PI * R2), 1 / 3), (W, r) => { const { cx, cy } = LP(); const k = Math.min(SW * 0.05, SH * 0.08), h = 9 / (PI * r * r); ctx.fillStyle = C['kin-tint']; ctx.strokeStyle = C.ink; ctx.lineWidth = 2; ctx.beginPath(); ctx.moveTo(cx, cy - (h / 2) * k); ctx.lineTo(cx - r * k, cy + (h / 2) * k); ctx.lineTo(cx + r * k, cy + (h / 2) * k); ctx.closePath(); ctx.fill(); ctx.stroke(); D.text('h/r = ' + fmtN(h / r, 3), cx, cy + (h / 2) * k + 18, { size: 12, w: 800 }); }, { min: true, step: 0.005, xlab: 'r (V = 3)', flab: 'curved surface', post: [{ k: 'tf', q: 'At the best r the readout h/r is about 1.414 = √2', a: true, x: 'Minimise S² = π²r²(r² + h²) with r²h fixed: h² = 2r².' }], w: 'h = √2 r' }),
  optQ('Ex 6.3', 'Q25', 'Show that the cone of given slant height and maximum volume has semi-vertical angle tan⁻¹√2', (t) => (PI / 3) * sin(t) ** 2 * cos(t), 0.05, PI / 2 - 0.05, atan(R2), (W, t) => { const { cx, cy } = LP(); const k = Math.min(SW * 0.16, SH * 0.28); ctx.fillStyle = C['kin-tint']; ctx.strokeStyle = C.ink; ctx.lineWidth = 2; ctx.beginPath(); ctx.moveTo(cx, cy - (cos(t) / 2) * k); ctx.lineTo(cx - sin(t) * k, cy + (cos(t) / 2) * k); ctx.lineTo(cx + sin(t) * k, cy + (cos(t) / 2) * k); ctx.closePath(); ctx.fill(); ctx.stroke(); D.text('θ = ' + fmtN(t, 3) + ' rad', cx, cy + k * 0.7, { size: 12, w: 800 }); }, { step: 0.005, xlab: 'θ (slant = 1)', flab: 'volume', post: [numP('tan θ at the best angle = ? (type with √)', R2, 'V ∝ sin²θ cos θ; V′ = 0 ⇒ tan²θ = 2.', { show: '√2', keys: '√', tol: 1e-3 })], w: 'θ = tan⁻¹√2' }),
  optQ('Ex 6.3', 'Q26', 'Show that the cone of given surface area and maximum volume has semi-vertical angle sin⁻¹(1/3)', (s) => { const r = sqrt(1 / (PI * (1 + 1 / s))); const l = r / s; return (PI / 3) * r * r * sqrt(Math.max(0, l * l - r * r)); }, 0.05, 0.95, 1 / 3, (W, s) => { const { cx, cy } = LP(); const k = Math.min(SW * 0.16, SH * 0.28), c = sqrt(1 - s * s); ctx.fillStyle = C['kin-tint']; ctx.strokeStyle = C.ink; ctx.lineWidth = 2; ctx.beginPath(); ctx.moveTo(cx, cy - (c / 2) * k); ctx.lineTo(cx - s * k, cy + (c / 2) * k); ctx.lineTo(cx + s * k, cy + (c / 2) * k); ctx.closePath(); ctx.fill(); ctx.stroke(); }, { step: 0.005, xlab: 'sin θ (area fixed)', flab: 'volume', post: [numP('sin θ at the best angle = ?', 1 / 3, 'V² ∝ S(S − 2πr²)r²; V′ = 0 ⇒ l = 3r, sin θ = r/l = 1/3.', { show: '1/3', tol: 1e-3 })], w: 'θ = sin⁻¹(1/3)' }),
  xs6('Ex 6.3', 'Q27', 'The point on x² = 2y nearest to (0, 5) is (A) (2√2, 4) (B) (2√2, 0) (C) (0, 0) (D) (2, 2)', [{ k: 'mcq', q: 'D² = x² + (x²/2 − 5)² = 2y + (y − 5)² is least at y = 4. So', o: ['(A) (2√2, 4)', '(B) (2√2, 0)', '(C) (0, 0)', '(D) (2, 2)'], a: 0, x: 'x² = 8.' }], '(A)', { scene: 'opt', setup: (W) => optSet(W, (y) => sqrt(2 * y + (y - 5) ** 2), 0, 8, 4, null, { xlab: 'y', flab: 'distance' }) }),
  xs6('Ex 6.3', 'Q28', 'For all real x, the minimum of (1 − x + x²)/(1 + x + x²) is (A) 0 (B) 1 (C) 3 (D) 1/3', [{ k: 'mcq', q: 'The derivative is 2(x² − 1)/(1 + x + x²)²: minimum at x = 1, value', o: ['(D) 1/3', '(A) 0', '(B) 1', '(C) 3'], a: 0, x: '(1 − 1 + 1)/(1 + 1 + 1).' }], '(D)', { scene: 'mono', setup: (W) => monoSet(W, (x) => (1 - x + x * x) / (1 + x + x * x), -4, 4, { crit: [-1, 1] }) }),
  xs6('Ex 6.3', 'Q29', 'The maximum of [x(x − 1) + 1]^(1/3), 0 ≤ x ≤ 1, is (A) (1/3)^(1/3) (B) 1/2 (C) 1 (D) 0', [{ k: 'mcq', q: 'x² − x + 1 is least at x = 1/2 and largest (= 1) at the ends. So the maximum is', o: ['(C) 1', '(A) (1/3)^(1/3)', '(B) 1/2', '(D) 0'], a: 0, x: 'Attained at x = 0 and x = 1.' }], '(C)', { scene: 'mono', setup: (W) => monoSet(W, (x) => cbrt(x * (x - 1) + 1), 0, 1, { dom: [0, 1], crit: [0.5] }) }),
];

/* ===================== MISCELLANEOUS ===================== */
const EX6M = [
  extQ('Misc', 'Q1', 'Show that f(x) = log x / x has a maximum at x = e', (x) => log(x) / x, [0.5, 8, -1, 0.5], [E], [{ k: 'mcq', q: 'f′ = (1 − log x)/x² is + before e and − after, so', o: ['local (and absolute) max at x = e, value 1/e', 'min at e', 'max at 1', 'no extremum'], a: 0, x: 'f(e) = 1/e.' }], 'Maximum 1/e at x = e', { critLab: () => 'e', dom: [0, 99] }),
  xs6('Misc', 'Q2', 'An isosceles triangle with fixed base b: the equal sides shrink at 3 cm/s. How fast is the area decreasing when the equal sides equal the base?', [{ k: 'mcq', q: 'A = (b/4)√(4x² − b²), so dA/dt = bx/√(4x² − b²) · dx/dt. At x = b:', o: ['dA/dt = −√3 b (decreasing at √3 b cm²/s)', '−3b', '−b/√3', '−3√3 b'], a: 0, x: 'b²/(√3 b) · (−3) = −√3 b.' }, numP('With b = 2 cm, the area falls at ? cm²/s (2 decimals)', 2 * R3, '2√3 ≈ 3.46.', { tol: 0.011, show: fmtN(2 * R3, 3) })], '√3 b cm²/s'),
  monoQ('Misc', 'Q3', 'Intervals where f(x) = (4 sin x − 2x − x cos x)/(2 + cos x) is (i) increasing (ii) decreasing', (x) => (4 * sin(x) - 2 * x - x * cos(x)) / (2 + cos(x)), [0, 2 * PI, -4, 1.5], [0, PI / 2, (3 * PI) / 2, 2 * PI], ['(0, π/2)', '(π/2, 3π/2)', '(3π/2, 2π)'], { dom: [0, 2 * PI], critLab: (c) => ['0', 'π/2', '3π/2', '2π'][Math.round(c / (PI / 2)) === 0 ? 0 : Math.round(c / (PI / 2)) === 1 ? 1 : Math.round(c / (PI / 2)) === 3 ? 2 : 3], pre: [{ k: 'mcq', q: 'f = 4 sin x/(2 + cos x) − x, so f′ =', o: ['cos x(4 − cos x)/(2 + cos x)²', '4 cos x/(2 + cos x) − 1', '(4 − cos x)/(2 + cos x)', '−cos x/(2 + cos x)'], a: 0, x: 'Sign of cos x.' }] }),
  monoQ('Misc', 'Q4', 'Intervals where f(x) = x³ + 1/x³, x ≠ 0, is (i) increasing (ii) decreasing', (x) => x ** 3 + 1 / x ** 3, [-2.5, 2.5, -12, 12], [-inf, -1, 0, 1, inf], ['(−∞, −1)', '(−1, 0)', '(0, 1)', '(1, ∞)'], { pre: [{ k: 'mcq', q: 'f′ =', o: ['3(x⁶ − 1)/x⁴', '3x² + 3/x⁴', '3x² − 1/x⁴', '(x⁶ − 1)/x³'], a: 0, x: '3x² − 3x⁻⁴.' }] }),
  optQ('Misc', 'Q5', 'Find the maximum area of an isosceles triangle inscribed in x²/a² + y²/b² = 1 with its vertex at one end of the major axis', (t) => (1 + cos(t)) * sin(t), 0.05, PI - 0.05, PI / 3, (W, t) => { const { cx, cy } = LP(); const A = Math.min(SW * 0.17, SH * 0.3), B = A * 0.6; ctx.strokeStyle = C.ink; ctx.lineWidth = 2; ctx.beginPath(); ctx.ellipse(cx, cy, A, B, 0, 0, 7); ctx.stroke(); ctx.fillStyle = C['kin-tint']; ctx.beginPath(); ctx.moveTo(cx + A, cy); ctx.lineTo(cx - A * cos(t), cy - B * sin(t)); ctx.lineTo(cx - A * cos(t), cy + B * sin(t)); ctx.closePath(); ctx.fill(); ctx.stroke(); }, { step: 0.01, xlab: 'θ', flab: 'area/ab', post: [{ k: 'mcq', q: 'At θ = π/3 the area is', o: ['(3√3/4) ab', '(√3/2) ab', 'ab', '2ab'], a: 0, x: 'ab(1 + cos θ) sin θ at π/3 = ab(3/2)(√3/2).' }], w: 'Maximum area (3√3/4)ab' }),
  optQ('Misc', 'Q6', 'An open tank, depth 2 m, volume 8 m³: base costs ₹70/m², sides ₹45/m². Cost of the least expensive tank?', (l) => 280 + 180 * (l + 4 / l), 0.5, 6, 2, (W, l) => PIC.split(W, l, 6.5, 'length', ''), { min: true, step: 0.05, xlab: 'length l (width 4/l)', flab: 'cost ₹', fields: [{ l: 'least cost ₹', a: 1000 }], x: 'l = w = 2: 280 + 180·4 = 1000.', w: '₹1000' }),
  xs6('Misc', 'Q7', 'Perimeter of a circle plus a square is k. Prove the sum of their areas is least when the side of the square is double the radius', [{ k: 'order', q: 'Order the proof', s: ['2πr + 4a = k, so a = (k − 2πr)/4', 'A = πr² + (k − 2πr)²/16', "A′ = 2πr − π(k − 2πr)/4 = 0", 'k = 2πr + 8r, so a = (k − 2πr)/4 = 2r'] }], 'Least when a = 2r'),
  optQ('Misc', 'Q8', 'A window: rectangle with a semicircle on top, perimeter 10 m. Dimensions for maximum light?', (x) => { const y = (10 - x - (PI * x) / 2) / 2; return y < 0 ? NaN : x * y + (PI * x * x) / 8; }, 0.2, 3.8, 20 / (PI + 4), (W, x) => PIC.window(W, x, 10), { step: 0.01, xlab: 'width', flab: 'area', fields: [{ l: 'width', a: 20 / (PI + 4), show: '20/(π + 4)', tol: 1e-3 }, { l: 'rectangle height', a: 10 / (PI + 4), show: '10/(π + 4)', tol: 1e-3 }], keys: 'π', x: 'Width 20/(π + 4) m, height of the rectangle 10/(π + 4) m.', w: 'Width 20/(π + 4) m, height 10/(π + 4) m' }),
  optQ('Misc', 'Q9', 'A point on the hypotenuse is at distances a and b from the sides. Show the least hypotenuse is (a^(2/3) + b^(2/3))^(3/2)', (t) => 1 / sin(t) + 8 / cos(t), 0.05, PI / 2 - 0.05, atan(cbrt(1 / 8)), (W, t) => { const { cx, cy } = LP(); const k = Math.min(SW * 0.02, SH * 0.035); const L1 = 1 / sin(t), L2 = 8 / cos(t); const X = cx - 8 * k * 0.5, Y = cy + 4 * k; ctx.strokeStyle = C.ink; ctx.lineWidth = 2; ctx.beginPath(); ctx.moveTo(X, Y); ctx.lineTo(X + (L1 + L2) * cos(t) * k * 0.5, Y); ctx.moveTo(X, Y); ctx.lineTo(X, Y - (L1 + L2) * sin(t) * k * 0.5); ctx.stroke(); ctx.strokeStyle = C.beni; ctx.beginPath(); ctx.moveTo(X + (L1 + L2) * cos(t) * k * 0.5, Y); ctx.lineTo(X, Y - (L1 + L2) * sin(t) * k * 0.5); ctx.stroke(); }, { min: true, step: 0.005, xlab: 'angle θ', flab: 'hypotenuse (a = 1, b = 8)', post: [numP('Least length with a = 1, b = 8: (1 + 4)^(3/2) = ? (2 decimals)', 5 ** 1.5, '5√5 ≈ 11.18.', { tol: 0.011, show: fmtN(5 ** 1.5, 3) })], w: '(a^(2/3) + b^(2/3))^(3/2)' }),
  extQ('Misc', 'Q10', 'f(x) = (x − 2)⁴(x + 1)³: find the points of (i) local maxima (ii) local minima (iii) inflexion', (x) => (x - 2) ** 4 * (x + 1) ** 3, [-1.6, 2.6, -15, 25], [-1, 2 / 7, 2], [{ k: 'mcq', q: 'f′ = (x − 2)³(x + 1)²(7x − 2). Classify:', o: ['max at 2/7, min at 2, inflexion at −1', 'max at 2, min at 2/7, inflexion at −1', 'max at −1, min at 2', 'min at 2/7, max at 2, inflexion at −1'], a: 0, x: '(x + 1)² does not change sign.' }], 'Local max at x = 2/7, local min at x = 2, inflexion at x = −1', { flat: true, critLab: (c) => (c > 1 ? '2' : c > 0 ? '2/7' : '−1') }),
  extQ('Misc', 'Q11', 'Absolute max and min of f(x) = cos²x + sin x on [0, π]', (x) => cos(x) ** 2 + sin(x), [0, PI, 0.8, 1.35], [0, PI / 6, PI / 2, (5 * PI) / 6, PI], [fld('f′ = cos x(1 − 2 sin x)', [{ l: 'max', a: 5 / 4, show: '5/4' }, { l: 'min', a: 1 }], 'f = 1, 5/4, 1, 5/4, 1 at 0, π/6, π/2, 5π/6, π.')], 'Max 5/4, min 1', { dom: [0, PI], critLab: (c) => ['0', 'π/6', 'π/2', '5π/6', 'π'][Math.round((c / PI) * 6) === 0 ? 0 : Math.round((c / PI) * 6) === 1 ? 1 : Math.round((c / PI) * 6) === 3 ? 2 : Math.round((c / PI) * 6) === 5 ? 3 : 4] }),
  optQ('Misc', 'Q12', 'Show that the altitude of the cone of maximum volume inscribed in a sphere of radius r is 4r/3', (h) => (PI / 3) * h * h * (2 - h), 0.05, 2, 4 / 3, (W, h) => PIC.coneIn(W, h, 1), { step: 0.01, xlab: 'h (r = 1)', flab: 'volume', post: [numP('Best altitude ÷ r = ?', 4 / 3, 'V ∝ h²(2r − h): V′ = 0 at h = 4r/3.', { show: '4/3' })], w: 'h = 4r/3' }),
  xs6('Misc', 'Q13', 'If f′(x) > 0 for all x in (a, b), prove f is increasing on (a, b)', [{ k: 'order', q: 'Order the proof (Mean Value Theorem)', s: ['Take x₁ < x₂ in (a, b)', 'f(x₂) − f(x₁) = f′(c)(x₂ − x₁) for some c in (x₁, x₂)', 'f′(c) > 0 and x₂ − x₁ > 0', 'So f(x₂) > f(x₁): f is increasing'] }], 'By the Mean Value Theorem'),
  optQ('Misc', 'Q14', 'Show that the cylinder of maximum volume in a sphere of radius R has height 2R/√3, and find the maximum volume', (r) => PI * r * r * 2 * sqrt(Math.max(0, 1 - r * r)), 0.05, 0.99, sqrt(2 / 3), (W, r) => PIC.cylIn(W, r, 'sphere', 1), { step: 0.005, xlab: 'radius (R = 1)', flab: 'volume', post: [fld('At the best radius (R = 1, type with √)', [{ l: 'height', a: 2 / R3, show: '2/√3', tol: 1e-3 }, { l: 'volume', a: (4 * PI) / (3 * R3), show: '4π/(3√3)', tol: 1e-3 }], 'h = 2R/√3, V = 4πR³/(3√3).', { keys: 'π √' })], w: 'h = 2R/√3, V = 4πR³/(3√3)' }),
  optQ('Misc', 'Q15', 'Show that the cylinder of greatest volume in a cone of height h and semi-vertical angle α has height h/3 and volume (4/27)πh³tan²α', (x) => PI * x * x * (1 - x / 1), 0.02, 0.98, 2 / 3, (W, x) => PIC.cylIn(W, x, 'cone', 1, 1.6), { step: 0.01, xlab: 'radius ÷ base radius', flab: 'volume', post: [{ k: 'mcq', q: 'V = πx²(h − x cot α) is largest at x = (2/3)h tan α, so the cylinder height is', o: ['h/3', '2h/3', 'h/2', 'h/4'], a: 0, x: 'And V = π(4/9)h²tan²α · h/3 = (4/27)πh³tan²α.' }], w: 'Height h/3, volume (4/27)πh³ tan²α' }),
  xs6('Misc', 'Q16', 'A cylindrical tank of radius 10 m is filled with wheat at 314 m³/h. The depth increases at (A) 1 m/h (B) 0.1 m/h (C) 1.1 m/h (D) 0.5 m/h', [numP('dh/dt = 314/(π·100) = ? (2 decimals)', 314 / (100 * PI), '≈ 1 m/h (exactly 1 with π = 3.14).', { tol: 0.011, show: '1' }), { k: 'mcq', q: 'Answer', o: ['(A) 1 m/h', '(B) 0.1 m/h', '(C) 1.1 m/h', '(D) 0.5 m/h'], a: 0, x: '(A).' }], '(A) 1 m/h', { scene: 'rate', setup: (W) => rateSet(W, 'cyl', 3, [['V = π(10)²h'], ['dV/dt = 314 m³/h', C.sora]], { scale: 0.9 }) }),
];

const BOSS6 = [['dA/dr for a circle', ['2πr', 'πr²', '2r', 'πr'], 0], ['f′ > 0 on I means f is', ['increasing', 'decreasing', 'constant', 'concave'], 0], ['f′(c) = 0 and f″(c) < 0 ⇒ c is a', ['local max', 'local min', 'inflexion', 'nothing'], 0], ['x³ at 0 is', ['a point of inflexion', 'a max', 'a min', 'not critical'], 0], ['Max of sin x + cos x', ['√2', '2', '1', '1/√2'], 0], ['Two numbers summing to 10 with max product', ['5 and 5', '1 and 9', '2 and 8', '0 and 10'], 0], ['On [a, b] the absolute max can be at', ['an end point or a critical point', 'only a critical point', 'only an end point', 'nowhere'], 0], ['Marginal cost means', ['dC/dx', 'C/x', 'C(x + 1)', '∫C'], 0], ['x² e⁻ˣ increases on', ['(0, 2)', '(2, ∞)', '(−∞, 0)', 'ℝ'], 0], ['Rectangle of max area in a circle', ['a square', 'a 2:1 rectangle', 'a line', 'any'], 0]];
const byId = (id) => LESSONS.find((l) => l.id === id);
(() => {
  const [ra, id, ex, op, ab, mi] = ['rates', 'incdec', 'extrema', 'optimise', 'absolute', 'miscex'].map(byId);
  LESSONS.length = 0;
  LESSONS.push(ra, exLesson({ id: 'ex61', title: 'Exercise 6.1', blurb: 'All 18: ripples, balloons, ladders and sand piles.', face: 'kimmy-playful', qs: EX61 }), id, exLesson({ id: 'ex62', title: 'Exercise 6.2', blurb: 'All 19: paint the sign of f′ and pick the intervals.', face: 'jess-happy', qs: EX62 }), ex, ab, op, exLesson({ id: 'ex63', title: 'Exercise 6.3', blurb: 'All 29: hills, valleys and optimisation playgrounds.', face: 'kimmy-curious', qs: EX63 }), mi, exLesson({ id: 'misc', title: 'Miscellaneous', blurb: 'All 16 Miscellaneous Exercise questions.', face: 'jess-thinking', qs: EX6M }));
})();
LESSONS.push(lesson({ id: 'boss', title: 'Boss Battle', blurb: 'Ten fast questions. Speed points. Beat Kimmy.', face: 'jess-excited', steps: [async function () { enterScene('board', (W) => { W.tag = 'BOSS'; W.sub = 'Class 12 · Ch 6'; }); await slam('BOSS BATTLE', '10 questions · speed counts'); await K('play', 'Find my maximum!'); await cont('Fight'); }, ...BOSS6.map(([q, o, a], i) => async function () { enterScene('board', (W) => { W.tag = 'Q' + (i + 1); W.sub = 'Boss Battle'; }); await quiz(q, o, a, plain(o[a]) + '.', null, 15); await cont(); }), async function () { enterScene('board', (W) => { W.tag = 'K.O.!'; W.sub = 'Class 12 · Ch 6'; }); await summary(['Class 12 Part 1 complete!', { t: 'Rates, monotonicity and optimisation: all f′', eq: true }]); }] }));
LESSONS.forEach((l) => { if (l.kind === 'ex') l.short = l.id === 'misc' ? 'M' : l.title.replace('Exercise ', ''); });
