/* =========================================================
   CLASS 12 · CHAPTER 13 — builders, Exercise 13.1 and 13.2
   ========================================================= */
const F_ = (n, d) => Qr(n, d), D_ = qd;
const dieSpace = () => ({ items: [1, 2, 3, 4, 5, 6].map((n) => ({ lab: String(n), n, w: 1, red: n <= 3 })), cols: 6, aspect: 1.1 });
const coinDie = () => { const it = []; for (const c of ['H', 'T']) for (let d = 1; d <= 6; d++) it.push({ lab: c + d, coin: c, n: d, w: 1 }); return { items: it, cols: 6, aspect: 0.8 }; };
const redGreen = () => ({ items: [1, 2, 3, 4, 5, 6].map((n) => ({ lab: n + (n <= 3 ? ' red' : ' green'), n, red: n <= 3, w: 1 })), cols: 3, aspect: 0.6 });
const bankSpace = () => ({ items: [{ lab: 'easy T/F', easy: 1, mcq: 0, w: 300, t2: '300' }, { lab: 'hard T/F', easy: 0, mcq: 0, w: 200, t2: '200' }, { lab: 'easy MCQ', easy: 1, mcq: 1, w: 500, t2: '500' }, { lab: 'hard MCQ', easy: 0, mcq: 1, w: 400, t2: '400' }], cols: 2, aspect: 0.55, showN: false });
const mixSpace = () => { const it = []; for (const f of [1, 2, 4, 5]) for (const c of ['H', 'T']) it.push({ lab: f + c, first: f, coin: c, w: 3, t2: '1/12' }); for (const f of [3, 6]) for (let k = 1; k <= 6; k++) it.push({ lab: f + ',' + k, first: f, second: k, w: 1, t2: '1/36' }); return { items: it, cols: 5, aspect: 0.55 }; };
const cnt = (s, ch) => s.split(ch).length - 1;
const heads = (it) => cnt(it.lab, 'H'), tails = (it) => cnt(it.lab, 'T');

/* conditional probability on an outcome grid. asks: [{ a:'E', A: fn, b:'F', B: fn }] — P(a | b) */
function condO(ex, n, q, spFn, asks, o = {}) {
  const sp = spFn(), tot = sp.items.reduce((s, i) => s + i.w, 0), wt = sp.items.some((i) => i.w !== 1) || o.prob, parts = [];
  const unit = (r) => (wt ? r : r);
  asks.forEach((k, ai) => {
    const nb = wsum(sp, k.B), nab = wsum(sp, (it) => k.A(it) && k.B(it)), r = Qr(nab, nb), setup = (W) => { W.sets = { E: k.A, F: k.B }; W.setNames = { E: k.a, F: k.b }; W.vis = { E: 0, F: 0, G: 0 }; W.given = null; W.sel = new Set(); };
    parts.push(runP(async (W) => { setup(W); SFX.pop(); await wait(AUTO ? 0.05 : 0.2); }));
    if (ai === 0 || o.tapEach) parts.push(tapP('Tap every outcome in ' + k.b + ' (what we are told has happened)', k.B, { x: k.b + ' has ' + (wt ? 'probability ' + qs(Qr(nb, tot)) : nb + ' outcomes') + '.' }));
    parts.push(runP(async (W) => { W.vis.F = 1; SFX.pop(); await wait(AUTO ? 0.05 : 0.2); }));
    parts.push(wt ? pnum('P(' + k.b + ') = ?', Qr(nb, tot), 'Add the probabilities of the outcomes in ' + k.b + '.', { act: async (W) => { W.vis.E = 1; } }) : pnum('n(' + k.b + ') = ?', Qr(nb), 'Count the outcomes in ' + k.b + '.', { act: async (W) => { W.vis.E = 1; } }));
    parts.push(wt ? pnum('P(' + k.a + ' ∩ ' + k.b + ') = ?', Qr(nab, tot), 'The outcomes in both colours.', {}) : pnum('n(' + k.a + ' ∩ ' + k.b + ') = ?', Qr(nab), 'The overlap (gold cells).', {}));
    parts.push(runP(async (W) => { W.given = 'F'; SFX.whoosh(); await wait(AUTO ? 0.05 : 0.7); }));
    parts.push(pnum('P(' + k.a + ' | ' + k.b + ') = ?', r, (wt ? 'P(' + k.a + '∩' + k.b + ')/P(' + k.b + ') = ' + qs(Qr(nab, tot)) + '/' + qs(Qr(nb, tot)) : 'n(' + k.a + '∩' + k.b + ')/n(' + k.b + ') = ' + nab + '/' + nb) + ' = ' + qs(r) + '.' + (o.note ? ' ' + o.note : '')));
    if (ai < asks.length - 1) parts.push(runP(async (W) => { W.given = null; W.sel = new Set(); }));
  });
  const w = asks.map((k) => 'P(' + k.a + '|' + k.b + ') = ' + qs(Qr(wsum(sp, (it) => k.A(it) && k.B(it)), wsum(sp, k.B)))).join(', ');
  return { ex, n, q, scene: 'out', setup: (W) => { outSet(W, spFn(), {}, {}); W.vis = { E: 0, F: 0, G: 0 }; W.rd = () => (W.given ? [['universe shrunk to ' + (W.setNames ? W.setNames.F : 'F'), C.beni]] : []); }, parts, w: [w], sp, asks };
}
/* independence on an outcome grid: P(E), P(F), P(E∩F), then the product test */
function indepO(ex, n, q, spFn, a, A, b, B, o = {}) {
  const sp = spFn(), tot = sp.items.reduce((s, i) => s + i.w, 0), pa = Qr(wsum(sp, A), tot), pb = Qr(wsum(sp, B), tot), pab = Qr(wsum(sp, (it) => A(it) && B(it)), tot), prod = qmul(pa, pb), ind = prod.n === pab.n && prod.d === pab.d;
  return { ex, n, q, scene: 'out', setup: (W) => { outSet(W, spFn(), { E: A, F: B }, { names: { E: a, F: b } }); W.vis = { E: 1, F: 1, G: 0 }; W.showN = false; W.rd = () => [['E = ' + a, C['ink-muted']], ['F = ' + b, C['ink-muted']]]; },
    parts: [pnum('P(' + a + ') = ?', pa, ''), pnum('P(' + b + ') = ?', pb, ''), pnum('P(both) = ?', pab, 'The gold overlap.'), pnum('P(' + a + ')·P(' + b + ') = ?', prod, ''), tfP('Is P(E ∩ F) = P(E)·P(F), so the events are independent?', ind, ind ? 'Equal: independent.' : qs(pab) + ' ≠ ' + qs(prod) + ': dependent.')],
    w: ['P(E∩F) = ' + qs(pab) + (ind ? ' = ' : ' ≠ ') + qs(prod) + ': ' + (ind ? 'independent' : 'not independent')], sp, ind };
}
/* Venn + exact bar. a, b, ab: rationals (true values). hide: keys hidden until answered ('ab','aOnly','bOnly','none').
   asks: [{ q, r, x, reveal: [keys], given: 'A' | 'B' }] */
function vnQ(ex, n, q, a, b, ab, asks, o = {}) {
  const names = o.names || ['A', 'B'], hide = {}; (o.hide || []).forEach((k) => (hide[k] = 1));
  const parts = [runP(async (W) => { SFX.pop(); await wait(AUTO ? 0.05 : 0.3); })];
  if (o.pre) parts.push(...o.pre);
  asks.forEach((k) => { parts.push(runP(async (W) => { W.given = null; W.zoom = 0; })); if (k.mq) parts.push(k.mq); parts.push({ ...pnum(k.q, k.r, k.x, k.opt || {}), act: async (W) => { (k.reveal || []).forEach((h) => delete W.hide[h]); if (k.given) await vennGiven(W, k.given); } }); if (k.tf) parts.push(k.tf); });
  return { ex, n, q, scene: 'venn', setup: (W) => { vennSet(W, a, b, ab, { names, hide }); }, parts, w: [o.w || asks.map((k) => k.q.replace(/ = \?.*/, '') + ' = ' + qs(k.r)).join('; ')], kim: o.kim };
}
/* a chain of conditional steps: answer each factor, the bar shrinks, then the product (and any follow-ups) */
function chainQ(ex, n, q, steps, o = {}) {
  const parts = [runP(async (W) => { shrinkSet(W, steps, { title: o.title || '' }); SFX.pop(); await wait(AUTO ? 0.05 : 0.3); })];
  let cum = Q1; steps.forEach((s, i) => { cum = qmul(cum, s.p); const c = cum; parts.push({ ...pnum(s.q || 'Factor ' + (i + 1) + ': ' + s.lab + ' = ?', s.p, s.x || ''), act: async (W) => { SFX.swish(); await tw(W, { k: i + 1, duration: AUTO ? 0.05 : 0.7, ease: 'power1.inOut' }); } }); });
  parts.push(pnum(o.fq || 'Multiply: the probability of the whole chain = ?', cum, o.fx || 'P(E∩F∩…) = P(E)·P(F|E)·…'));
  const out = [...parts]; let fin = cum; (o.after || []).forEach((k) => { out.push(pnum(k.q, k.r, k.x || '')); fin = k.r; });
  return { ex, n, q, scene: 'shrink', setup: (W) => { shrinkSet(W, steps, { title: o.title || '' }); W.k = 0; }, parts: out, w: [o.w || 'P = ' + qs(fin)], chainP: cum };
}
const boardQ = (ex, n, q, parts, w, tag) => ({ ex, n, q, scene: 'board', setup: (W) => { W.tag = tag || n; W.sub = ex; }, parts, w: [w] });
const mcqB = (q, o, x) => ({ k: 'mcq', q, o, a: 0, x });

/* ===================== EXERCISE 13.1 ===================== */
const EX131 = [
  vnQ('Ex 13.1', 'Q1', 'P(E) = 0.6, P(F) = 0.3, P(E ∩ F) = 0.2. Find P(E|F) and P(F|E)', D_(0.6), D_(0.3), D_(0.2), [{ q: 'P(E | F) = ?', r: F_(2, 3), x: 'P(E∩F)/P(F) = 0.2/0.3.', given: 'B' }, { q: 'P(F | E) = ?', r: F_(1, 3), x: 'P(E∩F)/P(E) = 0.2/0.6.', given: 'A' }], { names: ['E', 'F'] }),
  vnQ('Ex 13.1', 'Q2', 'Compute P(A|B) if P(B) = 0.5 and P(A ∩ B) = 0.32', D_(0.8), D_(0.5), D_(0.32), [{ q: 'P(A | B) = ?', r: F_(16, 25), x: '0.32/0.5 = 0.64.', given: 'B' }], { hide: ['aOnly', 'none'] }),
  vnQ('Ex 13.1', 'Q3', 'P(A) = 0.8, P(B) = 0.5, P(B|A) = 0.4. Find (i) P(A ∩ B) (ii) P(A|B) (iii) P(A ∪ B)', D_(0.8), D_(0.5), F_(8, 25), [{ q: '(i) P(A ∩ B) = P(A)·P(B|A) = ?', r: F_(8, 25), x: '0.8 × 0.4 = 0.32.', reveal: ['ab', 'aOnly', 'bOnly'] }, { q: '(ii) P(A | B) = ?', r: F_(16, 25), x: '0.32/0.5.', given: 'B' }, { q: '(iii) P(A ∪ B) = ?', r: F_(49, 50), x: '0.8 + 0.5 − 0.32 = 0.98.', reveal: ['none'] }], { hide: ['ab', 'aOnly', 'bOnly', 'none'] }),
  vnQ('Ex 13.1', 'Q4', 'Evaluate P(A ∪ B) if 2P(A) = P(B) = 5/13 and P(A|B) = 2/5', F_(5, 26), F_(5, 13), F_(2, 13), [{ q: 'P(A ∩ B) = P(A|B)·P(B) = ?', r: F_(2, 13), x: '(2/5)(5/13).', reveal: ['ab'] }, { q: 'P(A) = ?', r: F_(5, 26), x: '2P(A) = 5/13.' }, { q: 'P(A ∪ B) = P(A) + P(B) − P(A ∩ B) = ?', r: F_(11, 26), x: '5/26 + 10/26 − 4/26.', reveal: ['aOnly', 'bOnly', 'none'] }], { hide: ['ab', 'aOnly', 'bOnly', 'none'] }),
  vnQ('Ex 13.1', 'Q5', 'P(A) = 6/11, P(B) = 5/11, P(A ∪ B) = 7/11. Find (i) P(A ∩ B) (ii) P(A|B) (iii) P(B|A)', F_(6, 11), F_(5, 11), F_(4, 11), [{ q: '(i) P(A ∩ B) = ?', r: F_(4, 11), x: '6/11 + 5/11 − 7/11.', reveal: ['ab', 'aOnly', 'bOnly'] }, { q: '(ii) P(A | B) = ?', r: F_(4, 5), x: '(4/11)/(5/11).', given: 'B' }, { q: '(iii) P(B | A) = ?', r: F_(2, 3), x: '(4/11)/(6/11).', given: 'A' }], { hide: ['ab', 'aOnly', 'bOnly'] }),
  condO('Ex 13.1', 'Q6(i)', 'A coin is tossed three times. E: head on third toss, F: heads on first two tosses. Find P(E|F)', coinSpace.bind(null, 3), [{ a: 'E', A: (it) => it.lab[2] === 'H', b: 'F', B: (it) => it.lab.slice(0, 2) === 'HH' }]),
  condO('Ex 13.1', 'Q6(ii)', 'E: at least two heads, F: at most two heads. Find P(E|F)', coinSpace.bind(null, 3), [{ a: 'E', A: (it) => heads(it) >= 2, b: 'F', B: (it) => heads(it) <= 2 }]),
  condO('Ex 13.1', 'Q6(iii)', 'E: at most two tails, F: at least one tail. Find P(E|F)', coinSpace.bind(null, 3), [{ a: 'E', A: (it) => tails(it) <= 2, b: 'F', B: (it) => tails(it) >= 1 }]),
  condO('Ex 13.1', 'Q7(i)', 'Two coins are tossed once. E: tail appears on one coin, F: one coin shows head. Find P(E|F)', coinSpace.bind(null, 2), [{ a: 'E', A: (it) => tails(it) === 1, b: 'F', B: (it) => heads(it) === 1 }]),
  condO('Ex 13.1', 'Q7(ii)', 'E: no tail appears, F: no head appears. Find P(E|F)', coinSpace.bind(null, 2), [{ a: 'E', A: (it) => tails(it) === 0, b: 'F', B: (it) => heads(it) === 0 }]),
  condO('Ex 13.1', 'Q8', 'A die is thrown three times. E: 4 on the third toss, F: 6 and 5 on the first two tosses. Find P(E|F)', dice3Space, [{ a: 'E', A: (it) => it.r === 3, b: 'F', B: (it) => it.a === 6 && it.b === 5 }]),
  condO('Ex 13.1', 'Q9', 'Mother, father and son line up at random. E: son on one end, F: father in the middle. Find P(E|F)', lineSpace, [{ a: 'E', A: (it) => it.p[0] === 'S' || it.p[2] === 'S', b: 'F', B: (it) => it.p[1] === 'F' }]),
  condO('Ex 13.1', 'Q10(a)', 'A black and a red die are rolled. Conditional probability of a sum greater than 9, given that the black die resulted in a 5', diceSpace, [{ a: 'sum > 9', A: (it) => it.a + it.b > 9, b: 'black = 5', B: (it) => it.a === 5 }]),
  condO('Ex 13.1', 'Q10(b)', 'Conditional probability of the sum 8, given that the red die resulted in a number less than 4', diceSpace, [{ a: 'sum = 8', A: (it) => it.a + it.b === 8, b: 'red < 4', B: (it) => it.b < 4 }]),
  condO('Ex 13.1', 'Q11(i)', 'A fair die is rolled. E = {1, 3, 5}, F = {2, 3}, G = {2, 3, 4, 5}. Find P(E|F) and P(F|E)', dieSpace, [{ a: 'E', A: (it) => [1, 3, 5].includes(it.n), b: 'F', B: (it) => [2, 3].includes(it.n) }, { a: 'F', A: (it) => [2, 3].includes(it.n), b: 'E', B: (it) => [1, 3, 5].includes(it.n) }]),
  condO('Ex 13.1', 'Q11(ii)', 'Find P(E|G) and P(G|E)', dieSpace, [{ a: 'E', A: (it) => [1, 3, 5].includes(it.n), b: 'G', B: (it) => [2, 3, 4, 5].includes(it.n) }, { a: 'G', A: (it) => [2, 3, 4, 5].includes(it.n), b: 'E', B: (it) => [1, 3, 5].includes(it.n) }]),
  condO('Ex 13.1', 'Q11(iii)', 'Find P((E ∪ F)|G) and P((E ∩ F)|G)', dieSpace, [{ a: 'E∪F', A: (it) => [1, 2, 3, 5].includes(it.n), b: 'G', B: (it) => [2, 3, 4, 5].includes(it.n) }, { a: 'E∩F', A: (it) => it.n === 3, b: 'G', B: (it) => [2, 3, 4, 5].includes(it.n) }]),
  condO('Ex 13.1', 'Q12(i)', 'Each child is equally likely a boy or a girl. A family has two children. Probability that both are girls, given that the youngest is a girl', famSpace, [{ a: 'both girls', A: (it) => it.e === 'g' && it.y === 'g', b: 'youngest girl', B: (it) => it.y === 'g' }]),
  condO('Ex 13.1', 'Q12(ii)', 'Probability that both are girls, given that at least one is a girl', famSpace, [{ a: 'both girls', A: (it) => it.e === 'g' && it.y === 'g', b: 'at least one girl', B: (it) => it.e === 'g' || it.y === 'g' }]),
  condO('Ex 13.1', 'Q13', 'A bank has 300 easy and 200 difficult True/False, 500 easy and 400 difficult multiple choice questions. One is chosen at random. Probability that it is easy, given that it is a multiple choice question', bankSpace, [{ a: 'easy', A: (it) => it.easy, b: 'MCQ', B: (it) => it.mcq }], { prob: true }),
  condO('Ex 13.1', 'Q14', 'The two numbers on throwing two dice are different. Find the probability that the sum is 4', diceSpace, [{ a: 'sum = 4', A: (it) => it.a + it.b === 4, b: 'different', B: (it) => it.a !== it.b }]),
  condO('Ex 13.1', 'Q15', 'Throw a die. If a multiple of 3 comes up, throw the die again; if any other number comes, toss a coin. Probability that the coin shows a tail, given that at least one die shows a 3', mixSpace, [{ a: 'coin tail', A: (it) => it.coin === 'T', b: 'a die shows 3', B: (it) => it.first === 3 || it.second === 3 }], { prob: true, note: 'The coin is only tossed when the first throw is not a multiple of 3, and then no die ever shows a 3, so no outcome is in both events.' }),
  boardQ('Ex 13.1', 'Q16', 'If P(A) = 1/2 and P(B) = 0, then P(A|B) is (A) 0 (B) 1/2 (C) not defined (D) 1', [mcqB('P(A|B) = P(A∩B)/P(B). Here P(B) = 0, so', ['(C) not defined', '(A) 0', '(B) 1/2', '(D) 1'], 'Division by zero: the conditional probability needs P(B) ≠ 0.')], '(C) not defined'),
  boardQ('Ex 13.1', 'Q17', 'If P(A|B) = P(B|A), then (A) A ⊂ B but A ≠ B (B) A = B (C) A ∩ B = φ (D) P(A) = P(B)', [mcqB('P(A∩B)/P(B) = P(A∩B)/P(A) gives (when P(A∩B) ≠ 0)', ['(D) P(A) = P(B)', '(A) A ⊂ B but A ≠ B', '(B) A = B', '(C) A ∩ B = φ'], 'Equal numerators force P(A) = P(B). That does not make the events themselves equal.')], '(D) P(A) = P(B)'),
];

/* ===================== EXERCISE 13.2 ===================== */
const EX132 = [
  vnQ('Ex 13.2', 'Q1', 'If P(A) = 3/5 and P(B) = 1/5, find P(A ∩ B) if A and B are independent', F_(3, 5), F_(1, 5), F_(3, 25), [{ q: 'P(A ∩ B) = ?', r: F_(3, 25), x: 'Independent: P(A)·P(B) = 3/5 × 1/5.', reveal: ['ab'] }], { hide: ['ab', 'aOnly', 'bOnly', 'none'], pre: [mcqB('For independent events, P(A ∩ B) equals', ['P(A)·P(B)', 'P(A) + P(B)', 'P(A|B)', 'P(A) − P(B)'], 'Definition 3.')] }),
  chainQ('Ex 13.2', 'Q2', 'Two cards are drawn at random without replacement from 52 cards. Find the probability that both are black', [{ lab: '1st card black', p: F_(1, 2), x: '26 black of 52.' }, { lab: '2nd black | 1st black', p: F_(25, 51), x: '25 black of the 51 left.' }], { title: 'without replacement' }),
  chainQ('Ex 13.2', 'Q3', 'A box of 15 oranges (12 good, 3 bad) is inspected by drawing three without replacement. It is approved if all three are good. Find the probability of approval', [{ lab: '1st good', p: F_(4, 5), x: '12/15.' }, { lab: '2nd good | 1st good', p: F_(11, 14), x: '11 good of 14 left.' }, { lab: '3rd good | first two good', p: F_(10, 13), x: '10 good of 13 left.' }], { title: 'three oranges, no replacement' }),
  indepO('Ex 13.2', 'Q4', 'A fair coin and an unbiased die are tossed. A: head appears, B: 3 on the die. Are A and B independent?', coinDie, 'head', (it) => it.coin === 'H', '3 on die', (it) => it.n === 3),
  indepO('Ex 13.2', 'Q5', 'A die marked 1, 2, 3 in red and 4, 5, 6 in green is tossed. A: the number is even, B: the number is red. Are A and B independent?', redGreen, 'even', (it) => it.n % 2 === 0, 'red', (it) => it.red),
  vnQ('Ex 13.2', 'Q6', 'P(E) = 3/5, P(F) = 3/10 and P(E ∩ F) = 1/5. Are E and F independent?', F_(3, 5), F_(3, 10), F_(1, 5), [{ q: 'P(E)·P(F) = ?', r: F_(9, 50), x: '3/5 × 3/10.', tf: tfP('P(E ∩ F) = 1/5 = 10/50. Are E and F independent?', false, '10/50 ≠ 9/50: not independent.') }], { names: ['E', 'F'], w: 'P(E)P(F) = 9/50 ≠ 1/5 = P(E∩F): not independent' }),
  vnQ('Ex 13.2', 'Q7(i)', 'P(A) = 1/2, P(A ∪ B) = 3/5, P(B) = p. Find p if A and B are mutually exclusive', F_(1, 2), F_(1, 10), Q0, [{ q: 'p = P(A ∪ B) − P(A) = ?', r: F_(1, 10), x: 'Mutually exclusive: P(A ∪ B) = P(A) + P(B).', reveal: ['bOnly'] }], { hide: ['bOnly', 'none'] }),
  vnQ('Ex 13.2', 'Q7(ii)', 'P(A) = 1/2, P(A ∪ B) = 3/5, P(B) = p. Find p if A and B are independent', F_(1, 2), F_(1, 5), F_(1, 10), [{ q: 'p = ? (use P(A ∪ B) = P(A) + P(B) − P(A)P(B): 3/5 = 1/2 + p/2)', r: F_(1, 5), x: '3/5 − 1/2 = p/2, so p = 1/5.', reveal: ['bOnly', 'ab'] }], { hide: ['bOnly', 'ab', 'none'] }),
  vnQ('Ex 13.2', 'Q8', 'A and B are independent with P(A) = 0.3 and P(B) = 0.4. Find (i) P(A ∩ B) (ii) P(A ∪ B) (iii) P(A|B) (iv) P(B|A)', D_(0.3), D_(0.4), D_(0.12), [{ q: '(i) P(A ∩ B) = ?', r: F_(3, 25), x: '0.3 × 0.4.', reveal: ['ab', 'aOnly', 'bOnly'] }, { q: '(ii) P(A ∪ B) = ?', r: F_(29, 50), x: '0.3 + 0.4 − 0.12 = 0.58.', reveal: ['none'] }, { q: '(iii) P(A | B) = ?', r: F_(3, 10), x: 'Independent: P(A|B) = P(A).', given: 'B' }, { q: '(iv) P(B | A) = ?', r: F_(2, 5), x: 'Independent: P(B|A) = P(B).', given: 'A' }], { hide: ['ab', 'aOnly', 'bOnly', 'none'] }),
  vnQ('Ex 13.2', 'Q9', 'P(A) = 1/4, P(B) = 1/2 and P(A ∩ B) = 1/8. Find P(not A and not B)', F_(1, 4), F_(1, 2), F_(1, 8), [{ q: 'P(A ∪ B) = ?', r: F_(5, 8), x: '1/4 + 1/2 − 1/8.' }, { q: 'P(not A and not B) = 1 − P(A ∪ B) = ?', r: F_(3, 8), x: 'The grey part outside both circles.', reveal: ['none'] }], { hide: ['none'] }),
  boardQ('Ex 13.2', 'Q10', 'P(A) = 1/2, P(B) = 7/12 and P(not A or not B) = 1/4. Are A and B independent?', [pnum('P(A ∩ B) = 1 − P(not A or not B) = ?', F_(3, 4), 'By De Morgan, (A ∩ B)′ = A′ ∪ B′.'), mcqB('Is that possible when P(A) = 1/2?', ['No: P(A ∩ B) cannot exceed P(A)', 'Yes', 'Only if B ⊂ A', 'Only if A ⊂ B'], 'Answer-key check: P(A ∩ B) = 3/4 > P(A) = 1/2. No such events exist, so the data are inconsistent. The usual working says 3/4 ≠ 1/2 × 7/12 = 7/24, so "not independent", but really the question is flawed.'), tfP('So the textbook conclusion "A and B are not independent" really describes impossible events.', true, 'No events with these probabilities can exist.')], 'Data inconsistent: P(A∩B) = 3/4 > P(A); textbook answer: not independent', 'Ex 10'),
  vnQ('Ex 13.2', 'Q11', 'A and B independent with P(A) = 0.3, P(B) = 0.6. Find (i) P(A and B) (ii) P(A and not B) (iii) P(A or B) (iv) P(neither A nor B)', D_(0.3), D_(0.6), D_(0.18), [{ q: '(i) P(A and B) = ?', r: F_(9, 50), x: '0.3 × 0.6.', reveal: ['ab'] }, { q: '(ii) P(A and not B) = 0.3 × 0.4 = ?', r: F_(3, 25), x: 'The part of A outside B.', reveal: ['aOnly'] }, { q: '(iii) P(A or B) = ?', r: F_(18, 25), x: '0.3 + 0.6 − 0.18 = 0.72.', reveal: ['bOnly'] }, { q: '(iv) P(neither) = 1 − 0.72 = ?', r: F_(7, 25), x: '', reveal: ['none'] }], { hide: ['ab', 'aOnly', 'bOnly', 'none'] }),
  chainQ('Ex 13.2', 'Q12', 'A die is tossed thrice. Find the probability of getting an odd number at least once', [{ lab: '1st throw even', p: F_(1, 2), x: '' }, { lab: '2nd even', p: F_(1, 2), x: 'Throws are independent.' }, { lab: '3rd even', p: F_(1, 2), x: '' }], { title: 'no odd number in three throws', fq: 'P(all three even) = ?', after: [{ q: 'P(odd at least once) = 1 − P(all even) = ?', r: F_(7, 8) }] }),
  chainQ('Ex 13.2', 'Q13(i)', 'Two balls are drawn with replacement from 10 black and 8 red balls. Probability that both balls are red', [{ lab: '1st red', p: F_(4, 9), x: '8/18.' }, { lab: '2nd red', p: F_(4, 9), x: 'Replaced, so still 8/18.' }], { title: 'with replacement' }),
  chainQ('Ex 13.2', 'Q13(ii)', 'First ball is black and the second is red', [{ lab: '1st black', p: F_(5, 9), x: '10/18.' }, { lab: '2nd red', p: F_(4, 9), x: '8/18.' }], { title: 'with replacement' }),
  chainQ('Ex 13.2', 'Q13(iii)', 'One of them is black and the other is red', [{ lab: 'black then red: black', p: F_(5, 9), x: '10/18.' }, { lab: '… then red', p: F_(4, 9), x: '8/18.' }], { title: 'one order; the other order has the same probability', after: [{ q: 'Either order (black-red or red-black): 2 × that = ?', r: F_(40, 81), x: 'The two orders are disjoint.' }] }),
  vnQ('Ex 13.2', 'Q14', 'A and B solve a problem independently with probabilities 1/2 and 1/3. Find the probability that (i) the problem is solved (ii) exactly one of them solves it', F_(1, 2), F_(1, 3), F_(1, 6), [{ q: '(i) P(A ∪ B) = 1 − P(neither) = 1 − (1/2)(2/3) = ?', r: F_(2, 3), x: 'At least one solves it.' }, { q: '(ii) Exactly one = P(A ∪ B) − P(A ∩ B) = ?', r: F_(1, 2), x: '2/3 − 1/6: the two crescents of the Venn.' }], { hide: ['none'] }),
  indepO('Ex 13.2', 'Q15(i)', 'One card is drawn from 52. Are E: the card is a spade and F: the card is an ace independent?', deckSpace, 'spade', (it) => it.suit === '♠', 'ace', (it) => it.rank === 'A'),
  indepO('Ex 13.2', 'Q15(ii)', 'E: the card is black, F: the card is a king. Independent?', deckSpace, 'black', (it) => it.black, 'king', (it) => it.rank === 'K'),
  indepO('Ex 13.2', 'Q15(iii)', 'E: the card is a king or queen, F: the card is a queen or jack. Independent?', deckSpace, 'king or queen', (it) => it.rank === 'K' || it.rank === 'Q', 'queen or jack', (it) => it.rank === 'Q' || it.rank === 'J'),
  vnQ('Ex 13.2', 'Q16', 'In a hostel 60% read Hindi, 40% read English and 20% read both. A student is chosen at random. (a) neither (b) reads English given Hindi (c) reads Hindi given English', F_(3, 5), F_(2, 5), F_(1, 5), [{ q: '(a) P(neither) = 1 − P(H ∪ E) = ?', r: F_(1, 5), x: '1 − (0.6 + 0.4 − 0.2) = 0.2.', reveal: ['none'] }, { q: '(b) P(E | H) = ?', r: F_(1, 3), x: '0.2/0.6.', given: 'A' }, { q: '(c) P(H | E) = ?', r: F_(1, 2), x: '0.2/0.4.', given: 'B' }], { names: ['H', 'E'], hide: ['none'] }),
  boardQ('Ex 13.2', 'Q17', 'The probability of obtaining an even prime number on each die when a pair of dice is rolled is (A) 0 (B) 1/3 (C) 1/12 (D) 1/36', [mcqB('The only even prime is 2: probability 1/6 on each die, and the dice are independent, so', ['(D) 1/36', '(A) 0', '(B) 1/3', '(C) 1/12'], '(1/6)(1/6) = 1/36.')], '(D) 1/36'),
  boardQ('Ex 13.2', 'Q18', 'Two events A and B will be independent if (A) A and B are mutually exclusive (B) P(A′B′) = [1 − P(A)][1 − P(B)] (C) P(A) = P(B) (D) P(A) + P(B) = 1', [mcqB('Answer', ['(B) P(A′B′) = [1 − P(A)][1 − P(B)]', '(A) mutually exclusive', '(C) P(A) = P(B)', '(D) P(A) + P(B) = 1'], 'P(A′B′) = P(A′)P(B′) is exactly the independence of A′ and B′, which holds iff A and B are independent. Mutually exclusive events with positive probabilities are never independent.')], '(B)'),
];
