/* =========================================================
   CLASS 12 · CHAPTER 13 — Exercise 13.3, Miscellaneous Exercise and the Miscellaneous Examples
   areaQ: the area model. strips = hypotheses (width = prior), shaded height = P(A | hypothesis).
   ========================================================= */
/* hyps: [{ n, prior, like }] (rationals). o: { aname, kind: 'bayes' | 'total', target, steps: [parts], all: true (ask every posterior) } */
function areaQ(ex, n, q, hyps, aname, o = {}) {
  const B = bayes(hyps), kind = o.kind || 'bayes', tgt = o.target != null ? o.target : 0;
  const stp = o.steps || [], nums = stp.filter((p) => p.k === 'num'), lab = (q) => q.replace(/ = \?$/, '').split(/(?<=\.) /).pop().split(': ').pop();
  const stepParts = nums.length >= 2 ? [{ k: 'fields', q: 'First, the likelihoods', f: nums.map((p) => ({ l: lab(p.q), a: p.a, show: p.show, tol: p.tol })), x: nums.map((p) => p.x).filter(Boolean).join(' '), keys: '' }] : stp;
  const parts = [runP(async (W) => { areaSet(W, hyps, aname, { hideP: null }); SFX.pop(); await wait(AUTO ? 0.05 : 0.3); }), ...stepParts,
    runP(async (W) => { await areaIn(W); }),
    { ...pfld('Shaded area of each strip = P(hypothesis) · P(' + aname + ' | hypothesis), and the total = P(' + aname + ')', [...hyps.map((h, i) => [h.n, B.j[i]]), ['total', B.tot]], 'Prior times likelihood, strip by strip; the total is the theorem of total probability.'), act: async (W) => { W.showJ = true; } }];
  if (kind === 'bayes') {
    if (o.all) parts.push(pfld('Posterior of each hypothesis = its share of the shaded area', hyps.map((h, i) => [h.n, B.post[i]]), 'Bayes: strip area ÷ total area.'));
    else parts.push({ k: 'task', q: 'Tap the strip: ' + hyps[tgt].n, todo: 'Tap that strip on the picture.', pre: async (W) => { W.tapOn = true; W.pick = -1; }, check: (W) => W.pick === tgt, auto: (W) => (W.pick = tgt), reveal: (W) => (W.pick = tgt), act: async (W) => { W.tapOn = false; W.post = true; } },
      pnum('P(' + hyps[tgt].n + ' | ' + aname + ') = its area ÷ total area = ?', B.post[tgt], qs(B.j[tgt]) + ' ÷ ' + qs(B.tot) + ' = ' + qs(B.post[tgt]) + '.'));
    parts.push(runP(async (W) => { W.post = true; W.pick = o.all ? -1 : tgt; SFX.pop(); await wait(AUTO ? 0.05 : 0.6); }));
  }
  const w = kind === 'bayes' ? (o.all ? hyps.map((h, i) => 'P(' + h.n + '|' + aname + ') = ' + qs(B.post[i])).join(', ') : 'P(' + hyps[tgt].n + '|' + aname + ') = ' + qs(B.post[tgt])) : 'P(' + aname + ') = ' + qs(B.tot);
  return { ex, n, q, scene: 'areas', setup: (W) => { areaSet(W, hyps, aname, { ph: 0 }); }, parts, w: [w], B, hyps };
}
const hy = (n, prior, like) => ({ n, prior, like });
/* tap outcomes to find the probability of one event */
function probO(ex, n, q, spFn, a, A, o = {}) {
  const sp = spFn(), tot = sp.items.reduce((s, i) => s + i.w, 0), na = wsum(sp, A), r = Qr(na, tot);
  return { ex, n, q, scene: 'out', setup: (W) => { outSet(W, spFn(), { E: A }, { names: { E: a } }); W.vis = { E: 0, F: 0, G: 0 }; }, parts: [tapP('Tap every outcome in the event: ' + a, A, { x: na + ' outcomes.' }), runP(async (W) => { W.vis.E = 1; SFX.pop(); await wait(AUTO ? 0.05 : 0.3); }), pnum('n(' + a + ') = ?', Qr(na), ''), pnum('P(' + a + ') = ?', r, na + '/' + tot + '.')], w: ['P = ' + qs(r)], sp };
}
const bits = (m, k) => { const o = []; for (let i = k - 1; i >= 0; i--) o.push((m >> i) & 1); return o; };
const detSpace = () => ({ items: Array.from({ length: 16 }, (_, m) => { const [a, b, c, d] = bits(m, 4); return { lab: a + ' ' + b + '|' + c + ' ' + d, a, b, c, d, w: 1, det: a * d - b * c }; }), cols: 4, aspect: 0.7, note: '[a b | c d]' });
const weekSpace = () => { const D = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']; return { items: D.map((d, i) => ({ lab: d + '-' + D[(i + 1) % 7], days: [d, D[(i + 1) % 7]], w: 1 })), cols: 4, aspect: 0.6, note: 'the two extra days of a leap year' }; };
const step = (q, r, x) => pnum(q, r, x || '');

/* ===================== EXERCISE 13.3 ===================== */
const EX133 = [
  areaQ('Ex 13.3', 'Q1', 'An urn has 5 red and 5 black balls. A ball is drawn, its colour noted and returned with 2 more balls of that colour; then a second ball is drawn. Probability that the second ball is red', [hy('1st red', F_(1, 2), F_(7, 12)), hy('1st black', F_(1, 2), F_(5, 12))], 'second red', { kind: 'total', steps: [step('If the first was red, the urn has 7 red of 12. P(2nd red | 1st red) = ?', F_(7, 12)), step('If the first was black, the urn has 5 red of 12. P(2nd red | 1st black) = ?', F_(5, 12))] }),
  areaQ('Ex 13.3', 'Q2', 'A bag has 4 red and 4 black balls, another has 2 red and 6 black. One bag is chosen at random and a red ball drawn. Probability that it is from the first bag', [hy('first bag', F_(1, 2), F_(1, 2)), hy('second bag', F_(1, 2), F_(1, 4))], 'red', { target: 0, steps: [step('P(red | first bag) = ?', F_(1, 2)), step('P(red | second bag) = ?', F_(1, 4))] }),
  areaQ('Ex 13.3', 'Q3', '60% of college students live in hostel, 40% are day scholars. 30% of hostelers and 20% of day scholars get an A grade. A student with an A is chosen. Probability the student is a hostler', [hy('hostler', F_(3, 5), F_(3, 10)), hy('day scholar', F_(2, 5), F_(1, 5))], 'A grade', { target: 0 }),
  areaQ('Ex 13.3', 'Q4', 'In a multiple choice test a student knows the answer with probability 3/4 and guesses with probability 1/4; a guess is correct with probability 1/4. Probability that he knows the answer given that he answered correctly', [hy('knows', F_(3, 4), F_(1, 1)), hy('guesses', F_(1, 4), F_(1, 4))], 'correct', { target: 0, steps: [step('P(correct | knows the answer) = ?', Q1)] }),
  areaQ('Ex 13.3', 'Q5', 'A blood test is 99% effective in detecting a disease when present, and gives a false positive for 0.5% of healthy people. 0.1% of the population has the disease. Probability that a person has the disease given a positive result', [hy('diseased', D_(0.001), D_(0.99)), hy('healthy', D_(0.999), D_(0.005))], 'positive', { target: 0, steps: [step('P(positive | diseased) = ?', D_(0.99)), step('P(positive | healthy) = ?', D_(0.005))] }),
  areaQ('Ex 13.3', 'Q6', 'Three coins: a two-headed coin, a biased coin that comes up heads 75% of the time, and an unbiased coin. One is chosen at random and tossed; it shows heads. Probability that it was the two-headed coin', [hy('two-headed', F_(1, 3), Q1), hy('biased', F_(1, 3), F_(3, 4)), hy('unbiased', F_(1, 3), F_(1, 2))], 'heads', { target: 0 }),
  areaQ('Ex 13.3', 'Q7', 'An insurance company insured 2000 scooter, 4000 car and 6000 truck drivers. Accident probabilities are 0.01, 0.03 and 0.15. One insured person meets with an accident. Probability that he is a scooter driver', [hy('scooter', F_(1, 6), D_(0.01)), hy('car', F_(1, 3), D_(0.03)), hy('truck', F_(1, 2), D_(0.15))], 'accident', { target: 0, steps: [step('P(scooter driver) = 2000/12000 = ?', F_(1, 6))] }),
  areaQ('Ex 13.3', 'Q8', 'Machine A produced 60% of items and B 40%. 2% of A\'s and 1% of B\'s items were defective. An item is chosen and found defective. Probability that it was produced by B', [hy('machine A', D_(0.6), D_(0.02)), hy('machine B', D_(0.4), D_(0.01))], 'defective', { target: 1 }),
  areaQ('Ex 13.3', 'Q9', 'The first and second groups win with probabilities 0.6 and 0.4. A new product is introduced with probability 0.7 if the first wins and 0.3 if the second wins. Probability that the new product was introduced by the second group', [hy('group 1 wins', D_(0.6), D_(0.7)), hy('group 2 wins', D_(0.4), D_(0.3))], 'new product', { target: 1 }),
  areaQ('Ex 13.3', 'Q10', 'A girl throws a die. On 5 or 6 she tosses a coin three times; on 1, 2, 3 or 4 she tosses a coin once. She obtains exactly one head. Probability that she threw 1, 2, 3 or 4', [hy('5 or 6 (3 tosses)', F_(1, 3), F_(3, 8)), hy('1–4 (1 toss)', F_(2, 3), F_(1, 2))], 'exactly one head', { target: 1, steps: [step('Exactly one head in 3 tosses: 3 of the 8 outcomes (HTT, THT, TTH). Probability = ?', F_(3, 8)), step('Exactly one head in 1 toss = ?', F_(1, 2))] }),
  areaQ('Ex 13.3', 'Q11', 'Operators A, B, C are on the job 50%, 30%, 20% of the time and produce 1%, 5%, 7% defective items. A defective item is produced. Probability that it was produced by A', [hy('A', F_(1, 2), D_(0.01)), hy('B', F_(3, 10), D_(0.05)), hy('C', F_(1, 5), D_(0.07))], 'defective', { target: 0 }),
  areaQ('Ex 13.3', 'Q12', 'A card from a pack of 52 is lost. From the remaining cards two are drawn and both are diamonds. Probability that the lost card was a diamond', [hy('lost a diamond', F_(1, 4), F_(22, 425)), hy('lost another suit', F_(3, 4), F_(26, 425))], 'two diamonds', { target: 0, steps: [step('If the lost card was a diamond: 12 diamonds in 51. P(two diamonds) = (12/51)(11/50) = ?', F_(22, 425)), step('If it was not: 13 diamonds in 51. P(two diamonds) = (13/51)(12/50) = ?', F_(26, 425))] }),
  areaQ('Ex 13.3', 'Q13', 'The probability that A speaks the truth is 4/5. A coin is tossed and A reports a head. The probability that there actually was a head is (A) 4/5 (B) 1/2 (C) 1/5 (D) 2/5', [hy('really head', F_(1, 2), F_(4, 5)), hy('really tail', F_(1, 2), F_(1, 5))], 'reports head', { target: 0, steps: [step('P(reports head | head) = P(truthful) = ?', F_(4, 5)), step('P(reports head | tail) = P(lies) = ?', F_(1, 5))] }),
  boardQ('Ex 13.3', 'Q14', 'If A ⊂ B and P(B) ≠ 0, which is correct? (A) P(A|B) = P(B)/P(A) (B) P(A|B) < P(A) (C) P(A|B) ≥ P(A) (D) None of these', [mcqB('A ⊂ B gives A ∩ B = A, so P(A|B) = P(A)/P(B). Since P(B) ≤ 1,', ['(C) P(A|B) ≥ P(A)', '(A) P(A|B) = P(B)/P(A)', '(B) P(A|B) < P(A)', '(D) None of these'], 'Dividing by a number ≤ 1 can only make it bigger or equal.')], '(C) P(A|B) ≥ P(A)'),
];

/* ===================== MISCELLANEOUS EXERCISE ===================== */
const bin = (n, k, p) => nCk(n, k) * Math.pow(p, k) * Math.pow(1 - p, n - k);
const p7 = bin(10, 7, 0.9), p8 = bin(10, 8, 0.9), p9 = bin(10, 9, 0.9), p10 = bin(10, 10, 0.9), pge7 = p7 + p8 + p9 + p10;
const EX13M = [
  boardQ('Misc 13', 'Q1(i)', 'A and B are events with P(A) ≠ 0. Find P(B|A) if A is a subset of B', [mcqB('A ⊂ B means A ∩ B = A, so P(B|A) = P(A)/P(A) =', ['1', '0', 'P(B)', '1/2'], 'Every outcome in A is already in B.')], '1'),
  boardQ('Ex 13.3', 'Q1(ii)', 'P(B|A) if A ∩ B = φ', [mcqB('A ∩ B = φ means P(A ∩ B) = 0, so P(B|A) =', ['0', '1', 'P(B)', 'not defined'], 'A and B cannot both happen.')], '0'),
  condO('Misc 13', 'Q2(i)', 'A couple has two children. Probability that both are males, given that at least one is male', famSpace, [{ a: 'both boys', A: (it) => it.e === 'b' && it.y === 'b', b: 'at least one boy', B: (it) => it.e === 'b' || it.y === 'b' }]),
  condO('Misc 13', 'Q2(ii)', 'Probability that both are females, given that the elder child is a female', famSpace, [{ a: 'both girls', A: (it) => it.e === 'g' && it.y === 'g', b: 'elder girl', B: (it) => it.e === 'g' }]),
  areaQ('Misc 13', 'Q3', '5% of men and 0.25% of women have grey hair. A grey haired person is selected at random. Probability of being male, assuming equal numbers of males and females', [hy('male', F_(1, 2), D_(0.05)), hy('female', F_(1, 2), D_(0.0025))], 'grey hair', { target: 0 }),
  boardQ('Misc 13', 'Q4(i)', '90% of people are right-handed. Probability that at most 6 of a random sample of 10 people are right-handed. Step 1: the probability of exactly k', [mcqP('For k right-handed people out of 10 (independent, 0.9 each), P(exactly k) =', ['C(10, k)(0.9)ᵏ(0.1)¹⁰⁻ᵏ', '(0.9)ᵏ', 'k/10', 'C(10, k)(0.9)¹⁰'], 'Choose which k are right-handed; the rest are left-handed.'), mcqP('“At most 6” is easiest as', ['1 − P(7, 8, 9 or 10)', 'P(6) only', 'P(0) + P(10)', '6/10'], 'Four terms instead of seven.')], 'P(X = k) = C(10,k)(0.9)ᵏ(0.1)¹⁰⁻ᵏ'),
  boardQ('Misc 13', 'Q4(ii)', 'The four upper cases: P(exactly 7), P(8), P(9), P(10) right-handed', [pfld('P(exactly 7), 8, 9, 10 right-handed (4 decimals)', [['7', { n: Math.round(p7 * 1e4), d: 1e4 }, p7.toFixed(4)], ['8', { n: Math.round(p8 * 1e4), d: 1e4 }, p8.toFixed(4)], ['9', { n: Math.round(p9 * 1e4), d: 1e4 }, p9.toFixed(4)], ['10', { n: Math.round(p10 * 1e4), d: 1e4 }, p10.toFixed(4)]], 'P(k) = C(10,k)(0.9)ᵏ(0.1)¹⁰⁻ᵏ.')], '0.0574, 0.1937, 0.3874, 0.3487'),
  boardQ('Misc 13', 'Q4(iii)', 'Probability that at most 6 are right-handed', [{ k: 'num', q: 'P(at most 6) = 1 − (0.0574 + 0.1937 + 0.3874 + 0.3487) = ? (4 decimals)', a: 1 - pge7, show: (1 - pge7).toFixed(4), keys: '', tol: 2e-4, x: '1 − 0.9872 ≈ 0.0128.' }], '≈ 0.0128'),
  probO('Misc 13', 'Q5', 'A leap year is selected at random. Chance that it contains 53 Tuesdays (366 days = 52 weeks + 2 extra days)', weekSpace, 'an extra day is Tuesday', (it) => it.days.includes('Tue')),
  areaQ('Misc 13', 'Q6', 'Boxes A (1 red, 6 white, 3 black), B (6 red, 2 white, 2 black), C (8 red, 1 white, 1 black), D (0 red, 6 white, 4 black). A box is chosen at random and a red marble is drawn. Probability it came from box A, box B, box C', [hy('A', F_(1, 4), F_(1, 10)), hy('B', F_(1, 4), F_(3, 5)), hy('C', F_(1, 4), F_(4, 5)), hy('D', F_(1, 4), Q0)], 'red', { all: true }),
  areaQ('Misc 13', 'Q7', 'The chance of a heart attack is 40%. Meditation and yoga reduce it by 30%; a drug reduces it by 25%. A patient picks one option with equal probability and suffers a heart attack. Probability that he followed meditation and yoga', [hy('meditation', F_(1, 2), D_(0.28)), hy('drug', F_(1, 2), D_(0.3))], 'heart attack', { target: 0, steps: [step('Meditation: 40% reduced by 30% = 0.4 × 0.7 = ?', D_(0.28)), step('Drug: 0.4 × 0.75 = ?', D_(0.3))] }),
  probO('Misc 13', 'Q8', 'Each element of a second order determinant is 0 or 1, each with probability 1/2, independently. Probability that the determinant is positive', detSpace, 'ad − bc > 0', (it) => it.det > 0),
  vnQ('Misc 13', 'Q9(i)', 'P(A fails) = 0.2, P(B fails alone) = 0.15, P(A and B fail) = 0.15. Evaluate P(A fails | B has failed)', D_(0.2), D_(0.3), D_(0.15), [{ q: 'P(B fails) = P(B alone) + P(both) = ?', r: F_(3, 10), x: '0.15 + 0.15.', reveal: [] }, { q: 'P(A fails | B has failed) = ?', r: F_(1, 2), x: '0.15/0.30.', given: 'B' }], { hide: ['none'] }),
  vnQ('Misc 13', 'Q9(ii)', 'Evaluate P(A fails alone)', D_(0.2), D_(0.3), D_(0.15), [{ q: 'P(A fails alone) = P(A) − P(A and B) = ?', r: F_(1, 20), x: '0.2 − 0.15.', reveal: ['aOnly'] }], { hide: ['aOnly', 'none'] }),
  areaQ('Misc 13', 'Q10', 'Bag I has 3 red and 4 black balls, Bag II has 4 red and 5 black. One ball is moved from I to II, then a ball is drawn from II and is red. Probability that the transferred ball was black', [hy('black moved', F_(4, 7), F_(2, 5)), hy('red moved', F_(3, 7), F_(1, 2))], 'red drawn', { target: 0, steps: [step('If black moved, Bag II has 4 red of 10. P(red | black moved) = ?', F_(2, 5)), step('If red moved, Bag II has 5 red of 10. P(red | red moved) = ?', F_(1, 2))] }),
  boardQ('Misc 13', 'Q11', 'If A and B are events such that P(A) ≠ 0 and P(B|A) = 1, then (A) A ⊂ B (B) B ⊂ A (C) B = φ (D) A = φ', [mcqB('P(B|A) = P(A∩B)/P(A) = 1 means P(A ∩ B) = P(A), so', ['(A) A ⊂ B', '(B) B ⊂ A', '(C) B = φ', '(D) A = φ'], 'Every outcome of A lies in B.')], '(A) A ⊂ B'),
  boardQ('Misc 13', 'Q12', 'If P(A|B) > P(A), then (A) P(B|A) < P(B) (B) P(A ∩ B) < P(A)·P(B) (C) P(B|A) > P(B) (D) P(B|A) = P(B)', [mcqB('P(A|B) > P(A) means P(A ∩ B) > P(A)P(B). Divide by P(A):', ['(C) P(B|A) > P(B)', '(A) P(B|A) < P(B)', '(B) P(A ∩ B) < P(A)·P(B)', '(D) P(B|A) = P(B)'], 'If B makes A more likely, then A makes B more likely.')], '(C)'),
  boardQ('Misc 13', 'Q13', 'If P(A) + P(B) − P(A and B) = P(A), then (A) P(B|A) = 1 (B) P(A|B) = 1 (C) P(B|A) = 0 (D) P(A|B) = 0', [mcqB('The equation gives P(B) = P(A and B), so P(A|B) = P(A ∩ B)/P(B) =', ['(B) P(A|B) = 1', '(A) P(B|A) = 1', '(C) P(B|A) = 0', '(D) P(A|B) = 0'], 'B lies inside A.')], '(B) P(A|B) = 1'),
];
EX13M.forEach((q) => { if (q.n === 'Q1(ii)') q.ex = 'Misc 13'; });
