/* =========================================================
   CHAPTER 2 · RELATIONS & FUNCTIONS — every exercise question as a sim
   Relation answers are computed from their rules.
   ========================================================= */
const rel = (A, B, f) => prodPairs(A, B).filter(([a, b]) => f(a, b));
const pairPool = (ps) => ps.map(([a, b]) => pstr(a, b));

/* ===================== EXERCISE 2.1 ===================== */
const EX21 = [
  { ex: 'Ex 2.1', n: 'Q1', q: 'If ([[x|3]] + 1, y − [[2|3]]) = ([[5|3]], [[1|3]]), find x and y.', scene: 'board', kim: 'Equal pairs → two little equations.', parts: [{ k: 'fields', q: 'x/3 + 1 = 5/3 and y − 2/3 = 1/3', f: [{ l: 'x', a: 2 }, { l: 'y', a: 1 }], x: 'x/3 = 2/3 ⇒ x = 2;  y = 1/3 + 2/3 = 1.' }], w: ['x/3 + 1 = 5/3 ⇒ x/3 = 2/3 ⇒ x = 2', 'y − 2/3 = 1/3 ⇒ y = 1'] },
  { ex: 'Ex 2.1', n: 'Q2', q: 'If the set A has 3 elements and the set B = {3, 4, 5}, then find the number of elements in A × B.', scene: 'grid', setup: (W) => gridLoad(W, ['a₁', 'a₂', 'a₃'], [3, 4, 5]), parts: [{ k: 'num', q: 'n(A × B) = ?', a: 9, x: '3 × 3 = 9.', act: async () => gridLight(W, prodPairs(['a₁', 'a₂', 'a₃'], [3, 4, 5]), 0.06) }], w: ['n(A × B) = n(A) · n(B) = 3 × 3 = 9'] },
  { ex: 'Ex 2.1', n: 'Q3', q: 'If G = {7, 8} and H = {5, 4, 2}, find G × H and H × G.', scene: 'grid', parts: [gridPart('Tap every point of G × H', [7, 8], [5, 4, 2], prodPairs([7, 8], [5, 4, 2]), { labA: 'G', labB: 'H' }), gridPart('Now H × G (H goes first!)', [5, 4, 2], [7, 8], prodPairs([5, 4, 2], [7, 8]), { labA: 'H', labB: 'G' })], w: ['G × H = {(7,5), (7,4), (7,2), (8,5), (8,4), (8,2)}', 'H × G = {(5,7), (5,8), (4,7), (4,8), (2,7), (2,8)}'] },
  {
    ex: 'Ex 2.1', n: 'Q4', q: 'State whether each statement is true or false. If false, rewrite it correctly.', scene: 'grid', setup: (W) => gridLoad(W, ['m', 'n'], ['n', 'm'], { labA: 'P', labB: 'Q' }),
    parts: [
      { k: 'tf', q: '(i) If P = {m, n} and Q = {n, m}, then P × Q = {(m, n), (n, m)}.', a: false, x: 'P × Q has 4 pairs: {(m, m), (m, n), (n, m), (n, n)}.', act: async () => gridLight(W, prodPairs(['m', 'n'], ['n', 'm'])) },
      { k: 'tf', q: '(ii) If A and B are non-empty sets, then A × B is a non-empty set of ordered pairs (x, y) such that x ∈ A and y ∈ B.', a: true, x: 'That is the definition.' },
      { k: 'tf', q: '(iii) If A = {1, 2}, B = {3, 4}, then A × (B ∩ φ) = φ.', a: true, x: 'B ∩ φ = φ, and A × φ = φ.' },
    ],
    w: ['(i) False: P × Q = {(m, m), (m, n), (n, m), (n, n)}  (ii) True  (iii) True'],
  },
  { ex: 'Ex 2.1', n: 'Q5', q: 'If A = {−1, 1}, find A × A × A.', scene: 'board', parts: [{ k: 'pick', brace: false, q: 'Tap all 8 triplets', pool: ['(−1,−1,−1)', '(−1,−1,1)', '(−1,1,−1)', '(−1,1,1)', '(1,−1,−1)', '(1,−1,1)', '(1,1,−1)', '(1,1,1)', '(−1,1)', '(0,1,1)'], a: ['(−1,−1,−1)', '(−1,−1,1)', '(−1,1,−1)', '(−1,1,1)', '(1,−1,−1)', '(1,−1,1)', '(1,1,−1)', '(1,1,1)'], x: '2³ = 8 triplets.' }], w: ['A × A × A = {(−1,−1,−1), (−1,−1,1), (−1,1,−1), (−1,1,1), (1,−1,−1), (1,−1,1), (1,1,−1), (1,1,1)}'] },
  { ex: 'Ex 2.1', n: 'Q6', q: 'If A × B = {(a, x), (a, y), (b, x), (b, y)}, find A and B.', scene: 'grid', setup: (W) => gridLoad(W, ['a', 'b'], ['x', 'y'], { on: prodPairs(['a', 'b'], ['x', 'y']) }), parts: [{ k: 'pick', q: 'A = ?', pool: ['a', 'b', 'x', 'y'], a: ['a', 'b'], x: 'First elements.' }, { k: 'pick', q: 'B = ?', pool: ['a', 'b', 'x', 'y'], a: ['x', 'y'], x: 'Second elements.' }], w: ['A = {a, b}, B = {x, y}'] },
  {
    ex: 'Ex 2.1', n: 'Q7', q: 'A = {1, 2}, B = {1, 2, 3, 4}, C = {5, 6}, D = {5, 6, 7, 8}. Verify (i) A × (B ∩ C) = (A × B) ∩ (A × C) (ii) A × C is a subset of B × D.', scene: 'grid', setup: (W) => gridLoad(W, [1, 2, 3, 4], [1, 2, 3, 4, 5, 6, 7, 8], { labA: 'first', labB: 'second' }),
    parts: [
      { k: 'pick', q: 'B ∩ C = ?', pool: ['1', '2', '3', '4', '5', '6'], a: [], x: 'B and C share nothing: φ.' },
      { k: 'mcq', q: 'So A × (B ∩ C) = ?', o: ['φ', 'A', '{(1, 5)}', 'A × C'], a: 0, x: 'A × φ = φ.' },
      { k: 'mcq', q: 'A × B has second entries in {1,…,4}; A × C in {5, 6}. Their intersection is…', o: ['φ', 'A × B', '{(1, 1)}', '4 pairs'], a: 0, x: 'No common pair. Both sides are φ ✓.', act: async () => { await gridLight(W, prodPairs([1, 2], [1, 2, 3, 4]), 0.04); W.hl = new Set(prodPairs([1, 2], [5, 6]).map(([a, b]) => pk(a, b))); } },
      { k: 'tf', q: '(ii) A × C = {(1,5), (1,6), (2,5), (2,6)}. Is every pair in B × D?', o: ['Yes, A × C ⊂ B × D', 'No'], a: 0, x: '1, 2 ∈ B and 5, 6 ∈ D.', act: async () => { W.on = new Set(prodPairs([1, 2, 3, 4], [5, 6, 7, 8]).map(([a, b]) => pk(a, b))); SFX.whoosh(); } },
    ],
    w: ['(i) B ∩ C = φ ⇒ A × (B ∩ C) = φ; (A × B) ∩ (A × C) = φ. Verified.', '(ii) Each element of A × C has first entry in B and second in D, so A × C ⊂ B × D.'],
  },
  {
    ex: 'Ex 2.1', n: 'Q8', q: 'Let A = {1, 2} and B = {3, 4}. Write A × B. How many subsets will A × B have? List them.', scene: 'grid', setup: (W) => gridLoad(W, [1, 2], [3, 4]),
    parts: [{ k: 'pick', brace: false, q: 'A × B = ?', pool: ['(1,3)', '(1,4)', '(2,3)', '(2,4)', '(3,1)', '(4,2)'], a: ['(1,3)', '(1,4)', '(2,3)', '(2,4)'], x: '4 pairs.', act: async () => gridLight(W, prodPairs([1, 2], [3, 4])) }, { k: 'num', q: 'Number of subsets of A × B', a: 16, x: '2⁴ = 16.' }, { k: 'mcq', q: 'Which of these is NOT one of them?', o: ['φ', '{(1,3), (2,4)}', '{(3,1)}', '{(1,3), (1,4), (2,3), (2,4)}'], a: 2, x: '(3, 1) is not in A × B.' }],
    w: ['A × B = {(1,3), (1,4), (2,3), (2,4)}; it has 2⁴ = 16 subsets:', 'φ, 4 singletons, 6 pairs {(1,3),(1,4)}, {(1,3),(2,3)}, {(1,3),(2,4)}, {(1,4),(2,3)}, {(1,4),(2,4)}, {(2,3),(2,4)}, 4 triples, and A × B itself.'],
  },
  { ex: 'Ex 2.1', n: 'Q9', q: 'n(A) = 3, n(B) = 2. If (x, 1), (y, 2), (z, 1) are in A × B, find A and B (x, y, z distinct).', scene: 'grid', setup: (W) => gridLoad(W, ['x', 'y', 'z'], [1, 2], { on: [['x', 1], ['y', 2], ['z', 1]] }), parts: [{ k: 'pick', q: 'A = ?', pool: ['x', 'y', 'z', '1', '2'], a: ['x', 'y', 'z'], x: 'Three distinct first entries fill A.' }, { k: 'pick', q: 'B = ?', pool: ['x', 'y', 'z', '1', '2'], a: ['1', '2'], x: 'Two distinct second entries fill B.' }], w: ['A = {x, y, z}, B = {1, 2}'] },
  {
    ex: 'Ex 2.1', n: 'Q10', q: 'A × A has 9 elements, among which are (−1, 0) and (0, 1). Find A and the remaining elements of A × A.', scene: 'grid', setup: (W) => gridLoad(W, [-1, 0, 1], [-1, 0, 1], { on: [[-1, 0], [0, 1]] }),
    parts: [{ k: 'pick', q: 'n(A)² = 9, so n(A) = 3. A = ?', pool: ['−2', '−1', '0', '1', '2'], a: ['−1', '0', '1'], x: '−1, 0, 1 all appear.' }, gridPart('Tap all 9 points of A × A', [-1, 0, 1], [-1, 0, 1], prodPairs([-1, 0, 1], [-1, 0, 1]), { labA: 'A', labB: 'A' })],
    w: ['A = {−1, 0, 1}. Remaining: (−1,−1), (−1,1), (0,−1), (0,0), (1,−1), (1,0), (1,1)'],
  },
];

/* ===================== EXERCISE 2.2 ===================== */
const A14 = SET.range(1, 14);
const R1 = rel(A14, A14, (x, y) => 3 * x - y === 0);
const R3 = rel([1, 2, 3, 5], [4, 6, 9], (x, y) => Math.abs(x - y) % 2 === 1);
const A5r = [1, 2, 3, 4, 6]; const R5 = rel(A5r, A5r, (a, b) => b % a === 0);
const EX22 = [
  { ex: 'Ex 2.2', n: 'Q1', q: 'A = {1, 2, 3, …, 14}. R = {(x, y) : 3x − y = 0, x, y ∈ A}. Write its domain, codomain and range.', scene: 'arrows', setup: (W) => arrowsLoad(W, [1, 2, 3, 4, 5], [3, 6, 9, 12, 14], { LA: 'A (part)', LB: 'A (part)' }), kim: 'y = 3x and y must stay ≤ 14!', parts: [{ k: 'pick', brace: false, q: 'Tap the pairs in R', pool: pairPool([[1, 3], [2, 6], [3, 9], [4, 12], [5, 15], [3, 1]]), a: pairPool(R1), x: relStr(R1) + '. (5, 15) fails: 15 ∉ A.', act: async () => arrowsDraw(W, R1) }, { k: 'pick', q: 'Domain', pool: NUMS([1, 2, 3, 4, 5]), a: ['1', '2', '3', '4'], x: '{1, 2, 3, 4}' }, { k: 'mcq', q: 'Codomain', o: ['A = {1, 2, …, 14}', '{3, 6, 9, 12}', '{1, 2, 3, 4}', 'N'], a: 0, x: 'The whole target set A.' }, { k: 'pick', q: 'Range', pool: NUMS([3, 6, 9, 12, 14]), a: ['3', '6', '9', '12'], x: '{3, 6, 9, 12}' }], w: ['R = ' + relStr(R1), 'Domain = {1, 2, 3, 4}, Codomain = {1, 2, …, 14}, Range = {3, 6, 9, 12}'] },
  { ex: 'Ex 2.2', n: 'Q2', q: 'R on N: R = {(x, y) : y = x + 5, x is a natural number less than 4; x, y ∈ N}. Roster form, domain and range.', scene: 'machine', setup: (W) => { W.rule = 'y = x + 5'; W.f = (x) => x + 5; }, parts: [{ k: 'pick', brace: false, q: 'R in roster form', pool: pairPool([[0, 5], [1, 6], [2, 7], [3, 8], [4, 9]]), a: pairPool([[1, 6], [2, 7], [3, 8]]), x: 'x ∈ {1, 2, 3}.', act: async () => { for (const x of [1, 2, 3]) await feed(W, x, { d: 0.2 }); } }, { k: 'pick', q: 'Domain', pool: ['0', '1', '2', '3', '4'], a: ['1', '2', '3'], x: '{1, 2, 3}' }, { k: 'pick', q: 'Range', pool: ['5', '6', '7', '8', '9'], a: ['6', '7', '8'], x: '{6, 7, 8}' }], w: ['R = {(1, 6), (2, 7), (3, 8)}; domain {1, 2, 3}; range {6, 7, 8}'] },
  { ex: 'Ex 2.2', n: 'Q3', q: 'A = {1, 2, 3, 5}, B = {4, 6, 9}. R = {(x, y) : the difference between x and y is odd}. Write R in roster form.', scene: 'grid', kim: 'Odd difference means one is odd and the other even.', parts: [gridPart('Tap the pairs with an odd difference', [1, 2, 3, 5], [4, 6, 9], R3, { labA: 'A', labB: 'B' })], w: ['R = ' + relStr(R3)] },
  { ex: 'Ex 2.2', n: 'Q4', q: 'Fig 2.7 shows a relation between P = {5, 6, 7} and Q = {3, 4, 5}: 5→3, 6→4, 7→5. Write it in set-builder and roster form. Domain and range?', scene: 'arrows', setup: (W) => arrowsLoad(W, [5, 6, 7], [3, 4, 5], { LA: 'P', LB: 'Q', pairs: [[5, 3], [6, 4], [7, 5]] }), parts: [{ k: 'mcq', q: '(i) Set-builder form', o: ['{(x, y) : y = x − 2, x ∈ P, y ∈ Q}', '{(x, y) : y = x + 2}', '{(x, y) : y = x/2}', '{(x, y) : x = y − 2}'], a: 0, x: 'Each arrow subtracts 2.' }, { k: 'pick', brace: false, q: '(ii) Roster form', pool: pairPool([[5, 3], [6, 4], [7, 5], [3, 5], [5, 7]]), a: pairPool([[5, 3], [6, 4], [7, 5]]), x: '{(5, 3), (6, 4), (7, 5)}' }, { k: 'mcq', q: 'Domain and range', o: ['{5, 6, 7} and {3, 4, 5}', '{3, 4, 5} and {5, 6, 7}', 'P and N', '{5} and {3}'], a: 0, x: 'Every element is used on both sides.' }], w: ['R = {(x, y) : y = x − 2, x ∈ P, y ∈ Q} = {(5, 3), (6, 4), (7, 5)}', 'Domain = {5, 6, 7}, Range = {3, 4, 5}'] },
  { ex: 'Ex 2.2', n: 'Q5', q: 'A = {1, 2, 3, 4, 6}. R = {(a, b) : a, b ∈ A, b is exactly divisible by a}. (i) Roster form (ii) domain (iii) range.', scene: 'grid', parts: [gridPart('(i) Tap every (a, b) where a divides b', A5r, A5r, R5, { labA: 'a', labB: 'b' }), { k: 'pick', q: '(ii) Domain', pool: NUMS(A5r), a: NUMS(A5r), x: 'Every a divides itself.' }, { k: 'pick', q: '(iii) Range', pool: NUMS(A5r), a: NUMS(A5r), x: 'Every b is hit (b, b).' }], w: ['R = ' + relStr(R5), 'Domain = {1, 2, 3, 4, 6}, Range = {1, 2, 3, 4, 6}'] },
  { ex: 'Ex 2.2', n: 'Q6', q: 'Determine the domain and range of R = {(x, x + 5) : x ∈ {0, 1, 2, 3, 4, 5}}.', scene: 'machine', setup: (W) => { W.rule = 'x ↦ x + 5'; W.f = (x) => x + 5; }, parts: [{ k: 'run', run: async () => { for (const x of [0, 1, 2, 3, 4, 5]) await feed(W, x, { d: 0.15 }); } }, { k: 'pick', q: 'Domain', pool: NUMS(SET.range(0, 10)), a: NUMS(SET.range(0, 5)), x: '{0, 1, 2, 3, 4, 5}' }, { k: 'pick', q: 'Range', pool: NUMS(SET.range(0, 10)), a: NUMS(SET.range(5, 10)), x: '{5, 6, 7, 8, 9, 10}' }], w: ['Domain = {0, 1, 2, 3, 4, 5}, Range = {5, 6, 7, 8, 9, 10}'] },
  { ex: 'Ex 2.2', n: 'Q7', q: 'Write the relation R = {(x, x³) : x is a prime number less than 10} in roster form.', scene: 'machine', setup: (W) => { W.rule = 'x ↦ x³'; W.f = (x) => x ** 3; }, parts: [{ k: 'pick', brace: false, q: 'Tap the pairs', pool: pairPool([[1, 1], [2, 8], [3, 27], [4, 64], [5, 125], [7, 343], [9, 729]]), a: pairPool([[2, 8], [3, 27], [5, 125], [7, 343]]), x: 'Primes below 10: 2, 3, 5, 7.', act: async () => { for (const x of [2, 3, 5, 7]) await feed(W, x, { d: 0.15 }); } }], w: ['R = {(2, 8), (3, 27), (5, 125), (7, 343)}'] },
  { ex: 'Ex 2.2', n: 'Q8', q: 'Let A = {x, y, z} and B = {1, 2}. Find the number of relations from A to B.', scene: 'grid', setup: (W) => gridLoad(W, ['x', 'y', 'z'], [1, 2], { on: prodPairs(['x', 'y', 'z'], [1, 2]) }), parts: [{ k: 'num', q: 'n(A × B) = ?', a: 6, x: '3 × 2.' }, { k: 'num', q: 'Number of relations = 2^{6} = ?', a: 64, x: '2⁶ = 64.' }], w: ['n(A × B) = 6, so number of relations = 2⁶ = 64'] },
  { ex: 'Ex 2.2', n: 'Q9', q: 'R on Z: R = {(a, b) : a, b ∈ Z, a − b is an integer}. Find the domain and range.', scene: 'grid', setup: (W) => gridLoad(W, [-2, -1, 0, 1, 2], [-2, -1, 0, 1, 2], { on: prodPairs([-2, -1, 0, 1, 2], [-2, -1, 0, 1, 2]) }), parts: [{ k: 'mcq', q: 'Domain = Range = ?', o: ['Z', 'N', '{0}', 'Q'], a: 0, x: 'a − b is ALWAYS an integer, so every pair of integers is in R.' }], w: ['Every a, b ∈ Z gives a − b ∈ Z, so domain = range = Z.'] },
];

/* ===================== EXERCISE 2.3 ===================== */
const EX23 = [
  {
    ex: 'Ex 2.3', n: 'Q1', q: 'Which of the following relations are functions? If a function, give its domain and range.', scene: 'arrows',
    parts: [
      { pre: () => arrowsLoad(W, [2, 5, 8, 11, 14, 17], [1], { pairs: [2, 5, 8, 11, 14, 17].map((x) => [x, 1]) }), k: 'tf', q: '(i) {(2,1), (5,1), (8,1), (11,1), (14,1), (17,1)}', o: ['Function', 'Not a function'], a: 0, x: 'One image each (all the same, which is allowed). Domain {2, 5, 8, 11, 14, 17}, range {1}.', act: async () => { W.fnCheck = true; } },
      { pre: () => { W.fnCheck = false; arrowsLoad(W, [2, 4, 6, 8, 10, 12, 14], [1, 2, 3, 4, 5, 6, 7], { pairs: [2, 4, 6, 8, 10, 12, 14].map((x) => [x, x / 2]) }); }, k: 'tf', q: '(ii) {(2,1), (4,2), (6,3), (8,4), (10,5), (12,6), (14,7)}', o: ['Function', 'Not a function'], a: 0, x: 'Domain {2, 4, …, 14}, range {1, 2, …, 7}.', act: async () => { W.fnCheck = true; } },
      { pre: () => { W.fnCheck = false; arrowsLoad(W, [1, 2], [3, 5], { pairs: [[1, 3], [1, 5], [2, 5]] }); }, k: 'tf', q: '(iii) {(1,3), (1,5), (2,5)}', o: ['Function', 'Not a function'], a: 1, x: '1 has two images, 3 and 5.', act: async () => { W.fnCheck = true; } },
    ],
    w: ['(i) Function: domain {2, 5, 8, 11, 14, 17}, range {1}', '(ii) Function: domain {2, 4, 6, 8, 10, 12, 14}, range {1, 2, 3, 4, 5, 6, 7}', '(iii) Not a function: 1 has two images.'],
  },
  {
    ex: 'Ex 2.3', n: 'Q2', q: 'Find the domain and range of (i) f(x) = −|x| (ii) f(x) = √(9 − x²).', scene: 'plane', setup: (W) => planeView(W, -5, 5, -4, 4),
    parts: [
      { k: 'mcq', q: '(i) f(x) = −|x|: range = ?', o: ['R', '(−∞, 0]', '[0, ∞)', '(−∞, 0)'], a: 1, x: 'Domain R, range (−∞, 0].', pre: () => drawCurves(W, [curve((x) => -Math.abs(x), C.sora, { t: 'y = −|x|' })], 0.6), act: async () => { W.shadeY = { a: -9, b: 0 }; } },
      { k: 'mcq', q: '(ii) f(x) = √(9 − x²): domain = ?', o: ['R', '[−3, 3]', '(−3, 3)', '[0, 3]'], a: 1, x: '9 − x² ≥ 0 ⇒ −3 ≤ x ≤ 3.', pre: () => { W.curves = []; W.shadeY = null; return drawCurves(W, [curve((x) => Math.sqrt(9 - x * x), C.beni, { x0: -3, x1: 3, t: 'y = √(9 − x²)' })], 0.7); }, act: async () => { W.shadeX = { a: -3, b: 3 }; } },
      { k: 'mcq', q: '(ii) and its range = ?', o: ['[−3, 3]', '[0, 3]', '[0, 9]', '[0, ∞)'], a: 1, x: 'Largest at x = 0 (value 3), smallest 0 at x = ±3.', act: async () => { W.shadeY = { a: 0, b: 3 }; } },
    ],
    w: ['(i) Domain R, range (−∞, 0]', '(ii) Domain [−3, 3], range [0, 3]'],
  },
  { ex: 'Ex 2.3', n: 'Q3', q: 'A function f is defined by f(x) = 2x − 5. Write down the values of (i) f(0) (ii) f(7) (iii) f(−3).', scene: 'machine', setup: (W) => { W.rule = 'f(x) = 2x − 5'; W.f = (x) => 2 * x - 5; W.rows = [0, 7, -3].map((x) => ({ x, yShow: false })); }, parts: [0, 7, -3].map((x, i) => ({ k: 'num', q: '(' + ['i', 'ii', 'iii'][i] + ') f(' + SET.lbl(x) + ') = ?', a: 2 * x - 5, x: '2(' + SET.lbl(x) + ') − 5 = ' + SET.lbl(2 * x - 5) + '.', act: async () => feed(W, x, { d: 0.2 }) })), w: ['f(0) = −5, f(7) = 9, f(−3) = −11'] },
  { ex: 'Ex 2.3', n: 'Q4', q: 't(C) = [[9C|5]] + 32 maps Celsius to Fahrenheit. Find (i) t(0) (ii) t(28) (iii) t(−10) (iv) C when t(C) = 212.', scene: 'machine', setup: (W) => { W.rule = 't(C) = 9C/5 + 32'; W.f = (c) => (9 * c) / 5 + 32; W.yLab = 't(C)'; }, parts: [...[0, 28, -10].map((c, i) => ({ k: 'num', q: '(' + ['i', 'ii', 'iii'][i] + ') t(' + SET.lbl(c) + ') = ?', a: (9 * c) / 5 + 32, x: '9 × ' + SET.lbl(c) + '/5 + 32 = ' + fmtN((9 * c) / 5 + 32), act: async () => feed(W, c, { d: 0.2 }) })), { k: 'num', q: '(iv) 9C/5 + 32 = 212 ⇒ C = ?', a: 100, x: '9C/5 = 180 ⇒ C = 100. Water boils!', act: async () => feed(W, 100, { d: 0.2 }) }], w: ['t(0) = 32, t(28) = 82.4, t(−10) = 14, C = 100 when t(C) = 212'] },
  {
    ex: 'Ex 2.3', n: 'Q5', q: 'Find the range of each function: (i) f(x) = 2 − 3x, x ∈ R, x > 0 (ii) f(x) = x² + 2 (iii) f(x) = x.', scene: 'plane', setup: (W) => planeView(W, -3, 4, -4, 7),
    parts: [
      { pre: () => drawCurves(W, [curve((x) => 2 - 3 * x, C.sora, { x0: 0.001, open: [[0, 2]], t: 'y = 2 − 3x, x > 0' })], 0.6), k: 'mcq', q: '(i) Range of 2 − 3x for x > 0', o: ['(−∞, 2)', '(−∞, 2]', '(2, ∞)', 'R'], a: 0, x: 'x > 0 ⇒ −3x < 0 ⇒ 2 − 3x < 2.', act: async () => { W.shadeY = { a: -9, b: 2 }; } },
      { pre: () => { W.curves = []; W.shadeY = null; return drawCurves(W, [curve((x) => x * x + 2, C.beni, { t: 'y = x² + 2' })], 0.6); }, k: 'mcq', q: '(ii) Range of x² + 2', o: ['[2, ∞)', '(2, ∞)', 'R', '[0, ∞)'], a: 0, x: 'x² ≥ 0 ⇒ x² + 2 ≥ 2.', act: async () => { W.shadeY = { a: 2, b: 9 }; } },
      { pre: () => { W.curves = []; W.shadeY = null; return drawCurves(W, [curve((x) => x, C.sora, { t: 'y = x' })], 0.6); }, k: 'mcq', q: '(iii) Range of f(x) = x', o: ['R', '[0, ∞)', '{0}', 'N'], a: 0, x: 'Identity: every real is an output.' },
    ],
    w: ['(i) (−∞, 2)  (ii) [2, ∞)  (iii) R'],
  },
];

/* ===================== MISCELLANEOUS ===================== */
const EX2M = [
  { ex: 'Misc', n: 'Q1', q: 'f(x) = x² for 0 ≤ x ≤ 3 and 3x for 3 ≤ x ≤ 10. g(x) = x² for 0 ≤ x ≤ 2 and 3x for 2 ≤ x ≤ 10. Show f is a function and g is not.', scene: 'plane', setup: (W) => planeView(W, -0.5, 6, -1, 20, 1, 4), kim: 'The danger point is where the two pieces meet.', parts: [{ k: 'num', q: 'f at x = 3: first piece gives 3² = 9, second gives 3 × 3 = ?', a: 9, x: 'Both 9: no clash, f is a function.', pre: () => drawCurves(W, [curve((x) => (x <= 3 ? x * x : 3 * x), C.sora, { x0: 0, t: 'f' })], 0.6) }, { k: 'fields', q: 'g at x = 2: x² gives ? and 3x gives ?', f: [{ l: 'x²', a: 4 }, { l: '3x', a: 6 }], x: '4 ≠ 6: x = 2 has two images, so g is not a function.', pre: () => { W.curves = []; return drawCurves(W, [curve((x) => x * x, C.beni, { x0: 0, x1: 2 }), curve((x) => 3 * x, C.beni, { x0: 2, t: 'g' })], 0.6); }, act: async () => { W.pts.push({ x: 2, y: 4, t: '(2, 4)', col: C.beni }, { x: 2, y: 6, t: '(2, 6)', col: C.beni }); W.vline = { on: true, x: 2, hits: () => [4, 6] }; } }], w: ['At x = 3: x² = 9 = 3x, so f has one image everywhere: f is a function.', 'At x = 2: x² = 4 but 3x = 6, so 2 has two images: g is not a function.'] },
  { ex: 'Misc', n: 'Q2', q: 'If f(x) = x², find [[f(1.1) − f(1)|1.1 − 1]].', scene: 'plane', setup: (W) => { planeView(W, -0.5, 2, -0.3, 2); W.curves.push(curve((x) => x * x, C.sora, { p: 1, t: 'x²' })); W.pts.push({ x: 1, y: 1, t: '(1, 1)' }, { x: 1.1, y: 1.21, t: '(1.1, 1.21)', dy: -20 }); }, parts: [{ k: 'num', q: 'f(1.1) = ?', a: 1.21, x: '1.1² = 1.21.' }, { k: 'num', q: '(1.21 − 1)/0.1 = ?', a: 2.1, x: '0.21/0.1 = 2.1 (the slope of the chord).', act: async () => { W.vecs.push({ x0: 0.4, y0: 1 - 0.6 * 2.1, x1: 1.6, y1: 1 + 0.6 * 2.1, col: C.beni, dash: true }); } }], w: ['[f(1.1) − f(1)]/(1.1 − 1) = (1.21 − 1)/0.1 = 2.1'] },
  { ex: 'Misc', n: 'Q3', q: 'Find the domain of f(x) = [[x² + 2x + 1|x² − 8x + 12]].', scene: 'plane', setup: (W) => planeView(W, -2, 9, -10, 10, 1, 2), parts: [{ k: 'pick', brace: false, q: 'The bottom (x − 2)(x − 6) vanishes at…', pool: ['−6', '−2', '1', '2', '6', '12'], a: ['2', '6'], x: 'x² − 8x + 12 = (x − 2)(x − 6).', act: async () => { await drawCurves(W, [curve((x) => (x * x + 2 * x + 1) / (x * x - 8 * x + 12), C.sora, { n: 1500 })]); W.vecs.push({ x0: 2, y0: -10, x1: 2, y1: 10, col: C.beni, dash: true, t: 'x = 2' }, { x0: 6, y0: -10, x1: 6, y1: 10, col: C.beni, dash: true, t: 'x = 6' }); } }, { k: 'mcq', q: 'Domain = ?', o: ['R', 'R − {2, 6}', 'R − {−1}', '(2, 6)'], a: 1, x: 'Remove the two zeros of the denominator.' }], w: ['x² − 8x + 12 = (x − 2)(x − 6) ≠ 0, so domain = R − {2, 6}'] },
  { ex: 'Misc', n: 'Q4', q: 'Find the domain and range of f(x) = √(x − 1).', scene: 'plane', setup: (W) => planeView(W, -1, 8, -1, 3.5), parts: [{ k: 'mcq', q: 'Domain', o: ['[1, ∞)', '(1, ∞)', 'R', '[0, ∞)'], a: 0, x: 'x − 1 ≥ 0.', act: async () => { await drawCurves(W, [curve((x) => Math.sqrt(x - 1), C.sora, { x0: 1, closed: [[1, 0]], t: 'y = √(x − 1)' })]); W.shadeX = { a: 1, b: 99 }; } }, { k: 'mcq', q: 'Range', o: ['[1, ∞)', '[0, ∞)', 'R', '(0, ∞)'], a: 1, x: 'A square root is never negative and takes every value ≥ 0.', act: async () => { W.shadeY = { a: 0, b: 99 }; } }], w: ['Domain [1, ∞), range [0, ∞)'] },
  { ex: 'Misc', n: 'Q5', q: 'Find the domain and range of f(x) = |x − 1|.', scene: 'plane', setup: (W) => planeView(W, -3, 5, -1, 4), parts: [{ k: 'mcq', q: 'Domain', o: ['R', '[1, ∞)', '[0, ∞)', 'R − {1}'], a: 0, x: '|x − 1| works for every x.', act: async () => drawCurves(W, [curve((x) => Math.abs(x - 1), C.sora, { t: 'y = |x − 1|' })]) }, { k: 'mcq', q: 'Range', o: ['R', '[0, ∞)', '[1, ∞)', '(0, ∞)'], a: 1, x: 'Lowest value 0 at x = 1.', act: async () => { W.shadeY = { a: 0, b: 99 }; } }], w: ['Domain R, range [0, ∞)'] },
  { ex: 'Misc', n: 'Q6', q: 'Let f = {(x, [[x²|1 + x²]]) : x ∈ R} be a function from R into R. Determine the range of f.', scene: 'plane', setup: (W) => planeView(W, -5, 5, -0.6, 1.6, 1, 0.5), kim: 'The top is always smaller than the bottom…', parts: [{ k: 'mcq', q: 'Range of x²/(1 + x²)', o: ['[0, 1)', '[0, 1]', '(0, 1)', '[0, ∞)'], a: 0, x: '0 at x = 0; approaches 1 but never reaches it since x² < 1 + x².', act: async () => { await drawCurves(W, [curve((x) => (x * x) / (1 + x * x), C.sora, { t: 'y = x²/(1+x²)' }), curve(() => 1, C.beni, { dash: [6, 6], w: 2, t: 'y = 1 (never reached)' })]); W.shadeY = { a: 0, b: 1 }; } }], w: ['0 ≤ x²/(1 + x²) < 1, and every value in [0, 1) is attained, so range = [0, 1).'] },
  { ex: 'Misc', n: 'Q7', q: 'f(x) = x + 1, g(x) = 2x − 3. Find f + g, f − g and f/g.', scene: 'plane', setup: (W) => { planeView(W, -3, 4, -6, 6); W.curves.push(curve((x) => x + 1, C.sora, { p: 1, t: 'f' }), curve((x) => 2 * x - 3, C.khaki, { p: 1, t: 'g' })); }, parts: [{ k: 'mcq', q: '(f + g)(x)', o: ['3x − 2', '3x + 4', 'x − 4', '3x − 4'], a: 0, x: 'x + 1 + 2x − 3.', act: async () => drawCurves(W, [curve((x) => 3 * x - 2, C.beni, { t: 'f + g' })], 0.5) }, { k: 'mcq', q: '(f − g)(x)', o: ['−x + 4', '−x − 2', 'x − 4', '3x − 2'], a: 0, x: 'x + 1 − 2x + 3.' }, { k: 'mcq', q: '(f/g)(x)', o: ['[[x + 1|2x − 3]], x ≠ [[3|2]]', '[[x + 1|2x − 3]] for all x', '[[2x − 3|x + 1]]', 'x + 1 − 2x + 3'], a: 0, x: 'Remove x = 3/2 where g = 0.' }], w: ['f + g = 3x − 2;  f − g = −x + 4;  f/g = (x + 1)/(2x − 3), x ≠ 3/2'] },
  { ex: 'Misc', n: 'Q8', q: 'f = {(1,1), (2,3), (0,−1), (−1,−3)} from Z to Z is f(x) = ax + b. Determine a, b.', scene: 'plane', setup: (W) => { planeView(W, -3, 3, -4, 4); W.pts.push({ x: 1, y: 1 }, { x: 2, y: 3 }, { x: 0, y: -1 }, { x: -1, y: -3 }); }, parts: [{ k: 'fields', q: 'f(0) = b = −1, f(1) = a + b = 1', f: [{ l: 'a', a: 2 }, { l: 'b', a: -1 }], x: 'a = 2, b = −1.', act: async () => drawCurves(W, [curve((x) => 2 * x - 1, C.beni, { t: 'f(x) = 2x − 1' })]) }], w: ['f(0) = b = −1; f(1) = a + b = 1 ⇒ a = 2. So f(x) = 2x − 1.'] },
  { ex: 'Misc', n: 'Q9', q: 'R from N to N: R = {(a, b) : a, b ∈ N and a = b²}. Are these true?', scene: 'arrows', setup: (W) => arrowsLoad(W, [1, 4, 9, 16], [1, 2, 3, 4], { LA: 'a', LB: 'b', pairs: [[1, 1], [4, 2], [9, 3], [16, 4]] }), parts: [{ k: 'tf', q: '(i) (a, a) ∈ R for all a ∈ N', a: false, x: '(2, 2): 2 ≠ 2² = 4.' }, { k: 'tf', q: '(ii) (a, b) ∈ R implies (b, a) ∈ R', a: false, x: '(4, 2) ∈ R but (2, 4) ∉ R since 2 ≠ 16.' }, { k: 'tf', q: '(iii) (a, b) ∈ R, (b, c) ∈ R implies (a, c) ∈ R', a: false, x: '(16, 4), (4, 2) ∈ R but 16 ≠ 2² so (16, 2) ∉ R.' }], w: ['(i) False: (2, 2) ∉ R.  (ii) False: (4, 2) ∈ R, (2, 4) ∉ R.  (iii) False: (16, 4), (4, 2) ∈ R but (16, 2) ∉ R.'] },
  { ex: 'Misc', n: 'Q10', q: 'A = {1, 2, 3, 4}, B = {1, 5, 9, 11, 15, 16}, f = {(1,5), (2,9), (3,1), (4,5), (2,11)}. Are these true?', scene: 'arrows', setup: (W) => arrowsLoad(W, [1, 2, 3, 4], [1, 5, 9, 11, 15, 16], { pairs: [[1, 5], [2, 9], [3, 1], [4, 5], [2, 11]] }), parts: [{ k: 'tf', q: '(i) f is a relation from A to B', a: true, x: 'Every pair is in A × B.' }, { k: 'tf', q: '(ii) f is a function from A to B', a: false, x: '2 has two images, 9 and 11.', act: async () => { W.fnCheck = true; SFX.zap(); } }], w: ['(i) True: f ⊂ A × B.  (ii) False: 2 ↦ 9 and 2 ↦ 11.'] },
  { ex: 'Misc', n: 'Q11', q: 'Let f = {(ab, a + b) : a, b ∈ Z}. Is f a function from Z to Z?', scene: 'arrows', setup: (W) => arrowsLoad(W, [0, 2], [1, 2, 3], { LA: 'ab', LB: 'a + b', pairs: [[0, 1], [0, 2], [2, 3]] }), kim: 'Try a = 0 with different b…', parts: [{ k: 'mcq', q: 'a = 0, b = 1 gives (0, 1). a = 0, b = 2 gives…', o: ['(0, 2)', '(2, 0)', '(0, 1)', '(1, 2)'], a: 0, x: 'So 0 is sent to both 1 and 2.' }, { k: 'tf', q: 'Is f a function?', o: ['Yes', 'No'], a: 1, x: 'One input, two outputs.', act: async () => { W.fnCheck = true; } }], w: ['(0, 1) and (0, 2) both belong to f (a = 0, b = 1 and a = 0, b = 2). So f is not a function.'] },
  { ex: 'Misc', n: 'Q12', q: 'A = {9, 10, 11, 12, 13}, f : A → N, f(n) = the highest prime factor of n. Find the range of f.', scene: 'machine', setup: (W) => { W.rule = 'highest prime factor'; W.f = (n) => { let p = 1, m = n; for (let d = 2; d <= m; d++) while (m % d === 0) { p = d; m /= d; } return p; }; }, parts: [{ k: 'run', run: async () => { for (const n of [9, 10, 11, 12, 13]) await feed(W, n, { d: 0.18 }); } }, { k: 'pick', q: 'Range of f', pool: ['2', '3', '5', '9', '11', '13'], a: ['3', '5', '11', '13'], x: '9→3, 10→5, 11→11, 12→3, 13→13.' }], w: ['f(9) = 3, f(10) = 5, f(11) = 11, f(12) = 3, f(13) = 13. Range = {3, 5, 11, 13}'] },
];

const BOSS2 = [
  ['n(A) = 4, n(B) = 3. n(A × B) = ?', ['7', '12', '64', '81'], 1],
  ['(a + 1, 3) = (5, b − 1). a + b = ?', ['8', '7', '9', '6'], 0],
  ['Number of relations from {1, 2} to {a, b, c}', ['6', '8', '64', '32'], 2],
  ['Which is a function?', ['{(1,2), (1,3)}', '{(1,2), (2,2)}', '{(2,1), (2,3)}', '{(1,1), (1,2), (2,2)}'], 1],
  ['Range of f(x) = x² + 1', ['R', '[1, ∞)', '(1, ∞)', '[0, ∞)'], 1],
  ['Domain of 1/(x − 3)', ['R', 'R − {3}', 'R − {0}', '(3, ∞)'], 1],
  ['[−2.3] = ?', ['−2', '−3', '2', '−2.3'], 1],
  ['Range of signum', ['{−1, 1}', '{−1, 0, 1}', 'R', '[−1, 1]'], 1],
  ['f(x) = 3x, g(x) = x − 1. (fg)(2) = ?', ['6', '7', '5', '4'], 0],
  ['Domain of √(4 − x²)', ['[−2, 2]', '(−2, 2)', 'R', '[0, 2]'], 0],
];
LESSONS.splice(1, 0, exLesson({ id: 'ex21', title: 'Exercise 2.1', blurb: 'Ordered pairs and Cartesian products on a grid.', qs: EX21 }));
LESSONS.splice(3, 0, exLesson({ id: 'ex22', title: 'Exercise 2.2', blurb: 'Relations: arrows, roster form, domain and range.', face: 'kimmy-curious', qs: EX22 }));
LESSONS.splice(7, 0, exLesson({ id: 'ex23', title: 'Exercise 2.3', blurb: 'Functions, domains, ranges and values.', face: 'kimmy-excited', qs: EX23 }));
LESSONS.push(exLesson({ id: 'misc', title: 'Miscellaneous', blurb: 'All 12 Miscellaneous Exercise questions.', face: 'jess-thinking', qs: EX2M }));
LESSONS.push(lesson({
  id: 'boss', title: 'Boss Battle', blurb: 'Ten fast questions. Speed points. Beat Kimmy.', face: 'jess-excited',
  steps: [async function () { enterScene('board', (W) => { W.tag = 'BOSS'; W.sub = 'Chapter 2'; }); await slam('BOSS BATTLE', '10 questions · speed counts'); await K('play', 'I scored 7,200 this time. Come at me!'); await cont('Fight'); }, ...BOSS2.map(([q, o, a], i) => async function () { enterScene('board', (W) => { W.tag = 'Q' + (i + 1); W.sub = 'Boss Battle'; }); await quiz(q, o, a, plain(o[a]) + '.', null, 15); await cont(); }), async function () { enterScene('board', (W) => { W.tag = 'K.O.!'; W.sub = 'Chapter 2'; }); await summary(['Chapter 2 complete!', 'Products · Relations · Functions · Graphs', { t: 'n(A × B) = pq · #relations = 2^{pq}', eq: true }]); }],
}));
LESSONS.forEach((l) => { if (l.kind === 'ex') l.short = l.id === 'misc' ? 'M' : l.title.replace('Exercise ', ''); });
