/* =========================================================
   CHAPTER 3 · TRIGONOMETRIC FUNCTIONS — every exercise question as a sim
   Proofs: live LHS/RHS graph check → key identity → order the proof steps.
   ========================================================= */
const { sin, cos, tan, sqrt } = Math; const cot = (x) => 1 / tan(x), sec = (x) => 1 / cos(x), cosec = (x) => 1 / sin(x);
const RQ = ' √';

/* ===================== EXERCISE 3.1 ===================== */
const EX31 = [
  ...[['(i)', '25°', 25, '5/36', '5π/36'], ['(ii)', '−47° 30′', -47.5, '-19/72', '−19π/72'], ['(iii)', '240°', 240, '4/3', '4π/3'], ['(iv)', '520°', 520, '26/9', '26π/9']].map(([p, s, d, k, show]) => ({ ex: 'Ex 3.1', n: 'Q1 ' + p, q: 'Find the radian measure of ' + s + '.', scene: 'circle', setup: (W) => { W.uc.th = 0; }, parts: [{ k: 'num', q: s + ' × π/180 = ?·π   (type the multiplier, e.g. 5/36)', a: k, show: k.replace('-', '−'), x: s + ' = ' + show + ', so the multiplier is ' + k.replace('-', '−') + '.', act: async () => spinTo(W, D2R(d), Math.abs(d) > 360 ? 1.6 : 1) }], w: [s + ' = ' + s.replace('°', '') + ' × π/180 = ' + show] })),
  ...[['(i)', '11/16', 11 / 16, ['39° 22′ 30″', '39° 22′', '40° 10′', '38° 30′'], 0, '(11/16) × 180 × 7/22 = 39.375° = 39° 22′ 30″'], ['(ii)', '−4', -4, ['−229° 5′ 27″', '−229° 5′', '−230°', '−228° 30′'], 0, '−4 × 180 × 7/22 = −229 1/11° = −229° 5′ 27″'], ['(iii)', '5π/3', (5 * PI) / 3, ['300°', '330°', '240°', '150°'], 0, '(5π/3) × 180/π = 300°'], ['(iv)', '7π/6', (7 * PI) / 6, ['200°', '210°', '220°', '105°'], 1, '(7π/6) × 180/π = 210°']].map(([p, s, r, o, a, w]) => ({ ex: 'Ex 3.1', n: 'Q2 ' + p, q: 'Find the degree measure of ' + s + ' radians (use π = 22/7).', scene: 'circle', setup: (W) => { W.uc.th = 0; }, parts: [{ k: 'mcq', q: s + ' rad = ?', o, a, x: w, act: async () => spinTo(W, r) }], w: [w] })),
  { ex: 'Ex 3.1', n: 'Q3', q: 'A wheel makes 360 revolutions in one minute. Through how many radians does it turn in one second?', scene: 'arc', setup: (W) => { W.mode = 'wheel'; W.cap = '360 rev / min'; }, parts: [{ k: 'num', q: 'Revolutions per second = ?', a: 6, x: '360/60 = 6.', act: async () => { W.spin = 0; await tw(W, { spin: 12 * PI, duration: 1, ease: 'none' }); W.cap = 'in 1 second'; } }, { k: 'num', q: 'Radians per second = ?   (π key allowed)', a: '12π', show: '12π', keys: 'π', x: '6 × 2π = 12π.' }], w: ['360 rev/min = 6 rev/s; 1 rev = 2π rad ⇒ 12π radians in one second.'] },
  { ex: 'Ex 3.1', n: 'Q4', q: 'Find the degree measure of the angle subtended at the centre of a circle of radius 100 cm by an arc of length 22 cm (π = 22/7).', scene: 'arc', setup: (W) => { W.mode = 'arc'; W.th = 0.22; W.cap = 'r = 100, l = 22'; }, parts: [{ k: 'num', q: 'θ = l/r = ? radians', a: 0.22, x: '22/100.' }, { k: 'mcq', q: '0.22 × 180 × 7/22 = ?', o: ['12° 36′', '12° 6′', '13° 36′', '12.36°'], a: 0, x: '12.6° = 12° 36′.' }], w: ['θ = 22/100 rad = (22/100) × (180 × 7/22)° = 12.6° = 12° 36′'] },
  { ex: 'Ex 3.1', n: 'Q5', q: 'In a circle of diameter 40 cm, the length of a chord is 20 cm. Find the length of the minor arc of the chord.', scene: 'arc', setup: (W) => { W.mode = 'arc'; W.th = PI / 3; W.cap = 'r = 20, chord = 20'; }, kim: 'Chord = radius… that makes an equilateral triangle!', parts: [{ k: 'mcq', q: 'Central angle = ?', o: ['30°', '60°', '90°', '45°'], a: 1, x: 'Equilateral triangle: π/3.' }, { k: 'num', q: 'Arc = rθ = 20 × π/3 = ? cm  (π key allowed)', a: '20π/3', show: '20π/3', keys: 'π', x: '20π/3 cm ≈ 20.95 cm.' }], w: ['r = 20 = chord, so the triangle is equilateral and θ = π/3. l = 20 × π/3 = 20π/3 cm.'] },
  { ex: 'Ex 3.1', n: 'Q6', q: 'If in two circles, arcs of the same length subtend angles 60° and 75° at the centre, find the ratio of their radii.', scene: 'arc', setup: (W) => { W.mode = 'arc'; W.th = D2R(60); }, parts: [{ k: 'mcq', q: 'r₁ : r₂ = ?', o: ['4 : 5', '5 : 4', '60 : 75', '1 : 1'], a: 1, x: 'r₁ × 60 = r₂ × 75 ⇒ r₁/r₂ = 75/60 = 5/4.' }], w: ['l = r₁(π/3) = r₂(5π/12) ⇒ r₁ : r₂ = 5 : 4'] },
  { ex: 'Ex 3.1', n: 'Q7', q: 'A pendulum 75 cm long swings. Find the angle in radians if its tip describes an arc of (i) 10 cm (ii) 15 cm (iii) 21 cm.', scene: 'arc', setup: (W) => { W.mode = 'pend'; W.Lcm = 75; W.lcm = 10; W.pth = 10 / 75; }, parts: [[10, '2/15'], [15, '1/5'], [21, '7/25']].map(([l, a], i) => ({ pre: () => { W.lcm = l; gsap.to(W, { pth: l / 75, duration: 0.5 }); }, k: 'num', q: '(' + ['i', 'ii', 'iii'][i] + ') θ = ' + l + '/75 = ?', a, x: 'θ = ' + a + ' rad.', act: async () => { W.cap = 'θ = ' + a + ' rad'; } })), w: ['θ = l/r: (i) 10/75 = 2/15 (ii) 15/75 = 1/5 (iii) 21/75 = 7/25 radian'] },
];

/* ===================== EXERCISE 3.2 ===================== */
function fiveQ(n, given, quad, th, main, rest, wl) {
  return {
    ex: 'Ex 3.2', th, n, q: 'Find the values of the other five trigonometric functions: ' + given + ', x lies in quadrant ' + ['I', 'II', 'III', 'IV'][quad - 1] + '.', scene: 'circle', setup: (W) => { W.uc.th = th; W.uc.shadeQ = quad; W.uc.astc = true; W.uc.vals = false; },
    parts: [
      { k: 'mcq', q: 'Which functions are positive in quadrant ' + ['I', 'II', 'III', 'IV'][quad - 1] + '?', o: ['all six', 'sin and cosec', 'tan and cot', 'cos and sec'], a: quad - 1, x: 'All · Sin · Tan · Cos.' },
      { k: 'fields', q: 'First the pair from Pythagoras', f: main, keys: RQ, x: main.map((f) => f.l + ' = ' + (f.show || f.a)).join(', ') },
      { k: 'fields', q: 'Now the rest (reciprocals and ratios)', f: rest, keys: RQ, x: rest.map((f) => f.l + ' = ' + (f.show || f.a)).join(', '), act: async () => { W.uc.vals = true; } },
    ],
    w: wl,
  };
}
const F = (l, a, show) => ({ l, a, show });
const EX32 = [
  fiveQ('Q1', 'cos x = −1/2', 3, (4 * PI) / 3, [F('sin x', '-√3/2', '−√3/2'), F('sec x', -2, '−2')], [F('tan x', '√3', '√3'), F('cosec x', '-2/√3', '−2/√3'), F('cot x', '1/√3', '1/√3')], ['sin x = −√3/2, cosec x = −2/√3, sec x = −2, tan x = √3, cot x = 1/√3']),
  fiveQ('Q2', 'sin x = 3/5', 2, PI - Math.asin(0.6), [F('cos x', '-4/5', '−4/5'), F('cosec x', '5/3')], [F('sec x', '-5/4', '−5/4'), F('tan x', '-3/4', '−3/4'), F('cot x', '-4/3', '−4/3')], ['cos x = −4/5, cosec x = 5/3, sec x = −5/4, tan x = −3/4, cot x = −4/3']),
  fiveQ('Q3', 'cot x = 3/4', 3, PI + Math.atan(4 / 3), [F('tan x', '4/3'), F('cosec x', '-5/4', '−5/4')], [F('sin x', '-4/5', '−4/5'), F('cos x', '-3/5', '−3/5'), F('sec x', '-5/3', '−5/3')], ['tan x = 4/3, cosec x = −5/4 (1 + cot² = cosec², III ⇒ negative), sin x = −4/5, cos x = −3/5, sec x = −5/3']),
  fiveQ('Q4', 'sec x = 13/5', 4, 2 * PI - Math.acos(5 / 13), [F('cos x', '5/13'), F('tan x', '-12/5', '−12/5')], [F('sin x', '-12/13', '−12/13'), F('cosec x', '-13/12', '−13/12'), F('cot x', '-5/12', '−5/12')], ['cos x = 5/13, tan x = −12/5, sin x = −12/13, cosec x = −13/12, cot x = −5/12']),
  fiveQ('Q5', 'tan x = −5/12', 2, PI - Math.atan(5 / 12), [F('sec x', '-13/12', '−13/12'), F('cot x', '-12/5', '−12/5')], [F('cos x', '-12/13', '−12/13'), F('sin x', '5/13'), F('cosec x', '13/5')], ['cot x = −12/5, sec x = −13/12, cos x = −12/13, sin x = 5/13, cosec x = 13/5']),
  ...[['Q6', 'sin 765°', 765, '765° = 2 × 360° + 45°', ['1/√2', '−1/√2', '√3/2', '1/2'], 0], ['Q7', 'cosec(−1410°)', -1410, '−1410° + 4 × 360° = 30°', ['−2', '2', '2/√3', '1/2'], 1], ['Q8', 'tan(19π/3)', 1140, '19π/3 = 6π + π/3', ['1/√3', '√3', '−√3', '1'], 1], ['Q9', 'sin(−11π/3)', -660, '−11π/3 + 4π = π/3', ['−√3/2', '√3/2', '1/2', '−1/2'], 1], ['Q10', 'cot(−15π/4)', -675, '−15π/4 + 4π = π/4', ['−1', '1', '√3', '0'], 1]].map(([n, s, deg, red, o, a]) => ({ ex: 'Ex 3.2', n, q: 'Find the value of ' + s + '.', scene: 'circle', kim: n === 'Q6' ? 'Spin it! Every full turn changes nothing.' : null, parts: [anglePart('Drag P to ' + s.replace(/^\w+/, '').replace(/[()]/g, '').trim() + ' (wind the full turns!)', deg, { snap: 15 }), { k: 'mcq', q: red + '. So ' + s + ' = ?', o, a, x: s + ' = ' + o[a] + '.' }], w: [s + ': ' + red + ', so the value is ' + o[a] + '.'] })),
];

/* ===================== EXERCISE 3.3 ===================== */
const EX33 = [
  ...[
    ['Q1', 'sin²(π/6) + cos²(π/3) − tan²(π/4) = −1/2', [F('sin²(π/6)', '1/4'), F('cos²(π/3)', '1/4'), F('tan²(π/4)', 1)], -0.5, '1/4 + 1/4 − 1 = −1/2'],
    ['Q2', '2sin²(π/6) + cosec²(7π/6)cos²(π/3) = 3/2', [F('2sin²(π/6)', '1/2'), F('cosec²(7π/6)', 4), F('cos²(π/3)', '1/4')], 1.5, 'cosec(7π/6) = −2, so 1/2 + 4 × 1/4 = 3/2'],
    ['Q3', 'cot²(π/6) + cosec(5π/6) + 3tan²(π/6) = 6', [F('cot²(π/6)', 3), F('cosec(5π/6)', 2), F('3tan²(π/6)', 1)], 6, '3 + 2 + 1 = 6'],
    ['Q4', '2sin²(3π/4) + 2cos²(π/4) + 2sec²(π/3) = 10', [F('2sin²(3π/4)', 1), F('2cos²(π/4)', 1), F('2sec²(π/3)', 8)], 10, '1 + 1 + 8 = 10'],
  ].map(([n, s, f, tot, w]) => ({ ex: 'Ex 3.3', n, q: 'Prove that ' + s + '.', scene: 'circle', setup: (W) => { W.uc.astc = true; }, parts: [{ k: 'fields', q: 'Evaluate each term', f, keys: RQ, x: w }, { k: 'num', q: 'Total LHS = ?', a: tot, show: fracStr(tot), x: '= RHS ✓' }], w: ['LHS = ' + w + ' = RHS'] })),
  { ex: 'Ex 3.3', n: 'Q5', q: 'Find the value of (i) sin 75° (ii) tan 15°.', scene: 'circle', setup: (W) => { W.uc.th = D2R(75); }, parts: [{ k: 'mcq', q: '(i) sin 75° = sin(45° + 30°) = ?', o: ['(√6 + √2)/4', '(√6 − √2)/4', '(√3 + 1)/2', '√3/4'], a: 0, x: '(1/√2)(√3/2) + (1/√2)(1/2) = (√3 + 1)/(2√2) = (√6 + √2)/4 ≈ 0.966.' }, { k: 'mcq', q: '(ii) tan 15° = tan(45° − 30°) = ?', o: ['2 + √3', '2 − √3', '√3 − 1', '1/√3'], a: 1, x: '(1 − 1/√3)/(1 + 1/√3) = (√3 − 1)²/2 = 2 − √3 ≈ 0.268.', act: async () => spinTo(W, D2R(15)) }], w: ['sin 75° = (√3 + 1)/(2√2) = (√6 + √2)/4', 'tan 15° = (√3 − 1)/(√3 + 1) = 2 − √3'] },
  proofQ('Ex 3.3', 'Q6', 'Prove: cos(π/4 − x)cos(π/4 − y) − sin(π/4 − x)sin(π/4 − y) = sin(x + y)  (graph uses y = 0.7)', (x) => cos(PI / 4 - x) * cos(PI / 4 - 0.7) - sin(PI / 4 - x) * sin(PI / 4 - 0.7), (x) => sin(x + 0.7), { q: 'Which identity starts it?', o: ['cos A cos B − sin A sin B = cos(A + B)', 'sin A cos B − cos A sin B = sin(A − B)', 'cos A + cos B', 'tan(A + B)'], a: 0, x: 'With A = π/4 − x, B = π/4 − y.' }, ['LHS = cos[(π/4 − x) + (π/4 − y)]', '= cos[π/2 − (x + y)]', '= sin(x + y) = RHS']),
  proofQ('Ex 3.3', 'Q7', 'Prove: tan(π/4 + x)/tan(π/4 − x) = ((1 + tan x)/(1 − tan x))²', (x) => tan(PI / 4 + x) / tan(PI / 4 - x), (x) => ((1 + tan(x)) / (1 - tan(x))) ** 2, { q: 'tan(π/4 + x) = ?', o: ['(1 + tan x)/(1 − tan x)', '(1 − tan x)/(1 + tan x)', '1 + tan x', 'tan x − 1'], a: 0, x: 'tan π/4 = 1.' }, ['tan(π/4 + x) = (1 + tan x)/(1 − tan x)', 'tan(π/4 − x) = (1 − tan x)/(1 + tan x)', 'LHS = [(1 + tan x)/(1 − tan x)] ÷ [(1 − tan x)/(1 + tan x)] = ((1 + tan x)/(1 − tan x))²'], { x0: -0.7, x1: 0.7 }),
  proofQ('Ex 3.3', 'Q8', 'Prove: cos(π + x)cos(−x) / [sin(π − x)cos(π/2 + x)] = cot²x', (x) => (cos(PI + x) * cos(-x)) / (sin(PI - x) * cos(PI / 2 + x)), (x) => cot(x) ** 2, { q: 'cos(π/2 + x) = ?', o: ['−sin x', 'sin x', 'cos x', '−cos x'], a: 0, x: 'Quadrant II: cos negative.' }, ['cos(π + x) = −cos x, cos(−x) = cos x', 'sin(π − x) = sin x, cos(π/2 + x) = −sin x', 'LHS = (−cos x)(cos x) / [sin x (−sin x)] = cos²x / sin²x = cot²x'], { x0: 0.3, x1: 2.8, y0: -1, y1: 8 }),
  proofQ('Ex 3.3', 'Q9', 'Prove: cos(3π/2 + x) cos(2π + x) [cot(3π/2 − x) + cot(2π + x)] = 1', (x) => cos((3 * PI) / 2 + x) * cos(2 * PI + x) * (cot((3 * PI) / 2 - x) + cot(2 * PI + x)), () => 1, { q: 'cot(3π/2 − x) = ?', o: ['tan x', '−tan x', 'cot x', '−cot x'], a: 0, x: '3π/2 − x swaps cot → tan; quadrant III keeps it positive.' }, ['cos(3π/2 + x) = sin x, cos(2π + x) = cos x', 'cot(3π/2 − x) = tan x, cot(2π + x) = cot x', 'LHS = sin x cos x (tan x + cot x) = sin x cos x · (sin²x + cos²x)/(sin x cos x)', '= 1 = RHS'], { x0: 0.2, x1: 2.9, y0: -0.5, y1: 2.5 }),
  proofQ('Ex 3.3', 'Q10', 'Prove: sin(n + 1)x sin(n + 2)x + cos(n + 1)x cos(n + 2)x = cos x  (graph uses n = 2)', (x) => sin(3 * x) * sin(4 * x) + cos(3 * x) * cos(4 * x), (x) => cos(x), { q: 'cos A cos B + sin A sin B = ?', o: ['cos(A − B)', 'cos(A + B)', 'sin(A − B)', 'sin(A + B)'], a: 0, x: 'Identity 4.' }, ['LHS = cos(n + 2)x cos(n + 1)x + sin(n + 2)x sin(n + 1)x', '= cos[(n + 2)x − (n + 1)x]', '= cos x = RHS']),
  proofQ('Ex 3.3', 'Q11', 'Prove: cos(3π/4 + x) − cos(3π/4 − x) = −√2 sin x', (x) => cos((3 * PI) / 4 + x) - cos((3 * PI) / 4 - x), (x) => -Math.SQRT2 * sin(x), { q: 'cos A − cos B = ?', o: ['−2 sin ½(A + B) sin ½(A − B)', '2 cos ½(A + B) cos ½(A − B)', '2 sin ½(A + B) cos ½(A − B)', '−2 cos A cos B'], a: 0, x: 'Sum-to-product (ii).' }, ['LHS = −2 sin(3π/4) sin x', 'sin(3π/4) = 1/√2', '= −2 (1/√2) sin x = −√2 sin x = RHS']),
  proofQ('Ex 3.3', 'Q12', 'Prove: sin²6x − sin²4x = sin 2x sin 10x', (x) => sin(6 * x) ** 2 - sin(4 * x) ** 2, (x) => sin(2 * x) * sin(10 * x), { q: 'First move?', o: ['Factor: (sin 6x + sin 4x)(sin 6x − sin 4x)', 'Use sin² = 1 − cos²', 'Divide by cos²x', 'Use tan 2x'], a: 0, x: 'Difference of squares.' }, ['LHS = (sin 6x + sin 4x)(sin 6x − sin 4x)', '= (2 sin 5x cos x)(2 cos 5x sin x)', '= (2 sin 5x cos 5x)(2 sin x cos x)', '= sin 10x sin 2x = RHS'], { x0: -1, x1: 1 }),
  proofQ('Ex 3.3', 'Q13', 'Prove: cos²2x − cos²6x = sin 4x sin 8x', (x) => cos(2 * x) ** 2 - cos(6 * x) ** 2, (x) => sin(4 * x) * sin(8 * x), { q: 'cos 2x − cos 6x = ?', o: ['2 sin 4x sin 2x', '−2 sin 4x sin 2x', '2 cos 4x cos 2x', '2 sin 4x cos 2x'], a: 0, x: '−2 sin 4x sin(−2x) = 2 sin 4x sin 2x.' }, ['LHS = (cos 2x + cos 6x)(cos 2x − cos 6x)', '= (2 cos 4x cos 2x)(2 sin 4x sin 2x)', '= (2 sin 4x cos 4x)(2 sin 2x cos 2x)', '= sin 8x sin 4x = RHS'], { x0: -1, x1: 1 }),
  proofQ('Ex 3.3', 'Q14', 'Prove: sin 2x + 2 sin 4x + sin 6x = 4 cos²x sin 4x', (x) => sin(2 * x) + 2 * sin(4 * x) + sin(6 * x), (x) => 4 * cos(x) ** 2 * sin(4 * x), { q: 'sin 2x + sin 6x = ?', o: ['2 sin 4x cos 2x', '2 cos 4x sin 2x', '2 sin 4x sin 2x', 'sin 8x'], a: 0, x: 'Sum-to-product.' }, ['sin 2x + sin 6x = 2 sin 4x cos 2x', 'LHS = 2 sin 4x cos 2x + 2 sin 4x = 2 sin 4x (1 + cos 2x)', '= 2 sin 4x (2cos²x) = 4cos²x sin 4x = RHS']),
  proofQ('Ex 3.3', 'Q15', 'Prove: cot 4x (sin 5x + sin 3x) = cot x (sin 5x − sin 3x)', (x) => cot(4 * x) * (sin(5 * x) + sin(3 * x)), (x) => cot(x) * (sin(5 * x) - sin(3 * x)), { q: 'sin 5x + sin 3x = ?', o: ['2 sin 4x cos x', '2 cos 4x sin x', '2 sin 4x sin x', '2 cos 4x cos x'], a: 0, x: 'Sum-to-product.' }, ['LHS = (cos 4x / sin 4x)(2 sin 4x cos x) = 2 cos 4x cos x', 'RHS = (cos x / sin x)(2 cos 4x sin x) = 2 cos 4x cos x', 'LHS = RHS'], { x0: 0.1, x1: 1.4 }),
  proofQ('Ex 3.3', 'Q16', 'Prove: (cos 9x − cos 5x)/(sin 17x − sin 3x) = −sin 2x / cos 10x', (x) => (cos(9 * x) - cos(5 * x)) / (sin(17 * x) - sin(3 * x)), (x) => -sin(2 * x) / cos(10 * x), { q: 'cos 9x − cos 5x = ?', o: ['−2 sin 7x sin 2x', '2 sin 7x sin 2x', '2 cos 7x cos 2x', '−2 cos 7x sin 2x'], a: 0, x: '−2 sin ½(14x) sin ½(4x).' }, ['cos 9x − cos 5x = −2 sin 7x sin 2x', 'sin 17x − sin 3x = 2 cos 10x sin 7x', 'LHS = −2 sin 7x sin 2x / (2 cos 10x sin 7x) = −sin 2x / cos 10x'], { x0: 0.02, x1: 0.3, y0: -4, y1: 4 }),
  proofQ('Ex 3.3', 'Q17', 'Prove: (sin 5x + sin 3x)/(cos 5x + cos 3x) = tan 4x', (x) => (sin(5 * x) + sin(3 * x)) / (cos(5 * x) + cos(3 * x)), (x) => tan(4 * x), { q: 'cos 5x + cos 3x = ?', o: ['2 cos 4x cos x', '2 sin 4x cos x', '−2 sin 4x sin x', 'cos 8x'], a: 0, x: 'Sum-to-product (i).' }, ['sin 5x + sin 3x = 2 sin 4x cos x', 'cos 5x + cos 3x = 2 cos 4x cos x', 'LHS = sin 4x / cos 4x = tan 4x'], { x0: -0.35, x1: 0.35, y0: -5, y1: 5 }),
  proofQ('Ex 3.3', 'Q18', 'Prove: (sin x − sin y)/(cos x + cos y) = tan((x − y)/2)  (graph uses y = 0.5)', (x) => (sin(x) - sin(0.5)) / (cos(x) + cos(0.5)), (x) => tan((x - 0.5) / 2), { q: 'sin x − sin y = ?', o: ['2 cos ½(x + y) sin ½(x − y)', '2 sin ½(x + y) cos ½(x − y)', '−2 sin ½(x + y) sin ½(x − y)', 'sin(x − y)'], a: 0, x: 'Sum-to-product (iv).' }, ['sin x − sin y = 2 cos ½(x + y) sin ½(x − y)', 'cos x + cos y = 2 cos ½(x + y) cos ½(x − y)', 'LHS = sin ½(x − y)/cos ½(x − y) = tan ½(x − y)'], { x0: -2, x1: 2.5 }),
  proofQ('Ex 3.3', 'Q19', 'Prove: (sin x + sin 3x)/(cos x + cos 3x) = tan 2x', (x) => (sin(x) + sin(3 * x)) / (cos(x) + cos(3 * x)), (x) => tan(2 * x), { q: 'sin x + sin 3x = ?', o: ['2 sin 2x cos x', '2 cos 2x sin x', '2 sin 2x sin x', 'sin 4x'], a: 0, x: 'Sum-to-product.' }, ['sin x + sin 3x = 2 sin 2x cos x', 'cos x + cos 3x = 2 cos 2x cos x', 'LHS = tan 2x'], { x0: -0.7, x1: 0.7, y0: -5, y1: 5 }),
  proofQ('Ex 3.3', 'Q20', 'Prove: (sin x − sin 3x)/(sin²x − cos²x) = 2 sin x', (x) => (sin(x) - sin(3 * x)) / (sin(x) ** 2 - cos(x) ** 2), (x) => 2 * sin(x), { q: 'sin²x − cos²x = ?', o: ['−cos 2x', 'cos 2x', 'sin 2x', '1'], a: 0, x: 'cos 2x = cos²x − sin²x.' }, ['sin x − sin 3x = 2 cos 2x sin(−x) = −2 cos 2x sin x', 'sin²x − cos²x = −cos 2x', 'LHS = −2 cos 2x sin x / (−cos 2x) = 2 sin x'], { x0: -2.5, x1: 2.5, y0: -2.6, y1: 2.6 }),
  proofQ('Ex 3.3', 'Q21', 'Prove: (cos 4x + cos 3x + cos 2x)/(sin 4x + sin 3x + sin 2x) = cot 3x', (x) => (cos(4 * x) + cos(3 * x) + cos(2 * x)) / (sin(4 * x) + sin(3 * x) + sin(2 * x)), (x) => cot(3 * x), { q: 'Pair up cos 4x + cos 2x = ?', o: ['2 cos 3x cos x', '2 sin 3x cos x', '2 cos 3x sin x', 'cos 6x'], a: 0, x: 'Pair the outer terms.' }, ['cos 4x + cos 2x = 2 cos 3x cos x, sin 4x + sin 2x = 2 sin 3x cos x', 'Numerator = cos 3x (2cos x + 1), denominator = sin 3x (2cos x + 1)', 'LHS = cos 3x / sin 3x = cot 3x'], { x0: 0.05, x1: 1, y0: -5, y1: 5 }),
  proofQ('Ex 3.3', 'Q22', 'Prove: cot x cot 2x − cot 2x cot 3x − cot 3x cot x = 1', (x) => cot(x) * cot(2 * x) - cot(2 * x) * cot(3 * x) - cot(3 * x) * cot(x), () => 1, { q: 'Write 3x as…', o: ['2x + x', '4x − x', '6x/2', 'π − 3x'], a: 0, x: 'Then use cot(A + B).' }, ['cot 3x = cot(2x + x) = (cot 2x cot x − 1)/(cot x + cot 2x)', 'cot 3x (cot 2x + cot x) = cot 2x cot x − 1', 'cot x cot 2x − cot 2x cot 3x − cot 3x cot x = 1'], { x0: 0.1, x1: 1, y0: -1, y1: 3 }),
  proofQ('Ex 3.3', 'Q23', 'Prove: tan 4x = 4tan x(1 − tan²x)/(1 − 6tan²x + tan⁴x)', (x) => tan(4 * x), (x) => (4 * tan(x) * (1 - tan(x) ** 2)) / (1 - 6 * tan(x) ** 2 + tan(x) ** 4), { q: 'tan 4x = ?', o: ['2tan 2x/(1 − tan²2x)', '4tan x', '2tan x/(1 − tan²x)', 'tan²2x'], a: 0, x: 'Double angle of 2x.' }, ['tan 4x = 2tan 2x/(1 − tan²2x), with tan 2x = 2t/(1 − t²), t = tan x', '= [4t/(1 − t²)] / [1 − 4t²/(1 − t²)²]', '= 4t(1 − t²)/[(1 − t²)² − 4t²]', '= 4t(1 − t²)/(1 − 6t² + t⁴)'], { x0: -0.35, x1: 0.35, y0: -5, y1: 5 }),
  proofQ('Ex 3.3', 'Q24', 'Prove: cos 4x = 1 − 8 sin²x cos²x', (x) => cos(4 * x), (x) => 1 - 8 * sin(x) ** 2 * cos(x) ** 2, { q: 'cos 4x = 1 − 2 sin²(?)', o: ['2x', 'x', '4x', 'x/2'], a: 0, x: 'cos 2θ = 1 − 2sin²θ with θ = 2x.' }, ['cos 4x = 1 − 2 sin²2x', '= 1 − 2(2 sin x cos x)²', '= 1 − 8 sin²x cos²x']),
  proofQ('Ex 3.3', 'Q25', 'Prove: cos 6x = 32cos⁶x − 48cos⁴x + 18cos²x − 1', (x) => cos(6 * x), (x) => 32 * cos(x) ** 6 - 48 * cos(x) ** 4 + 18 * cos(x) ** 2 - 1, { q: 'cos 6x = cos 3(2x) = ?', o: ['4cos³2x − 3cos 2x', '3cos 2x − 4cos³2x', '2cos²3x − 1', '4cos³x − 3cos x'], a: 0, x: 'cos 3θ with θ = 2x.' }, ['cos 6x = 4cos³2x − 3cos 2x', '= 4(2cos²x − 1)³ − 3(2cos²x − 1)', '= 4(8cos⁶x − 12cos⁴x + 6cos²x − 1) − 6cos²x + 3', '= 32cos⁶x − 48cos⁴x + 18cos²x − 1']),
];

/* ===================== MISCELLANEOUS ===================== */
function halfQ(n, given, quad, th, ans, wl, hint) {
  return {
    ex: 'Misc', th, n, q: 'Find sin(x/2), cos(x/2) and tan(x/2): ' + given + ', x in quadrant ' + ['I', 'II', 'III', 'IV'][quad - 1] + '.', scene: 'circle', setup: (W) => { W.uc.th = th; W.uc.shadeQ = quad; },
    parts: [
      { k: 'fields', q: 'First cos x', f: [ans[0]], keys: RQ, x: hint },
      { k: 'mcq', q: 'x/2 lies in quadrant…', o: ['I', 'II', 'III', 'IV'], a: QUAD(th / 2) - 1, x: 'Halve the range of x.', act: async () => { W.uc.shadeQ = QUAD(th / 2); await spinTo(W, th / 2); } },
      { k: 'fields', q: 'Use 2sin²(x/2) = 1 − cos x, 2cos²(x/2) = 1 + cos x', f: ans.slice(1), keys: RQ, x: ans.slice(1).map((f) => f.l + ' = ' + (f.show || f.a)).join(', ') },
    ],
    w: wl,
  };
}
const EX3M = [
  proofQ('Misc', 'Q1', 'Prove: 2cos(π/13)cos(9π/13) + cos(3π/13) + cos(5π/13) = 0', (x) => 2 * cos(PI / 13) * cos((9 * PI) / 13) + cos((3 * PI) / 13) + cos((5 * PI) / 13) + 0 * x, () => 0, { q: '2 cos A cos B = ?', o: ['cos(A + B) + cos(A − B)', 'sin(A + B) + sin(A − B)', 'cos(A + B) − cos(A − B)', 'cos A + cos B'], a: 0, x: 'Product-to-sum.' }, ['2cos(π/13)cos(9π/13) = cos(10π/13) + cos(8π/13)', 'cos(10π/13) = cos(π − 3π/13) = −cos(3π/13)', 'cos(8π/13) = cos(π − 5π/13) = −cos(5π/13)', 'LHS = −cos(3π/13) − cos(5π/13) + cos(3π/13) + cos(5π/13) = 0'], { y0: -1, y1: 1 }),
  proofQ('Misc', 'Q2', 'Prove: (sin 3x + sin x) sin x + (cos 3x − cos x) cos x = 0', (x) => (sin(3 * x) + sin(x)) * sin(x) + (cos(3 * x) - cos(x)) * cos(x), () => 0, { q: 'cos 3x − cos x = ?', o: ['−2 sin 2x sin x', '2 sin 2x sin x', '2 cos 2x cos x', '−2 cos 2x sin x'], a: 0, x: 'Sum-to-product (ii).' }, ['sin 3x + sin x = 2 sin 2x cos x', 'cos 3x − cos x = −2 sin 2x sin x', 'LHS = 2 sin 2x cos x sin x − 2 sin 2x sin x cos x = 0'], { y0: -1, y1: 1 }),
  proofQ('Misc', 'Q3', 'Prove: (cos x + cos y)² + (sin x − sin y)² = 4cos²((x + y)/2)  (graph uses y = 0.8)', (x) => (cos(x) + cos(0.8)) ** 2 + (sin(x) - sin(0.8)) ** 2, (x) => 4 * cos((x + 0.8) / 2) ** 2, { q: 'After expanding, the cross terms give 2(cos x cos y − sin x sin y) = ?', o: ['2cos(x + y)', '2cos(x − y)', '2sin(x + y)', '0'], a: 0, x: 'cos(x + y) formula.' }, ['LHS = cos²x + cos²y + 2cos x cos y + sin²x + sin²y − 2 sin x sin y', '= 2 + 2cos(x + y)', '= 2[1 + cos(x + y)] = 4cos²((x + y)/2)']),
  proofQ('Misc', 'Q4', 'Prove: (cos x − cos y)² + (sin x − sin y)² = 4sin²((x − y)/2)  (graph uses y = 0.8)', (x) => (cos(x) - cos(0.8)) ** 2 + (sin(x) - sin(0.8)) ** 2, (x) => 4 * sin((x - 0.8) / 2) ** 2, { q: 'The cross terms −2(cos x cos y + sin x sin y) = ?', o: ['−2cos(x − y)', '−2cos(x + y)', '2cos(x − y)', '0'], a: 0, x: 'cos(x − y) formula.' }, ['LHS = 2 − 2(cos x cos y + sin x sin y)', '= 2 − 2cos(x − y)', '= 2[1 − cos(x − y)] = 4sin²((x − y)/2)']),
  proofQ('Misc', 'Q5', 'Prove: sin x + sin 3x + sin 5x + sin 7x = 4 cos x cos 2x sin 4x', (x) => sin(x) + sin(3 * x) + sin(5 * x) + sin(7 * x), (x) => 4 * cos(x) * cos(2 * x) * sin(4 * x), { q: 'Best grouping?', o: ['(sin x + sin 7x) + (sin 3x + sin 5x)', '(sin x + sin 3x) + (sin 5x + sin 7x)', 'sin x + (sin 3x + sin 5x + sin 7x)', 'no grouping'], a: 0, x: 'Both pairs give sin 4x.' }, ['sin x + sin 7x = 2 sin 4x cos 3x, sin 3x + sin 5x = 2 sin 4x cos x', 'LHS = 2 sin 4x (cos 3x + cos x)', '= 2 sin 4x (2 cos 2x cos x) = 4 cos x cos 2x sin 4x']),
  proofQ('Misc', 'Q6', 'Prove: [(sin 7x + sin 5x) + (sin 9x + sin 3x)] / [(cos 7x + cos 5x) + (cos 9x + cos 3x)] = tan 6x', (x) => (sin(7 * x) + sin(5 * x) + sin(9 * x) + sin(3 * x)) / (cos(7 * x) + cos(5 * x) + cos(9 * x) + cos(3 * x)), (x) => tan(6 * x), { q: 'sin 7x + sin 5x = ?', o: ['2 sin 6x cos x', '2 cos 6x sin x', '2 sin 6x sin x', 'sin 12x'], a: 0, x: 'Sum-to-product.' }, ['Numerator = 2 sin 6x cos x + 2 sin 6x cos 3x = 2 sin 6x (cos x + cos 3x)', 'Denominator = 2 cos 6x cos x + 2 cos 6x cos 3x = 2 cos 6x (cos x + cos 3x)', 'LHS = sin 6x / cos 6x = tan 6x'], { x0: -0.25, x1: 0.25, y0: -5, y1: 5 }),
  proofQ('Misc', 'Q7', 'Prove: sin 3x + sin 2x − sin x = 4 sin x cos(x/2) cos(3x/2)', (x) => sin(3 * x) + sin(2 * x) - sin(x), (x) => 4 * sin(x) * cos(x / 2) * cos((3 * x) / 2), { q: 'sin 3x − sin x = ?', o: ['2 cos 2x sin x', '2 sin 2x cos x', '−2 sin 2x sin x', 'sin 2x'], a: 0, x: 'Sum-to-product (iv).' }, ['sin 3x − sin x = 2 cos 2x sin x, and sin 2x = 2 sin x cos x', 'LHS = 2 sin x (cos 2x + cos x)', '= 2 sin x · 2 cos(3x/2) cos(x/2) = 4 sin x cos(x/2) cos(3x/2)']),
  halfQ('Q8', 'tan x = −4/3', 2, PI - Math.atan(4 / 3), [F('cos x', '-3/5', '−3/5'), F('sin(x/2)', '2/√5'), F('cos(x/2)', '1/√5'), F('tan(x/2)', 2)], ['sec²x = 1 + 16/9 = 25/9, II ⇒ cos x = −3/5', 'x/2 in I: sin(x/2) = √((1 + 3/5)/2) = 2/√5, cos(x/2) = √((1 − 3/5)/2) = 1/√5, tan(x/2) = 2'], 'sec²x = 25/9 and cos is negative in II.'),
  halfQ('Q9', 'cos x = −1/3', 3, PI + Math.acos(1 / 3), [F('cos x', '-1/3', '−1/3'), F('sin(x/2)', '√6/3'), F('cos(x/2)', '-√3/3', '−√3/3'), F('tan(x/2)', '-√2', '−√2')], ['x/2 in II: sin(x/2) = √((1 + 1/3)/2) = √6/3, cos(x/2) = −√((1 − 1/3)/2) = −√3/3, tan(x/2) = −√2'], 'Given directly.'),
  halfQ('Q10', 'sin x = 1/4', 2, PI - Math.asin(0.25), [F('cos x', '-√15/4', '−√15/4'), F('sin(x/2)', '√(8+2√15)/4'), F('cos(x/2)', '√(8−2√15)/4'), F('tan(x/2)', '4+√15')], ['cos x = −√15/4. x/2 in I: sin(x/2) = √(8 + 2√15)/4, cos(x/2) = √(8 − 2√15)/4, tan(x/2) = 4 + √15'], 'cos²x = 1 − 1/16 = 15/16, negative in II.'),
];
// typed answers for Q10 need nested roots: give them as numbers so any equivalent form passes
EX3M[9].parts[2].f.forEach((f) => { f.a = { 'sin(x/2)': Math.sqrt((1 + Math.sqrt(15) / 4) / 2), 'cos(x/2)': Math.sqrt((1 - Math.sqrt(15) / 4) / 2), 'tan(x/2)': 4 + Math.sqrt(15) }[f.l]; f.tol = 0.002; });
EX3M[9].parts[2].f.forEach((f, i) => { f.show = ['√(8 + 2√15)/4 ≈ 0.992', '√(8 − 2√15)/4 ≈ 0.126', '4 + √15 ≈ 7.873'][i]; });
EX3M[9].parts[2].q = 'Type decimals (3 places) or exact forms';

const BOSS3 = [
  ['150° in radians', ['5π/6', '3π/4', '2π/3', '5π/4'], 0],
  ['l = rθ: r = 4, θ = π/2, l = ?', ['2π', 'π', '4π', '8'], 0],
  ['sin 120° = ?', ['−√3/2', '√3/2', '1/2', '−1/2'], 1],
  ['tan is negative in quadrants…', ['I & III', 'II & IV', 'II & III', 'I & IV'], 1],
  ['cos(−x) = ?', ['−cos x', 'cos x', 'sin x', '−sin x'], 1],
  ['Period of tan x', ['π', '2π', 'π/2', '4π'], 0],
  ['cos 2x = 1 − ?', ['2sin²x', '2cos²x', 'sin²x', 'sin 2x'], 0],
  ['sin 3x = ?', ['3sin x − 4sin³x', '4sin³x − 3sin x', '3sin x', 'sin³x'], 0],
  ['cos 75° = ?', ['(√6 − √2)/4', '(√6 + √2)/4', '1/2', '√3/2'], 0],
  ['sin x + sin y = 2 sin ½(x + y) · ?', ['cos ½(x − y)', 'sin ½(x − y)', 'cos ½(x + y)', '1'], 0],
];
LESSONS.splice(1, 0, exLesson({ id: 'ex31', title: 'Exercise 3.1', blurb: 'Degree ↔ radian, wheels, arcs, pendulums.', qs: EX31 }));
LESSONS.splice(4, 0, exLesson({ id: 'ex32', title: 'Exercise 3.2', blurb: 'Other five ratios by quadrant, and big angles by spinning.', face: 'kimmy-curious', qs: EX32 }));
LESSONS.splice(7, 0, exLesson({ id: 'ex33', title: 'Exercise 3.3', blurb: '25 identities: graph check, key step, then build the proof.', face: 'kimmy-excited', qs: EX33 }));
LESSONS.push(exLesson({ id: 'misc', title: 'Miscellaneous', blurb: '7 proofs and 3 half-angle problems.', face: 'jess-thinking', qs: EX3M }));
LESSONS.push(lesson({
  id: 'boss', title: 'Boss Battle', blurb: 'Ten fast questions. Speed points. Beat Kimmy.', face: 'jess-excited',
  steps: [async function () { enterScene('board', (W) => { W.tag = 'BOSS'; W.sub = 'Chapter 3'; }); await slam('BOSS BATTLE', '10 questions · speed counts'); await K('play', 'Trig boss! I got 7,200.'); await cont('Fight'); }, ...BOSS3.map(([q, o, a], i) => async function () { enterScene('board', (W) => { W.tag = 'Q' + (i + 1); W.sub = 'Boss Battle'; }); await quiz(q, o, a, plain(o[a]) + '.', null, 15); await cont(); }), async function () { enterScene('board', (W) => { W.tag = 'K.O.!'; W.sub = 'Chapter 3'; }); await summary(['Chapter 3 complete!', 'Radians · Unit circle · Identities', { t: 'sin²x + cos²x = 1', eq: true }]); }],
}));
LESSONS.forEach((l) => { if (l.kind === 'ex') l.short = l.id === 'misc' ? 'M' : l.title.replace('Exercise ', ''); });
