/* =========================================================
   CLASS 12 · CHAPTER 1 · RELATIONS AND FUNCTIONS — every exercise question as a sim
   Finite relations are checked with relProps; property badges appear only after the learner answers.
   ========================================================= */
const ONTO = ['One-one', 'Onto'];
const propPick = (q, ans, x) => ({ k: 'pick', q: q || 'Tick every property it has (none is allowed)', pool: PROPS, a: ans, brace: false, x });
/* a finite relation on a grid: answer first, badges after */
const relQ = (ex, n, q, A, pairs, x, o = {}) => ({ ex, n, q, scene: 'grid', setup: (W) => { relLoad(W, A, pairs, { showLab: A.length <= 6 }); W.props = false; }, kim: o.kim, parts: [propPick(null, PROPS.filter((_, i) => [relProps(A, new Set(pairs.map(([a, b]) => pk(a, b))))][0][['R', 'S', 'T'][i]]), x), ...(o.more || [])].map((p, i) => (i === 0 ? Object.assign(p, { act: async () => { W.props = true; SFX.pop(); } }) : p)), w: [o.w || 'R is ' + propWords(relProps(A, new Set(pairs.map(([a, b]) => pk(a, b)))))] });
const abstractQ = (ex, n, q, ans, x, o = {}) => ({ ex, n, q, scene: 'board', kim: o.kim, parts: [propPick(null, ans, x), ...(o.more || [])], w: [o.w || (ans.length === 3 ? 'An equivalence relation' : ans.length ? ans.join(', ') + ' only' : 'Neither reflexive nor symmetric nor transitive')] });
const range = (a, b) => Array.from({ length: b - a + 1 }, (_, i) => a + i);
/* a function on a horizontal-line-test stage */
const fnQ = (ex, n, q, F, view, dom, cod, ans, x, o = {}) => ({ ex, n, q, scene: 'hlt', setup: (W) => hltSetup(W, F, view, dom, cod, Object.assign({ c: o.c != null ? o.c : 1, snap: dom === 'N' || dom === 'Z' ? 1 : 0.1 }, o.s || {})), kim: o.kim, parts: [...(o.pre || []), { k: 'pick', q: o.pq || 'Slide the red line, then tick what f is (none is allowed)', pool: ONTO, a: ans, brace: false, x }, ...(o.more || [])], w: [o.w || (ans.length === 2 ? 'Bijective (one-one and onto)' : ans.length ? ans[0] + ' only' : 'Neither one-one nor onto')] });

/* ===================== EXERCISE 1.1 ===================== */
const EX11 = [
  relQ('Ex 1.1', 'Q1 (i)', 'A = {1, 2, …, 14}, R = {(x, y): 3x − y = 0}', range(1, 14), [[1, 3], [2, 6], [3, 9], [4, 12]], '(1, 1) ∉ R; (1, 3) but not (3, 1); (1, 3), (3, 9) but not (1, 9).'),
  relQ('Ex 1.1', 'Q1 (ii)', 'N, R = {(x, y): y = x + 5 and x < 4}', range(1, 9), [[1, 6], [2, 7], [3, 8]], 'R = {(1, 6), (2, 7), (3, 8)}: no chain (a, b), (b, c) exists, so it is transitive (vacuously).', { kim: 'Transitivity needs a chain to break it…', w: 'Neither reflexive nor symmetric, but transitive' }),
  relQ('Ex 1.1', 'Q1 (iii)', 'A = {1, …, 6}, R = {(x, y): y is divisible by x}', range(1, 6), range(1, 6).flatMap((x) => range(1, 6).filter((y) => y % x === 0).map((y) => [x, y])), 'x | x; x | y and y | z ⇒ x | z; but 1 | 2 while 2 ∤ 1.'),
  abstractQ('Ex 1.1', 'Q1 (iv)', 'Z, R = {(x, y): x − y is an integer}', PROPS, 'Differences of integers are always integers.'),
  abstractQ('Ex 1.1', 'Q1 (v)(a)', 'People in a town: x and y work at the same place', PROPS, '“Same place” behaves like equality.'),
  abstractQ('Ex 1.1', 'Q1 (v)(b)', 'x and y live in the same locality', PROPS, 'Same reasoning as (a).'),
  abstractQ('Ex 1.1', 'Q1 (v)(c)', 'x is exactly 7 cm taller than y', [], 'Not reflexive or symmetric; x 7 cm taller than y, y 7 cm taller than z makes x 14 cm taller than z.'),
  abstractQ('Ex 1.1', 'Q1 (v)(d)', 'x is wife of y', ['Transitive'], 'If x is wife of y, y is a husband and cannot be anyone’s wife, so no chain exists: transitive (vacuously).', { w: 'Neither reflexive nor symmetric, but transitive' }),
  abstractQ('Ex 1.1', 'Q1 (v)(e)', 'x is father of y', [], 'Father of father is a grandfather.'),
  abstractQ('Ex 1.1', 'Q2', 'R in ℝ: R = {(a, b): a ≤ b²}. Show it is neither reflexive nor symmetric nor transitive.', [], '(1/2, 1/2) ∉ R; (1, 4) ∈ R but (4, 1) ∉ R; (3, 2), (2, 1.5) ∈ R but (3, 1.5) ∉ R.', { more: [{ k: 'num', q: 'Check: is 1/2 ≤ (1/2)²? Type (1/2)²', a: 0.25, show: '1/4', x: '1/2 > 1/4, so (1/2, 1/2) ∉ R.' }] }),
  relQ('Ex 1.1', 'Q3', 'A = {1, …, 6}, R = {(a, b): b = a + 1}', range(1, 6), range(1, 5).map((a) => [a, a + 1]), '(1, 2), (2, 3) ∈ R but (1, 3) ∉ R.'),
  abstractQ('Ex 1.1', 'Q4', 'R in ℝ: R = {(a, b): a ≤ b}', ['Reflexive', 'Transitive'], 'a ≤ a; a ≤ b ≤ c ⇒ a ≤ c; but 1 ≤ 2 and 2 ≰ 1.'),
  abstractQ('Ex 1.1', 'Q5', 'R in ℝ: R = {(a, b): a ≤ b³}', [], '(1/2, 1/2) ∉ R; (1, 2) ∈ R but (2, 1) ∉ R; (3, 3/2), (3/2, 6/5) ∈ R but (3, 6/5) ∉ R.'),
  relQ('Ex 1.1', 'Q6', 'A = {1, 2, 3}, R = {(1, 2), (2, 1)}', A3, [[1, 2], [2, 1]], 'Symmetric, but (1, 1) ∉ R and (1, 2), (2, 1) would need (1, 1).'),
  abstractQ('Ex 1.1', 'Q7', 'Books in a library: x and y have the same number of pages', PROPS, '“Same number” is an equivalence.'),
  { ex: 'Ex 1.1', n: 'Q8', q: 'A = {1, …, 5}, R = {(a, b): |a − b| is even}. Show R is an equivalence relation and find its classes.', scene: 'classes', parts: [propPick(null, PROPS, '|a − a| = 0; |a − b| = |b − a|; a − c = (a − b) + (b − c).'), { k: 'pick', q: 'Elements related to 1', pool: ['1', '2', '3', '4', '5'], a: ['1', '3', '5'], act: async () => sortClasses(W, [1, 2, 3, 4, 5], ['{1, 3, 5}', '{2, 4}'], (x) => (x % 2 ? 0 : 1)) }], w: ['Classes {1, 3, 5} and {2, 4}; no cross relations'] },
  { ex: 'Ex 1.1', n: 'Q9', q: 'A = {x ∈ Z : 0 ≤ x ≤ 12}. (i) |a − b| a multiple of 4 (ii) a = b. Show both are equivalences; find the elements related to 1.', scene: 'classes', parts: [{ k: 'pick', q: '(i) elements related to 1', pool: range(0, 12).map(String), a: ['1', '5', '9'], act: async () => sortClasses(W, range(0, 12), ['[0]', '[1]', '[2]', '[3]'], (x) => x % 4) }, { k: 'pick', q: '(ii) elements related to 1', pool: range(0, 12).map(String), a: ['1'] }], w: ['(i) {1, 5, 9}  (ii) {1}'] },
  { ex: 'Ex 1.1', n: 'Q10', q: 'Give examples of relations on {1, 2, 3} that are (i) symmetric only (ii) transitive only (iii) reflexive and symmetric, not transitive (iv) reflexive and transitive, not symmetric (v) symmetric and transitive, not reflexive.', scene: 'grid', kim: 'Build each one and let the badges confirm it.',
    parts: [buildRelPart('(i) Symmetric only', A3, [false, true, false], { example: [[1, 2], [2, 1]] }), buildRelPart('(ii) Transitive only', A3, [false, false, true], { example: [[1, 2]] }), buildRelPart('(iii) Reflexive and symmetric, not transitive', A3, [true, true, false], { example: [[1, 1], [2, 2], [3, 3], [1, 2], [2, 1], [2, 3], [3, 2]] }), buildRelPart('(iv) Reflexive and transitive, not symmetric', A3, [true, false, true], { example: [[1, 1], [2, 2], [3, 3], [1, 2]] }), buildRelPart('(v) Symmetric and transitive, not reflexive', A3, [false, true, true], { example: [[1, 1]] })], w: ['Many answers; e.g. {(1, 2), (2, 1)}, {(1, 2)}, …'] },
  abstractQ('Ex 1.1', 'Q11', 'Points in a plane: P R Q ⇔ OP = OQ (same distance from the origin).', PROPS, 'Equal distances behave like equality.', { more: [{ k: 'mcq', q: 'Points related to P ≠ O form…', o: ['the circle through P centred at O', 'the line OP', 'the point P only', 'a square'], a: 0 }] }),
  { ex: 'Ex 1.1', n: 'Q12', q: 'Triangles, T₁ R T₂ ⇔ similar. T₁: 3, 4, 5; T₂: 5, 12, 13; T₃: 6, 8, 10. Which are related?', scene: 'board', parts: [propPick(null, PROPS), { k: 'pick', q: 'Related triangles', pool: ['T₁', 'T₂', 'T₃'], a: ['T₁', 'T₃'], x: '6 : 8 : 10 = 3 : 4 : 5.' }], w: ['T₁ and T₃ are related'] },
  abstractQ('Ex 1.1', 'Q13', 'Polygons, P₁ R P₂ ⇔ same number of sides.', PROPS, '', { more: [{ k: 'mcq', q: 'Polygons related to the 3-4-5 right triangle', o: ['all triangles', 'all right triangles', 'only that triangle', 'all polygons'], a: 0 }] }),
  abstractQ('Ex 1.1', 'Q14', 'Lines in the plane, L₁ R L₂ ⇔ L₁ ∥ L₂ (a line counts as parallel to itself).', PROPS, '', { more: [{ k: 'mcq', q: 'Lines related to y = 2x + 4', o: ['y = 2x + c, c ∈ ℝ', 'y = −x/2 + c', 'only y = 2x + 4', 'all lines through (0, 4)'], a: 0 }] }),
  relQ('Ex 1.1', 'Q15', 'On {1, 2, 3, 4}: R = {(1, 2), (2, 2), (1, 1), (4, 4), (1, 3), (3, 3), (3, 2)}. Choose: (A) R, S not T (B) R, T not S (C) S, T not R (D) equivalence', [1, 2, 3, 4], [[1, 2], [2, 2], [1, 1], [4, 4], [1, 3], [3, 3], [3, 2]], '(1, 3), (3, 2) ⇒ (1, 2) is present; but (1, 2) without (2, 1).', { more: [{ k: 'mcq', q: 'Answer', o: ['(B)', '(A)', '(C)', '(D)'], a: 0 }], w: '(B): reflexive and transitive but not symmetric' }),
  { ex: 'Ex 1.1', n: 'Q16', q: 'R in N: R = {(a, b): a = b − 2, b > 6}. Choose: (A) (2, 4) (B) (3, 8) (C) (6, 8) (D) (8, 7)', scene: 'board', parts: [{ k: 'mcq', q: 'Which pair is in R?', o: ['(6, 8)', '(2, 4)', '(3, 8)', '(8, 7)'], a: 0, x: '8 > 6 and 6 = 8 − 2.' }], w: ['(C) (6, 8) ∈ R'] },
];

/* ===================== EXERCISE 1.2 ===================== */
const EX12 = [
  fnQ('Ex 1.2', 'Q1', 'f : ℝ* → ℝ*, f(x) = 1/x. One-one and onto? What if the domain is N (co-domain still ℝ*)?', (x) => 1 / x, [-4, 4, -4, 4], 'R*', 'R*', ONTO, 'Every y ≠ 0 has exactly one pre-image 1/y.', { more: [{ k: 'mcq', q: 'With domain N instead', o: ['one-one but not onto', 'onto but not one-one', 'still bijective', 'neither'], a: 0, x: '1/m = 1/n ⇒ m = n, so still one-one; but 2 ∈ ℝ* is not 1/n for any natural n, so not onto.', act: async () => { W.dom = 'N'; SFX.swish(); } }], w: 'ℝ*: bijective.  N: one-one, not onto' }),
  fnQ('Ex 1.2', 'Q2 (i)', 'f : N → N, f(x) = x²', (x) => x * x, [-0.5, 5, -1, 20], 'N', 'N', ['One-one'], 'Distinct naturals have distinct squares; 2 is never a square.', { c: 2 }),
  fnQ('Ex 1.2', 'Q2 (ii)', 'f : Z → Z, f(x) = x²', (x) => x * x, [-4, 4, -2, 12], 'Z', 'Z', [], 'f(−1) = f(1); −1 is never a square.', { c: 1 }),
  fnQ('Ex 1.2', 'Q2 (iii)', 'f : ℝ → ℝ, f(x) = x²', (x) => x * x, [-3, 3, -2, 6], 'R', 'R', [], 'f(−1) = f(1); −2 has no pre-image.', { c: 1 }),
  fnQ('Ex 1.2', 'Q2 (iv)', 'f : N → N, f(x) = x³', (x) => x ** 3, [-0.5, 4, -2, 30], 'N', 'N', ['One-one'], '2 is not a cube.', { c: 2 }),
  fnQ('Ex 1.2', 'Q2 (v)', 'f : Z → Z, f(x) = x³', (x) => x ** 3, [-3, 3, -10, 10], 'Z', 'Z', ['One-one'], 'x³ is increasing; 2 is not a cube of an integer.', { c: 2 }),
  fnQ('Ex 1.2', 'Q3', 'f : ℝ → ℝ, f(x) = [x] (greatest integer)', (x) => Math.floor(x), [-3, 3, -3, 3], 'R', 'R', [], '[1.2] = [1.5] = 1; 0.7 is never an output.', { c: 1 }),
  fnQ('Ex 1.2', 'Q4', 'f : ℝ → ℝ, f(x) = |x|', (x) => Math.abs(x), [-3, 3, -2, 3], 'R', 'R', [], '|−1| = |1|; −1 is never an output.', { c: 1 }),
  fnQ('Ex 1.2', 'Q5', 'f : ℝ → ℝ, signum: 1 (x > 0), 0 (x = 0), −1 (x < 0)', (x) => Math.sign(x), [-3, 3, -2, 2], 'R', 'R', [], 'f(1) = f(2) = 1; only −1, 0, 1 are outputs.', { c: 1, s: { open: [[0, 1], [0, -1]] } }),
  { ex: 'Ex 1.2', n: 'Q6', q: 'A = {1, 2, 3}, B = {4, 5, 6, 7}, f = {(1, 4), (2, 5), (3, 6)}. Show f is one-one.', scene: 'arrows', setup: (W) => arrowsLoad(W, [1, 2, 3], [4, 5, 6, 7], { pairs: [[1, 4], [2, 5], [3, 6]] }), parts: [{ k: 'pick', q: 'f is…', pool: ONTO, a: ['One-one'], brace: false, x: 'Distinct inputs, distinct outputs; 7 is not hit.' }], w: ['One-one (not onto: 7 has no pre-image)'] },
  fnQ('Ex 1.2', 'Q7 (i)', 'f : ℝ → ℝ, f(x) = 3 − 4x', (x) => 3 - 4 * x, [-2, 3, -6, 8], 'R', 'R', ONTO, 'x = (3 − y)/4 is the unique pre-image.'),
  fnQ('Ex 1.2', 'Q7 (ii)', 'f : ℝ → ℝ, f(x) = 1 + x²', (x) => 1 + x * x, [-3, 3, -1, 6], 'R', 'R', [], 'f(−1) = f(1); 0 is never reached.', { c: 2 }),
  { ex: 'Ex 1.2', n: 'Q8', q: 'f : A × B → B × A, f(a, b) = (b, a). Show f is bijective.', scene: 'board', parts: [{ k: 'order', q: 'Order the proof', s: ['f(a₁, b₁) = f(a₂, b₂) ⇒ (b₁, a₁) = (b₂, a₂)', '⇒ a₁ = a₂ and b₁ = b₂: one-one', 'Any (b, a) ∈ B × A is f(a, b): onto', 'So f is bijective'] }], w: ['Swapping is its own undo: bijective'] },
  fnQ('Ex 1.2', 'Q9', 'f : N → N, f(n) = (n + 1)/2 if n is odd, n/2 if n is even. Bijective?', (n) => (n % 2 ? (n + 1) / 2 : n / 2), [-0.5, 10, -1, 6], 'N', 'N', ['Onto'], 'f(1) = f(2) = 1, but every n is hit (by 2n).', { c: 1, w: 'Onto but not one-one: not bijective' }),
  fnQ('Ex 1.2', 'Q10', 'A = ℝ − {3}, B = ℝ − {1}, f(x) = (x − 2)/(x − 3). One-one and onto?', (x) => (Math.abs(x - 3) < 1e-9 ? NaN : (x - 2) / (x - 3)), [-3, 9, -5, 6], 'R', 'B', ONTO, 'x = (3y − 2)/(y − 1) works for every y ≠ 1.', { c: 2, s: { codTest: (c) => Math.abs(c - 1) > 1e-9 } }),
  fnQ('Ex 1.2', 'Q11', 'f : ℝ → ℝ, f(x) = x⁴. (A) one-one onto (B) many-one onto (C) one-one not onto (D) neither', (x) => x ** 4, [-2, 2, -2, 6], 'R', 'R', [], 'f(−1) = f(1); negatives are missed.', { c: 1, more: [{ k: 'mcq', q: 'Answer', o: ['(D)', '(A)', '(B)', '(C)'], a: 0 }], w: '(D)' }),
  fnQ('Ex 1.2', 'Q12', 'f : ℝ → ℝ, f(x) = 3x. (A) one-one onto (B) many-one onto (C) one-one not onto (D) neither', (x) => 3 * x, [-3, 3, -6, 6], 'R', 'R', ONTO, 'x = y/3.', { more: [{ k: 'mcq', q: 'Answer', o: ['(A)', '(B)', '(C)', '(D)'], a: 0 }], w: '(A)' }),
];

/* ===================== MISCELLANEOUS ===================== */
const EX1M = [
  fnQ('Misc', 'Q1', 'f : ℝ → {x : −1 < x < 1}, f(x) = x/(1 + |x|). Show f is one-one and onto.', (x) => x / (1 + Math.abs(x)), [-8, 8, -1.6, 1.6], 'R', 'B', ONTO, 'For −1 < y < 1: x = y/(1 − |y|).', { c: 0.5, s: { codTest: (c) => c > -1 && c < 1 } }),
  fnQ('Misc', 'Q2', 'f : ℝ → ℝ, f(x) = x³. Show f is injective.', (x) => x ** 3, [-2, 2, -6, 6], 'R', 'R', ONTO, 'x₁³ = x₂³ ⇒ x₁ = x₂ (it is onto too).', { pq: 'Slide the line: tick what f is', w: 'Injective (in fact bijective)' }),
  { ex: 'Misc', n: 'Q3', q: 'P(X) with A R B ⇔ A ⊂ B. Is R an equivalence relation?', scene: 'board', parts: [propPick(null, ['Reflexive', 'Transitive'], '{1} ⊂ {1, 2} but {1, 2} ⊄ {1}: not symmetric.'), { k: 'tf', q: 'Equivalence relation?', o: ['Yes', 'No'], a: 1 }], w: ['Not an equivalence relation (not symmetric)'] },
  { ex: 'Misc', n: 'Q4', q: 'Number of onto functions from {1, 2, …, n} to itself.', scene: 'board', parts: [{ k: 'mcq', q: 'On a finite set onto ⇔ one-one, so the count is', o: ['n!', 'nⁿ', '2ⁿ', 'n'], a: 0 }, { k: 'num', q: 'For n = 4: ?', a: 24 }], w: ['n!'] },
  { ex: 'Misc', n: 'Q5', q: 'A = {−1, 0, 1, 2}, f(x) = x² − x, g(x) = 2|x − 1/2| − 1. Are f and g equal?', scene: 'board', parts: [{ k: 'fields', q: 'f(x) for x = −1, 0, 1, 2', f: [-1, 0, 1, 2].map((x) => ({ l: 'f(' + String(x).replace('-', '−') + ')', a: x * x - x })) }, { k: 'fields', q: 'g(x) for x = −1, 0, 1, 2', f: [-1, 0, 1, 2].map((x) => ({ l: 'g(' + String(x).replace('-', '−') + ')', a: 2 * Math.abs(x - 0.5) - 1 })) }, { k: 'tf', q: 'f = g?', o: ['Yes', 'No'], a: 0, x: 'Same domain, same values everywhere.' }], w: ['f = g (values 2, 0, 0, 2)'] },
  { ex: 'Misc', n: 'Q6', q: 'A = {1, 2, 3}. Number of relations containing (1, 2) and (1, 3) that are reflexive and symmetric but not transitive: (A) 1 (B) 2 (C) 3 (D) 4', scene: 'grid', parts: [buildRelPart('Build one: reflexive, symmetric, not transitive, containing (1, 2) and (1, 3)', A3, [true, true, false], { must: [[1, 2], [1, 3]], start: [[1, 2], [1, 3]], example: [[1, 1], [2, 2], [3, 3], [1, 2], [2, 1], [1, 3], [3, 1]] }), { k: 'mcq', q: 'How many such relations?', o: ['(A) 1', '(B) 2', '(C) 3', '(D) 4'], a: 0, x: 'Adding (2, 3) forces (3, 2) and makes it the universal (transitive) relation.' }], w: ['(A) 1'] },
  { ex: 'Misc', n: 'Q7', q: 'A = {1, 2, 3}. Number of equivalence relations containing (1, 2): (A) 1 (B) 2 (C) 3 (D) 4', scene: 'grid', parts: [buildRelPart('Build the smallest equivalence relation containing (1, 2)', A3, [true, true, true], { must: [[1, 2]], start: [[1, 2]], example: [[1, 1], [2, 2], [3, 3], [1, 2], [2, 1]] }), { k: 'mcq', q: 'How many in all?', o: ['(B) 2', '(A) 1', '(C) 3', '(D) 4'], a: 0, x: 'That one, and the universal relation.' }], w: ['(B) 2'] },
];

const BOSS1 = [['(a, a) ∈ R for all a means', ['reflexive', 'symmetric', 'transitive', 'empty'], 0], ['“≤” on ℝ is not', ['symmetric', 'reflexive', 'transitive', 'a relation'], 0], ['Classes of “3 | a − b” on Z', ['3', '2', '1', '∞'], 0], ['f(x) = 2x, N → N is', ['one-one, not onto', 'onto', 'bijective', 'neither'], 0], ['f(x) = x², ℝ → ℝ is', ['neither', 'one-one', 'onto', 'bijective'], 0], ['gof(x) =', ['g(f(x))', 'f(g(x))', 'g(x)f(x)', 'g(x) + f(x)'], 0], ['Invertible ⇔', ['bijective', 'one-one', 'onto', 'continuous'], 0], ['Bijections {1, 2, 3} → itself', ['6', '3', '9', '27'], 0], ['Inverse of 4x + 3', ['(y − 3)/4', '(y + 3)/4', '4y − 3', '1/(4y + 3)'], 0], ['Equivalence relations on {1, 2, 3} containing (1, 2)', ['2', '1', '3', '5'], 0]];
LESSONS.splice(2, 0, exLesson({ id: 'ex11', title: 'Exercise 1.1', blurb: 'All 16: test relations, build them, sort classes.', face: 'kimmy-playful', qs: EX11 }));
LESSONS.splice(4, 0, exLesson({ id: 'ex12', title: 'Exercise 1.2', blurb: 'All 12: slide the line to test one-one and onto.', face: 'jess-happy', qs: EX12 }));
LESSONS.push(exLesson({ id: 'misc', title: 'Miscellaneous', blurb: 'All 7 Miscellaneous Exercise questions.', face: 'jess-thinking', qs: EX1M }));
LESSONS.push(lesson({ id: 'boss', title: 'Boss Battle', blurb: 'Ten fast questions. Speed points. Beat Kimmy.', face: 'jess-excited', steps: [async function () { enterScene('board', (W) => { W.tag = 'BOSS'; W.sub = 'Class 12 · Ch 1'; }); await slam('BOSS BATTLE', '10 questions · speed counts'); await K('play', 'R, S, T!'); await cont('Fight'); }, ...BOSS1.map(([q, o, a], i) => async function () { enterScene('board', (W) => { W.tag = 'Q' + (i + 1); W.sub = 'Boss Battle'; }); await quiz(q, o, a, plain(o[a]) + '.', null, 15); await cont(); }), async function () { enterScene('board', (W) => { W.tag = 'K.O.!'; W.sub = 'Class 12 · Ch 1'; }); await summary(['Chapter complete!', { t: 'Equivalence: R + S + T · Invertible: bijective', eq: true }]); }] }));
LESSONS.forEach((l) => { if (l.kind === 'ex') l.short = l.id === 'misc' ? 'M' : l.title.replace('Exercise ', ''); });
