/* =========================================================
   CHAPTER 11 · INTRODUCTION TO 3D GEOMETRY — every exercise question as a sim
   Distances are computed from the coordinates (rt() writes the exact surd).
   ========================================================= */
const sp = (o = {}) => (W) => { Object.assign(W, o.w || {}); (o.pts || []).forEach(([p, t, col]) => W.pts.push({ p, t, col })); (o.segs || []).forEach(([a, b]) => W.segs.push({ a, b })); };
const distF = (a, b, l) => { const s = sq3(a, b); return { l, a: Math.sqrt(s), show: rt(s), tol: 0.01 }; };
/* move a point to the given coordinates, then name its octant */
const octPart = (p) => ({ k: 'task', q: 'Slide P to ' + P3(p), todo: 'Use the x, y, z sliders.', pre: async () => { const P = xyzSliders(W, [0, 0, 0], 7); W.tmpP = P; W.pts.length = 0; W.pts.push({ p: () => P, t: () => P3(P), drop: true }); W.cap = () => { const o = octOf(P); W.oct = o; return o >= 0 ? 'octant ' + ROMAN[o] : ''; }; }, check: (W) => W.tmpP.every((v, i) => v === p[i]), auto: (W) => p.forEach((v, i) => (W.tmpP[i] = v)), reveal: (W) => p.forEach((v, i) => (W.tmpP[i] = v)) });

const EX111 = [
  { ex: 'Ex 11.1', n: 'Q1', q: 'A point is on the x-axis. What are its y- and z-coordinates?', scene: 'space', setup: sp({ pts: [[[4, 0, 0], '(x, 0, 0)']] }), parts: [{ k: 'fields', q: 'On the x-axis', f: [{ l: 'y', a: 0 }, { l: 'z', a: 0 }], x: 'Both zero: (x, 0, 0).' }], w: ['y = 0 and z = 0'] },
  { ex: 'Ex 11.1', n: 'Q2', q: 'A point is in the XZ-plane. What can you say about its y-coordinate?', scene: 'space', setup: sp({ w: { planes: ['zx'] }, pts: [[[3, 0, 3], '(x, 0, z)']] }), parts: [{ k: 'num', q: 'y = ?', a: 0, x: 'Zero: no distance from the ZX-plane.' }], w: ['y = 0'] },
  { ex: 'Ex 11.1', n: 'Q3', q: 'Name the octants of (1, 2, 3), (4, −2, 3), (4, −2, −5), (4, 2, −5), (−4, 2, −5), (−4, 2, 5), (−3, −1, 6), (−2, −4, −7).', scene: 'space', setup: sp({ w: { R: 7, s: 0.34 } }), kim: 'Read the signs: (+, +, +) is I.',
    parts: [octPart([4, -2, 3]), { k: 'match', q: 'Match each point to its octant (z > 0)', L: ['(1, 2, 3)', '(4, −2, 3)', '(−4, 2, 5)', '(−3, −1, 6)'], R: ['II', 'IV', 'I', 'III'], a: [2, 1, 0, 3] }, octPart([-2, -4, -7]), { k: 'match', q: 'Match each point to its octant (z < 0)', L: ['(4, −2, −5)', '(4, 2, −5)', '(−4, 2, −5)', '(−2, −4, −7)'], R: ['V', 'VII', 'VIII', 'VI'], a: [2, 0, 3, 1] }],
    w: ['I, IV, VIII, V, VI, II, III, VII'] },
  { ex: 'Ex 11.1', n: 'Q4', q: 'Fill in: (i) the x- and y-axes determine the ___ (ii) points in the XY-plane look like ___ (iii) coordinate planes divide space into ___ octants.', scene: 'space', setup: sp({ w: { planes: ['xy'] } }), parts: [{ k: 'mcq', q: '(i)', o: ['XY-plane', 'YZ-plane', 'ZX-plane', 'x-axis'], a: 0 }, { k: 'mcq', q: '(ii)', o: ['(x, y, 0)', '(0, y, z)', '(x, 0, z)', '(0, 0, z)'], a: 0 }, { k: 'num', q: '(iii)', a: 8, x: 'Eight.' }], w: ['XY-plane; (x, y, 0); eight'] },
];

const distQ = (n, A, B) => ({ ex: 'Ex 11.2', n, q: 'Distance between ' + P3(A) + ' and ' + P3(B) + '.', scene: 'space', setup: sp({ w: { boxes: [{ a: A, b: B, col: C.ink }] }, pts: [[A, 'A'], [B, 'B', C.sora]] }), parts: [{ k: 'fields', q: 'Edges of the box', f: [0, 1, 2].map((i) => ({ l: '|Δ' + 'xyz'[i] + '|', a: Math.abs(A[i] - B[i]) })), x: 'Differences of coordinates.' }, { k: 'num', ...(({ l, ...r }) => r)(distF(A, B)), q: 'AB = ?', keys: '√', x: '√' + sq3(A, B) + ' = ' + rt(sq3(A, B)) + '.', act: async () => { W.segs.push({ a: A, b: B, col: C.beni, p: 0 }); gsap.to(W.segs[W.segs.length - 1], { p: 1, duration: 0.6 }); SFX.swish(); } }], w: ['AB = √' + sq3(A, B) + ' = ' + rt(sq3(A, B))] });
const tri3 = (n, q, pts, labs, verdictQ) => ({ ex: 'Ex 11.2', n, q, scene: 'space', setup: sp({ w: { R: 7, s: 0.34 }, pts: pts.map((p, i) => [p, labs[i]]), segs: pts.map((p, i) => [p, pts[(i + 1) % pts.length]]) }), parts: [{ k: 'fields', q: 'Squared side lengths', f: pts.map((p, i) => ({ l: labs[i] + labs[(i + 1) % pts.length] + '²', a: sq3(p, pts[(i + 1) % pts.length]) })), x: pts.map((p, i) => labs[i] + labs[(i + 1) % pts.length] + '² = ' + sq3(p, pts[(i + 1) % pts.length])).join(', ') + '.' }, verdictQ], w: [pts.map((p, i) => labs[i] + labs[(i + 1) % pts.length] + '² = ' + sq3(p, pts[(i + 1) % pts.length])).join(', ')] });
const EX112 = [
  distQ('Q1 (i)', [2, 3, 5], [4, 3, 1]), distQ('Q1 (ii)', [-3, 7, 2], [2, 4, -1]), distQ('Q1 (iii)', [-1, 3, -4], [1, -3, 4]), distQ('Q1 (iv)', [2, -1, 3], [-2, 1, 3]),
  { ex: 'Ex 11.2', n: 'Q2', q: 'Show that (−2, 3, 5), (1, 2, 3) and (7, 0, −1) are collinear.', scene: 'space', setup: sp({ w: { R: 7, s: 0.34 }, pts: [[[-2, 3, 5], 'P'], [[1, 2, 3], 'Q'], [[7, 0, -1], 'R']] }), parts: [{ k: 'fields', q: 'Distances', f: [distF([-2, 3, 5], [1, 2, 3], 'PQ'), distF([1, 2, 3], [7, 0, -1], 'QR'), distF([-2, 3, 5], [7, 0, -1], 'PR')], keys: '√', x: '√14 + 2√14 = 3√14.', act: async () => { W.segs.push({ a: [-2, 3, 5], b: [7, 0, -1], col: C.beni }); SFX.swish(); } }, { k: 'tf', q: 'PQ + QR = PR?', o: ['Yes ⇒ collinear', 'No'], a: 0 }], w: ['√14 + 2√14 = 3√14 ⇒ collinear'] },
  tri3('Q3 (i)', 'Verify (0, 7, −10), (1, 6, −6), (4, 9, −6) form an isosceles triangle.', [[0, 7, -10], [1, 6, -6], [4, 9, -6]], ['A', 'B', 'C'], { k: 'mcq', q: 'AB² = BC² = 18 ⇒', o: ['isosceles (AB = BC)', 'equilateral', 'scalene', 'not a triangle'], a: 0, x: 'Two equal sides.' }),
  tri3('Q3 (ii)', 'Verify (0, 7, 10), (−1, 6, 6), (−4, 9, 6) form a right-angled triangle.', [[0, 7, 10], [-1, 6, 6], [-4, 9, 6]], ['A', 'B', 'C'], { k: 'mcq', q: '18 + 18 = 36 ⇒', o: ['right angle at B', 'right angle at A', 'right angle at C', 'not right-angled'], a: 0, x: 'AB² + BC² = CA².' }),
  tri3('Q3 (iii)', 'Verify (−1, 2, 1), (1, −2, 5), (4, −7, 8), (2, −3, 4) form a parallelogram.', [[-1, 2, 1], [1, -2, 5], [4, -7, 8], [2, -3, 4]], ['A', 'B', 'C', 'D'], { k: 'tf', q: 'AB = CD (√36) and BC = DA (√43). Parallelogram?', o: ['Yes', 'No'], a: 0, x: 'Opposite sides equal.' }),
  { ex: 'Ex 11.2', n: 'Q4', q: 'Equation of the set of points equidistant from (1, 2, 3) and (3, 2, −1).', scene: 'board', parts: [{ k: 'order', q: 'Build it', s: ['(x − 1)² + (y − 2)² + (z − 3)² = (x − 3)² + (y − 2)² + (z + 1)²', '−2x + 1 − 6z + 9 = −6x + 9 + 2z + 1', '4x − 8z = 0'] }, { k: 'mcq', q: 'Simplest form', o: ['x − 2z = 0', 'x + 2z = 0', '2x − z = 0', 'x − z = 1'], a: 0 }], w: ['x − 2z = 0'] },
  { ex: 'Ex 11.2', n: 'Q5', q: 'Equation of the set of points whose distances from A(4, 0, 0) and B(−4, 0, 0) add to 10.', scene: 'space', setup: sp({ pts: [[[4, 0, 0], 'A'], [[-4, 0, 0], 'B', C.sora]] }), kim: 'Isolate one root, square, isolate again, square again.', parts: [{ k: 'order', q: 'Steps', s: ['√((x−4)² + y² + z²) = 10 − √((x+4)² + y² + z²)', 'Square: 20√((x+4)² + y² + z²) = 100 + 16x', 'Divide by 4 and square again', '9x² + 25y² + 25z² = 225'] }, { k: 'mcq', q: 'The set is', o: ['9x² + 25y² + 25z² = 225', 'x² + y² + z² = 25', '25x² + 9y² + 9z² = 225', '9x² − 25y² = 225'], a: 0, x: 'An ellipsoid with foci A and B.' }], w: ['9x² + 25y² + 25z² = 225'] },
];

const EX11M = [
  { ex: 'Misc', n: 'Q1', q: 'Three vertices of parallelogram ABCD are A(3, −1, 2), B(1, 2, −4), C(−1, 1, 2). Find D.', scene: 'space', setup: sp({ w: { R: 7, s: 0.34 }, pts: [[[3, -1, 2], 'A'], [[1, 2, -4], 'B'], [[-1, 1, 2], 'C']], segs: [[[3, -1, 2], [1, 2, -4]], [[1, 2, -4], [-1, 1, 2]]] }), kim: 'Diagonals bisect each other: A + C = B + D.', parts: [{ k: 'fields', q: 'D = A + C − B', f: [{ l: 'x', a: 1 }, { l: 'y', a: -2 }, { l: 'z', a: 8 }], x: 'D(1, −2, 8).', act: async () => { W.pts.push({ p: [1, -2, 8], t: 'D', col: C.sora }); W.segs.push({ a: [-1, 1, 2], b: [1, -2, 8] }, { a: [1, -2, 8], b: [3, -1, 2] }); SFX.swish(); } }], w: ['D = (1, −2, 8)'] },
  { ex: 'Misc', n: 'Q2', q: 'Lengths of the medians of the triangle A(0, 0, 6), B(0, 4, 0), C(6, 0, 0).', scene: 'space', setup: sp({ w: { R: 7, s: 0.34 }, pts: [[[0, 0, 6], 'A'], [[0, 4, 0], 'B'], [[6, 0, 0], 'C']], segs: [[[0, 0, 6], [0, 4, 0]], [[0, 4, 0], [6, 0, 0]], [[6, 0, 0], [0, 0, 6]]] }), parts: [{ k: 'fields', q: 'Mid-points of BC, CA, AB', f: [{ l: 'BC: x', a: 3 }, { l: 'y', a: 2 }, { l: 'z', a: 0 }], x: '(3, 2, 0); also (3, 0, 3) and (0, 2, 3).' }, { k: 'fields', q: 'Median lengths', f: [distF([0, 0, 6], [3, 2, 0], 'from A'), distF([0, 4, 0], [3, 0, 3], 'from B'), distF([6, 0, 0], [0, 2, 3], 'from C')], keys: '√', x: '7, √34, 7.', act: async () => { W.segs.push({ a: [0, 0, 6], b: [3, 2, 0], col: C.beni }, { a: [0, 4, 0], b: [3, 0, 3], col: C.beni }, { a: [6, 0, 0], b: [0, 2, 3], col: C.beni }); SFX.swish(); } }], w: ['Medians 7, √34, 7'] },
  { ex: 'Misc', n: 'Q3', q: 'The origin is the centroid of P(2a, 2, 6), Q(−4, 3b, −10), R(8, 14, 2c). Find a, b, c.', scene: 'board', parts: [{ k: 'fields', q: 'Each coordinate sum is 0', f: [{ l: 'a', a: -2 }, { l: 'b', a: -16 / 3, show: '−16/3' }, { l: 'c', a: 2 }], x: '2a + 4 = 0, 3b + 16 = 0, 2c − 4 = 0.' }], w: ['a = −2, b = −16/3, c = 2'] },
  { ex: 'Misc', n: 'Q4', q: 'A(3, 4, 5), B(−1, 3, −7). Equation of the set of P with PA² + PB² = k².', scene: 'board', parts: [{ k: 'num', q: 'Constant from expanding: 9 + 16 + 25 + 1 + 9 + 49 = ?', a: 109, x: '109.' }, { k: 'mcq', q: 'Equation', o: ['x² + y² + z² − 2x − 7y + 2z = (k² − 109)/2', 'x² + y² + z² = k²', '2x² + 2y² + 2z² − 4x − 14y + 4z = 2k² − 109', 'x² + y² + z² − 2x − 7y + 2z = k² − 109'], a: 0, x: 'Same as Example 6 but with k² instead of 2k².' }], w: ['x² + y² + z² − 2x − 7y + 2z = (k² − 109)/2'] },
];

const BOSS11 = [['(0, y, z) lies in the', ['YZ-plane', 'XY-plane', 'ZX-plane', 'x-axis'], 0], ['Octant of (−1, −1, −1)', ['VII', 'III', 'VI', 'VIII'], 0], ['Distance of (3, 4, 0) from O', ['5', '7', '25', '√7'], 0], ['Number of octants', ['8', '4', '6', '3'], 0], ['Octant of (2, −3, 1)', ['IV', 'II', 'VIII', 'I'], 0], ['Distance (1, 1, 1) to (2, 2, 2)', ['√3', '3', '1', '√2'], 0], ['A point on the z-axis', ['(0, 0, z)', '(z, 0, 0)', '(0, z, 0)', '(z, z, z)'], 0], ['Centroid of (0,0,0), (3,0,0), (0,3,3)', ['(1, 1, 1)', '(3, 3, 3)', '(1, 0, 1)', '(0, 1, 1)'], 0], ['Distance of (x, y, z) from the XY-plane', ['|z|', '|x|', '|y|', '√(x² + y²)'], 0], ['(2, 0, 5) lies in the', ['ZX-plane', 'XY-plane', 'YZ-plane', 'octant I'], 0]];
LESSONS.splice(1, 0, exLesson({ id: 'ex111', title: 'Exercise 11.1', blurb: 'All 4: axes, planes and all eight octants.', face: 'kimmy-playful', qs: EX111 }));
LESSONS.splice(3, 0, exLesson({ id: 'ex112', title: 'Exercise 11.2', blurb: 'All 5: distances, collinear points, triangles, loci.', face: 'jess-happy', qs: EX112 }));
LESSONS.push(exLesson({ id: 'misc', title: 'Miscellaneous', blurb: 'All 4 Miscellaneous Exercise questions.', face: 'jess-thinking', qs: EX11M }));
LESSONS.push(lesson({ id: 'boss', title: 'Boss Battle', blurb: 'Ten fast questions. Speed points. Beat Kimmy.', face: 'jess-excited', steps: [async function () { enterScene('board', (W) => { W.tag = 'BOSS'; W.sub = 'Chapter 11'; }); await slam('BOSS BATTLE', '10 questions · speed counts'); await K('play', 'x, y, z!'); await cont('Fight'); }, ...BOSS11.map(([q, o, a], i) => async function () { enterScene('board', (W) => { W.tag = 'Q' + (i + 1); W.sub = 'Boss Battle'; }); await quiz(q, o, a, plain(o[a]) + '.', null, 15); await cont(); }), async function () { enterScene('board', (W) => { W.tag = 'K.O.!'; W.sub = 'Chapter 11'; }); await summary(['Chapter 11 complete!', { t: 'PQ = √(Δx² + Δy² + Δz²)', eq: true }]); }] }));
LESSONS.forEach((l) => { if (l.kind === 'ex') l.short = l.id === 'misc' ? 'M' : l.title.replace('Exercise ', ''); });
