/* =========================================================
   CHAPTER 6 · PERMUTATIONS & COMBINATIONS — every exercise question as a sim
   Answers are computed with fact / P / Cn (and re-checked by the test page).
   ========================================================= */
const ORD = ['Order matters → arrange (P)', 'Order doesn’t matter → select (C)'];
const orderPart = (perm, x) => ({ k: 'tf', q: 'Before counting: does ORDER matter here?', o: ORD, a: perm ? 0 : 1, x, time: 15 });
const slotQ = (ex, n, q, labs, counts, o = {}) => ({ ex, n, q, ans: counts.reduce((a, b) => a * b, 1), scene: 'slots', setup: (W) => { slotsSet(W, labs, o.pool || []); W.repeat = !!o.repeat; }, kim: o.kim, parts: [...(o.pre || []), { k: 'num', q: o.ask || 'How many?', a: counts.reduce((a, b) => a * b, 1), x: counts.join(' × ') + ' = ' + fmtBig(counts.reduce((a, b) => a * b, 1)) + '.', act: async () => slotsFill(W, counts, o.picks || []) }], w: o.w || [(o.wl || '') + counts.join(' × ') + ' = ' + fmtBig(counts.reduce((a, b) => a * b, 1))] });

/* ===================== EXERCISE 6.1 ===================== */
const EX61 = [
  slotQ('Ex 6.1', 'Q1 (i)', 'How many 3-digit numbers can be formed from 1, 2, 3, 4, 5 if repetition of digits is allowed?', ['h', 't', 'u'], [5, 5, 5], { pool: ['1', '2', '3', '4', '5'], repeat: true, picks: ['3', '3', '1'] }),
  slotQ('Ex 6.1', 'Q1 (ii)', 'Same digits, repetition NOT allowed?', ['h', 't', 'u'], [5, 4, 3], { pool: ['1', '2', '3', '4', '5'], picks: ['4', '1', '5'] }),
  slotQ('Ex 6.1', 'Q2', 'How many 3-digit even numbers can be formed from 1, 2, 3, 4, 5, 6 if the digits can be repeated?', ['h', 't', 'u (even)'], [6, 6, 3], { kim: 'Units place first: only 2, 4 or 6.', repeat: true, pool: ['1', '2', '3', '4', '5', '6'] }),
  slotQ('Ex 6.1', 'Q3', 'How many 4-letter codes can be formed using the first 10 letters of the English alphabet, if no letter can be repeated?', ['1', '2', '3', '4'], [10, 9, 8, 7], { pool: 'ABCDEFGHIJ'.split(''), picks: ['C', 'A', 'J', 'E'] }),
  slotQ('Ex 6.1', 'Q4', 'How many 5-digit telephone numbers can be constructed using 0–9 if each number starts with 67 and no digit appears more than once?', ['6', '7', '3rd', '4th', '5th'], [1, 1, 8, 7, 6], { picks: ['6', '7'], kim: '6 and 7 are used up, so 8 digits remain.' }),
  slotQ('Ex 6.1', 'Q5', 'A coin is tossed 3 times and the outcomes are recorded. How many possible outcomes are there?', ['toss 1', 'toss 2', 'toss 3'], [2, 2, 2], { pool: ['H', 'T'], repeat: true, picks: ['H', 'T', 'H'] }),
  slotQ('Ex 6.1', 'Q6', 'Given 5 flags of different colours, how many different signals can be generated if each signal requires 2 flags, one below the other?', ['upper', 'lower'], [5, 4]),
];

/* ===================== EXERCISE 6.2 ===================== */
const EX62 = [
  { ex: 'Ex 6.2', n: 'Q1', q: 'Evaluate (i) 8! (ii) 4! − 3!', scene: 'slots', setup: (W) => slotsSet(W, ['8', '7', '6', '5', '4', '3', '2', '1']), parts: [{ k: 'num', q: '(i) 8! = ?', a: 40320, x: '40320.', act: async () => slotsFill(W, [8, 7, 6, 5, 4, 3, 2, 1], [], 0.12) }, { k: 'num', q: '(ii) 4! − 3! = ?', a: 18, x: '24 − 6 = 18.' }], w: ['8! = 40320;  4! − 3! = 24 − 6 = 18'] },
  { ex: 'Ex 6.2', n: 'Q2', q: 'Is 3! + 4! = 7! ?', scene: 'board', parts: [{ k: 'fields', q: 'Compute both sides', f: [{ l: '3! + 4!', a: 30 }, { l: '7!', a: 5040 }], x: '6 + 24 = 30 but 7! = 5040.' }, { k: 'tf', q: 'So is 3! + 4! = 7!?', o: ['Yes', 'No'], a: 1, x: 'Factorials do not add like that.' }], w: ['3! + 4! = 30 ≠ 5040 = 7!. No.'] },
  { ex: 'Ex 6.2', n: 'Q3', q: 'Compute 8!/(6! × 2!).', scene: 'board', parts: [{ k: 'num', q: '8 × 7 × 6!/(6! × 2) = ?', a: 28, x: '56/2 = 28.' }], w: ['8!/(6! 2!) = 8 × 7/2 = 28'] },
  { ex: 'Ex 6.2', n: 'Q4', q: 'If 1/6! + 1/7! = x/8!, find x.', scene: 'board', kim: 'Multiply everything by 8!.', parts: [{ k: 'num', q: '8!/6! + 8!/7! = x ⇒ x = ?', a: 64, x: '56 + 8 = 64.' }], w: ['Multiply by 8!: 8 × 7 + 8 = x ⇒ x = 64'] },
  { ex: 'Ex 6.2', n: 'Q5', q: 'Evaluate n!/(n − r)! when (i) n = 6, r = 2 (ii) n = 9, r = 5.', scene: 'slots', setup: (W) => slotsSet(W, ['', '']), parts: [{ k: 'num', q: '(i) 6!/4! = ?', a: P(6, 2), x: '6 × 5 = 30.', act: async () => slotsFill(W, [6, 5]) }, { k: 'num', q: '(ii) 9!/4! = ?', a: P(9, 5), x: '9 × 8 × 7 × 6 × 5 = 15120.', pre: () => slotsSet(W, ['', '', '', '', '']), act: async () => slotsFill(W, [9, 8, 7, 6, 5], [], 0.15) }], w: ['(i) 30  (ii) 15120'] },
];

/* ===================== EXERCISE 6.3 ===================== */
const EX63 = [
  slotQ('Ex 6.3', 'Q1', 'How many 3-digit numbers can be formed by using the digits 1 to 9 if no digit is repeated?', ['h', 't', 'u'], [9, 8, 7], { pre: [orderPart(true, '312 and 213 are different numbers.')] }),
  slotQ('Ex 6.3', 'Q2', 'How many 4-digit numbers are there with no digit repeated?', ['th (≠ 0)', 'h', 't', 'u'], [9, 9, 8, 7], { kim: 'The first digit cannot be 0!' }),
  slotQ('Ex 6.3', 'Q3', 'How many 3-digit even numbers can be made using 1, 2, 3, 4, 6, 7 if no digit is repeated?', ['h', 't', 'u (even)'], [4, 5, 3], { pool: ['1', '2', '3', '4', '6', '7'], ask: 'Units: 2, 4 or 6 (3 ways). Then tens 5, hundreds 4. Total?' }),
  { ex: 'Ex 6.3', n: 'Q4', q: 'Find the number of 4-digit numbers that can be formed using 1, 2, 3, 4, 5 if no digit is repeated. How many of these will be even?', scene: 'slots', setup: (W) => slotsSet(W, ['th', 'h', 't', 'u'], ['1', '2', '3', '4', '5']), parts: [{ k: 'num', q: 'All: ⁵P₄ = ?', a: P(5, 4), x: '120.', act: async () => slotsFill(W, [5, 4, 3, 2]) }, { k: 'num', q: 'Even (units 2 or 4): 2 × ⁴P₃ = ?', a: 2 * P(4, 3), x: '48.', pre: () => slotsSet(W, ['th', 'h', 't', 'u'], ['1', '2', '3', '4', '5']), act: async () => slotsFill(W, [4, 3, 2, 2]) }], w: ['⁵P₄ = 120; even: 2 × 4 × 3 × 2 = 48'] },
  slotQ('Ex 6.3', 'Q5', 'From a committee of 8 persons, in how many ways can we choose a chairman and a vice chairman (one person cannot hold both)?', ['chairman', 'vice'], [8, 7], { pre: [orderPart(true, 'Chairman and vice are different posts.')] }),
  { ex: 'Ex 6.3', n: 'Q6', q: 'Find n if ⁿ⁻¹P₃ : ⁿP₄ = 1 : 9.', scene: 'board', parts: [{ k: 'mcq', q: 'ⁿ⁻¹P₃ / ⁿP₄ simplifies to…', o: ['1/n', 'n', '1/(n − 1)', '(n − 3)/n'], a: 0, x: '(n−1)(n−2)(n−3) / [n(n−1)(n−2)(n−3)] = 1/n.' }, { k: 'num', q: '1/n = 1/9 ⇒ n = ?', a: 9, x: 'n = 9.' }], w: ['ⁿ⁻¹P₃/ⁿP₄ = 1/n = 1/9 ⇒ n = 9'] },
  { ex: 'Ex 6.3', n: 'Q7', q: 'Find r if (i) ⁵Pᵣ = 2 · ⁶Pᵣ₋₁ (ii) ⁵Pᵣ = ⁶Pᵣ₋₁.', scene: 'board', parts: [{ k: 'mcq', q: '(i) reduces to (7 − r)(6 − r) = 12. r = ?', o: ['3', '10', '3 or 10', '4'], a: 0, x: 'r² − 13r + 30 = 0 ⇒ r = 3 or 10, but r ≤ 5 so r = 3.' }, { k: 'mcq', q: '(ii) reduces to (7 − r)(6 − r) = 6. r = ?', o: ['4', '9', '4 or 9', '3'], a: 0, x: 'r² − 13r + 36 = 0 ⇒ r = 4 or 9, but r ≤ 5 so r = 4.' }], w: ['(i) 5!/(5−r)! = 2·6!/(7−r)! ⇒ (7−r)(6−r) = 12 ⇒ r = 3', '(ii) (7−r)(6−r) = 6 ⇒ r = 4'] },
  { ex: 'Ex 6.3', n: 'Q8', q: 'How many words, with or without meaning, can be formed using all the letters of EQUATION, each exactly once?', scene: 'tiles', setup: (W) => tilesSet(W, 'EQUATION'), parts: [{ k: 'num', q: '8 different letters: 8! = ?', a: fact(8), x: '40320.', act: async () => tilesShuffle(W, 2) }], w: ['8! = 40320'] },
  { ex: 'Ex 6.3', n: 'Q9', q: 'Words from MONDAY, no letter repeated, if (i) 4 letters are used (ii) all letters are used (iii) all letters, first letter a vowel?', scene: 'tiles', setup: (W) => tilesSet(W, 'MONDAY'), parts: [{ k: 'num', q: '(i) ⁶P₄ = ?', a: P(6, 4), x: '360.' }, { k: 'num', q: '(ii) 6! = ?', a: fact(6), x: '720.', act: async () => tilesShuffle(W, 2) }, { k: 'num', q: '(iii) vowels O, A first (2 ways) × 5! = ?', a: 2 * fact(5), x: '240.' }], w: ['(i) 360 (ii) 720 (iii) 2 × 5! = 240'] },
  { ex: 'Ex 6.3', n: 'Q10', q: 'In how many of the distinct permutations of the letters in MISSISSIPPI do the four I’s not come together?', scene: 'tiles', setup: (W) => tilesSet(W, 'MISSISSIPPI'), parts: [{ k: 'num', q: 'All: 11!/(4! 4! 2!) = ?', a: arrangements('MISSISSIPPI'), x: '34650.' }, { k: 'num', q: 'I’s glued: 8!/(4! 2!) = ?', a: fact(8) / (fact(4) * fact(2)), x: '840.', act: async () => tilesGlue(W, (c) => c === 'I') }, { k: 'num', q: 'I’s NOT together = ?', a: arrangements('MISSISSIPPI') - fact(8) / (fact(4) * fact(2)), x: '34650 − 840 = 33810.' }], w: ['Total 11!/(4!4!2!) = 34650; I’s together 8!/(4!2!) = 840; answer 33810'] },
  { ex: 'Ex 6.3', n: 'Q11', q: 'PERMUTATIONS: in how many ways if (i) words start with P and end with S (ii) vowels are all together (iii) there are always 4 letters between P and S?', scene: 'tiles', setup: (W) => tilesSet(W, 'PERMUTATIONS'), kim: '12 letters, and T appears twice.', parts: [{ k: 'num', q: '(i) fix P and S, arrange 10 with two T: 10!/2! = ?', a: fact(10) / 2, x: '1814400.' }, { k: 'num', q: '(ii) vowels E, U, A, I, O glued: (8!/2!) × 5! = ?', a: (fact(8) / 2) * fact(5), x: '20160 × 120 = 2419200.', act: async () => tilesGlue(W, (c) => 'EUAIO'.includes(c)) }, { k: 'num', q: '(iii) positions for P…S with 4 between: (1,6) to (7,12) = 7 pairs × 2 orders = ?', a: 14, x: '14 placements.' }, { k: 'num', q: 'Total = 14 × 10!/2! = ?', a: 14 * (fact(10) / 2), x: '25401600.' }], w: ['(i) 10!/2! = 1814400', '(ii) 8!/2! × 5! = 2419200', '(iii) 14 × 10!/2! = 25401600'] },
];

/* ===================== EXERCISE 6.4 ===================== */
const EX64 = [
  { ex: 'Ex 6.4', n: 'Q1', q: 'If ⁿC₈ = ⁿC₂, find ⁿC₂.', scene: 'board', parts: [{ k: 'num', q: 'n = 8 + 2 = ?', a: 10, x: 'ⁿCₐ = ⁿC_b ⇒ n = a + b.' }, { k: 'num', q: '¹⁰C₂ = ?', a: Cn(10, 2), x: '45.' }], w: ['n = 10, ¹⁰C₂ = 45'] },
  { ex: 'Ex 6.4', n: 'Q2', q: 'Determine n if (i) ²ⁿC₃ : ⁿC₃ = 12 : 1 (ii) ²ⁿC₃ : ⁿC₃ = 11 : 1.', scene: 'board', parts: [{ k: 'mcq', q: '²ⁿC₃ / ⁿC₃ simplifies to…', o: ['4(2n − 1)/(n − 2)', '2(2n − 1)/(n − 2)', '8', '(2n − 1)/(n − 1)'], a: 0, x: '(2n)(2n−1)(2n−2)/[n(n−1)(n−2)] = 4(2n−1)/(n−2).' }, { k: 'num', q: '(i) = 12 ⇒ n = ?', a: 5, x: '8n − 4 = 12n − 24 ⇒ n = 5.' }, { k: 'num', q: '(ii) = 11 ⇒ n = ?', a: 6, x: '8n − 4 = 11n − 22 ⇒ n = 6.' }], w: ['4(2n − 1)/(n − 2) = 12 ⇒ n = 5;  = 11 ⇒ n = 6'] },
  { ex: 'Ex 6.4', n: 'Q3', q: 'How many chords can be drawn through 21 points on a circle?', scene: 'pick', parts: [orderPart(false, 'Chord AB = chord BA.'), { k: 'num', q: '²¹C₂ = ?', a: Cn(21, 2), x: '210.', act: async () => chordsDraw(W, 21) }], w: ['²¹C₂ = 210'] },
  { ex: 'Ex 6.4', n: 'Q4', q: 'In how many ways can a team of 3 boys and 3 girls be selected from 5 boys and 4 girls?', scene: 'pick', setup: (W) => pickSetup(W, [['boys', 5, C['sora-tint'], 'B'], ['girls', 4, C.sakura, 'G']]), parts: [{ k: 'num', q: '⁵C₃ × ⁴C₃ = ?', a: Cn(5, 3) * Cn(4, 3), x: '10 × 4 = 40.', act: async () => pickTake(W, [[0, 3], [1, 3]]) }], w: ['⁵C₃ × ⁴C₃ = 40'] },
  { ex: 'Ex 6.4', n: 'Q5', q: 'Selecting 9 balls from 6 red, 5 white and 5 blue, each selection having 3 of each colour.', scene: 'pick', setup: (W) => pickSetup(W, [['red', 6, C.sakura, 'R'], ['white', 5, C.panel, 'W'], ['blue', 5, C['sora-tint'], 'B']]), parts: [{ k: 'num', q: '⁶C₃ × ⁵C₃ × ⁵C₃ = ?', a: Cn(6, 3) * Cn(5, 3) ** 2, x: '20 × 10 × 10 = 2000.', act: async () => pickTake(W, [[0, 3], [1, 3], [2, 3]], 0.06) }], w: ['⁶C₃ × ⁵C₃ × ⁵C₃ = 2000'] },
  { ex: 'Ex 6.4', n: 'Q6', q: 'Determine the number of 5-card combinations out of a deck of 52 cards if there is exactly one ace in each combination.', scene: 'pick', setup: (W) => { W.mode = 'cards'; W.hl = (r) => r === 0; W.cap = '4 aces · 48 others'; }, parts: [{ k: 'num', q: '⁴C₁ × ⁴⁸C₄ = ?', a: 4 * Cn(48, 4), x: '4 × 194580 = 778320.' }], w: ['⁴C₁ × ⁴⁸C₄ = 778320'] },
  { ex: 'Ex 6.4', n: 'Q7', q: 'Select a cricket team of 11 from 17 players, of whom only 5 can bowl, with exactly 4 bowlers.', scene: 'pick', setup: (W) => pickSetup(W, [['bowlers', 5, C.kin, 'b'], ['others', 12, C['sora-tint'], 'p']]), parts: [{ k: 'num', q: '⁵C₄ × ¹²C₇ = ?', a: Cn(5, 4) * Cn(12, 7), x: '5 × 792 = 3960.', act: async () => pickTake(W, [[0, 4], [1, 7]], 0.05) }], w: ['⁵C₄ × ¹²C₇ = 3960'] },
  { ex: 'Ex 6.4', n: 'Q8', q: 'A bag contains 5 black and 6 red balls. In how many ways can 2 black and 3 red balls be selected?', scene: 'pick', setup: (W) => pickSetup(W, [['black', 5, C.tone, 'K'], ['red', 6, C.sakura, 'R']]), parts: [{ k: 'num', q: '⁵C₂ × ⁶C₃ = ?', a: Cn(5, 2) * Cn(6, 3), x: '10 × 20 = 200.', act: async () => pickTake(W, [[0, 2], [1, 3]]) }], w: ['⁵C₂ × ⁶C₃ = 200'] },
  { ex: 'Ex 6.4', n: 'Q9', q: 'A student chooses 5 of 9 courses; 2 specific courses are compulsory.', scene: 'pick', setup: (W) => pickSetup(W, [['compulsory', 2, C.kin, 'c'], ['optional', 7, C['sora-tint'], 'o']]), parts: [{ k: 'num', q: 'Choose the other 3 from 7: ⁷C₃ = ?', a: Cn(7, 3), x: '35.', act: async () => pickTake(W, [[0, 2], [1, 3]]) }], w: ['⁷C₃ = 35'] },
];

/* ===================== MISCELLANEOUS ===================== */
const EX6M = [
  { ex: 'Misc', n: 'Q1', q: 'How many words, each of 2 vowels and 3 consonants, can be formed from the letters of DAUGHTER?', scene: 'tiles', setup: (W) => tilesSet(W, 'DAUGHTER'), parts: [{ k: 'fields', q: 'Select', f: [{ l: '³C₂ vowels', a: 3 }, { l: '⁵C₃ consonants', a: 10 }], x: 'A, U, E and D, G, H, T, R.' }, { k: 'num', q: '3 × 10 × 5! = ?', a: 3 * 10 * 120, x: '3600.' }], w: ['³C₂ × ⁵C₃ × 5! = 3600'] },
  { ex: 'Misc', n: 'Q2', q: 'How many words can be formed using all the letters of EQUATION so that the vowels and consonants occur together?', scene: 'tiles', setup: (W) => tilesSet(W, 'EQUATION'), parts: [{ k: 'num', q: '2 blocks (vowels, consonants) × 5! × 3! = ?', a: 2 * 120 * 6, x: '1440.', act: async () => tilesGlue(W, (c) => 'EUAIO'.includes(c)) }], w: ['2! × 5! × 3! = 1440'] },
  { ex: 'Misc', n: 'Q3', q: 'A committee of 7 from 9 boys and 4 girls with (i) exactly 3 girls (ii) at least 3 girls (iii) at most 3 girls.', scene: 'pick', setup: (W) => pickSetup(W, [['girls', 4, C.sakura, 'G'], ['boys', 9, C['sora-tint'], 'B']]), parts: [{ k: 'num', q: '(i) ⁴C₃ × ⁹C₄ = ?', a: Cn(4, 3) * Cn(9, 4), x: '504.', act: async () => pickTake(W, [[0, 3], [1, 4]], 0.05) }, { k: 'num', q: '(ii) 3 or 4 girls: 504 + ⁴C₄ × ⁹C₃ = ?', a: Cn(4, 3) * Cn(9, 4) + Cn(9, 3), x: '504 + 84 = 588.' }, { k: 'num', q: '(iii) 0, 1, 2 or 3 girls: total = ?', a: [0, 1, 2, 3].reduce((s, g) => s + Cn(4, g) * Cn(9, 7 - g), 0), x: '36 + 336 + 756 + 504 = 1632.' }], w: ['(i) 504 (ii) 588 (iii) 1632'] },
  { ex: 'Misc', n: 'Q4', q: 'If the permutations of EXAMINATION are listed as in a dictionary, how many words come before the first word starting with E?', scene: 'tiles', setup: (W) => tilesSet(W, 'EXAMINATION'), kim: 'Only words starting with A come before E.', parts: [{ k: 'num', q: 'Fix A first; the other 10 letters have I×2, N×2: 10!/(2! 2!) = ?', a: fact(10) / 4, x: '907200.' }], w: ['Words starting with A: 10!/(2! 2!) = 907200'] },
  { ex: 'Misc', n: 'Q5', q: 'How many 6-digit numbers can be formed from 0, 1, 3, 5, 7, 9 which are divisible by 10, no digit repeated?', scene: 'slots', setup: (W) => slotsSet(W, ['', '', '', '', '', '0']), parts: [{ k: 'num', q: 'Last digit must be 0; arrange the other 5: 5! = ?', a: 120, x: '120.', act: async () => slotsFill(W, [5, 4, 3, 2, 1, 1]) }], w: ['Units digit 0; remaining 5! = 120'] },
  { ex: 'Misc', n: 'Q6', q: 'The alphabet has 5 vowels and 21 consonants. How many words with two different vowels and 2 different consonants can be formed?', scene: 'board', parts: [{ k: 'num', q: '⁵C₂ × ²¹C₂ × 4! = ?', a: Cn(5, 2) * Cn(21, 2) * 24, x: '10 × 210 × 24 = 50400.' }], w: ['⁵C₂ × ²¹C₂ × 4! = 50400'] },
  { ex: 'Misc', n: 'Q7', q: 'A paper has Part I (5 questions) and Part II (7). Attempt 8 in all, at least 3 from each part. In how many ways?', scene: 'pick', setup: (W) => pickSetup(W, [['Part I', 5, C.peach, 'a'], ['Part II', 7, C['sora-tint'], 'b']]), parts: [{ k: 'fields', q: 'Cases (I, II) = (3, 5), (4, 4), (5, 3)', f: [{ l: '⁵C₃·⁷C₅', a: 210 }, { l: '⁵C₄·⁷C₄', a: 175 }, { l: '⁵C₅·⁷C₃', a: 35 }], x: '210, 175, 35.' }, { k: 'num', q: 'Total = ?', a: 420, x: '420.' }], w: ['⁵C₃⁷C₅ + ⁵C₄⁷C₄ + ⁵C₅⁷C₃ = 210 + 175 + 35 = 420'] },
  { ex: 'Misc', n: 'Q8', q: 'Number of 5-card combinations from 52 cards with exactly one king.', scene: 'pick', setup: (W) => { W.mode = 'cards'; W.hl = (r) => r === 12; W.cap = '4 kings · 48 others'; }, parts: [{ k: 'num', q: '⁴C₁ × ⁴⁸C₄ = ?', a: 4 * Cn(48, 4), x: '778320.' }], w: ['⁴C₁ × ⁴⁸C₄ = 778320'] },
  { ex: 'Misc', n: 'Q9', q: 'Seat 5 men and 4 women in a row so that the women occupy the even places.', scene: 'slots', setup: (W) => slotsSet(W, ['1', '2', '3', '4', '5', '6', '7', '8', '9']), parts: [{ k: 'num', q: '4! (women in places 2,4,6,8) × 5! = ?', a: 24 * 120, x: '2880.', act: async () => slotsFill(W, [5, 4, 4, 3, 3, 2, 2, 1, 1], ['M', 'W', 'M', 'W', 'M', 'W', 'M', 'W', 'M'], 0.12) }], w: ['4! × 5! = 2880'] },
  { ex: 'Misc', n: 'Q10', q: '10 of 25 students go on an excursion. 3 students go all together or none of them goes. In how many ways?', scene: 'pick', setup: (W) => pickSetup(W, [['trio', 3, C.kin, 't'], ['others', 22, C['sora-tint'], 's']]), parts: [{ k: 'fields', q: 'Two cases', f: [{ l: 'trio in: ²²C₇', a: Cn(22, 7) }, { l: 'trio out: ²²C₁₀', a: Cn(22, 10) }], x: '170544 and 646646.' }, { k: 'num', q: 'Total = ?', a: Cn(22, 7) + Cn(22, 10), x: '817190.' }], w: ['²²C₇ + ²²C₁₀ = 170544 + 646646 = 817190'] },
  { ex: 'Misc', n: 'Q11', q: 'In how many ways can the letters of ASSASSINATION be arranged so that all the S’s are together?', scene: 'tiles', setup: (W) => tilesSet(W, 'ASSASSINATION'), parts: [{ k: 'num', q: 'Glue SSSS into one block: 10 objects with A×3, I×2, N×2 → 10!/(3! 2! 2!) = ?', a: fact(10) / (6 * 2 * 2), x: '151200.', act: async () => tilesGlue(W, (c) => c === 'S') }], w: ['10!/(3! 2! 2!) = 151200'] },
];

const BOSS6 = [['5! = ?', ['60', '120', '24', '720'], 1], ['⁶P₂ = ?', ['15', '30', '36', '12'], 1], ['⁶C₂ = ?', ['15', '30', '12', '36'], 0], ['Arrangements of BOOK', ['24', '12', '6', '4'], 1], ['Handshakes among 10 people', ['90', '45', '100', '20'], 1], ['ⁿCᵣ = ⁿC₇ and ⁿC₃ equal ⇒ n = ?', ['10', '21', '4', '7'], 0], ['3-digit codes from 0–9 with repetition', ['720', '1000', '999', '900'], 1], ['ⁿPᵣ ÷ ⁿCᵣ = ?', ['n!', 'r!', '(n − r)!', '1'], 1], ['Ways to pick 2 of 4 flags (unordered)', ['12', '6', '8', '16'], 1], ['0! = ?', ['0', '1', '∞', 'undefined'], 1]];
LESSONS.splice(1, 0, exLesson({ id: 'ex61', title: 'Exercise 6.1', blurb: 'Counting principle with slots.', qs: EX61 }));
LESSONS.splice(3, 0, exLesson({ id: 'ex62', title: 'Exercise 6.2', blurb: 'Factorials.', face: 'kimmy-curious', qs: EX62 }));
LESSONS.splice(5, 0, exLesson({ id: 'ex63', title: 'Exercise 6.3', blurb: 'Permutations, repeated letters, restrictions.', face: 'kimmy-playful', qs: EX63 }));
LESSONS.splice(7, 0, exLesson({ id: 'ex64', title: 'Exercise 6.4', blurb: 'Combinations: teams, chords, cards.', face: 'kimmy-excited', qs: EX64 }));
LESSONS.push(exLesson({ id: 'misc', title: 'Miscellaneous', blurb: 'All 11 Miscellaneous Exercise questions.', face: 'jess-thinking', qs: EX6M }));
LESSONS.push(lesson({ id: 'boss', title: 'Boss Battle', blurb: 'Ten fast questions. Speed points. Beat Kimmy.', face: 'jess-excited', steps: [async function () { enterScene('board', (W) => { W.tag = 'BOSS'; W.sub = 'Chapter 6'; }); await slam('BOSS BATTLE', '10 questions · speed counts'); await K('play', 'Count fast!'); await cont('Fight'); }, ...BOSS6.map(([q, o, a], i) => async function () { enterScene('board', (W) => { W.tag = 'Q' + (i + 1); W.sub = 'Boss Battle'; }); await quiz(q, o, a, plain(o[a]) + '.', null, 15); await cont(); }), async function () { enterScene('board', (W) => { W.tag = 'K.O.!'; W.sub = 'Chapter 6'; }); await summary(['Chapter 6 complete!', 'Multiply choices · Arrange with P · Select with C', { t: 'ⁿPᵣ = ⁿCᵣ × r!', eq: true }]); }] }));
LESSONS.forEach((l) => { if (l.kind === 'ex') l.short = l.id === 'misc' ? 'M' : l.title.replace('Exercise ', ''); });
