/* =========================================================
   CLASS 12 · CHAPTER 5 · CONTINUITY & DIFFERENTIABILITY — every exercise question as a sim
   Each derivative question carries f and its derivative; the test page checks it against a numeric derivative.
   Letters are graphed with a = 2, b = 1, c = 1, d = 0.5 unless the caption says otherwise.
   ========================================================= */
const { sin, cos, tan, log, exp, sqrt, abs, asin, acos, atan } = Math;
const sec = (x) => 1 / cos(x), csc = (x) => 1 / sin(x), cot = (x) => 1 / tan(x);
const sayP = (t, m = 'think') => ({ k: 'say', who: 'jess', m, t });
/* "show that LHS = value": a derivation step, then the LHS evaluated numerically at x0 */
function showQ(ex, n, q, f, lhs, val, x0, o = {}) {
  const v = o.view || [x0 - 2.5, x0 + 2.5];
  return { ex, n, q, scene: 'calc', f, lhs, val, x0,
    setup: (W) => { calcView(W, f, v[0], v[1], { y: o.y, fit: true }); W.a = x0; W.tan = true; W.read = true; grabCalc(W); if (o.cap) W.pl.caption = o.cap; },
    parts: [...(o.steps || []), { k: 'num', q: o.nq || 'Live check: the left side at x = ' + fmtN(x0, 3) + ' = ?', a: val, tol: 0.011, show: cell(val), x: 'Numerically ' + fmtN(lhs(x0), 4) + ': it holds.' }],
    w: [o.w || q.replace(/^.*show that /i, '')] };
}
const xs = (ex, n, q, parts, w, o = {}) => ({ ex, n, q, scene: o.scene || 'board', setup: o.setup, parts, w: [w] });

/* ===================== EXERCISE 5.1 ===================== */
const pieces = (...P) => (x) => { for (const [test, f] of P) if (test(x)) return f(x); return NaN; };
const EX51 = [
  contQ('Ex 5.1', 'Q1', 'Prove that f(x) = 5x − 3 is continuous at x = 0, x = −3 and x = 5', (x) => 5 * x - 3, [-3, 0, 5], [-5, 7, -22, 26], { pre: [{ k: 'fields', q: 'lim = f(c) at each point', f: [{ l: 'f(0)', a: -3 }, { l: 'f(−3)', a: -18 }, { l: 'f(5)', a: 22 }], x: 'Polynomials: limit = value.' }], noPick: true, post: [tfP('So f is continuous at all three points', true, 'lim (5x − 3) = 5c − 3 = f(c).')], grid: 2 }),
  contQ('Ex 5.1', 'Q2', 'Examine the continuity of f(x) = 2x² − 1 at x = 3', (x) => 2 * x * x - 1, [3], [-1, 5, -2, 22], { pre: [{ k: 'num', q: 'lim (x→3) f = f(3) = ?', a: 17 }], noPick: true, post: [tfP('f is continuous at x = 3', true, 'Both are 17.')], grid: 2 }),
  contQ('Ex 5.1', 'Q3 (a)', 'Examine for continuity: f(x) = x − 5', (x) => x - 5, [], [-2, 8, -7, 4], { flags: [0, 5], post: [tfP('f is continuous everywhere', true, 'A polynomial.')] }),
  contQ('Ex 5.1', 'Q3 (b)', 'Examine for continuity: f(x) = 1/(x − 5), x ≠ 5', (x) => 1 / (x - 5), [], [0, 10, -5, 5], { flags: [0, 5], post: [mcq('The gap at x = 5 is', ['outside the domain, so f is continuous', 'a point of discontinuity', 'a removable break', 'a jump'], 'f is continuous at every x ≠ 5, i.e. on its whole domain.')] }),
  contQ('Ex 5.1', 'Q3 (c)', 'Examine for continuity: f(x) = (x² − 25)/(x + 5), x ≠ −5', (x) => (x === -5 ? NaN : (x * x - 25) / (x + 5)), [], [-9, 3, -15, 2], { flags: [-5, 0, 5], post: [mcq('f is', ['continuous on its domain (it equals x − 5 there)', 'discontinuous at −5', 'discontinuous at 5', 'nowhere continuous'], '−5 is not in the domain.')] }),
  contQ('Ex 5.1', 'Q3 (d)', 'Examine for continuity: f(x) = |x − 5|', (x) => abs(x - 5), [5], [0, 10, -1, 5], { flags: [0, 5], post: [tfP('|x − 5| is continuous everywhere', true, 'A modulus of a polynomial.')] }),
  xs('Ex 5.1', 'Q4', 'Prove that f(x) = xⁿ is continuous at x = n, n a positive integer', [mcq('lim (x→n) xⁿ =', ['nⁿ = f(n), so continuous', 'n', '0', 'does not exist'], 'Polynomial: limit = value.')], 'lim xⁿ = nⁿ = f(n)'),
  contQ('Ex 5.1', 'Q5', 'f(x) = x (x ≤ 1), 5 (x > 1). Continuous at x = 0? At 1? At 2?', pieces([(x) => x <= 1, (x) => x], [() => true, () => 5]), [0, 1, 2], [-2, 4, -2, 6], { pq: 'At which of these is f discontinuous?' }),
  contQ('Ex 5.1', 'Q6', 'Find all points of discontinuity: 2x + 3 (x ≤ 2), 2x − 3 (x > 2)', pieces([(x) => x <= 2, (x) => 2 * x + 3], [() => true, (x) => 2 * x - 3]), [2], [-2, 6, -2, 10], { flags: [0, 2, 3] }),
  contQ('Ex 5.1', 'Q7', 'Find all points of discontinuity: |x| + 3 (x ≤ −3), −2x (−3 < x < 3), 6x + 2 (x ≥ 3)', pieces([(x) => x <= -3, (x) => abs(x) + 3], [(x) => x < 3, (x) => -2 * x], [() => true, (x) => 6 * x + 2]), [-3, 3], [-6, 6, -8, 24], { flags: [-3, 0, 3], grid: 2 }),
  contQ('Ex 5.1', 'Q8', 'Find all points of discontinuity: |x|/x (x ≠ 0), 0 (x = 0)', (x) => (x === 0 ? 0 : abs(x) / x), [0], [-4, 4, -2, 2], { flags: [-1, 0, 1] }),
  contQ('Ex 5.1', 'Q9', 'Find all points of discontinuity: x/|x| (x < 0), −1 (x ≥ 0)', (x) => (x < 0 ? x / abs(x) : -1), [0], [-4, 4, -2, 2], { flags: [-1, 0, 1] }),
  contQ('Ex 5.1', 'Q10', 'Find all points of discontinuity: x + 1 (x ≥ 1), x² + 1 (x < 1)', (x) => (x >= 1 ? x + 1 : x * x + 1), [1], [-3, 4, -1, 7], { flags: [0, 1, 2] }),
  contQ('Ex 5.1', 'Q11', 'Find all points of discontinuity: x³ − 3 (x ≤ 2), x² + 1 (x > 2)', (x) => (x <= 2 ? x ** 3 - 3 : x * x + 1), [2], [-2, 4, -8, 14], { flags: [0, 2, 3], grid: 2 }),
  contQ('Ex 5.1', 'Q12', 'Find all points of discontinuity: x¹⁰ − 1 (x ≤ 1), x² (x > 1)', (x) => (x <= 1 ? x ** 10 - 1 : x * x), [1], [-1.3, 2.5, -1.5, 5], { flags: [0, 1, 2] }),
  contQ('Ex 5.1', 'Q13', 'Is f(x) = x + 5 (x ≤ 1), x − 5 (x > 1) a continuous function?', (x) => (x <= 1 ? x + 5 : x - 5), [1], [-4, 6, -6, 9], { flags: [-5, 1, 5] }),
  contQ('Ex 5.1', 'Q14', 'Discuss continuity: 3 (0 ≤ x ≤ 1), 4 (1 < x < 3), 5 (3 ≤ x ≤ 10)', (x) => (x < 0 || x > 10 ? NaN : x <= 1 ? 3 : x < 3 ? 4 : 5), [1, 3], [-1, 11, -1, 7], { flags: [1, 3, 5, 10], grid: 1 }),
  contQ('Ex 5.1', 'Q15', 'Discuss continuity: 2x (x < 0), 0 (0 ≤ x ≤ 1), 4x (x > 1)', (x) => (x < 0 ? 2 * x : x <= 1 ? 0 : 4 * x), [0, 1], [-3, 3, -6, 10], { flags: [-1, 0, 1, 2] }),
  contQ('Ex 5.1', 'Q16', 'Discuss continuity: −2 (x ≤ −1), 2x (−1 < x ≤ 1), 2 (x > 1)', (x) => (x <= -1 ? -2 : x <= 1 ? 2 * x : 2), [-1, 1], [-4, 4, -3, 3], { flags: [-1, 0, 1] }),
  xs('Ex 5.1', 'Q17', 'Find the relation between a and b so that ax + 1 (x ≤ 3), bx + 3 (x > 3) is continuous at x = 3', [mcq('3a + 1 = 3b + 3 gives', ['a = b + 2/3', 'a = b', 'a = b − 2/3', 'a + b = 2/3'], 'Left value = right limit.'), { k: 'num', q: 'If b = 1, then a = ?', a: 5 / 3, show: '5/3', x: 'a = 1 + 2/3 = 5/3.' }], 'a = b + 2/3', { scene: 'pw', setup: (W) => pwSet(W, (x) => (x <= 3 ? (5 / 3) * x + 1 : x + 3), [3], [-1, 6, -1, 10], { cap: 'shown with b = 1, a = 5/3' }) }),
  xs('Ex 5.1', 'Q18', 'For what λ is λ(x² − 2x) (x ≤ 0), 4x + 1 (x > 0) continuous at x = 0? What about x = 1?', [
    { k: 'fields', q: 'At x = 0', f: [{ l: 'left limit (any λ)', a: 0 }, { l: 'right limit', a: 1 }], x: '0 ≠ 1.' },
    mcq('So', ['no λ makes f continuous at 0; f is continuous at 1 for every λ', 'λ = 1', 'λ = −1', 'λ = 0'], 'At x = 1 only the 4x + 1 piece matters.'),
  ], 'No value of λ works at 0; continuous at 1 for every λ', { scene: 'pw', setup: (W) => pwSet(W, (x) => (x <= 0 ? 1 * (x * x - 2 * x) : 4 * x + 1), [0], [-2, 2, -2, 9], { cap: 'shown with λ = 1' }) }),
  contQ('Ex 5.1', 'Q19', 'Show that g(x) = x − [x] is discontinuous at all integral points', (x) => x - fl(x), [-2, -1, 0, 1, 2, 3], [-2.5, 3.5, -1, 2], { flags: [-2, -1, -0.5, 0, 0.5, 1, 2, 3], pq: 'Tap-pick the breaks shown' }),
  contQ('Ex 5.1', 'Q20', 'Is f(x) = x² − sin x + 5 continuous at x = π?', (x) => x * x - sin(x) + 5, [PI], [0, 5, -1, 30], { pre: [{ k: 'num', q: 'f(π) = π² + 5 = ? (2 decimals)', a: PI * PI + 5, tol: 0.011, show: fmtN(PI * PI + 5, 3) }], noPick: true, post: [tfP('Continuous at π', true, 'Sum of continuous functions.')], grid: 2 }),
  contQ('Ex 5.1', 'Q21 (a)', 'Discuss the continuity of sin x + cos x', (x) => sin(x) + cos(x), [], [-7, 7, -2, 2], { noPick: true, post: [tfP('Continuous everywhere', true, 'Sum of continuous functions.')] }),
  contQ('Ex 5.1', 'Q21 (b)', 'Discuss the continuity of sin x − cos x', (x) => sin(x) - cos(x), [], [-7, 7, -2, 2], { noPick: true, post: [tfP('Continuous everywhere', true, 'Difference of continuous functions.')] }),
  contQ('Ex 5.1', 'Q21 (c)', 'Discuss the continuity of sin x · cos x', (x) => sin(x) * cos(x), [], [-7, 7, -1, 1], { noPick: true, post: [tfP('Continuous everywhere', true, 'Product of continuous functions.')] }),
  xs('Ex 5.1', 'Q22', 'Discuss the continuity of the cosine, cosecant, secant and cotangent functions', [mcq('cos is continuous everywhere. cosec, sec, cot are', ['continuous on their domains (where sin or cos ≠ 0)', 'continuous everywhere', 'nowhere continuous', 'continuous only at 0'], 'Reciprocals/quotients of continuous functions.')], 'cos on ℝ; cosec, sec, cot on their domains', { scene: 'pw', setup: (W) => pwSet(W, (x) => 1 / sin(x), [], [-7, 7, -4, 4], { cap: 'cosec x' }) }),
  contQ('Ex 5.1', 'Q23', 'Find all points of discontinuity: sin x / x (x < 0), x + 1 (x ≥ 0)', (x) => (x < 0 ? sin(x) / x : x + 1), [0], [-8, 3, -0.6, 4], { flags: [-PI, 0, 1] }),
  contQ('Ex 5.1', 'Q24', 'Is x² sin(1/x) (x ≠ 0), 0 (x = 0) continuous?', (x) => (x === 0 ? 0 : x * x * sin(1 / x)), [0], [-0.6, 0.6, -0.3, 0.3], { flags: [0], post: [sayP('Near 0, −x² ≤ x² sin(1/x) ≤ x² squeezes the limit to 0 = f(0).')] }),
  contQ('Ex 5.1', 'Q25', 'Examine continuity: sin x − cos x (x ≠ 0), −1 (x = 0)', (x) => (x === 0 ? -1 : sin(x) - cos(x)), [0], [-4, 4, -2, 2], { flags: [0] }),
  kQ('Ex 5.1', 'Q26', 'Find k: k cos x/(π − 2x) (x ≠ π/2), 3 (x = π/2) is continuous at π/2', (x, k) => (x === PI / 2 ? 3 : (k * cos(x)) / (PI - 2 * x)), PI / 2, 6, [0, 3.1, -1, 6], { cs: 'π/2', lo: 0, hi: 10, x: 'The limit is k/2, so k/2 = 3.' }),
  kQ('Ex 5.1', 'Q27', 'Find k: kx² (x ≤ 2), 3 (x > 2) is continuous at 2', (x, k) => (x <= 2 ? k * x * x : 3), 2, 0.75, [-1, 4, -1, 6], { lo: 0, hi: 2, step: 0.05, show: '3/4', x: '4k = 3.' }),
  kQ('Ex 5.1', 'Q28', 'Find k: kx + 1 (x ≤ π), cos x (x > π) is continuous at π', (x, k) => (x <= PI ? k * x + 1 : cos(x)), PI, -2 / PI, [0, 6, -3, 3], { cs: 'π', lo: -1, hi: 1, step: 0.01, show: '−2/π', keys: 'π', x: 'kπ + 1 = −1.', k0: 0.3 }),
  kQ('Ex 5.1', 'Q29', 'Find k: kx + 1 (x ≤ 5), 3x − 5 (x > 5) is continuous at 5', (x, k) => (x <= 5 ? k * x + 1 : 3 * x - 5), 5, 1.8, [0, 8, -2, 20], { lo: 0, hi: 4, step: 0.1, show: '9/5', x: '5k + 1 = 10.' }),
  xs('Ex 5.1', 'Q30', 'Find a, b so that 5 (x ≤ 2), ax + b (2 < x < 10), 21 (x ≥ 10) is continuous', [{ k: 'fields', q: '2a + b = 5 and 10a + b = 21', f: [{ l: 'a', a: 2 }, { l: 'b', a: 1 }], x: 'a = 2, b = 1.', act: async (W) => { await penRun(W); } }], 'a = 2, b = 1', { scene: 'pw', setup: (W) => pwSet(W, (x) => (x <= 2 ? 5 : x < 10 ? 2 * x + 1 : 21), [2, 10], [0, 12, -2, 25], { grid: 2 }) }),
  contQ('Ex 5.1', 'Q31', 'Show that f(x) = cos(x²) is continuous', (x) => cos(x * x), [], [-4, 4, -1.5, 1.5], { noPick: true, post: [mcq('Because it is', ['cos composed with x² (both continuous)', 'a polynomial', 'periodic', 'bounded'], 'Composition of continuous functions.')] }),
  contQ('Ex 5.1', 'Q32', 'Show that f(x) = |cos x| is continuous', (x) => abs(cos(x)), [], [-7, 7, -0.5, 1.5], { noPick: true, post: [mcq('Because it is', ['|·| composed with cos', 'differentiable', 'even', 'a polynomial'], 'Composition of continuous functions.')] }),
  contQ('Ex 5.1', 'Q33', 'Examine that sin |x| is continuous', (x) => sin(abs(x)), [0], [-8, 8, -1.5, 1.5], { flags: [0], post: [sayP('sin ∘ |x|: both continuous.')] }),
  contQ('Ex 5.1', 'Q34', 'Find all points of discontinuity of f(x) = |x| − |x + 1|', (x) => abs(x) - abs(x + 1), [-1, 0], [-4, 3, -2, 2], { flags: [-1, 0, 1] }),
];

/* ===================== EXERCISE 5.2 ===================== */
const ka = 2, kb = 1, kc = 1, kd = 0.5;
const EX52 = [
  dQ('Ex 5.2', 'Q1', 'Differentiate sin(x² + 5)', (x) => sin(x * x + 5), (x) => 2 * x * cos(x * x + 5), ['2x cos(x² + 5)', 'cos(x² + 5)', '2x sin(x² + 5)', '−2x cos(x² + 5)'], 1, { view: [-2, 2] }),
  dQ('Ex 5.2', 'Q2', 'Differentiate cos(sin x)', (x) => cos(sin(x)), (x) => -sin(sin(x)) * cos(x), ['−sin(sin x) cos x', 'sin(sin x) cos x', '−sin(cos x)', '−cos(sin x) sin x'], 1, { view: [-3, 3] }),
  dQ('Ex 5.2', 'Q3', 'Differentiate sin(ax + b)', (x) => sin(ka * x + kb), (x) => ka * cos(ka * x + kb), ['a cos(ax + b)', 'cos(ax + b)', '−a cos(ax + b)', 'a sin(ax + b)'], 0.5, { cap: 'graph with a = 2, b = 1', view: [-2, 2] }),
  dQ('Ex 5.2', 'Q4', 'Differentiate sec(tan √x)', (x) => sec(tan(sqrt(x))), (x) => sec(tan(sqrt(x))) * tan(tan(sqrt(x))) * sec(sqrt(x)) ** 2 / (2 * sqrt(x)), ['sec(tan√x) tan(tan√x) sec²√x / (2√x)', 'sec(tan√x) tan(tan√x)', 'sec²(tan√x) / (2√x)', 'tan(tan√x) sec²√x'], 0.5, { view: [0.05, 1.1], y: [0.8, 3] }),
  dQ('Ex 5.2', 'Q5', 'Differentiate sin(ax + b)/cos(cx + d)', (x) => sin(ka * x + kb) / cos(kc * x + kd), (x) => (ka * cos(ka * x + kb) * cos(kc * x + kd) + kc * sin(ka * x + kb) * sin(kc * x + kd)) / cos(kc * x + kd) ** 2, ['[a cos(ax+b) cos(cx+d) + c sin(ax+b) sin(cx+d)] / cos²(cx+d)', '[a cos(ax+b) cos(cx+d) − c sin(ax+b) sin(cx+d)] / cos²(cx+d)', 'a cos(ax+b) / (−c sin(cx+d))', 'a cos(ax+b) sec(cx+d)'], 0, { cap: 'graph with a = 2, b = 1, c = 1, d = 0.5', view: [-1.5, 0.9], y: [-4, 4] }),
  dQ('Ex 5.2', 'Q6', 'Differentiate cos x³ · sin²(x⁵)', (x) => cos(x ** 3) * sin(x ** 5) ** 2, (x) => 10 * x ** 4 * sin(x ** 5) * cos(x ** 5) * cos(x ** 3) - 3 * x * x * sin(x ** 3) * sin(x ** 5) ** 2, ['10x⁴ sin x⁵ cos x⁵ cos x³ − 3x² sin x³ sin² x⁵', '10x⁴ sin x⁵ cos x³ + 3x² sin x³', '−3x² sin x³ · 10x⁴ sin x⁵ cos x⁵', '2 sin x⁵ cos x⁵ cos x³'], 0.9, { view: [0, 1.2], snap: 0.05, x0s: '0.9' }),
  dQ('Ex 5.2', 'Q7', 'Differentiate 2√(cot(x²))', (x) => 2 * sqrt(cot(x * x)), (x) => (-2 * x * csc(x * x) ** 2) / sqrt(cot(x * x)), ['−2x cosec²(x²) / √(cot x²)  (= −2√2 x / (sin x² √(sin 2x²)))', 'cosec²(x²) / √(cot x²)', '−2x cosec²(x²)', '−4x cot(x²)'], 0.8, { view: [0.2, 1.2], y: [0, 6] }),
  dQ('Ex 5.2', 'Q8', 'Differentiate cos(√x)', (x) => cos(sqrt(x)), (x) => -sin(sqrt(x)) / (2 * sqrt(x)), ['−sin√x / (2√x)', 'sin√x / (2√x)', '−sin√x', '−cos√x / (2√x)'], 1, { view: [0.05, 5] }),
  xs('Ex 5.2', 'Q9', 'Prove that f(x) = |x − 1| is not differentiable at x = 1', [
    { k: 'task', q: 'Shrink h to below 0.1 and compare the two slopes', pre: async (W) => { W.hs = slider('h', 0.01, 1.5, 0.01, 1.5, (v) => fmtN(v, 2), (v) => (W.lr.h = v)); }, check: (W) => W.lr.h < 0.1, auto: (W) => { W.lr.h = 0.05; } },
    { k: 'fields', q: 'Left and right derivatives at x = 1', f: [{ l: 'left', a: -1 }, { l: 'right', a: 1 }], x: '−1 ≠ 1: not differentiable (but continuous).' },
  ], 'f′(1⁻) = −1 ≠ 1 = f′(1⁺)', { scene: 'pw', setup: (W) => { pwSet(W, (x) => abs(x - 1), [], [-2, 4, -1, 3]); W.lr = { c: 1, h: 1.5 }; } }),
  xs('Ex 5.2', 'Q10', 'Prove that [x], 0 < x < 3, is not differentiable at x = 1 and x = 2', [
    { k: 'run', run: async (W) => { await penRun(W); } },
    mcq('[x] is not differentiable at 1 and 2 because', ['it is not even continuous there', 'it has a kink', 'its slope is infinite', 'it is undefined there'], 'Differentiable ⇒ continuous, and [x] jumps at 1 and 2.'),
    { k: 'num', q: 'Right-hand derivative at 1: lim (h→0⁺) ([1 + h] − [1])/h = ?', a: 0, x: '0, but the left-hand one is lim (0 − 1)/(−h) = +∞: they cannot match.' },
  ], 'Not continuous at 1 and 2, hence not differentiable', { scene: 'pw', setup: (W) => pwSet(W, (x) => (x <= 0 || x >= 3 ? NaN : fl(x)), [1, 2], [-0.5, 3.5, -1, 3]) }),
];

/* ===================== EXERCISE 5.3 ===================== */
const pt = (G, x, y0) => [x, impSnap(G, x, y0)];
const G7 = (x, y) => sin(y) ** 2 + cos(x * y) - (sin(1) ** 2 + cos(0.5));
const G13 = (x, y) => x * log(y) - y * log(x), G15 = (x, y) => x * y - exp(x - y), G16 = (x, y) => cos(y) - x * cos(1 + y);
const EX53 = [
  impQ('Ex 5.3', 'Q1', 'Find dy/dx: 2x + 3y = sin x', (x, y) => 2 * x + 3 * y - sin(x), (x, y) => (cos(x) - 2) / 3, ['(cos x − 2)/3', '(2 − cos x)/3', 'cos x − 2', '(cos x + 2)/3'], pt((x, y) => 2 * x + 3 * y - sin(x), 1, 0), { view: [-4, 4, -3, 3] }),
  impQ('Ex 5.3', 'Q2', 'Find dy/dx: 2x + 3y = sin y', (x, y) => 2 * x + 3 * y - sin(y), (x, y) => 2 / (cos(y) - 3), ['2/(cos y − 3)', '−2/(cos y − 3)', '2/(3 − cos y)', 'cos y/3'], pt((x, y) => 2 * x + 3 * y - sin(y), 1, -1), { view: [-4, 4, -3, 3] }),
  impQ('Ex 5.3', 'Q3', 'Find dy/dx: ax + by² = cos y', (x, y) => x + y * y - cos(y), (x, y) => -1 / (2 * y + sin(y)), ['−a/(2by + sin y)', 'a/(2by + sin y)', '−a/(2by − sin y)', '−a/(2by)'], pt((x, y) => x + y * y - cos(y), 0, 0.8), { view: [-4, 2, -2.5, 2.5], mq: 'dy/dx = ? (graph with a = b = 1)' }),
  impQ('Ex 5.3', 'Q4', 'Find dy/dx: xy + y² = tan x + y', (x, y) => x * y + y * y - tan(x) - y, (x, y) => (sec(x) ** 2 - y) / (x + 2 * y - 1), ['(sec²x − y)/(x + 2y − 1)', '(sec²x + y)/(x + 2y − 1)', '(sec²x − y)/(x + 2y)', 'sec²x/(x + 2y − 1)'], pt((x, y) => x * y + y * y - tan(x) - y, 0.5, 1.2), { view: [-1.4, 1.4, -2, 2.5], snap: 0.05 }),
  impQ('Ex 5.3', 'Q5', 'Find dy/dx: x² + xy + y² = 100', (x, y) => x * x + x * y + y * y - 100, (x, y) => -(2 * x + y) / (x + 2 * y), ['−(2x + y)/(x + 2y)', '(2x + y)/(x + 2y)', '−(x + 2y)/(2x + y)', '−2x/(x + 2y)'], pt((x, y) => x * x + x * y + y * y - 100, 2, 8), { view: [-13, 13, -12, 12], snap: 0.5 }),
  impQ('Ex 5.3', 'Q6', 'Find dy/dx: x³ + x²y + xy² + y³ = 81', (x, y) => x ** 3 + x * x * y + x * y * y + y ** 3 - 81, (x, y) => -(3 * x * x + 2 * x * y + y * y) / (x * x + 2 * x * y + 3 * y * y), ['−(3x² + 2xy + y²)/(x² + 2xy + 3y²)', '(3x² + 2xy + y²)/(x² + 2xy + 3y²)', '−(x² + 2xy + 3y²)/(3x² + 2xy + y²)', '−3x²/(3y²)'], pt((x, y) => x ** 3 + x * x * y + x * y * y + y ** 3 - 81, 2, 3), { view: [-3, 7, -3, 7], snap: 0.5 }),
  impQ('Ex 5.3', 'Q7', 'Find dy/dx: sin²y + cos xy = κ', G7, (x, y) => (y * sin(x * y)) / (sin(2 * y) - x * sin(x * y)), ['y sin xy / (sin 2y − x sin xy)', '−y sin xy / (sin 2y − x sin xy)', 'y sin xy / sin 2y', 'sin xy / (sin 2y − x)'], [0.5, 1], { view: [-1.5, 2.5, -0.5, 2.5], mq: 'dy/dx = ? (graph with κ chosen so (0.5, 1) is on it)' }),
  impQ('Ex 5.3', 'Q8', 'Find dy/dx: sin²x + cos²y = 1', (x, y) => sin(x) ** 2 + cos(y) ** 2 - 1, (x, y) => sin(2 * x) / sin(2 * y), ['sin 2x / sin 2y', '−sin 2x / sin 2y', 'sin 2y / sin 2x', 'cos 2x / cos 2y'], pt((x, y) => sin(x) ** 2 + cos(y) ** 2 - 1, 0.4, 0.5), { view: [-1.5, 1.5, -1.5, 1.5] }),
  dQ('Ex 5.3', 'Q9', 'Find dy/dx: y = sin⁻¹(2x/(1 + x²))', (x) => asin((2 * x) / (1 + x * x)), (x) => 2 / (1 + x * x), ['2/(1 + x²)  (for |x| < 1)', '−2/(1 + x²)', '1/(1 + x²)', '2/√(1 − x²)'], 0.5, { view: [-0.95, 0.95], steps: [mcq('Put x = tan θ: 2x/(1 + x²) = sin 2θ, so y =', ['2 tan⁻¹ x', 'tan⁻¹ x', '2 sin⁻¹ x', 'π − 2 tan⁻¹ x'], 'For |x| < 1, 2θ is in the principal range.')] }),
  dQ('Ex 5.3', 'Q10', 'Find dy/dx: y = tan⁻¹((3x − x³)/(1 − 3x²)), −1/√3 < x < 1/√3', (x) => atan((3 * x - x ** 3) / (1 - 3 * x * x)), (x) => 3 / (1 + x * x), ['3/(1 + x²)', '1/(1 + x²)', '−3/(1 + x²)', '3x²/(1 + x²)'], 0.3, { view: [-0.55, 0.55], steps: [mcq('x = tan θ turns it into tan⁻¹(tan 3θ) =', ['3 tan⁻¹ x', 'tan⁻¹ 3x', '3x', 'tan⁻¹ x'], 'tan 3θ = (3t − t³)/(1 − 3t²).')] }),
  dQ('Ex 5.3', 'Q11', 'Find dy/dx: y = cos⁻¹((1 − x²)/(1 + x²)), 0 < x < 1', (x) => acos((1 - x * x) / (1 + x * x)), (x) => 2 / (1 + x * x), ['2/(1 + x²)', '−2/(1 + x²)', '1/(1 + x²)', '2x/(1 + x²)'], 0.5, { view: [0.02, 0.98], steps: [mcq('x = tan θ: (1 − x²)/(1 + x²) = cos 2θ, so y =', ['2 tan⁻¹ x', 'tan⁻¹ x', '−2 tan⁻¹ x', 'π/2 − tan⁻¹ x'], '2θ ∈ (0, π/2).')] }),
  dQ('Ex 5.3', 'Q12', 'Find dy/dx: y = sin⁻¹((1 − x²)/(1 + x²)), 0 < x < 1', (x) => asin((1 - x * x) / (1 + x * x)), (x) => -2 / (1 + x * x), ['−2/(1 + x²)', '2/(1 + x²)', '−1/(1 + x²)', '−2/√(1 − x²)'], 0.5, { view: [0.02, 0.98], steps: [mcq('sin⁻¹(cos 2θ) = π/2 − 2θ, so y =', ['π/2 − 2 tan⁻¹ x', '2 tan⁻¹ x', 'π − 2 tan⁻¹ x', 'tan⁻¹ x'], 'With x = tan θ.')] }),
  dQ('Ex 5.3', 'Q13', 'Find dy/dx: y = cos⁻¹(2x/(1 + x²)), −1 < x < 1', (x) => acos((2 * x) / (1 + x * x)), (x) => -2 / (1 + x * x), ['−2/(1 + x²)', '2/(1 + x²)', '−2x/(1 + x²)', '−1/(1 + x²)'], 0.5, { view: [-0.95, 0.95], steps: [mcq('cos⁻¹(sin 2θ) = π/2 − 2θ, so y =', ['π/2 − 2 tan⁻¹ x', '2 tan⁻¹ x', 'π/2 + 2 tan⁻¹ x', '2 cot⁻¹ x'], 'With x = tan θ.')] }),
  dQ('Ex 5.3', 'Q14', 'Find dy/dx: y = sin⁻¹(2x√(1 − x²)), −1/√2 < x < 1/√2', (x) => asin(2 * x * sqrt(1 - x * x)), (x) => 2 / sqrt(1 - x * x), ['2/√(1 − x²)', '1/√(1 − x²)', '−2/√(1 − x²)', '2x/√(1 − x²)'], 0.4, { view: [-0.7, 0.7], steps: [mcq('x = sin θ: 2x√(1 − x²) = sin 2θ, so y =', ['2 sin⁻¹ x', 'sin⁻¹ 2x', '2 cos⁻¹ x', 'sin⁻¹ x'], '2θ ∈ (−π/2, π/2).')] }),
  dQ('Ex 5.3', 'Q15', 'Find dy/dx: y = sec⁻¹(1/(2x² − 1)), 0 < x < 1/√2', (x) => acos(2 * x * x - 1), (x) => -2 / sqrt(1 - x * x), ['−2/√(1 − x²)', '2/√(1 − x²)', '−1/√(1 − x²)', '−2x/√(1 − x²)'], 0.4, { view: [0.02, 0.7], steps: [mcq('sec⁻¹(1/u) = cos⁻¹ u, and x = cos θ gives cos⁻¹(cos 2θ) =', ['2 cos⁻¹ x', 'cos⁻¹ x', '2 sin⁻¹ x', 'π − 2 cos⁻¹ x'], '2θ ∈ (π/2, π) ⊂ [0, π].')] }),
];

/* ===================== EXERCISE 5.4 ===================== */
const EX54 = [
  dQ('Ex 5.4', 'Q1', 'Differentiate eˣ/sin x', (x) => exp(x) / sin(x), (x) => (exp(x) * (sin(x) - cos(x))) / sin(x) ** 2, ['eˣ(sin x − cos x)/sin²x', 'eˣ(sin x + cos x)/sin²x', 'eˣ/cos x', 'eˣ cot x'], 1.2, { view: [0.4, 2.8], y: [0, 20] }),
  dQ('Ex 5.4', 'Q2', 'Differentiate e^(sin⁻¹ x)', (x) => exp(asin(x)), (x) => exp(asin(x)) / sqrt(1 - x * x), ['e^(sin⁻¹x)/√(1 − x²)', 'e^(sin⁻¹x)', 'e^(cos⁻¹x)/√(1 − x²)', '−e^(sin⁻¹x)/√(1 − x²)'], 0.5, { view: [-0.95, 0.95] }),
  dQ('Ex 5.4', 'Q3', 'Differentiate e^(x³)', (x) => exp(x ** 3), (x) => 3 * x * x * exp(x ** 3), ['3x² e^(x³)', 'e^(x³)', 'x³ e^(x³ − 1)', '3x e^(x³)'], 0.8, { view: [-1.2, 1.2], y: [-0.5, 6] }),
  dQ('Ex 5.4', 'Q4', 'Differentiate sin(tan⁻¹ e⁻ˣ)', (x) => sin(atan(exp(-x))), (x) => (-exp(-x) * cos(atan(exp(-x)))) / (1 + exp(-2 * x)), ['−e⁻ˣ cos(tan⁻¹e⁻ˣ)/(1 + e⁻²ˣ)', 'e⁻ˣ cos(tan⁻¹e⁻ˣ)/(1 + e⁻²ˣ)', 'cos(tan⁻¹e⁻ˣ)', '−e⁻ˣ/(1 + e⁻²ˣ)'], 0, { view: [-2.5, 2.5] }),
  dQ('Ex 5.4', 'Q5', 'Differentiate log(cos eˣ)', (x) => log(cos(exp(x))), (x) => -exp(x) * tan(exp(x)), ['−eˣ tan eˣ', 'eˣ tan eˣ', '−tan eˣ', '1/cos eˣ'], 0, { view: [-2, 0.4] }),
  dQ('Ex 5.4', 'Q6', 'Differentiate eˣ + e^(x²) + … + e^(x⁵)', (x) => [1, 2, 3, 4, 5].reduce((s, k) => s + exp(x ** k), 0), (x) => [1, 2, 3, 4, 5].reduce((s, k) => s + k * x ** (k - 1) * exp(x ** k), 0), ['eˣ + 2x e^(x²) + 3x² e^(x³) + 4x³ e^(x⁴) + 5x⁴ e^(x⁵)', 'eˣ + e^(x²) + … + e^(x⁵)', '15 x⁴ eˣ', 'eˣ(1 + 2x + 3x² + 4x³ + 5x⁴)'], 0.5, { view: [-0.6, 1.1] }),
  dQ('Ex 5.4', 'Q7', 'Differentiate √(e^(√x)), x > 0', (x) => sqrt(exp(sqrt(x))), (x) => exp(sqrt(x) / 2) / (4 * sqrt(x)), ['e^(√x/2)/(4√x)  (= e^√x / (4√(x e^√x)))', 'e^(√x/2)/(2√x)', 'e^(√x)/(2√x)', '½ e^(√x/2)'], 1, { view: [0.05, 4] }),
  dQ('Ex 5.4', 'Q8', 'Differentiate log(log x), x > 1', (x) => log(log(x)), (x) => 1 / (x * log(x)), ['1/(x log x)', '1/log x', 'log x / x', '1/x²'], 2, { view: [1.1, 5] }),
  dQ('Ex 5.4', 'Q9', 'Differentiate cos x / log x, x > 0', (x) => cos(x) / log(x), (x) => -(x * log(x) * sin(x) + cos(x)) / (x * log(x) ** 2), ['−(x log x sin x + cos x)/(x (log x)²)', '(x log x sin x + cos x)/(x (log x)²)', '−sin x · x', '−sin x / log x'], 2, { view: [1.2, 5], y: [-3, 1] }),
  dQ('Ex 5.4', 'Q10', 'Differentiate cos(log x + eˣ), x > 0', (x) => cos(log(x) + exp(x)), (x) => -sin(log(x) + exp(x)) * (1 / x + exp(x)), ['−sin(log x + eˣ)(1/x + eˣ)', 'sin(log x + eˣ)(1/x + eˣ)', '−sin(log x + eˣ)', '−(1/x + eˣ) cos(log x + eˣ)'], 0.5, { view: [0.1, 1.3] }),
];

/* ===================== EXERCISE 5.5 ===================== */
const f6a = (x) => (x + 1 / x) ** x, f6b = (x) => x ** (1 + 1 / x);
const f11a = (x) => (x * cos(x)) ** x, f11b = (x) => (x * sin(x)) ** (1 / x);
const G12 = (x, y) => x ** y + y ** x - 1;
const p17 = (x) => (x * x - 5 * x + 8) * (x ** 3 + 7 * x + 9), dp17 = (x) => 5 * x ** 4 - 20 * x ** 3 + 45 * x * x - 52 * x + 11;
const EX55 = [
  dQ('Ex 5.5', 'Q1', 'Differentiate cos x · cos 2x · cos 3x', (x) => cos(x) * cos(2 * x) * cos(3 * x), (x) => -cos(x) * cos(2 * x) * cos(3 * x) * (tan(x) + 2 * tan(2 * x) + 3 * tan(3 * x)), ['−y (tan x + 2 tan 2x + 3 tan 3x)', 'y (tan x + 2 tan 2x + 3 tan 3x)', '−sin x sin 2x sin 3x', '−6 sin x sin 2x sin 3x'], 0.3, { view: [-0.5, 0.5] }),
  dQ('Ex 5.5', 'Q2', 'Differentiate √((x − 1)(x − 2)/((x − 3)(x − 4)(x − 5)))', (x) => sqrt(((x - 1) * (x - 2)) / ((x - 3) * (x - 4) * (x - 5))), (x) => (sqrt(((x - 1) * (x - 2)) / ((x - 3) * (x - 4) * (x - 5))) / 2) * (1 / (x - 1) + 1 / (x - 2) - 1 / (x - 3) - 1 / (x - 4) - 1 / (x - 5)), ['(y/2)[1/(x−1) + 1/(x−2) − 1/(x−3) − 1/(x−4) − 1/(x−5)]', 'y[1/(x−1) + 1/(x−2) − 1/(x−3) − 1/(x−4) − 1/(x−5)]', '(y/2)[1/(x−1) + 1/(x−2) + 1/(x−3) + 1/(x−4) + 1/(x−5)]', '½√(…)'], 6, { view: [5.3, 9] }),
  dQ('Ex 5.5', 'Q3', 'Differentiate (log x)^(cos x)', (x) => log(x) ** cos(x), (x) => log(x) ** cos(x) * (cos(x) / (x * log(x)) - sin(x) * log(log(x))), ['(log x)^(cos x) [cos x/(x log x) − sin x log(log x)]', '(log x)^(cos x) [cos x/(x log x) + sin x log(log x)]', 'cos x (log x)^(cos x − 1)/x', '−sin x log(log x)'], 2, { view: [1.2, 4] }),
  dQ('Ex 5.5', 'Q4', 'Differentiate xˣ − 2^(sin x)', (x) => x ** x - 2 ** sin(x), (x) => x ** x * (1 + log(x)) - 2 ** sin(x) * cos(x) * log(2), ['xˣ(1 + log x) − 2^(sin x) cos x log 2', 'xˣ log x − 2^(sin x) log 2', 'x·xˣ⁻¹ − sin x 2^(sin x − 1)', 'xˣ(1 + log x) + 2^(sin x) cos x log 2'], 1.5, { view: [0.3, 2.3] }),
  dQ('Ex 5.5', 'Q5', 'Differentiate (x + 3)²(x + 4)³(x + 5)⁴', (x) => (x + 3) ** 2 * (x + 4) ** 3 * (x + 5) ** 4, (x) => (x + 3) ** 2 * (x + 4) ** 3 * (x + 5) ** 4 * (2 / (x + 3) + 3 / (x + 4) + 4 / (x + 5)), ['y[2/(x + 3) + 3/(x + 4) + 4/(x + 5)]', 'y[2/(x + 3) · 3/(x + 4) · 4/(x + 5)]', '24(x + 3)(x + 4)²(x + 5)³', 'y[2(x + 3) + 3(x + 4) + 4(x + 5)]'], -3.5, { view: [-4.3, -2.7], y: [-1.5, 1] }),
  dQ('Ex 5.5', 'Q6', 'Differentiate (x + 1/x)ˣ + x^(1 + 1/x)', (x) => f6a(x) + f6b(x), (x) => f6a(x) * ((x * x - 1) / (x * x + 1) + log(x + 1 / x)) + f6b(x) * ((x + 1 - log(x)) / (x * x)), ['(x + 1/x)ˣ[(x² − 1)/(x² + 1) + log(x + 1/x)] + x^(1 + 1/x)(x + 1 − log x)/x²', '(x + 1/x)ˣ log(x + 1/x) + x^(1/x)', 'x(x + 1/x)ˣ⁻¹(1 − 1/x²) + (1 + 1/x)x^(1/x)', '(x + 1/x)ˣ[(x² − 1)/(x² + 1)] + x^(1 + 1/x) log x'], 1.5, { view: [0.4, 2.5] }),
  dQ('Ex 5.5', 'Q7', 'Differentiate (log x)ˣ + x^(log x)', (x) => log(x) ** x + x ** log(x), (x) => log(x) ** x * (1 / log(x) + log(log(x))) + x ** log(x) * ((2 * log(x)) / x), ['(log x)ˣ[1/log x + log(log x)] + x^(log x) · 2 log x / x', '(log x)ˣ log(log x) + x^(log x) log x', 'x (log x)ˣ⁻¹/x + log x · x^(log x − 1)', '(log x)ˣ/log x + 2 log x'], 2, { view: [1.3, 3.5] }),
  dQ('Ex 5.5', 'Q8', 'Differentiate (sin x)ˣ + sin⁻¹√x', (x) => sin(x) ** x + asin(sqrt(x)), (x) => sin(x) ** x * (x / tan(x) + log(sin(x))) + 1 / (2 * sqrt(x - x * x)), ['(sin x)ˣ(x cot x + log sin x) + 1/(2√(x − x²))', '(sin x)ˣ log sin x + 1/√(1 − x)', 'x(sin x)ˣ⁻¹ cos x + 1/(2√x)', '(sin x)ˣ(x cot x − log sin x) + 1/(2√(x − x²))'], 0.5, { view: [0.1, 0.95] }),
  dQ('Ex 5.5', 'Q9', 'Differentiate x^(sin x) + (sin x)^(cos x)', (x) => x ** sin(x) + sin(x) ** cos(x), (x) => x ** sin(x) * (cos(x) * log(x) + sin(x) / x) + sin(x) ** cos(x) * (cos(x) / tan(x) - sin(x) * log(sin(x))), ['x^(sin x)(cos x log x + sin x/x) + (sin x)^(cos x)(cos x cot x − sin x log sin x)', 'x^(sin x) cos x log x + (sin x)^(cos x) cos x cot x', 'sin x · x^(sin x − 1) + cos x (sin x)^(cos x − 1)', 'x^(sin x)(cos x log x − sin x/x) + (sin x)^(cos x)(cos x cot x + sin x log sin x)'], 1, { view: [0.3, 2.5] }),
  dQ('Ex 5.5', 'Q10', 'Differentiate x^(x cos x) + (x² + 1)/(x² − 1)', (x) => x ** (x * cos(x)) + (x * x + 1) / (x * x - 1), (x) => x ** (x * cos(x)) * (cos(x) * (1 + log(x)) - x * sin(x) * log(x)) - (4 * x) / (x * x - 1) ** 2, ['x^(x cos x)[cos x(1 + log x) − x sin x log x] − 4x/(x² − 1)²', 'x^(x cos x)[cos x log x] + 4x/(x² − 1)²', 'x cos x · x^(x cos x − 1) − 4x/(x² − 1)²', 'x^(x cos x)[cos x(1 + log x) + x sin x log x] − 4x/(x² − 1)²'], 1.6, { view: [1.2, 2.6] }),
  dQ('Ex 5.5', 'Q11', 'Differentiate (x cos x)ˣ + (x sin x)^(1/x)', (x) => f11a(x) + f11b(x), (x) => f11a(x) * (1 - x * tan(x) + log(x * cos(x))) + f11b(x) * ((x / tan(x) + 1 - log(x * sin(x))) / (x * x)), ['(x cos x)ˣ[1 − x tan x + log(x cos x)] + (x sin x)^(1/x)[(x cot x + 1 − log(x sin x))/x²]', '(x cos x)ˣ log(x cos x) + (x sin x)^(1/x) log(x sin x)', '(x cos x)ˣ[1 + x tan x + log(x cos x)] + (x sin x)^(1/x)(x cot x + 1)/x²', 'x(x cos x)ˣ⁻¹ + (1/x)(x sin x)^(1/x − 1)'], 0.8, { view: [0.3, 1.3] }),
  xs('Ex 5.5', 'Q12', 'Find dy/dx: xʸ + yˣ = 1', [
    mcq('Differentiating u = xʸ and v = yˣ (as in Example 30) gives', ['dy/dx = −(y xʸ⁻¹ + yˣ log y)/(xʸ log x + x yˣ⁻¹)', 'dy/dx = (y xʸ⁻¹ + yˣ log y)/(xʸ log x + x yˣ⁻¹)', 'dy/dx = −y/x', 'dy/dx = −(xʸ log x)/(yˣ log y)'], 'u′ + v′ = 0, then collect dy/dx.'),
    { k: 'num', q: 'Kimmy’s check: at x = y = 0.5, xʸ + yˣ = ? (2 decimals)', a: 2 * 0.5 ** 0.5, tol: 0.011, show: fmtN(2 * sqrt(0.5), 3), x: 'Already more than 1.' },
    sayP('For x, y > 0 the sum xʸ + yˣ is always greater than 1, so this curve has no actual points. The answer is the formal derivative the book asks for.'),
  ], 'dy/dx = −(y xʸ⁻¹ + yˣ log y)/(xʸ log x + x yˣ⁻¹)'),
  impQ('Ex 5.5', 'Q13', 'Find dy/dx: yˣ = xʸ', G13, (x, y) => (y * (y - x * log(y))) / (x * (x - y * log(x))), ['y(y − x log y)/(x(x − y log x))', 'x(x − y log x)/(y(y − x log y))', 'y log y / (x log x)', '−y(y − x log y)/(x(x − y log x))'], [2, 4], { view: [1, 6, 1.2, 8], start: 2.3, snap: 0.05, mq: 'dy/dx = ? (P is on the branch through (2, 4); the straight line is y = x)' }),
  impQ('Ex 5.5', 'Q14', 'Find dy/dx: (cos x)ʸ = (cos y)ˣ', (x, y) => y * log(cos(x)) - x * log(cos(y)), (x, y) => (y * tan(x) + log(cos(y))) / (x * tan(y) + log(cos(x))), ['(y tan x + log cos y)/(x tan y + log cos x)', '(x tan y + log cos x)/(y tan x + log cos y)', '−(y tan x + log cos y)/(x tan y + log cos x)', 'tan x / tan y'], [0.6, 0.6], { view: [-0.2, 1.4, -0.2, 1.4], start: 0.3, mq: 'dy/dx = ? (the curve here is the line y = x and the axes)' }),
  impQ('Ex 5.5', 'Q15', 'Find dy/dx: xy = e^(x − y)', G15, (x, y) => (y * (x - 1)) / (x * (y + 1)), ['y(x − 1)/(x(y + 1))', 'x(y + 1)/(y(x − 1))', '(x − 1)/(y + 1)', '−y(x − 1)/(x(y + 1))'], pt(G15, 2, 1.5), { view: [0.2, 4, -0.2, 2.5] }),
  dQ('Ex 5.5', 'Q16', 'f(x) = (1 + x)(1 + x²)(1 + x⁴)(1 + x⁸). Find f′(x) and f′(1)', (x) => (1 + x) * (1 + x * x) * (1 + x ** 4) * (1 + x ** 8), (x) => (1 + x) * (1 + x * x) * (1 + x ** 4) * (1 + x ** 8) * (1 / (1 + x) + (2 * x) / (1 + x * x) + (4 * x ** 3) / (1 + x ** 4) + (8 * x ** 7) / (1 + x ** 8)), ['f(x)[1/(1+x) + 2x/(1+x²) + 4x³/(1+x⁴) + 8x⁷/(1+x⁸)]', 'f(x)[1 + 2x + 4x³ + 8x⁷]', '(1 + x)(1 + x²)(1 + x⁴)(1 + x⁸) · 15x¹⁴', 'f(x)[1/(1+x) + 1/(1+x²) + 1/(1+x⁴) + 1/(1+x⁸)]'], 1, { view: [0.4, 1.1], y: [0, 40], show: '120', mq: 'f′(x) = ?', post: [sayP('f′(1) = 16 × (1/2 + 1 + 2 + 4) = 16 × 15/2 = 120.', 'happy')] }),
  dQ('Ex 5.5', 'Q17', 'Differentiate (x² − 5x + 8)(x³ + 7x + 9) three ways: product rule, expanding, logarithms', p17, dp17, ['5x⁴ − 20x³ + 45x² − 52x + 11', '5x⁴ − 20x³ + 45x² + 52x + 11', '(2x − 5)(3x² + 7)', '5x⁴ + 45x² + 11'], 1, { view: [-0.5, 2.5], steps: [{ k: 'tf', q: 'All three methods give the same polynomial', a: true, x: 'A derivative does not depend on the method.' }] }),
  xs('Ex 5.5', 'Q18', 'If u, v, w are functions of x, show (uvw)′ = u′vw + uv′w + uvw′ in two ways', [{ k: 'order', q: 'Logarithmic way', s: ['log y = log u + log v + log w', '(1/y) y′ = u′/u + v′/v + w′/w', 'y′ = uvw(u′/u + v′/v + w′/w)', '= u′vw + uv′w + uvw′'] }, mcq('Product rule way: (u·(vw))′ =', ['u′(vw) + u(v′w + vw′)', 'u′v′w′', 'u′vw', '(uv)′w′'], 'Apply the product rule twice.')], '(uvw)′ = u′vw + uv′w + uvw′'),
];

/* ===================== EXERCISE 5.6 ===================== */
const EX56 = [
  parQ('Ex 5.6', 'Q1', 'x = 2at², y = at⁴. Find dy/dx', (t) => 2 * t * t, (t) => t ** 4, (t) => t * t, ['t²', '2t', 't³/2', '4at³'], 1.2, { range: [-1.6, 1.6], cap: 'a = 1' }),
  parQ('Ex 5.6', 'Q2', 'x = a cos θ, y = b cos θ. Find dy/dx', (t) => 2 * cos(t), (t) => cos(t), (t) => 0.5, ['b/a', 'a/b', '−b/a', 'tan θ'], 1, { range: [0.2, 3], tn: 'θ', cap: 'a = 2, b = 1: a straight segment' }),
  parQ('Ex 5.6', 'Q3', 'x = sin t, y = cos 2t. Find dy/dx', (t) => sin(t), (t) => cos(2 * t), (t) => -4 * sin(t), ['−4 sin t', '4 sin t', '−2 sin 2t', '−2 tan t'], 0.8, { range: [-1.5, 1.5] }),
  parQ('Ex 5.6', 'Q4', 'x = 4t, y = 4/t. Find dy/dx', (t) => 4 * t, (t) => 4 / t, (t) => -1 / (t * t), ['−1/t²', '1/t²', '−4/t²', '−t²'], 1.5, { range: [0.4, 2.5] }),
  parQ('Ex 5.6', 'Q5', 'x = cos θ − cos 2θ, y = sin θ − sin 2θ. Find dy/dx', (t) => cos(t) - cos(2 * t), (t) => sin(t) - sin(2 * t), (t) => (cos(t) - 2 * cos(2 * t)) / (2 * sin(2 * t) - sin(t)), ['(cos θ − 2 cos 2θ)/(2 sin 2θ − sin θ)', '(cos θ − 2 cos 2θ)/(sin θ − 2 sin 2θ)', '(2 sin 2θ − sin θ)/(cos θ − 2 cos 2θ)', 'cot θ'], 1, { range: [0, 2 * PI], tn: 'θ' }),
  parQ('Ex 5.6', 'Q6', 'x = a(θ − sin θ), y = a(1 + cos θ). Find dy/dx', (t) => t - sin(t), (t) => 1 + cos(t), (t) => -1 / tan(t / 2), ['−cot(θ/2)', 'cot(θ/2)', '−tan(θ/2)', 'tan θ'], 2, { range: [0.3, 6], tn: 'θ', cap: 'a = 1' }),
  parQ('Ex 5.6', 'Q7', 'x = sin³t/√(cos 2t), y = cos³t/√(cos 2t). Find dy/dx', (t) => sin(t) ** 3 / sqrt(cos(2 * t)), (t) => cos(t) ** 3 / sqrt(cos(2 * t)), (t) => -1 / tan(3 * t), ['−cot 3t', 'cot 3t', '−tan 3t', '−cot t'], 0.4, { range: [-0.7, 0.7] }),
  parQ('Ex 5.6', 'Q8', 'x = a(cos t + log tan(t/2)), y = a sin t. Find dy/dx', (t) => cos(t) + log(tan(t / 2)), (t) => sin(t), (t) => tan(t), ['tan t', 'cot t', '−tan t', 'sin t'], 1, { range: [0.3, 2.8], cap: 'a = 1 (a tractrix)' }),
  parQ('Ex 5.6', 'Q9', 'x = a sec θ, y = b tan θ. Find dy/dx', (t) => 2 * sec(t), (t) => tan(t), (t) => 1 / (2 * sin(t)), ['b cosec θ / a', 'b sec θ / a', 'a cosec θ / b', 'b tan θ / a'], 0.8, { range: [-1.2, 1.2], tn: 'θ', cap: 'a = 2, b = 1' }),
  parQ('Ex 5.6', 'Q10', 'x = a(cos θ + θ sin θ), y = a(sin θ − θ cos θ). Find dy/dx', (t) => cos(t) + t * sin(t), (t) => sin(t) - t * cos(t), (t) => tan(t), ['tan θ', 'cot θ', 'θ tan θ', '−tan θ'], 1, { range: [0.2, 4], tn: 'θ', cap: 'a = 1 (an involute)' }),
  parQ('Ex 5.6', 'Q11', 'x = √(a^(sin⁻¹t)), y = √(a^(cos⁻¹t)). Show dy/dx = −y/x', (t) => sqrt(2 ** asin(t)), (t) => sqrt(2 ** acos(t)), (t) => -sqrt(2 ** acos(t)) / sqrt(2 ** asin(t)), ['−y/x', 'y/x', '−x/y', 'x/y'], 0.3, { range: [-0.95, 0.95], cap: 'a = 2', mq: 'xy = √(a^(π/2)) is constant, so dy/dx =' }),
];

/* ===================== EXERCISE 5.7 ===================== */
const EX57 = [
  d2Q('Ex 5.7', 'Q1', 'Find d²y/dx²: x² + 3x + 2', (x) => x * x + 3 * x + 2, () => 2, ['2', '2x + 3', '0', '3'], 0),
  d2Q('Ex 5.7', 'Q2', 'Find d²y/dx²: x²⁰', (x) => x ** 20, (x) => 380 * x ** 18, ['380x¹⁸', '20x¹⁹', '380x¹⁹', '19x¹⁸'], 0.9, { view: [-1.1, 1.1], y: [-1, 6] }),
  d2Q('Ex 5.7', 'Q3', 'Find d²y/dx²: x cos x', (x) => x * cos(x), (x) => -(x * cos(x) + 2 * sin(x)), ['−(x cos x + 2 sin x)', 'x cos x − 2 sin x', '−x sin x + cos x', '−x cos x'], 1),
  d2Q('Ex 5.7', 'Q4', 'Find d²y/dx²: log x', log, (x) => -1 / (x * x), ['−1/x²', '1/x', '1/x²', '−1/x'], 1, { view: [0.3, 3] }),
  d2Q('Ex 5.7', 'Q5', 'Find d²y/dx²: x³ log x', (x) => x ** 3 * log(x), (x) => x * (5 + 6 * log(x)), ['x(5 + 6 log x)', '3x²(1 + log x)', '6x log x', 'x(6 + 5 log x)'], 1, { view: [0.2, 2] }),
  d2Q('Ex 5.7', 'Q6', 'Find d²y/dx²: eˣ sin 5x', (x) => exp(x) * sin(5 * x), (x) => 2 * exp(x) * (5 * cos(5 * x) - 12 * sin(5 * x)), ['2eˣ(5 cos 5x − 12 sin 5x)', 'eˣ(sin 5x + 5 cos 5x)', '−24eˣ sin 5x', '2eˣ(12 cos 5x − 5 sin 5x)'], 0.3, { view: [-1, 1] }),
  d2Q('Ex 5.7', 'Q7', 'Find d²y/dx²: e⁶ˣ cos 3x', (x) => exp(6 * x) * cos(3 * x), (x) => 9 * exp(6 * x) * (3 * cos(3 * x) - 4 * sin(3 * x)), ['9e⁶ˣ(3 cos 3x − 4 sin 3x)', 'e⁶ˣ(6 cos 3x − 3 sin 3x)', '27e⁶ˣ cos 3x', '9e⁶ˣ(4 cos 3x − 3 sin 3x)'], 0.1, { view: [-0.6, 0.4] }),
  d2Q('Ex 5.7', 'Q8', 'Find d²y/dx²: tan⁻¹ x', atan, (x) => (-2 * x) / (1 + x * x) ** 2, ['−2x/(1 + x²)²', '1/(1 + x²)', '2x/(1 + x²)²', '−1/(1 + x²)²'], 1),
  d2Q('Ex 5.7', 'Q9', 'Find d²y/dx²: log(log x)', (x) => log(log(x)), (x) => -(1 + log(x)) / (x * log(x)) ** 2, ['−(1 + log x)/(x log x)²', '1/(x log x)', '−1/(x log x)²', '(1 + log x)/(x log x)²'], 2, { view: [1.3, 4] }),
  d2Q('Ex 5.7', 'Q10', 'Find d²y/dx²: sin(log x)', (x) => sin(log(x)), (x) => -(sin(log(x)) + cos(log(x))) / (x * x), ['−[sin(log x) + cos(log x)]/x²', 'cos(log x)/x', '−sin(log x)/x²', '[sin(log x) − cos(log x)]/x²'], 1, { view: [0.3, 3] }),
  showQ('Ex 5.7', 'Q11', 'If y = 5 cos x − 3 sin x, show that d²y/dx² + y = 0', (x) => 5 * cos(x) - 3 * sin(x), (x) => ND2((t) => 5 * cos(t) - 3 * sin(t), x) + 5 * cos(x) - 3 * sin(x), 0, 1, { steps: [mcq('y″ =', ['−5 cos x + 3 sin x = −y', '5 cos x − 3 sin x', '−5 sin x − 3 cos x', '0'], 'Differentiate twice.')], nq: 'Live check: y″ + y at x = 1 = ?' }),
  { ...d2Q('Ex 5.7', 'Q12', 'If y = cos⁻¹ x, find d²y/dx² in terms of y alone', acos, (x) => -x / (1 - x * x) ** 1.5, ['−cot y cosec²y', 'cot y cosec²y', '−cosec²y', '−cos y'], 0.5, { view: [-0.95, 0.95], steps: [mcq('dy/dx = −1/√(1 − x²) = ?', ['−1/sin y', '1/sin y', '−1/cos y', '−sin y'], 'x = cos y, so √(1 − x²) = sin y.')] }) },
  showQ('Ex 5.7', 'Q13', 'If y = 3 cos(log x) + 4 sin(log x), show x²y₂ + xy₁ + y = 0', (x) => 3 * cos(log(x)) + 4 * sin(log(x)), (x) => { const f = (t) => 3 * cos(log(t)) + 4 * sin(log(t)); return x * x * ND2(f, x) + x * ND(f, x) + f(x); }, 0, 2, { view: [0.2, 6], steps: [{ k: 'order', q: 'Order the proof', s: ['x y₁ = −3 sin(log x) + 4 cos(log x)', 'Differentiate: x y₂ + y₁ = −[3 cos(log x) + 4 sin(log x)]/x', 'Multiply by x: x²y₂ + xy₁ = −y', 'So x²y₂ + xy₁ + y = 0'] }], nq: 'Live check: x²y₂ + xy₁ + y at x = 2 = ?' }),
  showQ('Ex 5.7', 'Q14', 'If y = Ae^(mx) + Be^(nx), show y″ − (m + n)y′ + mny = 0', (x) => 2 * exp(1 * x) + 3 * exp(-2 * x), (x) => { const f = (t) => 2 * exp(t) + 3 * exp(-2 * t); return ND2(f, x) - (1 - 2) * ND(f, x) + 1 * -2 * f(x); }, 0, 0.3, { view: [-1, 1.5], cap: 'A = 2, B = 3, m = 1, n = −2', steps: [mcq('y″ − (m + n)y′ + mny: the e^(mx) terms give A(m² − (m + n)m + mn) =', ['0', 'Am²', 'Amn', 'A'], 'Same for the e^(nx) terms.')], nq: 'Live check at x = 0.3: y″ − (m + n)y′ + mny = ?' }),
  showQ('Ex 5.7', 'Q15', 'If y = 500e^(7x) + 600e^(−7x), show d²y/dx² = 49y', (x) => 500 * exp(7 * x) + 600 * exp(-7 * x), (x) => { const f = (t) => 500 * exp(7 * t) + 600 * exp(-7 * t); return ND2(f, x, 1e-3) / f(x); }, 49, 0.1, { view: [-0.4, 0.4], steps: [mcq('y″ = 49·500e^(7x) + 49·600e^(−7x) =', ['49y', '7y', '−49y', '0'], 'Each term picks up (±7)² = 49.')], nq: 'Live check: y″/y at x = 0.1 = ?' }),
  showQ('Ex 5.7', 'Q16', 'If eʸ(x + 1) = 1, show d²y/dx² = (dy/dx)²', (x) => -log(x + 1), (x) => { const f = (t) => -log(t + 1); return ND2(f, x) - ND(f, x) ** 2; }, 0, 1, { view: [-0.6, 3], steps: [mcq('y = −log(x + 1), so y′ = −1/(x + 1) and y″ =', ['1/(x + 1)² = (y′)²', '−1/(x + 1)²', '2/(x + 1)³', '1/(x + 1)'], 'Differentiate again.')], nq: 'Live check: y″ − (y′)² at x = 1 = ?' }),
  showQ('Ex 5.7', 'Q17', 'If y = (tan⁻¹x)², show (x² + 1)²y₂ + 2x(x² + 1)y₁ = 2', (x) => atan(x) ** 2, (x) => { const f = (t) => atan(t) ** 2; return (x * x + 1) ** 2 * ND2(f, x) + 2 * x * (x * x + 1) * ND(f, x); }, 2, 1, { steps: [{ k: 'order', q: 'Order the proof', s: ['y₁ = 2 tan⁻¹x / (1 + x²)', '(1 + x²) y₁ = 2 tan⁻¹ x', 'Differentiate: (1 + x²) y₂ + 2x y₁ = 2/(1 + x²)', 'Multiply by (1 + x²)'] }], nq: 'Live check: the left side at x = 1 = ?' }),
];

/* ===================== MISCELLANEOUS ===================== */
const m3 = (x) => (5 * x) ** (3 * cos(2 * x)), m7 = (x) => log(x) ** log(x), m9 = (x) => (sin(x) - cos(x)) ** (sin(x) - cos(x));
const m11a = (x) => x ** (x * x - 3), m11b = (x) => (x - 3) ** (x * x);
const EX5M = [
  dQ('Misc', 'Q1', 'Differentiate (3x² − 9x + 5)⁹', (x) => (3 * x * x - 9 * x + 5) ** 9, (x) => 27 * (3 * x * x - 9 * x + 5) ** 8 * (2 * x - 3), ['27(3x² − 9x + 5)⁸(2x − 3)', '9(3x² − 9x + 5)⁸', '9(3x² − 9x + 5)⁸(6x)', '27(3x² − 9x + 5)⁸'], 1.5, { view: [1, 2.2], y: [-3, 1] }),
  dQ('Misc', 'Q2', 'Differentiate sin³x + cos⁶x', (x) => sin(x) ** 3 + cos(x) ** 6, (x) => 3 * sin(x) * cos(x) * (sin(x) - 2 * cos(x) ** 4), ['3 sin x cos x (sin x − 2 cos⁴x)', '3 sin²x − 6 cos⁵x', '3 sin²x cos x + 6 cos⁵x sin x', '3 sin x cos x (sin x + 2 cos⁴x)'], 1),
  dQ('Misc', 'Q3', 'Differentiate (5x)^(3 cos 2x)', m3, (x) => m3(x) * ((3 * cos(2 * x)) / x - 6 * sin(2 * x) * log(5 * x)), ['(5x)^(3cos2x)[3 cos 2x / x − 6 sin 2x log 5x]', '(5x)^(3cos2x)[3 cos 2x / x + 6 sin 2x log 5x]', '3 cos 2x (5x)^(3cos2x − 1)', '−6 sin 2x log 5x'], 0.5, { view: [0.2, 1] }),
  dQ('Misc', 'Q4', 'Differentiate sin⁻¹(x√x), 0 ≤ x ≤ 1', (x) => asin(x * sqrt(x)), (x) => (1.5 * sqrt(x)) / sqrt(1 - x ** 3), ['(3/2)√x / √(1 − x³)', '1/√(1 − x³)', '√x/√(1 − x³)', '(3/2)√x / √(1 − x²)'], 0.5, { view: [0.02, 0.95] }),
  dQ('Misc', 'Q5', 'Differentiate cos⁻¹(x/2)/√(2x + 7), −2 < x < 2', (x) => acos(x / 2) / sqrt(2 * x + 7), (x) => -(1 / (sqrt(4 - x * x) * sqrt(2 * x + 7)) + acos(x / 2) / (2 * x + 7) ** 1.5), ['−[1/(√(4 − x²)√(2x + 7)) + cos⁻¹(x/2)/(2x + 7)^(3/2)]', '1/(√(4 − x²)√(2x + 7)) − cos⁻¹(x/2)/(2x + 7)^(3/2)', '−1/(√(4 − x²)√(2x + 7))', '−cos⁻¹(x/2)/(2x + 7)^(3/2)'], 0, { view: [-1.9, 1.9] }),
  dQ('Misc', 'Q6', 'Differentiate cot⁻¹[(√(1 + sin x) + √(1 − sin x))/(√(1 + sin x) − √(1 − sin x))], 0 < x < π/2', (x) => atan((sqrt(1 + sin(x)) - sqrt(1 - sin(x))) / (sqrt(1 + sin(x)) + sqrt(1 - sin(x)))), () => 0.5, ['1/2', '1', '−1/2', '2'], 0.8, { view: [0.05, 1.5], steps: [mcq('√(1 ± sin x) = cos(x/2) ± sin(x/2), so the bracket is cot(x/2) and y =', ['x/2', 'x', 'π/2 − x/2', '2x'], 'For 0 < x < π/2.')] }),
  dQ('Misc', 'Q7', 'Differentiate (log x)^(log x), x > 1', m7, (x) => m7(x) * ((1 + log(log(x))) / x), ['(log x)^(log x) (1 + log(log x))/x', '(log x)^(log x) log(log x)/x', 'log x (log x)^(log x − 1)/x', '(log x)^(log x)/x'], 3, { view: [1.2, 5] }),
  dQ('Misc', 'Q8', 'Differentiate cos(a cos x + b sin x)', (x) => cos(2 * cos(x) + sin(x)), (x) => -sin(2 * cos(x) + sin(x)) * (-2 * sin(x) + cos(x)), ['sin(a cos x + b sin x)(a sin x − b cos x)', '−sin(a cos x + b sin x)(a sin x − b cos x)', '−sin(a cos x + b sin x)', 'sin(a cos x + b sin x)(a cos x + b sin x)'], 1, { cap: 'graph with a = 2, b = 1' }),
  dQ('Misc', 'Q9', 'Differentiate (sin x − cos x)^(sin x − cos x), π/4 < x < 3π/4', m9, (x) => m9(x) * (cos(x) + sin(x)) * (1 + log(sin(x) - cos(x))), ['(sin x − cos x)^(sin x − cos x)(cos x + sin x)(1 + log(sin x − cos x))', '(sin x − cos x)^(sin x − cos x) log(sin x − cos x)', '(cos x + sin x)(sin x − cos x)^(sin x − cos x − 1)', '(sin x − cos x)^(sin x − cos x)(cos x − sin x)(1 + log(sin x − cos x))'], 1.6, { view: [0.85, 2.3] }),
  dQ('Misc', 'Q10', 'Differentiate xˣ + xᵃ + aˣ + aᵃ, a > 0, x > 0', (x) => x ** x + x ** 2 + 2 ** x + 4, (x) => x ** x * (1 + log(x)) + 2 * x + 2 ** x * log(2), ['xˣ(1 + log x) + a xᵃ⁻¹ + aˣ log a', 'x·xˣ⁻¹ + a xᵃ⁻¹ + x aˣ⁻¹', 'xˣ log x + a xᵃ⁻¹ + aˣ log a + aᵃ log a', 'xˣ(1 + log x) + a xᵃ⁻¹ + aˣ'], 1, { view: [0.2, 2], cap: 'graph with a = 2' }),
  dQ('Misc', 'Q11', 'Differentiate x^(x² − 3) + (x − 3)^(x²), x > 3', (x) => m11a(x) + m11b(x), (x) => m11a(x) * ((x * x - 3) / x + 2 * x * log(x)) + m11b(x) * ((x * x) / (x - 3) + 2 * x * log(x - 3)), ['x^(x²−3)[(x² − 3)/x + 2x log x] + (x − 3)^(x²)[x²/(x − 3) + 2x log(x − 3)]', 'x^(x²−3) 2x log x + (x − 3)^(x²) 2x log(x − 3)', '(x² − 3)x^(x²−4) + x²(x − 3)^(x²−1)', 'x^(x²−3)[(x² − 3)/x] + (x − 3)^(x²)[x²/(x − 3)]'], 3.5, { view: [3.1, 3.8], y: [0, 5000] }),
  parQ('Misc', 'Q12', 'Find dy/dx if y = 12(1 − cos t), x = 10(t − sin t), −π/2 < t < π/2', (t) => 10 * (t - sin(t)), (t) => 12 * (1 - cos(t)), (t) => (6 / 5) / tan(t / 2), ['(6/5) cot(t/2)', '(6/5) tan(t/2)', '(5/6) cot(t/2)', '12 sin t'], 1, { range: [0.2, 1.55] }),
  dQ('Misc', 'Q13', 'Find dy/dx if y = sin⁻¹x + sin⁻¹√(1 − x²), 0 < x < 1', (x) => asin(x) + asin(sqrt(1 - x * x)), () => 0, ['0', '1/√(1 − x²)', '2/√(1 − x²)', '−1'], 0.5, { view: [0.05, 0.95], y: [0, 2.5], steps: [mcq('sin⁻¹√(1 − x²) = cos⁻¹x for 0 < x < 1, so y =', ['π/2', '2 sin⁻¹ x', '0', 'π'], 'sin⁻¹x + cos⁻¹x = π/2.')] }),
  dQ('Misc', 'Q14', 'If x√(1 + y) + y√(1 + x) = 0, −1 < x < 1, prove dy/dx = −1/(1 + x)²', (x) => -x / (1 + x), (x) => -1 / (1 + x) ** 2, ['−1/(1 + x)²', '1/(1 + x)²', '−1/(1 + x)', '−x/(1 + x)²'], 0.5, { view: [-0.6, 0.95], steps: [mcq('Squaring x²(1 + y) = y²(1 + x) and x ≠ y gives', ['y = −x/(1 + x)', 'y = x', 'y = x/(1 + x)', 'y = −x'], 'Factor (x − y)(x + y + xy) = 0.')] }),
  showQ('Misc', 'Q15', 'If (x − a)² + (y − b)² = c², show [1 + (dy/dx)²]^(3/2) / (d²y/dx²) is a constant independent of a and b', (x) => 1 + sqrt(4 - (x - 0.5) ** 2), (x) => { const f = (t) => 1 + sqrt(4 - (t - 0.5) ** 2); return (1 + ND(f, x) ** 2) ** 1.5 / ND2(f, x); }, -2, 1, { view: [-1.4, 2.4], cap: 'upper half of a circle with a = 0.5, b = 1, c = 2', steps: [mcq('The expression equals', ['−c (the radius, with a sign)', 'a + b', 'c²', '1/c'], 'It is the radius of curvature of the circle.')], nq: 'Live check: the expression at x = 1 (c = 2) = ?' }),
  impQ('Misc', 'Q16', 'If cos y = x cos(a + y), cos a ≠ ±1, prove dy/dx = cos²(a + y)/sin a', G16, (x, y) => cos(1 + y) ** 2 / sin(1), ['cos²(a + y)/sin a', 'sin a/cos²(a + y)', '−cos²(a + y)/sin a', 'cos(a + y)/sin a'], pt(G16, 2, 0.3), { view: [-1, 4, -1.5, 0.6], mq: 'dy/dx = ? (graph with a = 1)' }),
  { ...parQ('Misc', 'Q17', 'If x = a(cos t + t sin t), y = a(sin t − t cos t), find d²y/dx²', (t) => cos(t) + t * sin(t), (t) => sin(t) - t * cos(t), (t) => 1 / (cos(t) ** 3 * t), ['sec³t/(at)', 'sec²t/(at)', 'tan t', '−sec³t/(at)'], 0.8, { range: [0.2, 1.4], cap: 'a = 1', nq: 'd²y/dx²', mq: 'dy/dx = tan t, so d²y/dx² = sec²t · (dt/dx) =' }), d2: true },
  xs('Misc', 'Q18', 'If f(x) = |x|³, show f″(x) exists for all real x and find it', [mcq('f(x) = x³ (x ≥ 0), −x³ (x < 0). f′(x) =', ['3x|x| (and f′(0) = 0)', '3x²', '3|x|²·sign', 'not defined at 0'], 'Both one-sided derivatives at 0 are 0.'), mcq('f″(x) =', ['6|x| (exists everywhere)', '6x', '6x²', 'not defined at 0'], 'Left and right second derivatives at 0 are both 0.')], 'f″(x) = 6|x|', { scene: 'calc', setup: (W) => { calcView(W, (x) => abs(x) ** 3, -1.6, 1.6); W.extraF = [{ f: (x) => 6 * abs(x), col: C.beni, dash: [7, 5] }]; W.a = 0.5; W.tan = true; grabCalc(W); W.pl.caption = 'solid |x|³ · dashed 6|x|'; } }),
  xs('Misc', 'Q19', 'Using sin(A + B) = sin A cos B + cos A sin B and differentiation, obtain the sum formula for cosines', [mcq('Differentiate with respect to A (B fixed):', ['cos(A + B) = cos A cos B − sin A sin B', 'cos(A + B) = cos A cos B + sin A sin B', 'cos(A + B) = sin A sin B − cos A cos B', 'cos(A + B) = cos A + cos B'], 'd/dA sin A = cos A, d/dA cos A = −sin A.')], 'cos(A + B) = cos A cos B − sin A sin B'),
  xs('Misc', 'Q20', 'Does there exist a function continuous everywhere but not differentiable at exactly two points?', [{ k: 'run', run: async (W) => { W.lr = { c: 1, h: 0.5 }; await wait(AUTO ? 0.05 : 0.8); W.lr = { c: 2, h: 0.5 }; await wait(AUTO ? 0.05 : 0.8); W.lr = null; } }, mcq('Yes, for example', ['|x − 1| + |x − 2|', 'x² + 1', '[x]', '1/((x − 1)(x − 2))'], 'Two kinks, no breaks.')], 'Yes: f(x) = |x − 1| + |x − 2|', { scene: 'pw', setup: (W) => pwSet(W, (x) => abs(x - 1) + abs(x - 2), [], [-1, 4, -0.5, 4]) }),
  xs('Misc', 'Q21', 'If y = |f g h; l m n; a b c|, prove dy/dx = |f′ g′ h′; l m n; a b c|', [mcq('Expand along R₁: y = f·A₁₁ + g·A₁₂ + h·A₁₃ where the cofactors are constants. So dy/dx =', ['f′A₁₁ + g′A₁₂ + h′A₁₃', 'f′g′h′', '0', 'fA₁₁′'], 'Which is the determinant with R₁ differentiated.')], 'dy/dx = |f′ g′ h′; l m n; a b c|'),
  showQ('Misc', 'Q22', 'If y = e^(a cos⁻¹x), −1 ≤ x ≤ 1, show (1 − x²)y₂ − xy₁ − a²y = 0', (x) => exp(1.5 * acos(x)), (x) => { const f = (t) => exp(1.5 * acos(t)); return (1 - x * x) * ND2(f, x) - x * ND(f, x) - 2.25 * f(x); }, 0, 0.3, { view: [-0.9, 0.9], cap: 'a = 1.5', steps: [{ k: 'order', q: 'Order the proof', s: ['y₁ = −a y / √(1 − x²)', '(1 − x²) y₁² = a² y²', 'Differentiate: (1 − x²) 2y₁y₂ − 2x y₁² = 2a² y y₁', 'Divide by 2y₁: (1 − x²)y₂ − xy₁ − a²y = 0'] }], nq: 'Live check: the left side at x = 0.3 = ?' }),
];

const BOSS5 = [['lim f = f(c) means f is', ['continuous at c', 'differentiable at c', 'zero at c', 'constant'], 0], ['|x| at 0 is', ['continuous, not differentiable', 'differentiable', 'discontinuous', 'undefined'], 0], ['d/dx sin(x²)', ['2x cos x²', 'cos x²', '2 sin x', 'cos 2x'], 0], ['d/dx eˣ', ['eˣ', 'x eˣ⁻¹', '1', 'eˣ log x'], 0], ['d/dx log x', ['1/x', 'log x', 'x', 'eˣ'], 0], ['d/dx tan⁻¹x', ['1/(1 + x²)', '1/√(1 − x²)', 'sec²x', '−1/(1 + x²)'], 0], ['d/dx aˣ', ['aˣ log a', 'x aˣ⁻¹', 'aˣ', 'log a'], 0], ['x = t², y = 2t: dy/dx', ['1/t', 't', '2t', '2'], 0], ['[x] is discontinuous at', ['every integer', 'nowhere', '0 only', 'every non-integer'], 0], ['d²/dx² sin x', ['−sin x', 'cos x', 'sin x', '−cos x'], 0]];
const byId = (id) => LESSONS.find((l) => l.id === id);
(() => {
  const [cn, al, df, im, el, ld, pa, se, me] = ['cont', 'algebra', 'diff', 'implicit', 'explog', 'logdiff', 'param', 'second', 'miscex'].map(byId);
  LESSONS.length = 0;
  LESSONS.push(cn, al, exLesson({ id: 'ex51', title: 'Exercise 5.1', blurb: 'All 34: pen-lift tests, tap the breaks, slide k to join the graph.', face: 'kimmy-playful', qs: EX51 }), df, exLesson({ id: 'ex52', title: 'Exercise 5.2', blurb: 'All 10: chain rule with live tangents, and two kinks.', face: 'jess-happy', qs: EX52 }), im, exLesson({ id: 'ex53', title: 'Exercise 5.3', blurb: 'All 15: drag along implicit curves; inverse-trig substitutions.', face: 'kimmy-curious', qs: EX53 }), el, exLesson({ id: 'ex54', title: 'Exercise 5.4', blurb: 'All 10: exponentials and logs.', face: 'jess-thinking', qs: EX54 }), ld, exLesson({ id: 'ex55', title: 'Exercise 5.5', blurb: 'All 18: logarithmic differentiation.', face: 'kimmy-excited', qs: EX55 }), pa, exLesson({ id: 'ex56', title: 'Exercise 5.6', blurb: 'All 11: slide t along parametric curves.', face: 'jess-excited', qs: EX56 }), se, exLesson({ id: 'ex57', title: 'Exercise 5.7', blurb: 'All 17: second derivatives and live checks.', face: 'kimmy-lookup', qs: EX57 }), me, exLesson({ id: 'misc', title: 'Miscellaneous', blurb: 'All 22 Miscellaneous Exercise questions.', face: 'jess-thinking', qs: EX5M }));
})();
LESSONS.push(lesson({ id: 'boss', title: 'Boss Battle', blurb: 'Ten fast questions. Speed points. Beat Kimmy.', face: 'jess-excited', steps: [async function () { enterScene('board', (W) => { W.tag = 'BOSS'; W.sub = 'Class 12 · Ch 5'; }); await slam('BOSS BATTLE', '10 questions · speed counts'); await K('play', 'No lifting the pen!'); await cont('Fight'); }, ...BOSS5.map(([q, o, a], i) => async function () { enterScene('board', (W) => { W.tag = 'Q' + (i + 1); W.sub = 'Boss Battle'; }); await quiz(q, o, a, plain(o[a]) + '.', null, 15); await cont(); }), async function () { enterScene('board', (W) => { W.tag = 'K.O.!'; W.sub = 'Class 12 · Ch 5'; }); await summary(['Chapter complete!', { t: 'Continuous: no lift · Differentiable: no kink', eq: true }]); }] }));
LESSONS.forEach((l) => { if (l.kind === 'ex') l.short = l.id === 'misc' ? 'M' : l.title.replace('Exercise ', ''); });
