/* =========================================================
   CHAPTER 9 · STRAIGHT LINES — every exercise question as a sim
   Target lines are checked geometrically (L9.same); numeric answers re-checked by the test page.
   ========================================================= */
const S3 = Math.sqrt(3);
const Q9 = (ex, n, q, view, parts, w, o = {}) => ({ ex, n, q, scene: 'lines', setup: (W) => { planeView(W, ...view); (o.pts || []).forEach((p) => W.pts.push(pt9(...p))); (o.L || []).forEach((l) => W.L.push(Object.assign({ col: C.ink }, l))); if (o.setup) o.setup(W); }, kim: o.kim, parts, w: [w] });
const B9 = (ex, n, q, parts, w, kim) => ({ ex, n, q, scene: 'board', kim, parts, w: [w] });
const prf = (s) => ({ k: 'order', q: 'Order the proof', s });

/* ===================== EXERCISE 9.1 ===================== */
const EX91 = [
  Q9('Ex 9.1', 'Q1', 'Draw the quadrilateral with vertices (−4, 5), (0, 7), (5, −5), (−4, −2) and find its area.', [-6, 7, -6, 8], [
    { k: 'run', run: async () => { const b = button('Draw'); await waitFor(() => b.clicked()); b.stop(); W.polys.push({ pts: [[-4, 5], [0, 7], [5, -5], [-4, -2]], col: C['sora-tint'], a: 0 }); gsap.to(W.polys[0], { a: 0.6, duration: 0.6 }); SFX.swish(); } },
    { k: 'order', q: 'Shoelace: Σ(xᵢyᵢ₊₁ − xᵢ₊₁yᵢ)', s: ['(−4)(7) − 0(5) = −28', '0(−5) − 5(7) = −35', '5(−2) − (−4)(−5) = −30', '(−4)(5) − (−4)(−2) = −28'] },
    { k: 'num', q: 'Area = |−121|/2 = ?', a: 60.5, show: '121/2', x: '121/2 square units.' }], 'Area = ½|−28 − 35 − 30 − 28| = 121/2', { pts: [[-4, 5, 'A'], [0, 7, 'B'], [5, -5, 'C'], [-4, -2, 'D']] }),
  B9('Ex 9.1', 'Q2', 'An equilateral triangle with side 2a has its base on the y-axis with mid-point at the origin. Find its vertices.', [{ k: 'mcq', q: 'Base ends: (0, ±a). Height = √3·a. Third vertex?', o: ['(±√3a, 0)', '(√3a, a)', '(0, √3a)', '(±2a, 0)'], a: 0, x: 'Either side of the y-axis.' }], 'Vertices (0, a), (0, −a), (√3a, 0) or (−√3a, 0)'),
  B9('Ex 9.1', 'Q3', 'Find the distance between P(x₁, y₁) and Q(x₂, y₂) when PQ is (i) parallel to the y-axis (ii) parallel to the x-axis.', [{ k: 'match', q: 'Match', L: ['PQ ∥ y-axis (x₁ = x₂)', 'PQ ∥ x-axis (y₁ = y₂)'], R: ['|x₂ − x₁|', '|y₂ − y₁|'], a: [1, 0] }], '(i) |y₂ − y₁|  (ii) |x₂ − x₁|'),
  Q9('Ex 9.1', 'Q4', 'Find a point on the x-axis equidistant from (7, 6) and (3, 4).', [-1, 10, -1, 7], [
    { k: 'task', q: 'Slide the gold point along the x-axis until both distances match', todo: 'Watch the two dashed lengths.', pre: async () => { const P = axisDrag(W, 'x', 2); W.tmp = P; W.L.length = 0; W.labs.push({ x: 4.5, y: 6.6, t: () => 'PA = ' + fmtN(Math.hypot(P.x - 7, 6), 2) + '   PB = ' + fmtN(Math.hypot(P.x - 3, 4), 2) }); W.feet.length = 0; W.polys.push({ pts: [[7, 6], [P.x, 0], [3, 4]], col: C.sakura, a: 0 }); W.vecs.push({ x0: 7, y0: 6, x1: 0, y1: 0, dash: true, col: C.beni }, { x0: 3, y0: 4, x1: 0, y1: 0, dash: true, col: C.sora }); W.tickV = () => { W.vecs[0].x1 = P.x; W.vecs[1].x1 = P.x; }; }, check: (W) => Math.abs(W.tmp.x - 7.5) < 0.01, auto: (W) => (W.tmp.x = 7.5), reveal: (W) => (W.tmp.x = 7.5) },
    { k: 'num', q: '(x − 7)² + 36 = (x − 3)² + 16 ⇒ x = ?', a: 7.5, show: '15/2', x: '(15/2, 0).' }], 'Point (15/2, 0)', { pts: [[7, 6, 'A(7, 6)'], [3, 4, 'B(3, 4)']] }),
  Q9('Ex 9.1', 'Q5', 'Find the slope of the line through the origin and the mid-point of P(0, −4) and B(8, 0).', [-2, 9, -5, 2], [{ k: 'fields', q: 'Mid-point', f: [{ l: 'x', a: 4 }, { l: 'y', a: -2 }], x: '(4, −2).', act: async () => { W.pts.push(pt9(4, -2, 'M')); await drawLines(W, [lineOf(1, 2, 0, { col: C.beni })], 0.4); } }, { k: 'num', q: 'Slope of OM = ?', a: -0.5, show: '−1/2', x: '−2/4 = −1/2.' }], 'm = −1/2', { pts: [[0, -4, 'P'], [8, 0, 'B']] }),
  Q9('Ex 9.1', 'Q6', 'Without Pythagoras, show (4, 4), (3, 5), (−1, −1) form a right-angled triangle.', [-3, 7, -3, 7], [{ k: 'fields', q: 'Slopes', f: [{ l: 'AB', a: -1 }, { l: 'BC', a: 1.5, show: '3/2' }, { l: 'CA', a: 1 }], x: '−1, 3/2, 1.', act: async () => { W.polys.push({ pts: [[4, 4], [3, 5], [-1, -1]], col: C['matcha-tint'], a: 0.6 }); SFX.swish(); } }, { k: 'mcq', q: 'Which two sides are perpendicular?', o: ['AB and CA (product −1)', 'AB and BC', 'BC and CA', 'none'], a: 0, x: '(−1)(1) = −1: right angle at A(4, 4).' }], 'm_AB · m_CA = (−1)(1) = −1 ⇒ right angle at (4, 4)', { pts: [[4, 4, 'A'], [3, 5, 'B'], [-1, -1, 'C']] }),
  Q9('Ex 9.1', 'Q7', 'Find the slope of the line making 30° with the positive y-axis, measured anticlockwise.', [-4, 4, -3, 3], [
    { k: 'task', q: 'Rotate the line to 30° anticlockwise from the y-axis', todo: 'The readout shows the angle from the x-axis.', pre: async () => userLine(W, { mode: 'pivot', piv: [0, 0], deg: 90 }), check: (W) => W.ul.deg === 120, auto: (W) => (W.ul.deg = 120), reveal: (W) => (W.ul.deg = 120) },
    { k: 'num', q: 'Inclination 120° ⇒ slope tan 120° = ?', a: -S3, show: '−√3', keys: '√', tol: 0.01, x: '−√3.' }], 'Inclination 90° + 30° = 120° ⇒ m = −√3'),
  Q9('Ex 9.1', 'Q8', 'Without the distance formula, show (−2, −1), (4, 0), (3, 3), (−3, 2) form a parallelogram.', [-4, 5, -2, 4], [{ k: 'fields', q: 'Slopes of the four sides', f: [{ l: 'AB', a: 1 / 6, show: '1/6' }, { l: 'BC', a: -3 }, { l: 'CD', a: 1 / 6, show: '1/6' }, { l: 'DA', a: -3 }], x: 'Opposite sides have equal slopes ⇒ parallel.', act: async () => { W.polys.push({ pts: [[-2, -1], [4, 0], [3, 3], [-3, 2]], col: C['sora-tint'], a: 0.6 }); SFX.swish(); } }], 'AB ∥ CD (1/6), BC ∥ DA (−3) ⇒ parallelogram', { pts: [[-2, -1, 'A'], [4, 0, 'B'], [3, 3, 'C'], [-3, 2, 'D']] }),
  Q9('Ex 9.1', 'Q9', 'Find the angle between the x-axis and the line joining (3, −1) and (4, −2).', [0, 6, -4, 2], [{ k: 'num', q: 'Slope = −1 ⇒ angle with the x-axis = ? (degrees)', a: 135, x: '135°.', act: async () => drawLines(W, [lineOf(1, 1, -2, { col: C.beni, t: 'm = −1' })], 0.4) }], 'm = −1 ⇒ θ = 135°', { pts: [[3, -1, '(3, −1)'], [4, -2, '(4, −2)']] }),
  B9('Ex 9.1', 'Q10', 'The slope of one line is double the other. If tan(angle between them) = 1/3, find the slopes.', [{ k: 'mcq', q: '|m/(1 + 2m²)| = 1/3 ⇒ 2m² ∓ 3m + 1 = 0. The pairs (m, 2m) are…', o: ['(1, 2), (1/2, 1), (−1, −2), (−1/2, −1)', '(1, 2) only', '(1/2, 1) only', '(3, 6), (1/3, 2/3)'], a: 0, x: 'Four pairs.' }], 'm = ±1, ±1/2: (1, 2), (1/2, 1), (−1, −2), (−1/2, −1)'),
  B9('Ex 9.1', 'Q11', 'A line through (x₁, y₁) and (h, k) has slope m. Show k − y₁ = m(h − x₁).', [prf(['Slope through the two points = (k − y₁)/(h − x₁)', 'This equals m', 'Multiply out: k − y₁ = m(h − x₁)'])], 'm = (k − y₁)/(h − x₁)'),
];

/* ===================== EXERCISE 9.2 ===================== */
const EX92 = [
  B9('Ex 9.2', 'Q1', 'Write the equations of the x- and y-axes.', [{ k: 'match', q: 'Match', L: ['x-axis', 'y-axis'], R: ['x = 0', 'y = 0'], a: [1, 0] }], 'x-axis: y = 0; y-axis: x = 0'),
  Q9('Ex 9.2', 'Q2', 'Line through (−4, 3) with slope 1/2.', [-7, 4, -1, 6], [linePart('Drag the line', lineOf(1, -2, 10), { p: [-4, 3], q: [0, 0] })], 'x − 2y + 10 = 0', { pts: [[-4, 3, '(−4, 3)']] }),
  B9('Ex 9.2', 'Q3', 'Line through (0, 0) with slope m.', [{ k: 'mcq', q: 'Equation', o: ['y = mx', 'y = m', 'x = my', 'y = mx + 1'], a: 0, x: 'y − 0 = m(x − 0).' }], 'y = mx'),
  Q9('Ex 9.2', 'Q4', 'Line through (2, 2√3) inclined at 75° to the x-axis.', [-2, 5, -1, 6], [{ k: 'task', q: 'Rotate the line to 75°', todo: 'Pivot is (2, 2√3).', pre: async () => userLine(W, { mode: 'pivot', piv: [2, 2 * S3], deg: 30 }), check: (W) => W.ul.deg === 75, auto: (W) => (W.ul.deg = 75), reveal: (W) => (W.ul.deg = 75) }, { k: 'mcq', q: 'tan 75° = 2 + √3, so the line is…', o: ['(2 + √3)x − y − 4 = 0', '(2 + √3)x − y + 4 = 0', '(2 − √3)x − y − 4 = 0', 'x − (2 + √3)y = 0'], a: 0, x: 'y − 2√3 = (2 + √3)(x − 2).' }], '(2 + √3)x − y − 4 = 0'),
  Q9('Ex 9.2', 'Q5', 'Line meeting the x-axis 3 units left of the origin with slope −2.', [-6, 3, -4, 4], [linePart('Drag the line', lineOf(2, 1, 6), { p: [0, 0], q: [1, 1] })], '2x + y + 6 = 0'),
  Q9('Ex 9.2', 'Q6', 'Line meeting the y-axis 2 units above the origin at 30° to the positive x-axis.', [-5, 4, -1, 5], [{ k: 'task', q: 'Rotate the line to 30°', pre: async () => userLine(W, { mode: 'pivot', piv: [0, 2], deg: 90 }), check: (W) => W.ul.deg === 30, auto: (W) => (W.ul.deg = 30), reveal: (W) => (W.ul.deg = 30) }, { k: 'mcq', q: 'y = x/√3 + 2 becomes…', o: ['x − √3y + 2√3 = 0', 'x + √3y − 2√3 = 0', '√3x − y + 2 = 0', 'x − √3y + 2 = 0'], a: 0, x: 'Multiply by √3.' }], 'x − √3y + 2√3 = 0'),
  Q9('Ex 9.2', 'Q7', 'Line through (−1, 1) and (2, −4).', [-3, 4, -5, 3], [linePart('Drag the line through both points', lineOf(5, 3, 2), { p: [0, 0], q: [1, 2] })], '5x + 3y + 2 = 0', { pts: [[-1, 1, '(−1, 1)'], [2, -4, '(2, −4)']] }),
  Q9('Ex 9.2', 'Q8', 'Triangle P(2, 1), Q(−2, 3), R(4, 5). Find the median through R.', [-3, 6, -1, 6], [{ k: 'fields', q: 'Mid-point of PQ', f: [{ l: 'x', a: 0 }, { l: 'y', a: 2 }], x: '(0, 2).', act: async () => W.pts.push(pt9(0, 2, 'M')) }, linePart('Drag the median RM', lineOf(3, -4, 8), { p: [1, 1], q: [3, 2] })], '3x − 4y + 8 = 0', { pts: [[2, 1, 'P'], [-2, 3, 'Q'], [4, 5, 'R']], setup: (W) => W.polys.push({ pts: [[2, 1], [-2, 3], [4, 5]], col: C['sora-tint'], a: 0.5 }) }),
  Q9('Ex 9.2', 'Q9', 'Line through (−3, 5) perpendicular to the line through (2, 5) and (−3, 6).', [-5, 3, -1, 7], [{ k: 'num', q: 'Given slope −1/5 ⇒ perpendicular slope = ?', a: 5, x: '5.' }, linePart('Drag the perpendicular through (−3, 5)', lineOf(5, -1, 20), { p: [-3, 5], q: [0, 1] })], '5x − y + 20 = 0', { pts: [[-3, 5, '(−3, 5)'], [2, 5, ''], [-3, 6, '']], L: [lineOf(1, 5, -27, { col: C.ink })] }),
  B9('Ex 9.2', 'Q10', 'A line perpendicular to the segment joining (1, 0) and (2, 3) divides it in the ratio 1 : n. Find its equation.', [{ k: 'mcq', q: 'Dividing point ((n + 2)/(n + 1), 3/(n + 1)), slope −1/3 ⇒', o: ['(1 + n)x + 3(1 + n)y = n + 11', 'x + 3y = n + 11', '(1 + n)x − 3y = n', '3x + y = 1 + n'], a: 0, x: 'Multiply through by 3(1 + n).' }], '(1 + n)x + 3(1 + n)y = n + 11'),
  Q9('Ex 9.2', 'Q11', 'Line through (2, 3) cutting equal intercepts on the axes.', [-1, 6, -1, 6], [linePart('Drag a line with equal intercepts through (2, 3)', lineOf(1, 1, -5), { p: [0, 1], q: [1, 0] })], 'x + y = 5', { pts: [[2, 3, '(2, 3)']] }),
  Q9('Ex 9.2', 'Q12', 'Line through (2, 2) with intercepts summing to 9.', [-1, 7, -1, 7], [{ k: 'fields', q: 'x/a + y/b = 1 through (2, 2), a + b = 9 ⇒ ab = 18', f: [{ l: 'a', a: 3 }, { l: 'b', a: 6 }], x: '(3, 6) or (6, 3).' }, linePart('Drag one of the two lines', [lineOf(2, 1, -6), lineOf(1, 2, -6)], { p: [0, 1], q: [1, 0] })], '2x + y = 6 or x + 2y = 6', { pts: [[2, 2, '(2, 2)']] }),
  Q9('Ex 9.2', 'Q13', 'Line through (0, 2) at 2π/3 to the positive x-axis; also the parallel line crossing the y-axis 2 below the origin.', [-4, 4, -4, 4], [{ k: 'task', q: 'Rotate the line to 2π/3 = 120°', pre: async () => userLine(W, { mode: 'pivot', piv: [0, 2], deg: 45 }), check: (W) => W.ul.deg === 120, auto: (W) => (W.ul.deg = 120), reveal: (W) => (W.ul.deg = 120) }, { k: 'mcq', q: 'The two lines', o: ['√3x + y − 2 = 0 and √3x + y + 2 = 0', 'x + √3y = 2 and x + √3y = −2', '√3x − y + 2 = 0 and √3x − y − 2 = 0', 'y = −√3x only'], a: 0, x: 'Slope −√3, intercepts 2 and −2.', act: async () => drawLines(W, [lineOf(S3, 1, 2, { col: C['matcha-deep'], t: 'c = −2' })], 0.4) }], '√3x + y − 2 = 0 and √3x + y + 2 = 0'),
  Q9('Ex 9.2', 'Q14', 'The perpendicular from the origin meets a line at (−2, 9). Find the line.', [-6, 4, -1, 11], [{ k: 'num', q: 'Slope of OP = −9/2 ⇒ slope of the line = ?', a: 2 / 9, show: '2/9', x: '2/9.' }, { k: 'mcq', q: 'Line', o: ['2x − 9y + 85 = 0', '9x + 2y = 0', '2x − 9y − 85 = 0', '2x + 9y − 77 = 0'], a: 0, x: 'y − 9 = (2/9)(x + 2).', act: async () => drawLines(W, [lineOf(2, -9, 85, { col: C.beni })], 0.4) }], '2x − 9y + 85 = 0', { pts: [[-2, 9, 'P(−2, 9)'], [0, 0, 'O']], setup: (W) => W.vecs.push({ x0: 0, y0: 0, x1: -2, y1: 9, dash: true, col: C.ink }) }),
  B9('Ex 9.2', 'Q15', 'L = 124.942 at C = 20 and L = 125.134 at C = 110. Express L in terms of C.', [{ k: 'num', q: 'Slope = 0.192/90 ≈ ? (5 decimals)', a: 0.192 / 90, tol: 0.00001, show: '0.00213', x: '0.192/90.' }, { k: 'mcq', q: 'L = ?', o: ['0.192(C − 20)/90 + 124.942', '0.192C + 124.942', '90(C − 20)/0.192 + 124.942', '124.942 + C/90'], a: 0, x: 'Point–slope form through (20, 124.942).' }], 'L = (0.192/90)(C − 20) + 124.942'),
  B9('Ex 9.2', 'Q16', '980 L/week at Rs 14/L and 1220 L/week at Rs 16/L. Assuming a linear relation, how much at Rs 17/L?', [{ k: 'num', q: 'Extra litres per rupee = (1220 − 980)/2 = ?', a: 120, x: '120.' }, { k: 'num', q: 'At Rs 17: 1220 + 120 = ?', a: 1340, x: '1340 litres.' }], 'L = 120P − 700 ⇒ 1340 litres at Rs 17'),
  B9('Ex 9.2', 'Q17', 'P(a, b) is the mid-point of a segment between the axes. Show x/a + y/b = 2.', [prf(['Ends are (2a, 0) and (0, 2b)', 'Intercept form: x/(2a) + y/(2b) = 1', 'Multiply by 2: x/a + y/b = 2'])], 'Intercepts 2a, 2b ⇒ x/a + y/b = 2'),
  B9('Ex 9.2', 'Q18', 'R(h, k) divides a segment between the axes in the ratio 1 : 2. Find the line.', [{ k: 'mcq', q: 'Ends (a, 0), (0, b): R = (2a/3, b/3) ⇒ a = 3h/2, b = 3k. The line is', o: ['2kx + hy = 3hk', 'kx + 2hy = 3hk', 'x/h + y/k = 3', '2hx + ky = 3hk'], a: 0, x: 'x/(3h/2) + y/(3k) = 1.' }], '2kx + hy = 3hk'),
  Q9('Ex 9.2', 'Q19', 'Using the equation of a line, prove (3, 0), (−2, −2), (8, 2) are collinear.', [-3, 9, -3, 3], [linePart('Drag the line through (3, 0) and (−2, −2)', lineOf(2, -5, -6), { p: [0, 1], q: [1, 2] }), { k: 'tf', q: 'Does (8, 2) satisfy 2x − 5y − 6 = 0?', o: ['Yes: 16 − 10 − 6 = 0', 'No'], a: 0, x: 'So all three are collinear.' }], '2x − 5y − 6 = 0 passes through (8, 2)', { pts: [[3, 0, ''], [-2, -2, ''], [8, 2, '(8, 2)']] }),
];

/* ===================== EXERCISE 9.3 ===================== */
const EX93 = [
  B9('Ex 9.3', 'Q1', 'Reduce to slope–intercept form; find slopes and y-intercepts: (i) x + 7y = 0 (ii) 6x + 3y − 5 = 0 (iii) y = 0.', [{ k: 'fields', q: '(i) y = −x/7', f: [{ l: 'm', a: -1 / 7, show: '−1/7' }, { l: 'c', a: 0 }] }, { k: 'fields', q: '(ii) y = −2x + 5/3', f: [{ l: 'm', a: -2 }, { l: 'c', a: 5 / 3, show: '5/3' }] }, { k: 'fields', q: '(iii) y = 0·x + 0', f: [{ l: 'm', a: 0 }, { l: 'c', a: 0 }] }], '(i) −1/7, 0  (ii) −2, 5/3  (iii) 0, 0'),
  B9('Ex 9.3', 'Q2', 'Reduce to intercept form; find the intercepts: (i) 3x + 2y − 12 = 0 (ii) 4x − 3y = 6 (iii) 3y + 2 = 0.', [{ k: 'fields', q: '(i) x/4 + y/6 = 1', f: [{ l: 'a', a: 4 }, { l: 'b', a: 6 }] }, { k: 'fields', q: '(ii) x/(3/2) + y/(−2) = 1', f: [{ l: 'a', a: 1.5, show: '3/2' }, { l: 'b', a: -2 }] }, { k: 'mcq', q: '(iii) y = −2/3 is…', o: ['parallel to the x-axis: y-intercept −2/3, no x-intercept', 'x-intercept −2/3', 'both intercepts −2/3', 'through the origin'], a: 0, x: 'A horizontal line.' }], '(i) 4, 6  (ii) 3/2, −2  (iii) y-intercept −2/3 only'),
  Q9('Ex 9.3', 'Q3', 'Distance of (−1, 1) from 12(x + 6) = 5(y − 2).', [-9, 3, -2, 9], [{ k: 'mcq', q: 'General form', o: ['12x − 5y + 82 = 0', '12x + 5y + 82 = 0', '12x − 5y + 62 = 0', '12x − 5y − 82 = 0'], a: 0, x: '12x + 72 − 5y + 10 = 0.' }, { k: 'num', q: 'd = |−12 − 5 + 82|/13 = ?', a: 5, x: '5 units.' }], 'd = 65/13 = 5', { L: [lineOf(12, -5, 82, { col: C.ink })], setup: (W) => dropPoint(W, [-1, 1], W.L[0], { t: '(−1, 1)' }) }),
  Q9('Ex 9.3', 'Q4', 'Points on the x-axis at distance 4 from x/3 + y/4 = 1.', [-4, 10, -3, 6], [{ k: 'task', q: 'Slide P along the x-axis to a spot where d = 4', pre: async () => { const P = axisDrag(W, 'x', 1); W.tmp = P; W.feet.push({ P: () => [P.x, P.y], l: W.L[0] }); }, check: (W) => [8, -2].includes(W.tmp.x), auto: (W) => (W.tmp.x = 8), reveal: (W) => (W.tmp.x = 8) }, { k: 'fields', q: '|4a − 12|/5 = 4: both points', f: [{ l: 'a₁', a: 8 }, { l: 'a₂', a: -2 }], x: '(8, 0) and (−2, 0).' }], '(8, 0) and (−2, 0)', { L: [lineOf(4, 3, -12, { col: C.ink, t: '4x + 3y = 12' })] }),
  B9('Ex 9.3', 'Q5', 'Distance between the parallel lines (i) 15x + 8y − 34 = 0, 15x + 8y + 31 = 0 (ii) l(x + y) + p = 0, l(x + y) − r = 0.', [{ k: 'num', q: '(i) |−34 − 31|/17 = ?', a: 65 / 17, show: '65/17', x: '65/17.' }, { k: 'mcq', q: '(ii) d = ?', o: ['|p + r|/(|l|√2)', '|p − r|/√2', '(p + r)/l', '|p + r|/√2'], a: 0, x: '√(l² + l²) = |l|√2.' }], '(i) 65/17  (ii) |p + r|/(|l|√2)'),
  Q9('Ex 9.3', 'Q6', 'Line parallel to 3x − 4y + 2 = 0 through (−2, 3).', [-5, 4, -1, 7], [linePart('Drag a parallel line through (−2, 3)', lineOf(3, -4, 18), { p: [-2, 2], q: [1, 2] })], '3x − 4y + 18 = 0', { pts: [[-2, 3, '(−2, 3)']], L: [lineOf(3, -4, 2, { col: C.ink })] }),
  Q9('Ex 9.3', 'Q7', 'Line perpendicular to x − 7y + 5 = 0 with x-intercept 3.', [-2, 6, -2, 8], [linePart('Drag the line', lineOf(7, 1, -21), { p: [0, 0], q: [1, 1] })], '7x + y − 21 = 0', { L: [lineOf(1, -7, 5, { col: C.ink })], pts: [[3, 0, '(3, 0)']] }),
  Q9('Ex 9.3', 'Q8', 'Angles between √3x + y = 1 and x + √3y = 1.', [-2, 3, -2, 3], [{ k: 'fields', q: 'Inclinations 120° and 150°. Angles between them', f: [{ l: 'acute', a: 30 }, { l: 'obtuse', a: 150 }], x: '30° and 150°.' }], '30° and 150°', { L: [lineOf(S3, 1, -1, { t: '√3x + y = 1' }), lineOf(1, S3, -1, { col: C['matcha-deep'], t: 'x + √3y = 1', tAt: 0.2 })] }),
  B9('Ex 9.3', 'Q9', 'The line through (h, 3) and (4, 1) meets 7x − 9y − 19 = 0 at right angles. Find h.', [{ k: 'num', q: '(1 − 3)/(4 − h) = −9/7 ⇒ h = ?', a: 22 / 9, show: '22/9', x: 'h = 22/9.' }], 'h = 22/9'),
  B9('Ex 9.3', 'Q10', 'Prove the line through (x₁, y₁) parallel to Ax + By + C = 0 is A(x − x₁) + B(y − y₁) = 0.', [prf(['Parallel ⇒ slope −A/B', 'y − y₁ = (−A/B)(x − x₁)', 'B(y − y₁) = −A(x − x₁)', 'A(x − x₁) + B(y − y₁) = 0'])], 'Point–slope with m = −A/B'),
  Q9('Ex 9.3', 'Q11', 'Two lines through (2, 3) meet at 60°. One has slope 2. Find the other.', [-2, 6, -1, 7], [{ k: 'task', q: 'Rotate your line to make 60° with the black line', todo: 'Black: slope 2 (63.4°). Two answers work.', pre: async () => userLine(W, { mode: 'pivot', piv: [2, 3], deg: 63 }), check: (W) => [3, 4, 123, 124].includes(W.ul.deg), auto: (W) => (W.ul.deg = 123), reveal: (W) => (W.ul.deg = 123) }, { k: 'mcq', q: '|(m − 2)/(1 + 2m)| = √3 gives…', o: ['(√3 + 2)x + (2√3 − 1)y = 8√3 + 1 or (√3 − 2)x + (2√3 + 1)y = 8√3 − 1', 'y − 3 = √3(x − 2)', '(2 + √3)x − y = 4', 'x + 2y = 8'], a: 0, x: 'm = (2 + √3)/(1 − 2√3) or (2 − √3)/(1 + 2√3).' }], '(√3 + 2)x + (2√3 − 1)y = 8√3 + 1  or  (√3 − 2)x + (2√3 + 1)y = 8√3 − 1', { L: [lineOf(2, -1, -1, { col: C.ink, t: 'm = 2' })] }),
  Q9('Ex 9.3', 'Q12', 'Right bisector of the segment joining (3, 4) and (−1, 2).', [-3, 5, -1, 6], [linePart('Drag the perpendicular bisector', lineOf(2, 1, -5), { p: [0, 0], q: [1, 0] })], 'Mid-point (1, 3), slope −2: 2x + y − 5 = 0', { pts: [[3, 4, '(3, 4)'], [-1, 2, '(−1, 2)']], setup: (W) => W.vecs.push({ x0: 3, y0: 4, x1: -1, y1: 2, col: C.ink, dash: true }) }),
  Q9('Ex 9.3', 'Q13', 'Foot of the perpendicular from (−1, 3) to 3x − 4y − 16 = 0.', [-3, 6, -4, 5], [{ k: 'fields', q: 'Foot (x, y)', f: [{ l: 'x', a: 68 / 25, show: '68/25' }, { l: 'y', a: -49 / 25, show: '−49/25' }], x: '(68/25, −49/25).' }], 'Foot = (68/25, −49/25)', { L: [lineOf(3, -4, -16, { col: C.ink })], setup: (W) => dropPoint(W, [-1, 3], W.L[0], { t: '(−1, 3)' }) }),
  Q9('Ex 9.3', 'Q14', 'The perpendicular from the origin to y = mx + c meets it at (−1, 2). Find m and c.', [-4, 3, -1, 5], [{ k: 'fields', q: 'Slope of OP is −2', f: [{ l: 'm', a: 0.5, show: '1/2' }, { l: 'c', a: 2.5, show: '5/2' }], x: 'm = 1/2; 2 = −1/2 + c.', act: async () => drawLines(W, [lineOf(1, -2, 5, { col: C.beni })], 0.4) }], 'm = 1/2, c = 5/2', { pts: [[-1, 2, '(−1, 2)']], setup: (W) => W.vecs.push({ x0: 0, y0: 0, x1: -1, y1: 2, dash: true, col: C.ink }) }),
  B9('Ex 9.3', 'Q15', 'p, q are perpendiculars from the origin to x cos θ − y sin θ = k cos 2θ and x sec θ + y cosec θ = k. Prove p² + 4q² = k².', [prf(['p = |k cos 2θ|/√(cos²θ + sin²θ) = |k cos 2θ|', 'q = |k|/√(sec²θ + cosec²θ) = |k sin θ cos θ|', '4q² = k² sin² 2θ', 'p² + 4q² = k²(cos² 2θ + sin² 2θ) = k²'])], 'p² + 4q² = k²'),
  Q9('Ex 9.3', 'Q16', 'Triangle A(2, 3), B(4, −1), C(1, 2). Equation and length of the altitude from A.', [-1, 6, -2, 5], [linePart('Drag the altitude from A (⟂ BC)', lineOf(1, -1, 1), { p: [0, 0], q: [1, -1] }), { k: 'num', q: 'Length = |2 + 3 − 3|/√2 = ? (type √2 or a decimal)', a: Math.SQRT2, show: '√2', keys: '√', tol: 0.01, x: '√2.' }], 'x − y + 1 = 0, length √2', { pts: [[2, 3, 'A'], [4, -1, 'B'], [1, 2, 'C']], L: [lineOf(1, 1, -3, { col: C.ink, t: 'BC' })], setup: (W) => W.polys.push({ pts: [[2, 3], [4, -1], [1, 2]], col: C['sora-tint'], a: 0.5 }) }),
  B9('Ex 9.3', 'Q17', 'p is the perpendicular from the origin to the line with intercepts a and b. Show 1/p² = 1/a² + 1/b².', [prf(['Line: x/a + y/b = 1, i.e. bx + ay − ab = 0', 'p = |ab|/√(a² + b²)', '1/p² = (a² + b²)/(a²b²)', '= 1/a² + 1/b²'])], '1/p² = 1/a² + 1/b²'),
];

/* ===================== MISCELLANEOUS ===================== */
const EX9M = [
  B9('Misc', 'Q1', '(k − 3)x − (4 − k²)y + k² − 7k + 6 = 0 is (a) ∥ x-axis (b) ∥ y-axis (c) through the origin. Find k.', [{ k: 'num', q: '(a) x-coefficient 0 ⇒ k = ?', a: 3, x: 'k = 3.' }, { k: 'mcq', q: '(b) y-coefficient 0 ⇒ k = ?', o: ['±2', '2', '4', '±4'], a: 0, x: '4 − k² = 0.' }, { k: 'fields', q: '(c) k² − 7k + 6 = 0', f: [{ l: 'k₁', a: 1 }, { l: 'k₂', a: 6 }], x: 'k = 1 or 6.' }], '(a) 3  (b) ±2  (c) 1, 6'),
  B9('Misc', 'Q2', 'Lines with intercepts whose sum is 1 and product −6.', [{ k: 'fields', q: 'a + b = 1, ab = −6', f: [{ l: 'a', a: 3 }, { l: 'b', a: -2 }], x: '3 and −2 (either order).' }, { k: 'mcq', q: 'Lines', o: ['2x − 3y = 6 and −3x + 2y = 6', '2x + 3y = 6 only', 'x − y = 1', '3x − 2y = 6'], a: 0, x: 'x/3 − y/2 = 1 and −x/2 + y/3 = 1.' }], '2x − 3y − 6 = 0 and −3x + 2y − 6 = 0'),
  Q9('Misc', 'Q3', 'Points on the y-axis at distance 4 from x/3 + y/4 = 1.', [-4, 7, -4, 12], [{ k: 'task', q: 'Slide P along the y-axis to a spot where d = 4', pre: async () => { const P = axisDrag(W, 'y', 1, 1 / 3); W.tmp = P; W.feet.push({ P: () => [P.x, P.y], l: W.L[0] }); }, check: (W) => Math.abs(W.tmp.y - 32 / 3) < 0.01 || Math.abs(W.tmp.y + 8 / 3) < 0.01, auto: (W) => (W.tmp.y = 32 / 3), reveal: (W) => (W.tmp.y = 32 / 3) }, { k: 'fields', q: '|3b − 12|/5 = 4', f: [{ l: 'b₁', a: 32 / 3, show: '32/3' }, { l: 'b₂', a: -8 / 3, show: '−8/3' }], x: '(0, 32/3), (0, −8/3).' }], '(0, 32/3) and (0, −8/3)', { L: [lineOf(4, 3, -12, { col: C.ink })] }),
  B9('Misc', 'Q4', 'Perpendicular distance from the origin to the line joining (cos θ, sin θ) and (cos φ, sin φ).', [{ k: 'mcq', q: 'Both points lie on the unit circle; distance to the chord = ?', o: ['|cos((θ − φ)/2)|', '|sin((θ − φ)/2)|', '1', '|cos(θ − φ)|'], a: 0, x: 'Half-angle of the chord.' }], 'd = |cos((θ − φ)/2)|'),
  B9('Misc', 'Q5', 'Line parallel to the y-axis through the intersection of x − 7y + 5 = 0 and 3x + y = 0.', [{ k: 'num', q: 'Intersection x = ?', a: -5 / 22, show: '−5/22', x: 'y = 15/22, x = −5/22.' }], 'x = −5/22'),
  Q9('Misc', 'Q6', 'Line perpendicular to x/4 + y/6 = 1 through the point where it meets the y-axis.', [-7, 5, -1, 8], [linePart('Drag the perpendicular through (0, 6)', lineOf(2, -3, 18), { p: [0, 0], q: [1, 0] })], '2x − 3y + 18 = 0', { L: [lineOf(3, 2, -12, { col: C.ink })], pts: [[0, 6, '(0, 6)']] }),
  Q9('Misc', 'Q7', 'Area of the triangle formed by y − x = 0, x + y = 0 and x − k = 0.', [-1, 4, -3, 3], [{ k: 'mcq', q: 'Vertices (0, 0), (k, k), (k, −k) ⇒ area = ?', o: ['k²', '2k²', 'k²/2', 'k'], a: 0, x: '½ · 2k · k.' }], 'Area = k²', { L: [lineOf(1, -1, 0), lineOf(1, 1, 0, { col: C['matcha-deep'] }), lineOf(1, 0, -2, { col: C.beni, t: 'x = k' })], setup: (W) => W.polys.push({ pts: [[0, 0], [2, 2], [2, -2]], col: C['kin-tint'], a: 0.6 }) }),
  B9('Misc', 'Q8', 'Find p so that 3x + y − 2 = 0, px + 2y − 3 = 0 and 2x − y − 3 = 0 meet at one point.', [{ k: 'fields', q: 'First and third meet at', f: [{ l: 'x', a: 1 }, { l: 'y', a: -1 }] }, { k: 'num', q: 'p − 2 − 3 = 0 ⇒ p = ?', a: 5, x: 'p = 5.' }], 'Meet at (1, −1) ⇒ p = 5'),
  B9('Misc', 'Q9', 'If y = m₁x + c₁, y = m₂x + c₂, y = m₃x + c₃ are concurrent, show m₁(c₂ − c₃) + m₂(c₃ − c₁) + m₃(c₁ − c₂) = 0.', [prf(['First two meet at x = (c₂ − c₁)/(m₁ − m₂)', 'y = (m₁c₂ − m₂c₁)/(m₁ − m₂)', 'Substitute into y = m₃x + c₃', 'Rearrange: m₁(c₂ − c₃) + m₂(c₃ − c₁) + m₃(c₁ − c₂) = 0'])], 'Common point satisfies the third line'),
  Q9('Misc', 'Q10', 'Lines through (3, 2) making 45° with x − 2y = 3.', [-1, 7, -3, 6], [linePart('Drag a line through (3, 2) at 45° to the black line', [lineOf(3, -1, -7), lineOf(1, 3, -9)], { p: [3, 2], q: [5, 2] }), { k: 'mcq', q: 'Both answers', o: ['3x − y − 7 = 0 and x + 3y − 9 = 0', 'x − y − 1 = 0 only', '3x + y = 11', 'x − 3y + 3 = 0'], a: 0, x: 'm = 3 or −1/3.' }], '3x − y − 7 = 0 and x + 3y − 9 = 0', { L: [lineOf(1, -2, -3, { col: C.ink })], pts: [[3, 2, '(3, 2)']] }),
  B9('Misc', 'Q11', 'Line through the intersection of 4x + 7y − 3 = 0 and 2x − 3y + 1 = 0 with equal intercepts.', [{ k: 'fields', q: 'Intersection', f: [{ l: 'x', a: 1 / 13, show: '1/13' }, { l: 'y', a: 5 / 13, show: '5/13' }] }, { k: 'mcq', q: 'x + y = a through it gives', o: ['13x + 13y = 6', 'x + y = 1', '13x − 13y = 4', 'x + y = 13'], a: 0, x: 'a = 6/13.' }], '13x + 13y = 6'),
  B9('Misc', 'Q12', 'Show the line through the origin at angle θ to y = mx + c is y/x = (m ± tan θ)/(1 ∓ m tan θ).', [prf(['Let the required slope be y/x = m₁', 'tan θ = |(m₁ − m)/(1 + m m₁)|', 'Solve both signs for m₁', 'm₁ = (m ± tan θ)/(1 ∓ m tan θ)'])], 'y/x = (m ± tan θ)/(1 ∓ m tan θ)'),
  B9('Misc', 'Q13', 'In what ratio does x + y = 4 divide the line joining (−1, 1) and (5, 7)?', [{ k: 'num', q: 'Point (5k − 1, 7k + 1)/(k + 1) on x + y = 4 ⇒ k = ?', a: 0.5, show: '1/2', x: 'k = 1/2: ratio 1 : 2.' }], 'Ratio 1 : 2'),
  Q9('Misc', 'Q14', 'Distance of 4x + 7y + 5 = 0 from (1, 2) along 2x − y = 0.', [-2, 3, -2, 3], [{ k: 'fields', q: 'Where 2x − y = 0 meets the line', f: [{ l: 'x', a: -5 / 18, show: '−5/18' }, { l: 'y', a: -5 / 9, show: '−5/9' }], act: async () => W.pts.push(pt9(-5 / 18, -5 / 9, 'Q')) }, { k: 'num', q: 'Distance from (1, 2) = ?  (23√5/18)', a: (23 * Math.sqrt(5)) / 18, show: '23√5/18', keys: '√', tol: 0.01, x: '≈ 2.857.' }], 'd = 23√5/18', { L: [lineOf(4, 7, 5, { col: C.ink }), lineOf(2, -1, 0, { col: C.sora })], pts: [[1, 2, '(1, 2)']] }),
  Q9('Misc', 'Q15', 'Direction of a line through (−1, 2) whose intersection with x + y = 4 is 3 units away.', [-3, 4, -1, 6], [{ k: 'task', q: 'Rotate the line so the meeting point is 3 away', pre: async () => { userLine(W, { mode: 'pivot', piv: [-1, 2], deg: 45 }); W.read = false; W.labs.push({ x: 0.5, y: 5.5, t: () => { const M = L9.meet(W.ul.line(), W.L[0]); return M ? 'distance ' + fmtN(Math.hypot(M[0] + 1, M[1] - 2), 2) : 'parallel'; } }); }, check: (W) => [0, 90].includes(W.ul.deg), auto: (W) => (W.ul.deg = 0), reveal: (W) => (W.ul.deg = 0) }, { k: 'mcq', q: 'The line must be…', o: ['parallel to the x-axis or the y-axis', 'at 45°', 'at 135°', 'only horizontal'], a: 0, x: 'cos θ + sin θ = 1 ⇒ θ = 0° or 90°.' }], 'θ = 0° or 90°: parallel to an axis', { L: [lineOf(1, 1, -4, { col: C.ink })] }),
  Q9('Misc', 'Q16', 'The hypotenuse of a right triangle joins (1, 3) and (−4, 1). Find the legs parallel to the axes.', [-6, 3, -1, 5], [{ k: 'mcq', q: 'The right-angle vertex is', o: ['(1, 1) or (−4, 3)', '(1, 3)', '(0, 0)', '(−4, 1)'], a: 0, x: 'Two possible triangles.', act: async () => { W.polys.push({ pts: [[1, 3], [-4, 1], [1, 1]], col: C['sora-tint'], a: 0.5 }, { pts: [[1, 3], [-4, 1], [-4, 3]], col: C.sakura, a: 0.4 }); SFX.swish(); } }, { k: 'mcq', q: 'Legs', o: ['x = 1, y = 1  or  x = −4, y = 3', 'x = 1, y = 3', 'y = 1, y = 3', 'x = −4, x = 1'], a: 0, x: 'Both pairs.' }], 'x = 1, y = 1 or x = −4, y = 3', { pts: [[1, 3, '(1, 3)'], [-4, 1, '(−4, 1)']] }),
  Q9('Misc', 'Q17', 'Image of (3, 8) in the line x + 3y = 7.', [-3, 6, -6, 9], [{ k: 'run', run: async () => { const P = pt9(3, 8, 'P'); W.pts.push(P); W.mirrors.push({ P: () => [3, 8], l: W.L[0], k: 0 }); const b = button('Reflect!'); await waitFor(() => b.clicked()); b.stop(); gsap.to(W.mirrors[0], { k: 1, duration: 0.8 }); SFX.whoosh(); await wait(0.9); } }, { k: 'fields', q: 'Image', f: [{ l: 'x', a: -1 }, { l: 'y', a: -4 }], x: '(−1, −4).' }], 'Image (−1, −4)', { L: [lineOf(1, 3, -7, { col: C.ink })] }),
  B9('Misc', 'Q18', 'y = 3x + 1 and 2y = x + 3 are equally inclined to y = mx + 4. Find m.', [{ k: 'mcq', q: '(m − 3)/(1 + 3m) = −(m − 1/2)/(1 + m/2) gives 7m² − 2m − 7 = 0, so m = ?', o: ['(1 ± 5√2)/7', '(1 ± √2)/7', '±1', '(2 ± 5√2)/7'], a: 0, x: 'The other sign gives m² = −1: no real m.' }], '7m² − 2m − 7 = 0 ⇒ m = (1 ± 5√2)/7'),
  B9('Misc', 'Q19', 'The sum of distances of P(x, y) from x + y − 5 = 0 and 3x − 2y + 7 = 0 is always 10. Show P moves on a line.', [prf(['|x + y − 5|/√2 + |3x − 2y + 7|/√13 = 10', 'In any one region the signs are fixed', 'So it is (±)(x + y − 5)/√2 + (±)(3x − 2y + 7)/√13 = 10', 'First degree in x, y ⇒ a straight line'])], 'A first-degree equation ⇒ a line'),
  B9('Misc', 'Q20', 'Line equidistant from the parallel lines 9x + 6y − 7 = 0 and 3x + 2y + 6 = 0.', [{ k: 'mcq', q: 'Rewrite the second as 9x + 6y + 18 = 0; midway constant = (−7 + 18)/2', o: ['18x + 12y + 11 = 0', '9x + 6y + 11 = 0', '3x + 2y − 1 = 0', '18x + 12y − 11 = 0'], a: 0, x: '9x + 6y + 11/2 = 0.' }], '18x + 12y + 11 = 0'),
  Q9('Misc', 'Q21', 'A ray through (1, 2) reflects on the x-axis at A and then passes through (5, 3). Find A.', [-1, 7, -4, 4], [{ k: 'task', q: 'Slide A until the path is shortest (angle in = angle out)', pre: async () => { const A = axisDrag(W, 'x', 1, 0.2); W.tmp = A; W.vecs.push({ x0: 1, y0: 2, x1: 1, y1: 0, col: C.kin }, { x0: 1, y0: 0, x1: 5, y1: 3, col: C.kin }); W.tickV = () => { W.vecs[0].x1 = A.x; W.vecs[1].x0 = A.x; }; W.labs.push({ x: 3, y: -3.4, t: () => 'path ' + fmtN(Math.hypot(A.x - 1, 2) + Math.hypot(5 - A.x, 3), 3) }); }, check: (W) => Math.abs(W.tmp.x - 2.6) < 0.01, auto: (W) => (W.tmp.x = 2.6), reveal: (W) => (W.tmp.x = 2.6) }, { k: 'num', q: 'Reflect (5, 3) to (5, −3) and join to (1, 2). A = (?, 0)', a: 2.6, show: '13/5', x: 'A = (13/5, 0).' }], 'A = (13/5, 0)', { pts: [[1, 2, '(1, 2)'], [5, 3, '(5, 3)']] }),
  B9('Misc', 'Q22', 'Prove the product of perpendiculars from (±√(a² − b²), 0) to (x/a) cos θ + (y/b) sin θ = 1 is b².', [prf(['p₁ = |(√(a² − b²)/a) cos θ − 1| / √(cos²θ/a² + sin²θ/b²)', 'p₂ = |(√(a² − b²)/a) cos θ + 1| / (same root)', 'p₁p₂ = |1 − (a² − b²)cos²θ/a²| / (cos²θ/a² + sin²θ/b²)', 'Numerator = b²(cos²θ/a² + sin²θ/b²) ⇒ p₁p₂ = b²'])], 'p₁p₂ = b²'),
  B9('Misc', 'Q23', 'A person at the junction of 2x − 3y + 4 = 0 and 3x + 4y − 5 = 0 wants to reach 6x − 7y + 8 = 0 in the least time. Find the path.', [{ k: 'fields', q: 'Junction', f: [{ l: 'x', a: -1 / 17, show: '−1/17' }, { l: 'y', a: 22 / 17, show: '22/17' }] }, { k: 'mcq', q: 'Shortest path ⟂ to 6x − 7y + 8 = 0 (slope −7/6):', o: ['119x + 102y − 125 = 0', '6x − 7y + 8 = 0', '7x + 6y − 7 = 0', '119x − 102y + 125 = 0'], a: 0, x: 'y − 22/17 = −(7/6)(x + 1/17).' }], '119x + 102y − 125 = 0'),
];

const BOSS9 = [['Slope through (1, 2) and (3, 8)', ['3', '1/3', '6', '−3'], 0], ['Perpendicular to slope 2/3', ['−3/2', '3/2', '2/3', '−2/3'], 0], ['Slope of a vertical line', ['undefined', '0', '1', '∞ = 1'], 0], ['x/2 + y/3 = 1: y-intercept', ['3', '2', '1/3', '6'], 0], ['Distance of (0, 0) from 3x + 4y = 10', ['2', '10', '5', '7'], 0], ['Lines 2x + 3y = 5 and 4x + 6y = 1 are', ['parallel', 'perpendicular', 'the same', 'meeting at 45°'], 0], ['Slope of 3x − 6y + 1 = 0', ['1/2', '−1/2', '2', '3'], 0], ['Line through (1, 1) with slope 0', ['y = 1', 'x = 1', 'y = x', 'y = 0'], 0], ['Image of (2, 3) in the x-axis', ['(2, −3)', '(−2, 3)', '(3, 2)', '(−2, −3)'], 0], ['Inclination of y = x', ['45°', '30°', '60°', '90°'], 0]];

LESSONS.splice(1, 0, exLesson({ id: 'ex91', title: 'Exercise 9.1', blurb: 'All 11: areas, slopes, angles, right triangles and parallelograms.', face: 'kimmy-playful', qs: EX91 }));
LESSONS.splice(3, 0, exLesson({ id: 'ex92', title: 'Exercise 9.2', blurb: 'All 19: drag every line into place.', face: 'jess-happy', qs: EX92 }));
LESSONS.splice(5, 0, exLesson({ id: 'ex93', title: 'Exercise 9.3', blurb: 'All 17: forms, distances, feet of perpendiculars.', face: 'kimmy-excited', qs: EX93 }));
LESSONS.push(exLesson({ id: 'misc', title: 'Miscellaneous', blurb: 'All 23 Miscellaneous Exercise questions.', face: 'jess-thinking', qs: EX9M }));
LESSONS.push(lesson({ id: 'boss', title: 'Boss Battle', blurb: 'Ten fast questions. Speed points. Beat Kimmy.', face: 'jess-excited', steps: [async function () { enterScene('board', (W) => { W.tag = 'BOSS'; W.sub = 'Chapter 9'; }); await slam('BOSS BATTLE', '10 questions · speed counts'); await K('play', 'Rise over run!'); await cont('Fight'); }, ...BOSS9.map(([q, o, a], i) => async function () { enterScene('board', (W) => { W.tag = 'Q' + (i + 1); W.sub = 'Boss Battle'; }); await quiz(q, o, a, plain(o[a]) + '.', null, 15); await cont(); }), async function () { enterScene('board', (W) => { W.tag = 'K.O.!'; W.sub = 'Chapter 9'; }); await summary(['Chapter 9 complete!', { t: 'y − y₀ = m(x − x₀),  d = |Ax₁ + By₁ + C|/√(A² + B²)', eq: true }]); }] }));
LESSONS.forEach((l) => { if (l.kind === 'ex') l.short = l.id === 'misc' ? 'M' : l.title.replace('Exercise ', ''); });
