/* =========================================================
   CLASS 12 · CHAPTER 10 — Exercises 10.1 and 10.2
   ========================================================= */
const S6 = Math.sqrt(6), S3 = Math.sqrt(3), S2 = Math.SQRT2, S14 = Math.sqrt(14), S30 = Math.sqrt(30);
const bearing = (v) => { let b = 90 - (Math.atan2(v[1], v[0]) * 180) / Math.PI; b = ((b % 360) + 360) % 360; return Math.round(b); };
const bearTxt = (b) => (b <= 90 ? 'N ' + b + '° E' : b <= 180 ? 'S ' + (180 - b) + '° E' : b <= 270 ? 'S ' + (b - 180) + '° W' : 'N ' + (360 - b) + '° W');
/* a vector question in space: draw the arrows, then the parts */
const v3Q = (ex, n, q, arrows, parts, w, o = {}) => vQ(ex, n, q, { d3: true, R: o.R || 5, arr: arrows, tri: o.tri, para: o.para, dots: o.dots }, parts, w, o);
const unitRun = (i, col) => runP(async (W) => { const a = W.arr[i], u = V.unit(v3(a.v)); W.arr.push({ v: a.v.slice(), o: a.o, col: col || C.beni, t: 'unit', p: 1 }); const b = W.arr[W.arr.length - 1]; SFX.swish(); await tw({ k: 1 }, { k: 0, duration: AUTO ? 0.05 : 0.9, onUpdate() { const k = this.targets()[0].k; b.v = V.add(V.mul(k, v3(a.v)), V.mul(1 - k, u)); } }); SFX.pop(); });

/* ===================== EXERCISE 10.1 ===================== */
const EX101 = [
  { ex: 'Ex 10.1', n: 'Q1', q: 'Represent graphically a displacement of 40 km, 30° east of north (scale: 1 square = 10 km)', scene: 'vec',
    setup: (W) => { vecSet(W, { v: [-5, 5, -1.2, 5], arr: [{ v: [2, 0, 0], col: C.sora, t: 'OP' }] }); W.rd = () => { const v = W.arr[0].v; return [['length = ' + fmtN(V.norm(v) * 10, 1) + ' km', C.sora], ['bearing: ' + bearTxt(bearing(v)), C.beni]]; }; },
    parts: [{ k: 'task', q: 'Drag the gold head: 40 km at N 30° E', pre: async (W) => dragHeads(W, [0], { polar: [5, 0.5] }), check: (W) => Math.abs(V.norm(W.arr[0].v) - 4) < 0.01 && bearing(W.arr[0].v) === 30, auto: (W) => (W.arr[0].v = [4 * Math.cos(Math.PI / 3), 4 * Math.sin(Math.PI / 3), 0]), reveal: (W) => (W.arr[0].v = [2, 2 * S3, 0]), todo: 'Length 4 squares, turned 30° from north towards east.' },
      mcqP('Its angle with the positive x-axis (east) is', ['60°', '30°', '120°', '45°'], '90° − 30° = 60°.')],
    w: ['A 4-unit arrow at 30° east of north'] },
  bQ('Ex 10.1', 'Q2', 'Classify as scalars and vectors: (i) 10 kg (ii) 2 m north-west (iii) 40° (iv) 40 watt (v) 10⁻¹⁹ coulomb (vi) 20 m/s²', [{ k: 'pick', q: 'Tap the vectors', pool: ['10 kg', '2 m north-west', '40°', '40 watt', '10⁻¹⁹ coulomb', '20 m/s²'], a: ['2 m north-west', '20 m/s²'], brace: false, x: 'A displacement (2 m NW) and an acceleration (20 m/s²) have direction. Mass, angle, power and charge are scalars.' }], 'Vectors: (ii), (vi). Scalars: (i), (iii), (iv), (v)'),
  bQ('Ex 10.1', 'Q3', 'Classify as scalar and vector quantities: (i) time period (ii) distance (iii) force (iv) velocity (v) work done', [{ k: 'pick', q: 'Tap the vectors', pool: ['time period', 'distance', 'force', 'velocity', 'work done'], a: ['force', 'velocity'], brace: false, x: 'Force and velocity have direction. Work done is a scalar (it is a dot product!).' }], 'Vectors: force, velocity'),
  { ex: 'Ex 10.1', n: 'Q4', q: 'In Fig 10.6 (a square), identify the vectors that are (i) coinitial (ii) equal (iii) collinear but not equal', scene: 'vec',
    setup: (W) => vecSet(W, { v: [-3.6, 3.6, -2.6, 2.6], arr: [{ o: [-2, 2, 0], v: [4, 0, 0], col: C.sora, t: 'a⃗' }, { o: [2, 2, 0], v: [0, -4, 0], col: C.beni, t: 'b⃗' }, { o: [2, -2, 0], v: [-4, 0, 0], col: C['matcha-deep'], t: 'c⃗' }, { o: [-2, 2, 0], v: [0, -4, 0], col: C.kin, t: 'd⃗' }] }),
    parts: [{ k: 'pick', q: '(i) Coinitial', pool: ['a⃗', 'b⃗', 'c⃗', 'd⃗'], a: ['a⃗', 'd⃗'], brace: false, x: 'a⃗ and d⃗ start at the same corner.' }, { k: 'pick', q: '(ii) Equal', pool: ['a⃗', 'b⃗', 'c⃗', 'd⃗'], a: ['b⃗', 'd⃗'], brace: false, x: 'Same length, same direction (down).' }, { k: 'pick', q: '(iii) Collinear but not equal', pool: ['a⃗', 'b⃗', 'c⃗', 'd⃗'], a: ['a⃗', 'c⃗'], brace: false, x: 'Parallel, but opposite directions.' }],
    w: ['(i) a⃗, d⃗ (ii) b⃗, d⃗ (iii) a⃗, c⃗'] },
  { ex: 'Ex 10.1', n: 'Q5', q: 'True or false', scene: 'vec', setup: (W) => vecSet(W, { v: [-4, 4, -2.6, 2.6], arr: [{ v: [2, 1, 0], col: C.sora, t: 'a⃗' }, { o: [0, -1, 0], v: [-2, -1, 0], col: C.beni, t: '−a⃗' }] }),
    parts: [{ k: 'tf', q: '(i) a⃗ and −a⃗ are collinear', a: true, x: 'Parallel to the same line.' }, { k: 'tf', q: '(ii) Two collinear vectors are always equal in magnitude', a: false, x: 'a⃗ and 2a⃗ are collinear.' }, { k: 'tf', q: '(iii) Two vectors having the same magnitude are collinear', a: false, x: 'î and ĵ both have length 1.' }, { k: 'tf', q: '(iv) Two collinear vectors having the same magnitude are equal', a: false, x: 'a⃗ and −a⃗.' }],
    w: ['T, F, F, F'] },
];

/* ===================== EXERCISE 10.2 ===================== */
const a17 = [3, -4, -4], b17 = [2, -1, 1], c17 = [1, -3, -5];
const EX102 = [
  v3Q('Ex 10.2', 'Q1', 'Magnitudes of a⃗ = î + ĵ + k̂, b⃗ = 2î − 7ĵ − 3k̂, c⃗ = (1/√3)î + (1/√3)ĵ − (1/√3)k̂', [A3([1, 1, 1], C.sora, 'a⃗'), A3([2, -7, -3], C.beni, 'b⃗'), A3([1 / S3, 1 / S3, -1 / S3], C['matcha-deep'], 'c⃗')], [numP('|a⃗| = ?', S3, '√3'), numP('|b⃗| = ?', Math.sqrt(62), '√62', '4 + 49 + 9 = 62.'), numP('|c⃗| = ?', 1, '1', '⅓ + ⅓ + ⅓ = 1: a unit vector.')], '√3, √62, 1', { R: 8 }),
  { ex: 'Ex 10.2', n: 'Q2', q: 'Write two different vectors having the same magnitude', scene: 'vec', setup: (W) => { vecSet(W, { v: [-5, 5, -3.5, 3.5], arr: [{ v: [3, 0, 0], col: C.sora, t: 'a⃗' }, { v: [1, 2, 0], col: C.beni, t: 'b⃗' }] }); W.rd = () => [['|a⃗| = ' + rt(V.dot(W.arr[0].v, W.arr[0].v)), C.sora], ['|b⃗| = ' + rt(V.dot(W.arr[1].v, W.arr[1].v)), C.beni]]; },
    parts: [{ k: 'task', q: 'Drag b⃗ so |b⃗| = |a⃗| but b⃗ ≠ a⃗', pre: async (W) => dragHeads(W, [1]), check: (W) => Math.abs(V.norm(W.arr[1].v) - 3) < 1e-9 && V.norm(V.sub(W.arr[1].v, W.arr[0].v)) > 1e-9, auto: (W) => (W.arr[1].v = [0, 3, 0]), todo: 'e.g. 3ĵ, or −3î.' }, mcqP('Which pair also works?', ['î + 2ĵ + 3k̂ and 3î + 2ĵ + k̂', 'î and 2î', 'î + ĵ and î', '2ĵ and ĵ'], 'Both have magnitude √14.')], w: ['e.g. a⃗ = î + 2ĵ + 3k̂, b⃗ = 3î + 2ĵ + k̂ (both √14)'] },
  { ex: 'Ex 10.2', n: 'Q3', q: 'Write two different vectors having the same direction', scene: 'vec', setup: (W) => vecSet(W, { v: [-5, 5, -3.5, 3.5], arr: [{ v: [2, 1, 0], col: C.sora, t: 'a⃗' }, { v: [-1, 2, 0], col: C.beni, t: 'b⃗' }] }),
    parts: [{ k: 'task', q: 'Drag b⃗ to point the same way as a⃗, with a different length', pre: async (W) => dragHeads(W, [1]), check: (W) => { const a = W.arr[0].v, b = W.arr[1].v; return Math.abs(V.cross(a, b)[2]) < 1e-9 && V.dot(a, b) > 0 && Math.abs(V.norm(b) - V.norm(a)) > 1e-9; }, auto: (W) => (W.arr[1].v = [4, 2, 0]), todo: 'b⃗ = λa⃗ with λ > 0, λ ≠ 1.' }, mcqP('Which pair has the same direction?', ['î + ĵ + k̂ and 2î + 2ĵ + 2k̂', 'î + ĵ and −î − ĵ', 'î and ĵ', 'î + ĵ and î − ĵ'], 'A positive multiple.')], w: ['e.g. î + ĵ + k̂ and 2î + 2ĵ + 2k̂'] },
  vQ('Ex 10.2', 'Q4', 'Find x and y so that 2î + 3ĵ and xî + yĵ are equal', { v: [-1, 4, -1, 4], arr: [A3([2, 3, 0], C.sora, '2î + 3ĵ')] }, [fldP('Equal vectors: equal components', [{ l: 'x', a: 2 }, { l: 'y', a: 3 }], 'Compare î and ĵ parts.')], 'x = 2, y = 3'),
  vQ('Ex 10.2', 'Q5', 'Scalar and vector components of the vector from (2, 1) to (−5, 7)', { v: [-6.5, 3.5, -0.5, 8], arr: [A3([-7, 6, 0], C.sora, 'AB', [2, 1, 0])], dots: [{ p: [2, 1, 0], t: '(2, 1)' }, { p: [-5, 7, 0], t: '(−5, 7)' }] }, [fldP('Scalar components', [{ l: 'x', a: -7 }, { l: 'y', a: 6 }], '(−5 − 2, 7 − 1).'), mcqP('Vector components', ['−7î and 6ĵ', '−7 and 6', '7î and −6ĵ', '−5î and 7ĵ'], 'Scalars times the unit vectors.')], 'Scalar: −7, 6; vector: −7î, 6ĵ'),
  v3Q('Ex 10.2', 'Q6', 'Find a⃗ + b⃗ + c⃗: a⃗ = î − 2ĵ + k̂, b⃗ = −2î + 4ĵ + 5k̂, c⃗ = î − 6ĵ − 7k̂', [A3([1, -2, 1], C.sora, 'a⃗'), A3([-2, 4, 5], C.beni, 'b⃗', [1, -2, 1]), A3([1, -6, -7], C['matcha-deep'], 'c⃗', [-1, 2, 6]), A3([0, -4, -1], C.kin, 'sum')], [fldP('a⃗ + b⃗ + c⃗ = ?', cmp([0, -4, -1]), 'Add î, ĵ, k̂ parts: tip-to-tail.')], '−4ĵ − k̂', { R: 7 }),
  v3Q('Ex 10.2', 'Q7', 'Unit vector in the direction of a⃗ = î + ĵ + 2k̂', [A3([1, 1, 2], C.sora, 'a⃗')], [numP('|a⃗| = ?', S6, '√6'), unitRun(0), fldP('â = ?', cmp([1 / S6, 1 / S6, 2 / S6], ['1/√6', '1/√6', '2/√6']), 'Divide by √6.')], 'â = (1/√6)î + (1/√6)ĵ + (2/√6)k̂', { R: 3 }),
  v3Q('Ex 10.2', 'Q8', 'Unit vector along PQ, P(1, 2, 3), Q(4, 5, 6)', [A3([3, 3, 3], C.sora, 'PQ', [1, 2, 3])], [fldP('PQ = ?', cmp([3, 3, 3]), 'Q − P.'), numP('|PQ| = ?', 3 * S3, '3√3'), fldP('Unit vector', cmp([1 / S3, 1 / S3, 1 / S3], ['1/√3', '1/√3', '1/√3'])) ], '(1/√3)(î + ĵ + k̂)', { R: 7, dots: [{ p: [1, 2, 3], t: 'P' }, { p: [4, 5, 6], t: 'Q' }] }),
  v3Q('Ex 10.2', 'Q9', 'a⃗ = 2î − ĵ + 2k̂, b⃗ = −î + ĵ − k̂: unit vector along a⃗ + b⃗', [A3([2, -1, 2], C.sora, 'a⃗'), A3([-1, 1, -1], C.beni, 'b⃗', [2, -1, 2]), A3([1, 0, 1], C.kin, 'a⃗ + b⃗')], [fldP('a⃗ + b⃗ = ?', cmp([1, 0, 1])), fldP('Unit vector', cmp([1 / S2, 0, 1 / S2], ['1/√2', '0', '1/√2']), '|a⃗ + b⃗| = √2.')], '(1/√2)î + (1/√2)k̂', { R: 3 }),
  v3Q('Ex 10.2', 'Q10', 'Vector along 5î − ĵ + 2k̂ with magnitude 8', [A3([5, -1, 2], C.sora, 'a⃗'), A3(V.mul(8 / S30, [5, -1, 2]), C.beni, '8â')], [numP('|5î − ĵ + 2k̂| = ?', S30, '√30'), fldP('8â = ?', cmp(V.mul(8 / S30, [5, -1, 2]), ['40/√30', '−8/√30', '16/√30']), '8 × (5, −1, 2)/√30.')], '(40/√30)î − (8/√30)ĵ + (16/√30)k̂', { R: 8 }),
  v3Q('Ex 10.2', 'Q11', 'Show that 2î − 3ĵ + 4k̂ and −4î + 6ĵ − 8k̂ are collinear', [A3([2, -3, 4], C.sora, 'a⃗'), A3([-4, 6, -8], C.beni, 'b⃗')], [numP('b⃗ = λa⃗ with λ = ?', -2, '−2', '−4/2 = 6/(−3) = −8/4.', { keys: '' }), { k: 'tf', q: 'So they are collinear (opposite directions).', a: true, x: 'A scalar multiple.' }], 'b⃗ = −2a⃗: collinear', { R: 9 }),
  v3Q('Ex 10.2', 'Q12', 'Direction cosines of î + 2ĵ + 3k̂', [A3([1, 2, 3], C.sora, 'r⃗')], [numP('|r⃗| = ?', S14, '√14'), fldP('(l, m, n) = ?', [{ l: 'l', a: 1 / S14, show: '1/√14' }, { l: 'm', a: 2 / S14, show: '2/√14' }, { l: 'n', a: 3 / S14, show: '3/√14' }], 'Components ÷ magnitude.')], '1/√14, 2/√14, 3/√14', { R: 4 }),
  v3Q('Ex 10.2', 'Q13', 'Direction cosines of the vector from A(1, 2, −3) to B(−1, −2, 1)', [A3([-2, -4, 4], C.sora, 'AB', [1, 2, -3])], [fldP('AB = ?', cmp([-2, -4, 4])), numP('|AB| = ?', 6, '6', '√(4 + 16 + 16).', { keys: '' }), fldP('(l, m, n) = ?', [{ l: 'l', a: -1 / 3, show: '−1/3' }, { l: 'm', a: -2 / 3, show: '−2/3' }, { l: 'n', a: 2 / 3, show: '2/3' }], '÷ 6.')], '−1/3, −2/3, 2/3', { R: 5, dots: [{ p: [1, 2, -3], t: 'A' }, { p: [-1, -2, 1], t: 'B' }] }),
  v3Q('Ex 10.2', 'Q14', 'Show that î + ĵ + k̂ is equally inclined to OX, OY and OZ', [A3([1, 1, 1], C.sora, 'r⃗')], [fldP('Direction cosines', [{ l: 'l', a: 1 / S3, show: '1/√3' }, { l: 'm', a: 1 / S3, show: '1/√3' }, { l: 'n', a: 1 / S3, show: '1/√3' }]), { k: 'tf', q: 'Equal cosines, so equal angles with the three axes.', a: true, x: 'Each angle is cos⁻¹(1/√3).' }], 'l = m = n = 1/√3', { R: 2.5 }),
  v3Q('Ex 10.2', 'Q15', 'P = î + 2ĵ − k̂, Q = −î + ĵ + k̂. R divides PQ in 2 : 1 (i) internally (ii) externally', [A3([1, 2, -1], C.sora, 'P'), A3([-1, 1, 1], C.beni, 'Q')], [fldP('(i) (2Q + P)/3 = ?', cmp(V.sec([1, 2, -1], [-1, 1, 1], 2, 1)), '(−2 + 1, 2 + 2, 2 − 1)/3.'), fldP('(ii) (2Q − P)/(2 − 1) = ?', cmp(V.secX([1, 2, -1], [-1, 1, 1], 2, 1)), '(−2 − 1, 2 − 2, 2 + 1).'), runP(async (W) => { W.dots = [{ p: V.sec([1, 2, -1], [-1, 1, 1], 2, 1), t: 'R (int)', col: C.kin }, { p: V.secX([1, 2, -1], [-1, 1, 1], 2, 1), t: 'R (ext)', col: C['matcha-deep'] }]; SFX.pop(); await wait(AUTO ? 0.05 : 0.8); })], '(i) −⅓î + (4/3)ĵ + ⅓k̂ (ii) −3î + 3k̂', { R: 4 }),
  v3Q('Ex 10.2', 'Q16', 'Position vector of the midpoint of P(2, 3, 4), Q(4, 1, −2)', [A3([2, 3, 4], C.sora, 'P'), A3([4, 1, -2], C.beni, 'Q'), A3([3, 2, 1], C.kin, 'mid')], [fldP('(P + Q)/2 = ?', cmp([3, 2, 1]))], '3î + 2ĵ + k̂', { R: 5 }),
  v3Q('Ex 10.2', 'Q17', 'Show that a⃗ = 3î − 4ĵ − 4k̂, b⃗ = 2î − ĵ + k̂, c⃗ = î − 3ĵ − 5k̂ form a right-angled triangle', [A3(V.sub(b17, a17), C.sora, 'AB', a17), A3(V.sub(c17, b17), C.beni, 'BC', b17), A3(V.sub(a17, c17), C['matcha-deep'], 'CA', c17)], [fldP('Squared side lengths', [{ l: '|AB|²', a: 35 }, { l: '|BC|²', a: 41 }, { l: '|CA|²', a: 6 }], 'AB = −î + 3ĵ + 5k̂, BC = −î − 2ĵ − 6k̂, CA = 2î − ĵ + k̂.', ''), mcqP('Right angle at', ['A (35 + 6 = 41)', 'B', 'C', 'nowhere'], '|BC|² = |AB|² + |CA|², so BC is the hypotenuse.')], '35 + 6 = 41: right angle at A', { R: 6, tri: [{ pts: [a17, b17, c17] }] }),
  bQ('Ex 10.2', 'Q18', 'In triangle ABC (Fig 10.18), which is NOT true? (A) AB + BC + CA = 0⃗ (B) AB + BC − AC = 0⃗ (C) AB + BC − CA = 0⃗ (D) AB − CB + CA = 0⃗', [mcqP('Answer', ['(C)', '(A)', '(B)', '(D)'], 'AB + BC = AC, so AB + BC − CA = AC + AC = 2AC ≠ 0⃗. (D) is (A) rewritten, since −CB = BC.')], '(C)'),
  bQ('Ex 10.2', 'Q19', 'a⃗, b⃗ collinear. Which are incorrect? (A) b⃗ = λa⃗ for some λ (B) a⃗ = ±b⃗ (C) the components of a⃗ and b⃗ are not proportional (D) both have the same direction but different magnitudes', [{ k: 'pick', q: 'Tap every incorrect statement', pool: ['(A)', '(B)', '(C)', '(D)'], a: ['(B)', '(C)', '(D)'], brace: false, x: 'Answer-key check: the book lists only (D). But (B) fails for a⃗ = 2b⃗, and (C) is false because collinear vectors DO have proportional components. Only (A) is always correct.' }], '(B), (C) and (D) are incorrect (book: only D)'),
];
