/* =========================================================
   CHAPTER 5 · LINEAR INEQUALITIES — every exercise question as a sim
   Each inequality: predict the flip → watch the balance solve it → order the steps → build the answer.
   ========================================================= */
const TILT = { '<': -0.16, '≤': -0.12, '>': 0.16, '≥': 0.12 };
/* steps: [[op, L, R, neg?]] ; ans interval */
function ineqQ(ex, n, q, L0, sign, R0, steps, ans, o = {}) {
  const flips = steps.some((s) => s[3]); const lo = isFinite(ans.a) ? ans.a : ans.b, hi = isFinite(ans.b) ? ans.b : ans.a;
  const span = Math.max(6, Math.abs(hi - lo) + 6); const c = isFinite(ans.a) && isFinite(ans.b) ? (ans.a + ans.b) / 2 : lo;
  const nlLo = o.lo != null ? o.lo : Math.floor(c - span / 2), nlHi = o.hi != null ? o.hi : Math.ceil(c + span / 2);
  return {
    ex, n, q, ans, scene: 'scale', setup: (W) => { W.L = L0; W.R = R0; W.sign = sign; W.tilt = TILT[sign]; },
    parts: [
      { k: 'tf', q: 'Will the sign FLIP at some step?', o: ['Yes, it flips', 'No flip'], a: flips ? 0 : 1, x: flips ? 'At some point we multiply or divide by a negative.' : 'We only add, subtract, or divide by positives.', act: async () => { for (const [op, L2, R2, neg] of steps) await scaleStep(W, op, L2, R2, { neg: !!neg, weight: /^[+−-]/.test(op) ? op.split(' ')[0] : '' }); } },
      Object.assign(ivPart('Build the solution set on the number line', ans, { lo: nlLo, hi: nlHi, step: o.step || (nlHi - nlLo > 24 ? 5 : nlHi - nlLo > 14 ? 2 : 1), snap: o.snap, x: o.x }), {}),
    ],
    w: o.w || [L0 + ' ' + sign + ' ' + R0, ...steps.map(([op, L2, R2], i) => '⇒ ' + L2 + ' ' + signAfter(sign, steps, i) + ' ' + R2 + '   (' + op + ')'), 'Solution set: ' + ivText(ans)],
  };
}
function signAfter(sign, steps, i) { let s = sign; for (let k = 0; k <= i; k++) if (steps[k][3]) s = FLIPS[s]; return s; }
const iv = (a, b, lc, rc) => ({ a, b, lc, rc });

/* integer / natural solution picks on the line */
function intPick(q, lo, hi, test, label) { const pool = []; for (let k = lo; k <= hi; k++) pool.push(SET.lbl(k)); const ans = pool.filter((s, i) => test(lo + i)); return { k: 'pick', q, pool, a: ans, x: (ans.length ? '{' + ans.join(', ') + '}' : 'φ') + (label || ''), pre: () => { enterScene('numline', (W) => { Object.assign(W.nl, { lo: lo - 1, hi: hi + 1 }); MINI.numline.fit(W); intDots(W, lo, hi, test); }); }, act: async () => lightDots(W) }; }

const EX51 = [
  { ex: 'Ex 5.1', n: 'Q1', q: 'Solve 24x < 100 when (i) x is a natural number (ii) x is an integer.', scene: 'scale', setup: (W) => { W.L = '24x'; W.R = '100'; W.sign = '<'; W.tilt = -0.16; }, parts: [{ k: 'num', q: 'Divide by 24: x < ?', a: '25/6', show: '25/6', x: '100/24 = 25/6 ≈ 4.17.', act: async () => scaleStep(W, '÷ 24', 'x', '25/6') }, intPick('(i) x natural: tap the solutions', 0, 6, (k) => k >= 1 && k < 25 / 6), { k: 'mcq', q: '(ii) x integer: solution set', o: ['{…, −2, −1, 0, 1, 2, 3, 4}', '{1, 2, 3, 4}', '{0, 1, 2, 3, 4}', '{…, 3, 4, 5}'], a: 0, x: 'Every integer below 25/6.' }], w: ['24x < 100 ⇒ x < 25/6', '(i) {1, 2, 3, 4}  (ii) {…, −3, −2, −1, 0, 1, 2, 3, 4}'] },
  { ex: 'Ex 5.1', n: 'Q2', q: 'Solve −12x > 30 when (i) x is a natural number (ii) x is an integer.', scene: 'scale', setup: (W) => { W.L = '−12x'; W.R = '30'; W.sign = '>'; W.tilt = 0.16; }, parts: [{ k: 'mcq', q: 'Divide by −12:', o: ['x > −5/2', 'x < −5/2', 'x < 5/2', 'x > 5/2'], a: 1, x: 'Negative divisor ⇒ flip.', act: async () => scaleStep(W, '÷ (−12)', 'x', '−5/2', { neg: true }) }, { k: 'pick', q: '(i) x natural: solution set (empty set allowed)', pool: ['1', '2', '3'], a: [], x: 'No natural number is below −5/2: φ.' }, intPick('(ii) x integer: tap the solutions shown', -6, 1, (k) => k < -2.5, ' and every smaller integer.')], w: ['−12x > 30 ⇒ x < −5/2', '(i) no natural solution (φ)  (ii) {…, −5, −4, −3}'] },
  { ex: 'Ex 5.1', n: 'Q3', q: 'Solve 5x − 3 < 7 when (i) x is an integer (ii) x is a real number.', scene: 'scale', setup: (W) => { W.L = '5x − 3'; W.R = '7'; W.sign = '<'; W.tilt = -0.16; }, parts: [{ k: 'num', q: '5x < 10 ⇒ x < ?', a: 2, x: 'x < 2.', act: async () => { await scaleStep(W, '+3 both sides', '5x', '10', { weight: '+3' }); await scaleStep(W, '÷ 5', 'x', '2'); } }, intPick('(i) x integer: tap the solutions shown', -3, 3, (k) => k < 2, ' and every smaller integer.'), ivPart('(ii) x real: build it', iv(-INF, 2, false, false), { lo: -4, hi: 5 })], w: ['5x < 10 ⇒ x < 2', '(i) {…, −1, 0, 1}  (ii) (−∞, 2)'] },
  { ex: 'Ex 5.1', n: 'Q4', q: 'Solve 3x + 8 > 2 when (i) x is an integer (ii) x is a real number.', scene: 'scale', setup: (W) => { W.L = '3x + 8'; W.R = '2'; W.sign = '>'; W.tilt = 0.16; }, parts: [{ k: 'num', q: '3x > −6 ⇒ x > ?', a: -2, show: '−2', x: 'x > −2.', act: async () => { await scaleStep(W, '−8 both sides', '3x', '−6', { weight: '−8' }); await scaleStep(W, '÷ 3', 'x', '−2'); } }, intPick('(i) x integer: tap the solutions shown', -4, 3, (k) => k > -2, ' and every larger integer.'), ivPart('(ii) x real: build it', iv(-2, INF, false, false), { lo: -5, hi: 4 })], w: ['3x > −6 ⇒ x > −2', '(i) {−1, 0, 1, 2, …}  (ii) (−2, ∞)'] },
  ineqQ('Ex 5.1', 'Q5', 'Solve 4x + 3 < 5x + 7 for real x.', '4x + 3', '<', '5x + 7', [['−5x − 3', '−x', '4'], ['× (−1)', 'x', '−4', 1]], iv(-4, INF, false, false)),
  ineqQ('Ex 5.1', 'Q6', 'Solve 3x − 7 > 5x − 1 for real x.', '3x − 7', '>', '5x − 1', [['−5x + 7', '−2x', '6'], ['÷ (−2)', 'x', '−3', 1]], iv(-INF, -3, false, false)),
  ineqQ('Ex 5.1', 'Q7', 'Solve 3(x − 1) ≤ 2(x − 3) for real x.', '3(x − 1)', '≤', '2(x − 3)', [['expand', '3x − 3', '2x − 6'], ['−2x + 3', 'x', '−3']], iv(-INF, -3, false, true)),
  ineqQ('Ex 5.1', 'Q8', 'Solve 3(2 − x) ≥ 2(1 − x) for real x.', '3(2 − x)', '≥', '2(1 − x)', [['expand', '6 − 3x', '2 − 2x'], ['+2x − 6', '−x', '−4'], ['× (−1)', 'x', '4', 1]], iv(-INF, 4, false, true)),
  ineqQ('Ex 5.1', 'Q9', 'Solve x + x/2 + x/3 < 11 for real x.', 'x + x/2 + x/3', '<', '11', [['combine', '11x/6', '11'], ['× 6/11', 'x', '6']], iv(-INF, 6, false, false)),
  ineqQ('Ex 5.1', 'Q10', 'Solve x/3 > x/2 + 1 for real x.', 'x/3', '>', 'x/2 + 1', [['× 6', '2x', '3x + 6'], ['−3x', '−x', '6'], ['× (−1)', 'x', '−6', 1]], iv(-INF, -6, false, false)),
  ineqQ('Ex 5.1', 'Q11', 'Solve 3(x − 2)/5 ≤ 5(2 − x)/3 for real x.', '3(x − 2)/5', '≤', '5(2 − x)/3', [['× 15', '9(x − 2)', '25(2 − x)'], ['expand', '9x − 18', '50 − 25x'], ['+25x + 18', '34x', '68'], ['÷ 34', 'x', '2']], iv(-INF, 2, false, true)),
  ineqQ('Ex 5.1', 'Q12', 'Solve ½(3x/5 + 4) ≥ ⅓(x − 6) for real x.', '½(3x/5 + 4)', '≥', '⅓(x − 6)', [['× 30', '9x + 60', '10x − 60'], ['−10x − 60', '−x', '−120'], ['× (−1)', 'x', '120', 1]], iv(-INF, 120, false, true), { lo: 100, hi: 130, step: 5 }),
  ineqQ('Ex 5.1', 'Q13', 'Solve 2(2x + 3) − 10 < 6(x − 2) for real x.', '2(2x + 3) − 10', '<', '6(x − 2)', [['expand', '4x − 4', '6x − 12'], ['−6x + 4', '−2x', '−8'], ['÷ (−2)', 'x', '4', 1]], iv(4, INF, false, false)),
  ineqQ('Ex 5.1', 'Q14', 'Solve 37 − (3x + 5) > 9x − 8(x − 3) for real x.', '37 − (3x + 5)', '>', '9x − 8(x − 3)', [['simplify', '32 − 3x', 'x + 24'], ['−x − 32', '−4x', '−8'], ['÷ (−4)', 'x', '2', 1]], iv(-INF, 2, false, false)),
  ineqQ('Ex 5.1', 'Q15', 'Solve x/4 < (5x − 2)/3 − (7x − 3)/5 for real x.', 'x/4', '<', '(5x−2)/3 − (7x−3)/5', [['× 60', '15x', '16x − 4'], ['−16x', '−x', '−4'], ['× (−1)', 'x', '4', 1]], iv(4, INF, false, false)),
  ineqQ('Ex 5.1', 'Q16', 'Solve (2x − 1)/3 ≥ (3x − 2)/4 − (2 − x)/5 for real x.', '(2x − 1)/3', '≥', '(3x−2)/4 − (2−x)/5', [['× 60', '40x − 20', '57x − 54'], ['−57x + 20', '−17x', '−34'], ['÷ (−17)', 'x', '2', 1]], iv(-INF, 2, false, true)),
  ineqQ('Ex 5.1', 'Q17', 'Solve 3x − 2 < 2x + 1 and show the graph of the solution on the number line.', '3x − 2', '<', '2x + 1', [['−2x + 2', 'x', '3']], iv(-INF, 3, false, false)),
  ineqQ('Ex 5.1', 'Q18', 'Solve 5x − 3 > 3x − 5 and show the graph on the number line.', '5x − 3', '>', '3x − 5', [['−3x + 3', '2x', '−2'], ['÷ 2', 'x', '−1']], iv(-1, INF, false, false)),
  ineqQ('Ex 5.1', 'Q19', 'Solve 3(1 − x) < 2(x + 4) and show the graph on the number line.', '3(1 − x)', '<', '2(x + 4)', [['expand', '3 − 3x', '2x + 8'], ['−2x − 3', '−5x', '5'], ['÷ (−5)', 'x', '−1', 1]], iv(-1, INF, false, false)),
  ineqQ('Ex 5.1', 'Q20', 'Solve x/2 ≥ (5x − 2)/3 − (7x − 3)/5 and show the graph on the number line.', 'x/2', '≥', '(5x−2)/3 − (7x−3)/5', [['× 30', '15x', '8x − 2'], ['−8x', '7x', '−2'], ['÷ 7', 'x', '−2/7']], iv(-2 / 7, INF, true, false), { lo: -3, hi: 3, step: 1, snap: 1 / 7 }),
  { ex: 'Ex 5.1', n: 'Q21', q: 'Ravi obtained 70 and 75 marks in the first two unit tests. Find the minimum marks he should get in the third test to have an average of at least 60.', scene: 'bars', setup: (W) => { W.max = 100; W.bars = [{ v: 70, lab: 'Test 1' }, { v: 75, lab: 'Test 2' }, { v: 10, lab: 'Test 3' }]; W.line = { v: 60, t: 'avg ≥ 60' }; W.avg = (70 + 75 + 10) / 3; }, parts: [{ k: 'task', q: 'Drag Test 3 until the average just reaches 60', todo: 'Drag the pink bar.', pre: () => barDrag(W, W.bars[2], { onMove: (v) => (W.avg = (145 + v) / 3) }), check: (W) => W.bars[2].v === 35, auto: (W) => { W.bars[2].v = 35; W.avg = 60; }, reveal: (W) => { W.bars[2].v = 35; W.avg = 60; }, hint: 'The average should be exactly 60 at the minimum.', x: 'Exactly 35 brings the average to 60.' }, { k: 'num', q: '(70 + 75 + x)/3 ≥ 60 ⇒ x ≥ ?', a: 35, x: '145 + x ≥ 180.' }], w: ['(70 + 75 + x)/3 ≥ 60 ⇒ 145 + x ≥ 180 ⇒ x ≥ 35. Minimum 35 marks.'] },
  { ex: 'Ex 5.1', n: 'Q22', q: 'Grade A needs an average of 90 or more in five exams. Sunita got 87, 92, 94 and 95. Find the minimum marks she needs in the fifth exam.', scene: 'bars', setup: (W) => { W.max = 100; W.bars = [87, 92, 94, 95, 50].map((v, i) => ({ v, lab: 'E' + (i + 1) })); W.line = { v: 90, t: 'avg ≥ 90' }; W.avg = (87 + 92 + 94 + 95 + 50) / 5; }, parts: [{ k: 'task', q: 'Drag E5 until the average just reaches 90', todo: 'Drag the pink bar.', pre: () => barDrag(W, W.bars[4], { onMove: (v) => (W.avg = (368 + v) / 5) }), check: (W) => W.bars[4].v === 82, auto: (W) => { W.bars[4].v = 82; W.avg = 90; }, reveal: (W) => { W.bars[4].v = 82; W.avg = 90; }, x: '82 makes the average exactly 90.' }, { k: 'num', q: '(368 + x)/5 ≥ 90 ⇒ x ≥ ?', a: 82, x: '368 + x ≥ 450.' }], w: ['(87 + 92 + 94 + 95 + x)/5 ≥ 90 ⇒ 368 + x ≥ 450 ⇒ x ≥ 82. Minimum 82 marks.'] },
  { ex: 'Ex 5.1', n: 'Q23', q: 'Find all pairs of consecutive odd positive integers, both smaller than 10, such that their sum is more than 11.', scene: 'numline', setup: (W) => { Object.assign(W.nl, { lo: 0, hi: 11 }); MINI.numline.fit(W); }, parts: [{ k: 'mcq', q: 'With x and x + 2: the conditions are…', o: ['x + 2 < 10 and 2x + 2 > 11', 'x < 10 and x > 11', 'x + 2 > 10 and 2x < 11', '2x + 2 < 10'], a: 0, x: 'So 4.5 < x < 8.', act: async () => { await showSeg(W, { a: 4.5, b: 8, lc: false, rc: false, t: '4.5 < x < 8' }); intDots(W, 1, 10, (k) => k > 4.5 && k < 8 && k % 2 === 1); await lightDots(W, 0.2); } }, { k: 'pick', brace: false, q: 'Tap the pairs', pool: ['(3, 5)', '(5, 7)', '(7, 9)', '(9, 11)'], a: ['(5, 7)', '(7, 9)'], x: 'x = 5 or 7.' }], w: ['x + 2 < 10 and x + (x + 2) > 11 ⇒ 9/2 < x < 8, x odd ⇒ x = 5, 7. Pairs (5, 7) and (7, 9).'] },
  { ex: 'Ex 5.1', n: 'Q24', q: 'Find all pairs of consecutive even positive integers, both larger than 5, such that their sum is less than 23.', scene: 'numline', setup: (W) => { Object.assign(W.nl, { lo: 3, hi: 14 }); MINI.numline.fit(W); }, parts: [{ k: 'mcq', q: 'With x and x + 2: conditions', o: ['x > 5 and 2x + 2 < 23', 'x < 5 and 2x > 23', 'x + 2 > 5 and x < 23', 'x > 23'], a: 0, x: '5 < x < 10.5.', act: async () => { await showSeg(W, { a: 5, b: 10.5, lc: false, rc: false, t: '5 < x < 10.5' }); intDots(W, 4, 13, (k) => k > 5 && k < 10.5 && k % 2 === 0); await lightDots(W, 0.2); } }, { k: 'pick', brace: false, q: 'Tap the pairs', pool: ['(4, 6)', '(6, 8)', '(8, 10)', '(10, 12)', '(12, 14)'], a: ['(6, 8)', '(8, 10)', '(10, 12)'], x: 'x = 6, 8, 10.' }], w: ['x > 5 and 2x + 2 < 23 ⇒ 5 < x < 21/2, x even ⇒ 6, 8, 10. Pairs (6, 8), (8, 10), (10, 12).'] },
  { ex: 'Ex 5.1', n: 'Q25', q: 'The longest side of a triangle is 3 times the shortest side and the third side is 2 cm shorter than the longest side. If the perimeter is at least 61 cm, find the minimum length of the shortest side.', scene: 'bars', setup: (W) => { W.max = 40; W.bars = [{ v: 5, lab: 'x' }, { v: 15, lab: '3x' }, { v: 13, lab: '3x − 2' }]; W.cap = 'perimeter = 7x − 2'; }, parts: [{ k: 'mcq', q: 'Perimeter inequality', o: ['x + 3x + (3x − 2) ≥ 61', 'x + 3x + 3x ≤ 61', '3x − 2 ≥ 61', '7x + 2 ≥ 61'], a: 0, x: '7x − 2 ≥ 61.' }, { k: 'task', q: 'Drag the shortest side until the perimeter reaches 61', todo: 'Drag the x bar.', pre: () => barDrag(W, W.bars[0], { lo: 1, hi: 12, onMove: (v) => { W.bars[1].v = 3 * v; W.bars[2].v = 3 * v - 2; W.cap = 'perimeter = ' + (7 * v - 2); } }), check: (W) => W.bars[0].v === 9, auto: (W) => { W.bars[0].v = 9; W.bars[1].v = 27; W.bars[2].v = 25; }, reveal: (W) => { W.bars[0].v = 9; W.bars[1].v = 27; W.bars[2].v = 25; }, x: 'x = 9 gives 9 + 27 + 25 = 61.' }, { k: 'num', q: 'Minimum shortest side = ? cm', a: 9, x: '7x ≥ 63 ⇒ x ≥ 9.' }], w: ['x + 3x + (3x − 2) ≥ 61 ⇒ 7x ≥ 63 ⇒ x ≥ 9. Minimum 9 cm.'] },
  { ex: 'Ex 5.1', n: 'Q26', q: 'A 91 cm board is cut into three lengths: the second is 3 cm longer than the shortest, the third is twice the shortest. What are the possible lengths of the shortest piece if the third is at least 5 cm longer than the second?', scene: 'numline', setup: (W) => { Object.assign(W.nl, { lo: 0, hi: 30, step: 2, label: 4 }); MINI.numline.fit(W); }, parts: [{ k: 'num', q: 'x + (x + 3) + 2x ≤ 91 ⇒ x ≤ ?', a: 22, x: '4x ≤ 88.' }, { k: 'num', q: '2x ≥ (x + 3) + 5 ⇒ x ≥ ?', a: 8, x: 'x ≥ 8.' }, ivPart('Build the possible lengths', iv(8, 22, true, true), { lo: 0, hi: 30, step: 2 })], w: ['x + (x + 3) + 2x ≤ 91 ⇒ x ≤ 22; 2x ≥ x + 8 ⇒ x ≥ 8. So 8 ≤ x ≤ 22 cm.'] },
];

/* ===================== MISCELLANEOUS ===================== */
function dblQ(n, q, steps, flip, ans, o = {}) { return { ex: 'Misc', n, q, scene: 'numline', setup: (W) => { Object.assign(W.nl, { lo: o.lo, hi: o.hi, step: o.step || 1, label: o.label || o.step || 1 }); MINI.numline.fit(W); }, parts: [{ k: 'tf', q: 'Will the signs flip?', o: ['Yes, both flip', 'No flip'], a: flip ? 0 : 1, x: flip ? 'We divide all three parts by a negative.' : 'Only positive multipliers.' }, { k: 'order', q: 'Order the steps', s: steps }, ivPart('Build the solution', ans, { lo: o.lo, hi: o.hi, step: o.step || 1, snap: o.snap })], w: [...steps, 'Solution: ' + ivText(ans)] }; }
function sysQ(n, q, a1, a2, ans, o = {}) { return { ex: 'Misc', n, q, scene: 'numline', setup: (W) => { Object.assign(W.nl, { lo: o.lo, hi: o.hi, step: o.step || 1, label: o.label || o.step || 1 }); MINI.numline.fit(W); }, parts: [Object.assign({ k: 'mcq', time: 30 }, a1, { act: async () => showSeg(W, Object.assign({ col: C.sora, y: 0.6 }, a1.seg)) }), Object.assign({ k: 'mcq', time: 30 }, a2, { act: async () => showSeg(W, Object.assign({ col: C.khaki, y: 1.1 }, a2.seg)) }), ivPart('Build the common part', ans, { lo: o.lo, hi: o.hi, step: o.step || 1 })], w: [a1.o[a1.a] + ' and ' + a2.o[a2.a], 'Solution: ' + ivText(ans)] }; }
const EX5M = [
  dblQ('Q1', 'Solve 2 ≤ 3x − 4 ≤ 5.', ['Add 4 to all parts: 6 ≤ 3x ≤ 9', 'Divide by 3: 2 ≤ x ≤ 3'], false, iv(2, 3, true, true), { lo: 0, hi: 5 }),
  dblQ('Q2', 'Solve 6 ≤ −3(2x − 4) < 12.', ['Divide by −3 (flip both): −2 ≥ 2x − 4 > −4', 'Add 4: 2 ≥ 2x > 0', 'Divide by 2: 0 < x ≤ 1'], true, iv(0, 1, false, true), { lo: -2, hi: 3, step: 0.5, label: 1 }),
  dblQ('Q3', 'Solve −3 ≤ 4 − 7x/2 ≤ 18.', ['Subtract 4: −7 ≤ −7x/2 ≤ 14', 'Multiply by −2/7 (flip): 2 ≥ x ≥ −4', 'So −4 ≤ x ≤ 2'], true, iv(-4, 2, true, true), { lo: -6, hi: 4 }),
  dblQ('Q4', 'Solve −15 < 3(x − 2)/5 ≤ 0.', ['Multiply by 5: −75 < 3(x − 2) ≤ 0', 'Divide by 3: −25 < x − 2 ≤ 0', 'Add 2: −23 < x ≤ 2'], false, iv(-23, 2, false, true), { lo: -26, hi: 4, step: 1, label: 4 }),
  dblQ('Q5', 'Solve −12 < 4 − 3x/(−5) ≤ 2.', ['Note 4 − 3x/(−5) = 4 + 3x/5', 'Subtract 4: −16 < 3x/5 ≤ −2', 'Multiply by 5/3: −80/3 < x ≤ −10/3'], false, iv(-80 / 3, -10 / 3, false, true), { lo: -30, hi: 0, step: 1 / 3, label: 5, snap: 1 / 3 }),
  dblQ('Q6', 'Solve 7 ≤ (3x + 11)/2 ≤ 11.', ['Multiply by 2: 14 ≤ 3x + 11 ≤ 22', 'Subtract 11: 3 ≤ 3x ≤ 11', 'Divide by 3: 1 ≤ x ≤ 11/3'], false, iv(1, 11 / 3, true, true), { lo: -1, hi: 5, step: 1 / 3, label: 1, snap: 1 / 3 }),
  sysQ('Q7', 'Solve 5x + 1 > −24, 5x − 1 < 24 and show on the number line.', { q: '5x + 1 > −24 gives…', o: ['x > −5', 'x < −5', 'x > 5', 'x < 5'], a: 0, x: '5x > −25.', seg: iv(-5, INF, false, false) }, { q: '5x − 1 < 24 gives…', o: ['x < 5', 'x > 5', 'x < −5', 'x ≤ 5'], a: 0, x: '5x < 25.', seg: iv(-INF, 5, false, false) }, iv(-5, 5, false, false), { lo: -8, hi: 8 }),
  sysQ('Q8', 'Solve 2(x − 1) < x + 5, 3(x + 2) > 2 − x and show on the number line.', { q: '2(x − 1) < x + 5 gives…', o: ['x < 7', 'x > 7', 'x < 3', 'x < −7'], a: 0, x: '2x − 2 < x + 5.', seg: iv(-INF, 7, false, false) }, { q: '3(x + 2) > 2 − x gives…', o: ['x > −1', 'x < −1', 'x > 1', 'x > −4'], a: 0, x: '4x > −4.', seg: iv(-1, INF, false, false) }, iv(-1, 7, false, false), { lo: -4, hi: 10 }),
  sysQ('Q9', 'Solve 3x − 7 > 2(x − 6), 6 − x > 11 − 2x and show on the number line.', { q: '3x − 7 > 2(x − 6) gives…', o: ['x > −5', 'x < −5', 'x > 5', 'x > −19'], a: 0, x: '3x − 7 > 2x − 12.', seg: iv(-5, INF, false, false) }, { q: '6 − x > 11 − 2x gives…', o: ['x > 5', 'x < 5', 'x > −5', 'x > 17'], a: 0, x: 'x > 5.', seg: iv(5, INF, false, false) }, iv(5, INF, false, false), { lo: -8, hi: 10 }),
  sysQ('Q10', 'Solve 5(2x − 7) − 3(2x + 3) ≤ 0, 2x + 19 ≤ 6x + 47 and show on the number line.', { q: '5(2x − 7) − 3(2x + 3) ≤ 0 gives…', o: ['x ≤ 11', 'x ≥ 11', 'x ≤ −11', 'x < 11'], a: 0, x: '4x − 44 ≤ 0.', seg: iv(-INF, 11, false, true) }, { q: '2x + 19 ≤ 6x + 47 gives…', o: ['x ≥ −7', 'x ≤ −7', 'x ≥ 7', 'x ≥ −28'], a: 0, x: '−28 ≤ 4x.', seg: iv(-7, INF, true, false) }, iv(-7, 11, true, true), { lo: -10, hi: 14, step: 1, label: 2 }),
  { ex: 'Misc', n: 'Q11', q: 'A solution is to be kept between 68°F and 77°F. What is the range in °C if F = (9/5)C + 32?', scene: 'thermo', setup: (W) => { W.cLo = 10; W.cHi = 30; W.band = [20, 25]; }, parts: [{ k: 'order', q: 'Order the steps', s: ['68 < (9/5)C + 32 < 77', '36 < (9/5)C < 45', 'Multiply by 5/9: 20 < C < 25'] }, { k: 'fields', q: 'So C lies between…', f: [{ l: 'C >', a: 20 }, { l: 'C <', a: 25 }], x: '20°C < C < 25°C.' }], w: ['68 < 9C/5 + 32 < 77 ⇒ 36 < 9C/5 < 45 ⇒ 20 < C < 25'] },
  { ex: 'Misc', n: 'Q12', q: '640 L of 8% boric acid is diluted with 2% boric acid. The mixture must be more than 4% but less than 6%. How many litres of the 2% solution must be added?', scene: 'tank', setup: (W) => { Object.assign(W, { base: 640, pct0: 8, pct1: 2, lo: 4, hi: 6, what: 'boric acid', cap: 2200 }); }, parts: [{ k: 'task', q: 'Find any amount that lands between 4% and 6%', todo: 'Use the slider.', pre: () => slider('x (litres of 2% added)', 0, 1500, 20, 0, (v) => v + ' L', (v) => (W.add = v), 640), check: () => { const c = MINI.tank.conc(W); return c > 4 && c < 6; }, auto: (W) => (W.add = 640), reveal: (W) => (W.add = 640), x: 'Anything strictly between 320 L and 1280 L works.' }, { k: 'fields', q: 'Exact range: x between…', f: [{ l: 'x >', a: 320 }, { l: 'x <', a: 1280 }], x: '0.08(640) + 0.02x > 0.04(640 + x) ⇒ x < 1280; < 0.06(640 + x) ⇒ x > 320.' }], w: ['51.2 + 0.02x > 0.04(640 + x) ⇒ x < 1280', '51.2 + 0.02x < 0.06(640 + x) ⇒ x > 320', 'So 320 < x < 1280 litres.'] },
  { ex: 'Misc', n: 'Q13', q: 'How many litres of water must be added to 1125 L of a 45% acid solution so that the mixture contains more than 25% but less than 30% acid?', scene: 'tank', setup: (W) => { Object.assign(W, { base: 1125, pct0: 45, pct1: 0, lo: 25, hi: 30, what: 'acid', cap: 2400 }); }, parts: [{ k: 'task', q: 'Pour water until the mix is between 25% and 30%', todo: 'Use the slider.', pre: () => slider('x (litres of water)', 0, 1200, 25, 0, (v) => v + ' L', (v) => (W.add = v), 700), check: () => { const c = MINI.tank.conc(W); return c > 25 && c < 30; }, auto: (W) => (W.add = 700), reveal: (W) => (W.add = 700), x: 'Between 562.5 L and 900 L.' }, { k: 'fields', q: 'Exact range: x between…', f: [{ l: 'x >', a: 562.5 }, { l: 'x <', a: 900 }], x: '506.25/(1125 + x) between 0.25 and 0.30.' }], w: ['Acid = 0.45 × 1125 = 506.25 L', '0.25(1125 + x) < 506.25 < 0.30(1125 + x) ⇒ 562.5 < x < 900 litres.'] },
  { ex: 'Misc', n: 'Q14', q: 'IQ = (MA/CA) × 100. If 80 ≤ IQ ≤ 140 for 12-year-old children, find the range of their mental age.', scene: 'bars', setup: (W) => { W.max = 20; W.bars = [{ v: 9.6, lab: 'MA at IQ 80' }, { v: 16.8, lab: 'MA at IQ 140' }]; W.cap = 'CA = 12'; }, parts: [{ k: 'order', q: 'Order the steps', s: ['80 ≤ (MA/12) × 100 ≤ 140', 'Multiply by 12/100: 9.6 ≤ MA ≤ 16.8'] }, { k: 'fields', q: 'Mental age range', f: [{ l: 'MA ≥', a: 9.6 }, { l: 'MA ≤', a: 16.8 }], x: '9.6 ≤ MA ≤ 16.8.' }], w: ['80 ≤ 100·MA/12 ≤ 140 ⇒ 9.6 ≤ MA ≤ 16.8'] },
];
const BOSS5 = [
  ['−3x < 9 ⇒ ?', ['x < −3', 'x > −3', 'x < 3', 'x > 3'], 1], ['x ≥ 2 on a number line: the dot at 2 is…', ['hollow', 'filled', 'absent', 'red'], 1], ['2x − 5 ≤ 7 ⇒ ?', ['x ≤ 6', 'x ≥ 6', 'x ≤ 1', 'x < 6'], 0], ['Natural solutions of x < 3', ['{0, 1, 2}', '{1, 2}', '{1, 2, 3}', 'φ'], 1], ['−1 < x ≤ 4 in interval form', ['(−1, 4]', '[−1, 4)', '(−1, 4)', '[−1, 4]'], 0],
  ['Adding 7 to both sides…', ['flips the sign', 'keeps the sign', 'makes it an equation', 'squares it'], 1], ['−x > −5 ⇒ ?', ['x > 5', 'x < 5', 'x > −5', 'x = 5'], 1], ['x > 2 and x < 6 overlap in…', ['(2, 6)', '[2, 6]', '(6, ∞)', 'φ'], 0], ['x/(−2) ≥ 3 ⇒ ?', ['x ≥ −6', 'x ≤ −6', 'x ≥ 6', 'x ≤ 6'], 1], ['3 ≤ 2x + 1 < 9 ⇒ ?', ['1 ≤ x < 4', '2 ≤ x < 8', '1 < x ≤ 4', '0 ≤ x < 4'], 0],
];
LESSONS.push(exLesson({ id: 'ex51', title: 'Exercise 5.1', blurb: 'All 26: solve on the balance, build on the number line, word problems with sims.', face: 'kimmy-excited', qs: EX51 }));
LESSONS.push(exLesson({ id: 'misc', title: 'Miscellaneous', blurb: 'All 14: double inequalities, systems, °F/°C, mixtures, IQ.', face: 'jess-thinking', qs: EX5M }));
LESSONS.push(lesson({
  id: 'boss', title: 'Boss Battle', blurb: 'Ten fast questions. Speed points. Beat Kimmy.', face: 'jess-excited',
  steps: [async function () { enterScene('board', (W) => { W.tag = 'BOSS'; W.sub = 'Chapter 5'; }); await slam('BOSS BATTLE', '10 questions · speed counts'); await K('play', 'Last boss of the book! I got 7,200.'); await cont('Fight'); }, ...BOSS5.map(([q, o, a], i) => async function () { enterScene('board', (W) => { W.tag = 'Q' + (i + 1); W.sub = 'Boss Battle'; }); await quiz(q, o, a, plain(o[a]) + '.', null, 15); await cont(); }), async function () { enterScene('board', (W) => { W.tag = 'K.O.!'; W.sub = 'Chapter 5'; }); await summary(['Chapter 5 complete!', 'Two rules · Number lines · Systems · Word problems', { t: '× negative ⇒ FLIP', eq: true }]); }],
}));
LESSONS.forEach((l) => { if (l.kind === 'ex') l.short = l.id === 'misc' ? 'M' : l.title.replace('Exercise ', ''); });
