/* =========================================================
   CLASS 12 · CHAPTER 9 — Exercises 9.1, 9.2, 9.3
   ========================================================= */
const boardQ = (ex, n, q, parts, w, tag) => ({ ex, n, q, scene: 'board', setup: (W) => { W.tag = tag || n; W.sub = ex; }, parts, w: [w] });
const cbrt = Math.cbrt;
/* numerical residual of a 2nd-order check: L(x, y, y′, y″) for the plotted y(x) */
const resid = (yf, L) => (x, c) => { const h = 1e-3, y0 = yf(x, c), y1 = (yf(x + h, c) - yf(x - h, c)) / (2 * h), y2 = (yf(x + h, c) - 2 * y0 + yf(x - h, c)) / (h * h); return L(x, y0, y1, y2); };

/* ===================== EXERCISE 9.1 ===================== */
const EX91 = [
  odQ('Ex 9.1', 'Q1', 'Order and degree of d⁴y/dx⁴ + sin(y‴) = 0', 'y⁗ + sin(y‴) = 0', [[4, 1, 'y⁗'], [3, 1, 'sin(y‴)', 'sin']], 4, 'nd'),
  odQ('Ex 9.1', 'Q2', 'Order and degree of y′ + 5y = 0', 'y′ + 5y = 0', [[1, 1, 'y′'], [0, 1, '5y']], 1, 1),
  odQ('Ex 9.1', 'Q3', 'Order and degree of (ds/dt)⁴ + 3s d²s/dt² = 0', '(s′)⁴ + 3s·s″ = 0', [[1, 4, '(s′)⁴'], [2, 1, '3s·s″']], 2, 1, { x: 'Order 2 (s″). s″ appears to the first power: degree 1. The 4th power is on s′, a lower derivative.' }),
  odQ('Ex 9.1', 'Q4', 'Order and degree of (d²y/dx²)² + cos(dy/dx) = 0', '(y″)² + cos(y′) = 0', [[2, 2, '(y″)²'], [1, 1, 'cos(y′)', 'cos']], 2, 'nd'),
  odQ('Ex 9.1', 'Q5', 'Order and degree of d²y/dx² = cos 3x + sin 3x', 'y″ = cos 3x + sin 3x', [[2, 1, 'y″']], 2, 1),
  odQ('Ex 9.1', 'Q6', 'Order and degree of (y‴)² + (y″)³ + (y′)⁴ + y⁵ = 0', '(y‴)² + (y″)³ + (y′)⁴ + y⁵ = 0', [[3, 2, '(y‴)²'], [2, 3, '(y″)³'], [1, 4, '(y′)⁴'], [0, 5, 'y⁵']], 3, 2),
  odQ('Ex 9.1', 'Q7', 'Order and degree of y‴ + 2y″ + y′ = 0', 'y‴ + 2y″ + y′ = 0', [[3, 1, 'y‴'], [2, 1, '2y″'], [1, 1, 'y′']], 3, 1),
  odQ('Ex 9.1', 'Q8', 'Order and degree of y′ + y = eˣ', 'y′ + y = eˣ', [[1, 1, 'y′'], [0, 1, 'y']], 1, 1),
  odQ('Ex 9.1', 'Q9', 'Order and degree of y″ + (y′)² + 2y = 0', 'y″ + (y′)² + 2y = 0', [[2, 1, 'y″'], [1, 2, '(y′)²'], [0, 1, '2y']], 2, 1),
  odQ('Ex 9.1', 'Q10', 'Order and degree of y″ + 2y′ + sin y = 0', 'y″ + 2y′ + sin y = 0', [[2, 1, 'y″'], [1, 1, '2y′'], [0, 1, 'sin y']], 2, 1, { x: 'sin y is fine: y itself is not a derivative. Polynomial in y″, y′; degree 1.' }),
  odQ('Ex 9.1', 'Q11', 'The degree of (y″)³ + (y′)² + sin(y′) + 1 = 0 is (A) 3 (B) 2 (C) 1 (D) not defined', '(y″)³ + (y′)² + sin(y′) + 1 = 0', [[2, 3, '(y″)³'], [1, 2, '(y′)²'], [1, 1, 'sin(y′)', 'sin']], 2, 'nd', { post: [mcqP('Answer', ['(D) not defined', '(A) 3', '(B) 2', '(C) 1'], 'sin(y′) is not a polynomial in y′.')] }),
  odQ('Ex 9.1', 'Q12', 'The order of 2x² y″ − 3y′ + y = 0 is (A) 2 (B) 1 (C) 0 (D) not defined', '2x²y″ − 3y′ + y = 0', [[2, 1, '2x²y″'], [1, 1, '3y′'], [0, 1, 'y']], 2, 1, { post: [mcqP('Answer', ['(A) 2', '(B) 1', '(C) 0', '(D) not defined'], 'Highest derivative y″.')] }),
];

/* ===================== EXERCISE 9.2 ===================== */
const vR = (yf, L, v, steps, o = {}) => ({ fam: yf, res: resid(yf, L), v, steps, ...o });
const EX92 = [
  verQ('Ex 9.2', 'Q1', 'Verify y = eˣ + 1 is a solution of y″ − y′ = 0', vR((x) => exp(x) + 1, (x, y, y1, y2) => y2 - y1, [-3, 2.5, -1, 6], [mcqP('y′ and y″ are', ['eˣ and eˣ', 'eˣ + 1 and eˣ', 'eˣ and 0', 'xeˣ and eˣ'], 'The constant 1 disappears.')])),
  verQ('Ex 9.2', 'Q2', 'Verify y = x² + 2x + C is a solution of y′ − 2x − 2 = 0', { F: (x) => 2 * x + 2, G: (x, y) => y - x * x - 2 * x, fam: (x, c) => x * x + 2 * x + c, cs: [-3, 3, 0.5, 2], c0: 0, v: [-4, 2.5, -3, 4], steps: [mcqP('y′ = ?', ['2x + 2', '2x', 'x² + 2', '2x + 2 + C'], 'C differentiates to 0.')] }),
  verQ('Ex 9.2', 'Q3', 'Verify y = cos x + C is a solution of y′ + sin x = 0', { F: (x) => -sin(x), G: (x, y) => y - cos(x), fam: (x, c) => cos(x) + c, cs: [-2, 2, 0.5, 1], c0: 0, v: [-5, 5, -3, 3], steps: [mcqP('y′ = ?', ['−sin x', 'sin x', '−sin x + C', 'cos x'], 'So y′ + sin x = 0.')] }),
  verQ('Ex 9.2', 'Q4', 'Verify y = √(1 + x²) is a solution of y′ = xy/(1 + x²)', { F: (x, y) => (x * y) / (1 + x * x), G: (x, y) => y / sqrt(1 + x * x), fam: (x) => sqrt(1 + x * x), v: [-4, 4, -1, 5], steps: [mcqP('y′ = ?', ['x/√(1 + x²)', '1/(2√(1 + x²))', 'x√(1 + x²)', '2x/√(1 + x²)'], 'Chain rule.'), mcqP('xy/(1 + x²) with y = √(1 + x²) equals', ['x/√(1 + x²)', 'x', '√(1 + x²)', 'x(1 + x²)'], 'Same as y′.')] }),
  verQ('Ex 9.2', 'Q5', 'Verify y = Ax is a solution of xy′ = y (x ≠ 0)', { F: (x, y) => y / x, G: (x, y) => y / x, fam: (x, c) => c * x, cs: [-2, 2, 0.5, 1.5], c0: 0.5, cname: 'A', v: [-4, 4, -3, 3], steps: [mcqP('xy′ = ?', ['Ax = y', 'A', 'x', 'A²x'], 'y′ = A.')] }),
  verQ('Ex 9.2', 'Q6', 'Verify y = x sin x is a solution of xy′ = y + x√(x² − y²) (x ≠ 0 and x > y or x < −y)', { F: (x, y) => (y + x * sqrt(x * x - y * y)) / x, fam: (x) => x * sin(x), res: resid((x) => x * sin(x), (x, y, y1) => x * y1 - y - x * sqrt(x * x - y * y)), v: [-2 * PI, 2 * PI, -6, 6], fx: piLab9, ok: false,
    steps: [mcqP('xy′ = ?', ['x sin x + x² cos x', 'x² cos x', 'x sin x', 'sin x + x cos x'], 'y′ = sin x + x cos x.'), mcqP('x√(x² − y²) with y = x sin x equals', ['x·|x|·|cos x|', 'x² cos x', 'x cos x', 'x²'], '√(x² cos²x) = |x||cos x|: a square root is never negative.')],
    tq: 'So y = x sin x satisfies the equation for every allowed x.', tx: 'Answer-key check: the red residual is NOT flat. x²cos x = x|x||cos x| only when x cos x ≥ 0 (e.g. 0 < x ≤ π/2). At x = 2: LHS = 0.15, RHS = 3.48. The book verifies it everywhere; it really holds only where x cos x ≥ 0.',
    post: [mcqP('Where does it actually hold?', ['where x cos x ≥ 0, e.g. 0 < x ≤ π/2', 'for every x ≠ 0', 'only where x < 0', 'nowhere'], 'There the residual sits on 0.')], w: 'Holds only where x cos x ≥ 0 (book says everywhere)' }),
  verQ('Ex 9.2', 'Q7', 'Verify xy = log y + C is a solution of y′ = y²/(1 − xy) (xy ≠ 1)', { F: (x, y) => (y * y) / (1 - x * y), G: (x, y) => x * y - log(y), imp: [[-1, 1], [0.5, 2]], v: [-3, 3, 0, 4], steps: [mcqP('Differentiate xy = log y + C:', ['y + xy′ = y′/y', 'xy′ = y′/y', 'y + xy′ = 1/y', 'y′ = y′/y'], 'Product rule on the left.'), mcqP('Solve for y′:', ['y²/(1 − xy)', 'y/(1 − xy)', 'y²/(xy − 1)', '1/(1 − xy)'], 'y′(1/y − x) = y.')] }),
  verQ('Ex 9.2', 'Q8', 'Verify y − cos y = x is a solution of (y sin y + cos y + x) y′ = y', { F: (x, y) => 1 / (1 + sin(y)), G: (x, y) => y - cos(y) - x, imp: [[-1, 0]], v: [-3, 4, -1, 4], steps: [mcqP('Differentiate: y′ = ?', ['1/(1 + sin y)', '1/(1 − sin y)', '1 + sin y', 'sin y'], 'y′ + sin y·y′ = 1.'), mcqP('With x = y − cos y, y sin y + cos y + x = ?', ['y(1 + sin y)', 'y sin y', '1 + sin y', 'y + cos y'], 'Times y′ gives y.')] }),
  verQ('Ex 9.2', 'Q9', 'Verify x + y = tan⁻¹y is a solution of y² y′ + y² + 1 = 0', { F: (x, y) => -(1 + y * y) / (y * y), G: (x, y) => x + y - atan(y), imp: [[PI / 4 - 1, 1]], v: [-3, 3, -3, 3], steps: [mcqP('Differentiate: 1 + y′ = ?', ['y′/(1 + y²)', '1/(1 + y²)', 'y′(1 + y²)', '0'], 'Chain rule on tan⁻¹y.'), mcqP('So y′ = ?', ['−(1 + y²)/y²', '(1 + y²)/y²', '−y²/(1 + y²)', '−1/y²'], 'Then y²y′ = −(1 + y²).')] }),
  verQ('Ex 9.2', 'Q10', 'Verify y = √(a² − x²), x ∈ (−a, a), is a solution of x + y y′ = 0 (y ≠ 0)', { F: (x, y) => -x / y, G: (x, y) => x * x + y * y, fam: (x, a) => sqrt(a * a - x * x), cs: [1, 3, 0.5, 2.5], c0: 1.5, cname: 'a', v: [-4, 4, -1, 3.5], steps: [mcqP('y y′ = ?', ['−x', 'x', '−x/y', 'a² − x²'], 'y′ = −x/√(a² − x²).')] }),
  boardQ('Ex 9.2', 'Q11', 'The number of arbitrary constants in the general solution of a 4th order differential equation: (A) 0 (B) 2 (C) 3 (D) 4', [mcqP('Answer', ['(D) 4', '(A) 0', '(B) 2', '(C) 3'], 'General solution: as many constants as the order.')], '(D) 4'),
  boardQ('Ex 9.2', 'Q12', 'The number of arbitrary constants in the particular solution of a 3rd order differential equation: (A) 3 (B) 2 (C) 1 (D) 0', [mcqP('Answer', ['(D) 0', '(A) 3', '(B) 2', '(C) 1'], 'A particular solution has no arbitrary constants.')], '(D) 0'),
];

/* ===================== EXERCISE 9.3 ===================== */
const sepS = (o, x) => mcqP('Separate the variables', o, x || 'y on one side, x on the other.');
const EX93 = [
  solQ('Ex 9.3', 'Q1', 'General solution of dy/dx = (1 − cos x)/(1 + cos x)', (x) => (1 - cos(x)) / (1 + cos(x)), (x, y) => y - 2 * tan(x / 2) + x, ['y = 2 tan(x/2) − x + C', 'y = tan(x/2) − x + C', 'y = 2 tan(x/2) + x + C', 'y = sec²(x/2) + C'], { v: [-3, 3, -3, 3], steps: [mcqP('(1 − cos x)/(1 + cos x) = ?', ['tan²(x/2)', 'cot²(x/2)', 'sec²(x/2)', '1 − tan x'], 'Half-angle: 2sin²(x/2)/2cos²(x/2).')] }),
  solQ('Ex 9.3', 'Q2', 'General solution of dy/dx = √(4 − y²) (−2 < y < 2)', (x, y) => sqrt(4 - y * y), (x, y) => asin(y / 2) - x, ['y = 2 sin(x + C)', 'y = 2 cos(x + C)', 'y = sin(2x + C)', 'y = 4 sin(x + C)'], { v: [-4, 4, -2.6, 2.6], seeds: [[-1, 0], [1, 0.5]], steps: [sepS(['dy/√(4 − y²) = dx', 'dy/(4 − y²) = dx', '√(4 − y²) dy = dx', 'dy = √(4 − y²) dx'])], x: 'sin⁻¹(y/2) = x + C.' }),
  solQ('Ex 9.3', 'Q3', 'General solution of dy/dx + y = 1 (y ≠ 1)', (x, y) => 1 - y, (x, y) => (y - 1) * exp(x), ['y = 1 + Ae⁻ˣ', 'y = 1 + Aeˣ', 'y = Ae⁻ˣ', 'y = x + A'], { v: [-2, 4, -2, 4], steps: [sepS(['dy/(1 − y) = dx', 'dy/y = dx', '(1 − y) dy = dx', 'dy = (1 + y) dx'])], x: '−log|1 − y| = x + C, so y = 1 + Ae⁻ˣ.' }),
  solQ('Ex 9.3', 'Q4', 'General solution of sec²x tan y dx + sec²y tan x dy = 0', (x, y) => -(sec(x) ** 2 * tan(y)) / (sec(y) ** 2 * tan(x)), (x, y) => tan(x) * tan(y), ['tan x tan y = C', 'tan x + tan y = C', 'sec x sec y = C', 'tan x = C tan y'], { v: [-1.45, 1.45, -1.45, 1.45], seeds: [[0.6, 0.5], [-0.7, 0.4]], steps: [sepS(['(sec²x/tan x) dx = −(sec²y/tan y) dy', 'sec²x dx = sec²y dy', 'tan x dx = −tan y dy', '(tan x/sec²x) dx = (tan y/sec²y) dy'])], x: 'log|tan x| = −log|tan y| + C.' }),
  solQ('Ex 9.3', 'Q5', 'General solution of (eˣ + e⁻ˣ) dy − (eˣ − e⁻ˣ) dx = 0', (x) => (exp(x) - exp(-x)) / (exp(x) + exp(-x)), (x, y) => y - log(exp(x) + exp(-x)), ['y = log(eˣ + e⁻ˣ) + C', 'y = log(eˣ − e⁻ˣ) + C', 'y = eˣ − e⁻ˣ + C', 'y = tan⁻¹(eˣ) + C'], { v: [-4, 4, -2, 4], steps: [mcqP('∫ (eˣ − e⁻ˣ)/(eˣ + e⁻ˣ) dx: the top is', ['the derivative of the bottom', 'the bottom squared', 'a constant', 'unrelated'], 'So the integral is log(eˣ + e⁻ˣ).')] }),
  solQ('Ex 9.3', 'Q6', 'General solution of dy/dx = (1 + x²)(1 + y²)', (x, y) => (1 + x * x) * (1 + y * y), (x, y) => atan(y) - x - x ** 3 / 3, ['tan⁻¹y = x + x³/3 + C', 'tan⁻¹y = tan⁻¹x + C', 'y = x + x³/3 + C', 'log(1 + y²) = x + C'], { v: [-2, 2, -3, 3], seeds: [[-0.5, 0], [0.3, -1]], steps: [sepS(['dy/(1 + y²) = (1 + x²) dx', '(1 + y²) dy = (1 + x²) dx', 'dy/(1 + y²) = dx/(1 + x²)', 'dy = (1 + y²) dx'])] }),
  solQ('Ex 9.3', 'Q7', 'General solution of y log y dx − x dy = 0', (x, y) => (y * log(y)) / x, (x, y) => log(y) / x, ['y = e^(Cx)', 'y = Cx', 'log y = x + C', 'y = Ceˣ'], { v: [-3, 3, 0, 5], seeds: [[1, 2], [-1, 0.5]], steps: [sepS(['dy/(y log y) = dx/x', 'y log y dy = x dx', 'dy/log y = dx/x', 'log y dy = dx'])], x: 'log|log y| = log|x| + C, so log y = Cx.' }),
  solQ('Ex 9.3', 'Q8', 'General solution of x⁵ dy/dx = −y⁵', (x, y) => -(y ** 5) / x ** 5, (x, y) => x ** -4 + y ** -4, ['x⁻⁴ + y⁻⁴ = C', 'x⁴ + y⁴ = C', 'x⁻⁴ − y⁻⁴ = C', 'x⁵ + y⁵ = C'], { v: [-3, 3, -3, 3], seeds: [[1, 1.2], [-1.3, 1]], steps: [sepS(['dy/y⁵ = −dx/x⁵', 'y⁵ dy = −x⁵ dx', 'dy/y⁵ = dx/x⁵', 'y dy = −x dx'])], x: '−y⁻⁴/4 = x⁻⁴/4 + C.' }),
  solQ('Ex 9.3', 'Q9', 'General solution of dy/dx = sin⁻¹x', (x) => asin(x), (x, y) => y - x * asin(x) - sqrt(1 - x * x), ['y = x sin⁻¹x + √(1 − x²) + C', 'y = x sin⁻¹x − √(1 − x²) + C', 'y = 1/√(1 − x²) + C', 'y = x sin⁻¹x + C'], { v: [-1.2, 1.2, -1.2, 1.6], seeds: [[0, 0], [0, 0.8]], steps: [mcqP('∫ sin⁻¹x dx: use', ['parts with 1 as the second function', 'substitution t = x²', 'partial fractions', 'a trig identity'], 'x sin⁻¹x − ∫ x/√(1 − x²) dx.')] }),
  solQ('Ex 9.3', 'Q10', 'General solution of eˣ tan y dx + (1 − eˣ) sec²y dy = 0', (x, y) => -(exp(x) * tan(y)) / ((1 - exp(x)) * sec(y) ** 2), (x, y) => tan(y) / (1 - exp(x)), ['tan y = C(1 − eˣ)', 'tan y = C(1 + eˣ)', 'tan y = Ceˣ', 'sec²y = C(1 − eˣ)'], { v: [-3, 3, -1.45, 1.45], seeds: [[-1, 0.5], [1, -0.4]], steps: [sepS(['sec²y/tan y dy = eˣ/(eˣ − 1) dx', 'tan y dy = eˣ dx', 'sec²y dy = eˣ dx', 'dy/tan y = dx/(1 − eˣ)'])], x: 'log|tan y| = log|eˣ − 1| + C.' }),
  solQ('Ex 9.3', 'Q11', 'Particular solution: (x³ + x² + x + 1) dy/dx = 2x² + x; y = 1 when x = 0', (x) => (2 * x * x + x) / (x ** 3 + x * x + x + 1), (x, y) => y - 0.25 * (2 * ln(x + 1) + 3 * log(x * x + 1)) + 0.5 * atan(x), ['y = ½ log|x + 1| + ¾ log(x² + 1) − ½ tan⁻¹x + C', 'y = log|x + 1| + log(x² + 1) + C', 'y = ½ log|x + 1| − ¾ log(x² + 1) + ½ tan⁻¹x + C', 'y = tan⁻¹x + C'], { v: [-0.9, 3.5, -1, 3], ic: [0, 1], icLab: '(0, 1)', cq: { q: 'C = ?', a: 1, x: 'At x = 0 every log and tan⁻¹ term is 0.' }, pq: ['y = ¼ log[(x + 1)²(x² + 1)³] − ½ tan⁻¹x + 1', 'y = ¼ log[(x + 1)²(x² + 1)³] + ½ tan⁻¹x', 'y = log[(x + 1)(x² + 1)] + 1', 'y = ¼ log[(x + 1)³(x² + 1)²] − ½ tan⁻¹x + 1'], steps: [mcqP('(2x² + x)/((x + 1)(x² + 1)) = ?', ['(½)/(x + 1) + (3x/2 − ½)/(x² + 1)', '1/(x + 1) + x/(x² + 1)', '(½)/(x + 1) + (x/2 + ½)/(x² + 1)', '2/(x + 1) − 1/(x² + 1)'], 'A = ½ from x = −1; then B = 3/2, C = −½.')] }),
  solQ('Ex 9.3', 'Q12', 'Particular solution: x(x² − 1) dy/dx = 1; y = 0 when x = 2', (x) => 1 / (x * (x * x - 1)), (x, y) => y - 0.5 * log(abs((x * x - 1) / (x * x))), ['y = ½ log|(x² − 1)/x²| + C', 'y = log|x(x² − 1)| + C', 'y = ½ log|x² − 1| + C', 'y = −1/(x² − 1) + C'], { v: [1.05, 4, -1.5, 1.5], ic: [2, 0], icLab: '(2, 0)', cq: { q: 'C = ? (2 decimals)', a: -0.5 * log(0.75), tol: 0.006, show: '−½ log(3/4) ≈ 0.14', keys: '' }, pq: ['y = ½ log((x² − 1)/x²) − ½ log(3/4)', 'y = ½ log((x² − 1)/x²) + ½ log(3/4)', 'y = log((x² − 1)/x²)', 'y = ½ log(x² − 1) − log 2'], steps: [mcqP('1/(x(x − 1)(x + 1)) = ?', ['−1/x + ½/(x − 1) + ½/(x + 1)', '1/x − ½/(x − 1) − ½/(x + 1)', '1/x + 1/(x − 1) + 1/(x + 1)', '−1/x + 1/(x² − 1)'], 'Cover-up at 0, 1, −1.')] }),
  solQ('Ex 9.3', 'Q13', 'Particular solution: cos(dy/dx) = a (a ∈ R); y = 1 when x = 0', (x) => Math.acos(0.5), (x, y) => y - x * Math.acos(0.5), ['y = x cos⁻¹a + C', 'y = x cos a + C', 'y = a x + C', 'y = sin⁻¹(a) x + C'], { v: [-3, 3, -2, 4], cap: 'drawn for a = ½', ic: [0, 1], icLab: '(0, 1)', cq: { q: 'C = ?', a: 1 }, pq: ['cos((y − 1)/x) = a', 'cos(y − 1) = ax', 'y = cos⁻¹a + 1', 'sin((y − 1)/x) = a'], steps: [mcqP('dy/dx = ?', ['cos⁻¹a', 'cos a', 'a', 'sin⁻¹a'], 'A constant slope.')] }),
  solQ('Ex 9.3', 'Q14', 'Particular solution: dy/dx = y tan x; y = 1 when x = 0', (x, y) => y * tan(x), (x, y) => y * cos(x), ['y = C sec x', 'y = C cos x', 'y = tan x + C', 'y = Ceˣ'], { v: [-1.5, 1.5, -1, 4], ic: [0, 1], icLab: '(0, 1)', cq: { q: 'C = ?', a: 1 }, pq: ['y = sec x', 'y = cos x', 'y = 1 + tan x', 'y = eˣ sec x'], steps: [sepS(['dy/y = tan x dx', 'y dy = tan x dx', 'dy = y tan x', 'dy/tan x = y dx'])], x: 'log|y| = log|sec x| + C.' }),
  solQ('Ex 9.3', 'Q15', 'Find the curve through (0, 0) with y′ = eˣ sin x', (x) => exp(x) * sin(x), (x, y) => y - (exp(x) * (sin(x) - cos(x))) / 2, ['y = ½eˣ(sin x − cos x) + C', 'y = eˣ(sin x + cos x) + C', 'y = ½eˣ(cos x − sin x) + C', 'y = eˣ sin x + C'], { v: [-3, 2, -2, 3], ic: [0, 0], icLab: '(0, 0)', cq: { q: 'C = ?', a: 0.5, show: '½', x: '0 = ½(0 − 1) + C.' }, pq: ['2y − 1 = eˣ(sin x − cos x)', '2y + 1 = eˣ(sin x − cos x)', 'y = eˣ(sin x − cos x)', '2y = eˣ(sin x + cos x)'] }),
  solQ('Ex 9.3', 'Q16', 'For xy dy/dx = (x + 2)(y + 2), find the solution curve through (1, −1)', (x, y) => ((x + 2) * (y + 2)) / (x * y), (x, y) => y - 2 * ln(y + 2) - x - 2 * ln(x), ['y − 2 log|y + 2| = x + 2 log|x| + C', 'y + 2 log|y + 2| = x − 2 log|x| + C', 'log|y + 2| = log|x| + C', 'y = x + C'], { v: [-0.6, 4, -1.95, 2.5], ic: [1, -1], icLab: '(1, −1)', cq: { q: 'C = ?', a: -2, x: '−1 − 0 = 1 + 0 + C.' }, pq: ['y − x + 2 = log(x²(y + 2)²)', 'y − x − 2 = log(x²(y + 2)²)', 'y + x = log(x(y + 2))', 'y − x + 2 = log(x(y + 2))'], steps: [sepS(['y/(y + 2) dy = (x + 2)/x dx', '(y + 2) dy = x dx', 'dy/(y + 2) = dx/x', 'y dy = (x + 2) dx'])] }),
  solQ('Ex 9.3', 'Q17', 'Curve through (0, −2): at any point, (slope of tangent) × (y) = x', (x, y) => x / y, (x, y) => y * y - x * x, ['y² − x² = C', 'x² + y² = C', 'y = Cx', 'xy = C'], { v: [-4, 4, -4, 2], ic: [0, -2], icLab: '(0, −2)', cq: { q: 'C = ?', a: 4 }, pq: ['y² − x² = 4', 'x² − y² = 4', 'x² + y² = 4', 'y = x − 2'], steps: [mcqP('Translate:', ['y·dy/dx = x', 'dy/dx = xy', 'dy/dx + y = x', 'x·dy/dx = y'], 'slope × y = x.')] }),
  solQ('Ex 9.3', 'Q18', 'Slope of the tangent is twice the slope of the segment joining (x, y) to (−4, −3). Curve through (−2, 1)', (x, y) => (2 * (y + 3)) / (x + 4), (x, y) => (y + 3) / (x + 4) ** 2, ['y + 3 = C(x + 4)²', 'y + 3 = C(x + 4)', 'y − 3 = C(x − 4)²', 'y = Cx²'], { v: [-7.5, 1.5, -4, 3], ic: [-2, 1], icLab: '(−2, 1)', cq: { q: 'C = ?', a: 1 }, pq: ['(x + 4)² = y + 3', '(x + 4)² = 2(y + 3)', '(x − 4)² = y − 3', 'x + 4 = y + 3'], steps: [mcqP('dy/dx = ?', ['2(y + 3)/(x + 4)', '(y + 3)/(x + 4)', '2(y − 3)/(x − 4)', '(x + 4)/(2(y + 3))'], 'Slope of the segment is (y + 3)/(x + 4).')] }),
  solQ('Ex 9.3', 'Q19', 'Balloon volume changes at a constant rate. r = 3 initially and 6 after 3 seconds. Find r after t seconds.', (x, y) => 21 / (y * y), (x, y) => y ** 3 - 63 * x, ['r³ = kt + C', 'r = kt + C', 'r² = kt + C', 'r = Ce^(kt)'], { v: [-0.5, 6.5, -0.5, 8], cap: 't across, r up', ic: [0, 3], icLab: 't = 0, r = 3', cq: { q: 'Radius after 1 second? (2 decimals)', a: cbrt(90), tol: 0.006, keys: '', show: '∛90 ≈ 4.48' }, pq: ['r = (63t + 27)^(1/3)', 'r = (21t + 27)^(1/3)', 'r = 3 + t', 'r = 3·2^(t/3)'], mq: 'dV/dt = k with V = (4/3)πr³ gives', steps: [mcqP('Volume changes at a constant rate:', ['4πr² dr/dt = k', 'dr/dt = k', 'dV/dt = kV', 'r dr/dt = k'], 'dV/dt = 4πr² dr/dt.')], x: '(4/3)πr³ = kt + C, so r³ is linear in t: 27 at t = 0, 216 at t = 3, so r³ = 63t + 27.' }),
  solQ('Ex 9.3', 'Q20', 'Principal grows continuously at r% a year. Find r if ₹100 doubles in 10 years (logₑ2 = 0.6931).', (x, y) => 0.06931 * y, (x, y) => y * exp(-0.06931 * x), ['P = P₀e^(rt/100)', 'P = P₀(1 + r)ᵗ', 'P = P₀ + rt', 'P = P₀ e^(rt)'], { v: [-1, 12, -0.4, 2.8], cap: 'P in ₹100s, t in years', ic: [0, 1], icLab: '₹100 at t = 0', cq: { q: 'r = ? (%, 2 decimals)', a: 6.931, tol: 0.006, keys: '', show: '6.93' }, mq: 'dP/dt = (r/100)P gives', x: 'e^(10r/100) = 2, so r = 10 logₑ2 = 6.931%.' }),
  solQ('Ex 9.3', 'Q21', 'At 5% continuous growth, what is ₹1000 worth after 10 years? (e^0.5 = 1.648)', (x, y) => 0.05 * y, (x, y) => y * exp(-0.05 * x), ['P = 1000e^(0.05t)', 'P = 1000(1.05)ᵗ', 'P = 1000 + 50t', 'P = 1000e^(5t)'], { v: [-1, 12, -0.3, 2.2], cap: 'P in ₹1000s', ic: [0, 1], icLab: '₹1000 at t = 0', cq: { q: 'Worth after 10 years (₹)?', a: 1648, tol: 0.5, keys: '', show: '₹1648' }, mq: 'dP/dt = P/20 with P(0) = 1000 gives' }),
  solQ('Ex 9.3', 'Q22', 'Bacteria: 1,00,000 grow by 10% in 2 hours, growth rate ∝ count. When will they reach 2,00,000?', (x, y) => 0.5 * log(1.1) * y, (x, y) => y * exp(-0.5 * log(1.1) * x), ['N = N₀e^(kt) with e^(2k) = 1.1', 'N = N₀ + kt', 'N = N₀(1.1)ᵗ', 'N = N₀e^(1.1t)'], { v: [-1, 18, -0.3, 2.6], cap: 'N in lakhs, t in hours', ic: [0, 1], icLab: '1 lakh at t = 0', cq: { q: 'Hours to double? (2 decimals)', a: (2 * log(2)) / log(1.1), tol: 0.006, keys: '', show: '2 log 2/log 1.1 ≈ 14.55' }, mq: 'dN/dt = kN gives' }),
  solQ('Ex 9.3', 'Q23', 'The general solution of dy/dx = e^(x + y) is (A) eˣ + e⁻ʸ = C (B) eˣ + eʸ = C (C) e⁻ˣ + eʸ = C (D) e⁻ˣ + e⁻ʸ = C', (x, y) => exp(x + y), (x, y) => exp(x) + exp(-y), ['eˣ + e⁻ʸ = C', 'eˣ + eʸ = C', 'e⁻ˣ + eʸ = C', 'e⁻ˣ + e⁻ʸ = C'], { v: [-3, 2, -3, 2], seeds: [[-1, -1], [0, -2]], steps: [sepS(['e⁻ʸ dy = eˣ dx', 'eʸ dy = eˣ dx', 'dy = eˣ dx', 'e⁻ʸ dy = e⁻ˣ dx'])], post: [mcqP('Answer', ['(A)', '(B)', '(C)', '(D)'], '−e⁻ʸ = eˣ + C.')] }),
];
