/* =========================================================
   CLASS 12 · CHAPTER 9 — Exercises 9.4, 9.5 and Miscellaneous
   ========================================================= */
const vxS = (o, x) => mcqP('Put y = vx. Then x dv/dx = ?', o, x || 'dy/dx = v + x dv/dx.');
const ifS = (o, x) => mcqP('Integrating factor = ?', o, x || 'I.F. = e^(∫P dx).');
const at2 = Math.atan2;

/* ===================== EXERCISE 9.4 ===================== */
const EX94 = [
  solQ('Ex 9.4', 'Q1', 'Show homogeneous and solve: (x² + xy) dy = (x² + y²) dx', (x, y) => (x * x + y * y) / (x * x + x * y), (x, y) => ((x - y) ** 2 * exp(y / x)) / x, ['(x − y)² = Cx e^(−y/x)', '(x + y)² = Cx e^(y/x)', 'x − y = Ce^(y/x)', '(x − y)² = Cx'], { v: [0.2, 4.5, -1.5, 3.5], seeds: [[1, 0], [2, 3]], steps: [vxS(['(1 − v)/(1 + v)', '(1 + v)/(1 − v)', '(1 + v²)/(1 + v)', 'v²'], 'v + x dv/dx = (1 + v²)/(1 + v).')], x: '∫(1 + v)/(1 − v) dv = log|x| + C gives −v − 2 log|1 − v| = log|x| + C.' }),
  solQ('Ex 9.4', 'Q2', 'Show homogeneous and solve: y′ = (x + y)/x', (x, y) => (x + y) / x, (x, y) => y / x - ln(x), ['y = x log|x| + Cx', 'y = log|x| + C', 'y = Cx', 'y = x² + Cx'], { v: [-4, 4, -3, 3], steps: [vxS(['1', 'v', '1 + v', 'v²'])] }),
  solQ('Ex 9.4', 'Q3', 'Show homogeneous and solve: (x − y) dy − (x + y) dx = 0', (x, y) => (x + y) / (x - y), (x, y) => at2(y, x) - 0.5 * log(x * x + y * y), ['tan⁻¹(y/x) = ½ log(x² + y²) + C', 'tan⁻¹(y/x) = log(x² + y²) + C', 'x² + y² = C', 'y = Cx'], { v: [-4, 4, -3, 3], seeds: [[1, 0], [-0.5, 1]], steps: [vxS(['(1 + v²)/(1 − v)', '(1 − v²)/(1 + v)', '(1 + v)/(1 − v)', '2v/(1 − v)'])], x: 'Spirals! (1 − v)/(1 + v²) dv = dx/x integrates to tan⁻¹v − ½ log(1 + v²) = log|x| + C.' }),
  solQ('Ex 9.4', 'Q4', 'Show homogeneous and solve: (x² − y²) dx + 2xy dy = 0', (x, y) => (y * y - x * x) / (2 * x * y), (x, y) => (x * x + y * y) / x, ['x² + y² = Cx', 'x² − y² = Cx', 'x² + y² = Cy', 'y² = Cx'], { v: [-4, 4, -3, 3], seeds: [[1, 1], [-2, 0.5]], steps: [vxS(['−(1 + v²)/(2v)', '(1 + v²)/(2v)', '(v² − 1)/(2v)', '−v'])], x: 'Circles through the origin, centred on the x-axis.' }),
  solQ('Ex 9.4', 'Q5', 'Show homogeneous and solve: x² dy/dx = x² − 2y² + xy', (x, y) => (x * x - 2 * y * y + x * y) / (x * x), (x, y) => (1 / (2 * sqrt(2))) * log(abs((x + sqrt(2) * y) / (x - sqrt(2) * y))) - ln(x), ['(1/(2√2)) log|(x + √2y)/(x − √2y)| = log|x| + C', '(1/√2) tan⁻¹(√2 y/x) = log|x| + C', 'log|x² − 2y²| = x + C', 'y = x log|x| + C'], { v: [0.2, 4.5, -2.5, 3], seeds: [[1, 0], [3, -1]], steps: [vxS(['1 − 2v²', '1 + v − 2v²', '1 − v²', '1 − 2v'])] }),
  solQ('Ex 9.4', 'Q6', 'Show homogeneous and solve: x dy − y dx = √(x² + y²) dx', (x, y) => (y + sqrt(x * x + y * y)) / x, (x, y) => (y + sqrt(x * x + y * y)) / (x * x), ['y + √(x² + y²) = Cx²', 'y + √(x² + y²) = Cx', 'x² + y² = Cx²', 'y = Cx²'], { v: [0.1, 4.5, -3, 3], seeds: [[1, 0], [2, -1.5]], steps: [vxS(['√(1 + v²)', '1 + v²', 'v + √(1 + v²)', '1/√(1 + v²)'])], x: 'log|v + √(1 + v²)| = log|x| + C.' }),
  solQ('Ex 9.4', 'Q7', 'Show homogeneous and solve: {x cos(y/x) + y sin(y/x)} y dx = {y sin(y/x) − x cos(y/x)} x dy', (x, y) => { const v = y / x; return (v * (cos(v) + v * sin(v))) / (v * sin(v) - cos(v)); }, (x, y) => x * y * cos(y / x), ['xy cos(y/x) = C', 'xy sin(y/x) = C', 'cos(y/x) = Cxy', 'y = Cx cos(y/x)'], { v: [0.2, 4, -2.5, 2.5], seeds: [[1, 0.5], [2, -0.5]], steps: [vxS(['2v cos v/(v sin v − cos v)', 'v cos v/(v sin v − cos v)', '2v sin v/(v cos v − sin v)', 'cos v'])], x: 'Same type as Example 21: sec(y/x) = Cxy, i.e. xy cos(y/x) = C.' }),
  solQ('Ex 9.4', 'Q8', 'Show homogeneous and solve: x dy/dx − y + x sin(y/x) = 0', (x, y) => y / x - sin(y / x), (x, y) => (x * (1 - cos(y / x))) / sin(y / x), ['x[1 − cos(y/x)] = C sin(y/x)', 'x sin(y/x) = C', 'cos(y/x) = log|Cx|', 'x[1 + cos(y/x)] = C sin(y/x)'], { v: [0.2, 4.5, -1, 5], seeds: [[1, 1], [2, 4]], steps: [vxS(['−sin v', 'sin v', 'v − sin v', '−cos v'])], x: 'cosec v dv = −dx/x: log|cosec v − cot v| = −log|x| + C.' }),
  solQ('Ex 9.4', 'Q9', 'Show homogeneous and solve: y dx + x log(y/x) dy − 2x dy = 0', (x, y) => y / (x * (2 - log(y / x))), (x, y) => (log(y / x) - 1) / y, ['Cy = log|y/x| − 1', 'Cy = log|y/x| + 1', 'y = Cx log|y/x|', 'log(y/x) = Cx'], { v: [0.2, 4, 0.2, 4], seeds: [[1, 1], [2, 1]], steps: [vxS(['v(log v − 1)/(2 − log v)', 'v/(2 − log v)', 'v(1 − log v)', '(log v − 1)/(2 − log v)'])] }),
  solQ('Ex 9.4', 'Q10', 'Show homogeneous and solve: (1 + e^(x/y)) dx + e^(x/y)(1 − x/y) dy = 0', (x, y) => -(1 + exp(x / y)) / (exp(x / y) * (1 - x / y)), (x, y) => x + y * exp(x / y), ['x + y e^(x/y) = C', 'x − y e^(x/y) = C', 'y + x e^(y/x) = C', 'e^(x/y) = Cy'], { v: [-3, 3, 0.4, 4], seeds: [[-1, 1], [0, 2.5]], steps: [mcqP('dx/dy depends on x/y, so put', ['x = vy', 'y = vx', 'v = x + y', 'x = v'], 'Use x = vy for dx/dy = h(x/y).')] }),
  solQ('Ex 9.4', 'Q11', 'Particular solution: (x + y) dy + (x − y) dx = 0; y = 1 when x = 1', (x, y) => (y - x) / (x + y), (x, y) => log(x * x + y * y) + 2 * at2(y, x), ['log(x² + y²) + 2 tan⁻¹(y/x) = C', 'log(x² + y²) − 2 tan⁻¹(y/x) = C', 'x² + y² = C', 'y = Cx'], { v: [-3, 3, -2.5, 3], ic: [1, 1], icLab: '(1, 1)', cq: { q: 'C = ? (2 decimals)', a: log(2) + PI / 2, tol: 0.006, keys: '', show: 'π/2 + log 2 ≈ 2.26' }, pq: ['log(x² + y²) + 2 tan⁻¹(y/x) = π/2 + log 2', 'log(x² + y²) − 2 tan⁻¹(y/x) = log 2 − π/2', 'x² + y² = 2', 'log(x² + y²) = log 2'], steps: [vxS(['−(1 + v²)/(1 + v)', '(1 + v²)/(1 + v)', '(v − 1)/(v + 1)', '−v'])] }),
  solQ('Ex 9.4', 'Q12', 'Particular solution: x² dy + (xy + y²) dx = 0; y = 1 when x = 1', (x, y) => -(x * y + y * y) / (x * x), (x, y) => (x * x * y) / (y + 2 * x), ['x²y = C(y + 2x)', 'xy = C(y + x)', 'x²y = C', 'y = Cx'], { v: [0.2, 3.5, -1, 3], ic: [1, 1], icLab: '(1, 1)', cq: { q: 'C = ?', a: 1 / 3, show: '1/3' }, pq: ['y + 2x = 3x²y', 'y + 2x = x²y', '3(y + 2x) = x²y', 'y = x'], steps: [vxS(['−v(v + 2)', '−v²', 'v(v + 2)', '−2v'])] }),
  solQ('Ex 9.4', 'Q13', 'Particular solution: [x sin²(y/x) − y] dx + x dy = 0; y = π/4 when x = 1', (x, y) => (y - x * sin(y / x) ** 2) / x, (x, y) => cot(y / x) - ln(x), ['cot(y/x) = log|x| + C', 'tan(y/x) = log|x| + C', 'sin(y/x) = log|x| + C', 'cot(y/x) = x + C'], { v: [0.3, 4.5, -0.5, 4], ic: [1, PI / 4], icLab: '(1, π/4)', cq: { q: 'C = ?', a: 1 }, pq: ['cot(y/x) = log|ex|', 'cot(y/x) = log|x|', 'tan(y/x) = log|ex|', 'cot(y/x) = 1 + x'], steps: [vxS(['−sin²v', 'sin²v', 'v − sin²v', '−cos²v'])], x: '−cosec²v dv = dx/x, so cot v = log|x| + C.' }),
  solQ('Ex 9.4', 'Q14', 'Particular solution: dy/dx − y/x + cosec(y/x) = 0; y = 0 when x = 1', (x, y) => y / x - csc(y / x), (x, y) => cos(y / x) - ln(x), ['cos(y/x) = log|x| + C', 'sin(y/x) = log|x| + C', 'cos(y/x) = x + C', 'sec(y/x) = log|x| + C'], { v: [0.3, 3, -2.5, 2.5], ic: [1, 0], icLab: '(1, 0)', cq: { q: 'C = ?', a: 1 }, pq: ['cos(y/x) = log|ex|', 'cos(y/x) = log|x|', 'sin(y/x) = log|ex|', 'cos(y/x) = e·x'], steps: [vxS(['−cosec v', 'cosec v', 'v − cosec v', '−sin v'])] }),
  solQ('Ex 9.4', 'Q15', 'Particular solution: 2xy + y² − 2x² dy/dx = 0; y = 2 when x = 1', (x, y) => (2 * x * y + y * y) / (2 * x * x), (x, y) => (2 * x) / y + ln(x), ['2x/y + log|x| = C', 'y = Cx', '2y/x + log|x| = C', 'y² = Cx'], { v: [0.2, 2.6, -1, 5.5], ic: [1, 2], icLab: '(1, 2)', cq: { q: 'C = ?', a: 1 }, pq: ['y = 2x/(1 − log x)', 'y = 2x/(1 + log x)', 'y = 2x log x', 'y = 2x'], steps: [vxS(['v²/2', 'v + v²/2', 'v²', '2v'])] }),
  boardQ('Ex 9.4', 'Q16', 'A homogeneous equation dx/dy = h(x/y) is solved by the substitution (A) y = vx (B) v = yx (C) x = vy (D) x = v', [mcqP('Answer', ['(C) x = vy', '(A) y = vx', '(B) v = yx', '(D) x = v'], 'x/y = v, so x = vy.')], '(C)'),
  boardQ('Ex 9.4', 'Q17', 'Which is homogeneous? (A) (4x + 6y + 5) dy − (3y + 2x + 4) dx = 0 (B) xy dx − (x³ + y³) dy = 0 (C) (x³ + 2y²) dx + 2xy dy = 0 (D) y² dx + (x² − xy − y²) dy = 0', [mcqP('Answer', ['(D)', '(A)', '(B)', '(C)'], 'Every term in (D) has degree 2. (A) has constants, (B) mixes degrees 2 and 3, (C) mixes 3 and 2.')], '(D)'),
];

/* ===================== EXERCISE 9.5 ===================== */
const EX95 = [
  solQ('Ex 9.5', 'Q1', 'General solution of dy/dx + 2y = sin x', (x, y) => sin(x) - 2 * y, (x, y) => (y - (2 * sin(x) - cos(x)) / 5) * exp(2 * x), ['y = (2 sin x − cos x)/5 + Ce^(−2x)', 'y = (sin x − 2 cos x)/5 + Ce^(−2x)', 'y = sin x + Ce^(2x)', 'y = −cos x/2 + Ce^(−2x)'], { v: [-2, 5, -2, 2.5], steps: [ifS(['e^(2x)', 'e^(−2x)', '2x', 'eˣ'])] }),
  solQ('Ex 9.5', 'Q2', 'General solution of dy/dx + 3y = e^(−2x)', (x, y) => exp(-2 * x) - 3 * y, (x, y) => (y - exp(-2 * x)) * exp(3 * x), ['y = e^(−2x) + Ce^(−3x)', 'y = e^(−2x) + Ce^(3x)', 'y = −e^(−2x) + Ce^(−3x)', 'y = e^(x) + Ce^(−3x)'], { v: [-1, 4, -1.5, 3], steps: [ifS(['e^(3x)', 'e^(−3x)', 'e^(−2x)', '3x'])] }),
  solQ('Ex 9.5', 'Q3', 'General solution of dy/dx + y/x = x²', (x, y) => x * x - y / x, (x, y) => x * y - x ** 4 / 4, ['xy = x⁴/4 + C', 'y = x³/3 + C', 'xy = x³/3 + C', 'y/x = x⁴/4 + C'], { v: [0.2, 3, -2, 4], seeds: [[1, 0], [1, 2]], steps: [ifS(['x', '1/x', 'log x', 'x²'])] }),
  solQ('Ex 9.5', 'Q4', 'General solution of dy/dx + (sec x) y = tan x (0 ≤ x < π/2)', (x, y) => tan(x) - y / cos(x), (x, y) => y * (sec(x) + tan(x)) - (sec(x) + tan(x) - x), ['y(sec x + tan x) = sec x + tan x − x + C', 'y sec x = tan x + C', 'y(sec x + tan x) = x + C', 'y = tan x + C sec x'], { v: [0, 1.5, -1.5, 2], seeds: [[0.2, -1], [0.2, 1.5]], fx: piLab9, steps: [ifS(['sec x + tan x', 'sec x', 'e^(sec x)', 'cos x'], '∫sec x dx = log|sec x + tan x|.')] }),
  solQ('Ex 9.5', 'Q5', 'General solution of cos²x dy/dx + y = tan x (0 ≤ x < π/2)', (x, y) => (tan(x) - y) / cos(x) ** 2, (x, y) => (y - tan(x) + 1) * exp(tan(x)), ['y = tan x − 1 + Ce^(−tan x)', 'y = tan x + 1 + Ce^(tan x)', 'y = tan x + C', 'y = −1 + Ce^(tan x)'], { v: [0, 1.4, -2, 3], seeds: [[0.1, -1.5], [0.1, 2]], steps: [ifS(['e^(tan x)', 'e^(sec²x)', 'tan x', 'cos²x'], 'Divide by cos²x: P = sec²x.')] }),
  solQ('Ex 9.5', 'Q6', 'General solution of x dy/dx + 2y = x² log x', (x, y) => x * log(x) - (2 * y) / x, (x, y) => x * x * y - (x ** 4 * log(x)) / 4 + x ** 4 / 16, ['y = (x²/16)(4 log x − 1) + Cx⁻²', 'y = (x²/4) log x + Cx⁻²', 'y = x² log x + C', 'y = (x/16)(4 log x − 1) + C/x'], { v: [0.2, 3, -2, 3], seeds: [[1, 1], [1, -0.5]], steps: [ifS(['x²', 'x', '1/x²', 'e^(2x)'])] }),
  solQ('Ex 9.5', 'Q7', 'General solution of x log x dy/dx + y = (2/x) log x', (x, y) => 2 / (x * x) - y / (x * log(x)), (x, y) => y * log(x) + (2 / x) * (1 + log(x)), ['y log x = −(2/x)(1 + log x) + C', 'y log x = (2/x)(1 + log x) + C', 'y = −2/x + C', 'y log x = −2/x + C'], { v: [0.2, 4, -4, 4], seeds: [[2, 0], [0.5, 1]], steps: [ifS(['log x', 'x log x', '1/log x', 'x'])] }),
  solQ('Ex 9.5', 'Q8', 'General solution of (1 + x²) dy + 2xy dx = cot x dx (x ≠ 0)', (x, y) => (1 / tan(x) - 2 * x * y) / (1 + x * x), (x, y) => y * (1 + x * x) - log(abs(sin(x))), ['(1 + x²) y = log|sin x| + C', '(1 + x²) y = log|cos x| + C', 'y = cot x + C', '(1 + x²) y = tan x + C'], { v: [0.1, 3, -2, 2], seeds: [[1, 0], [2, 1]], steps: [ifS(['1 + x²', 'e^(x²)', '2x', 'log(1 + x²)'])] }),
  solQ('Ex 9.5', 'Q9', 'General solution of x dy/dx + y − x + xy cot x = 0 (x ≠ 0)', (x, y) => 1 - y / x - y / tan(x), (x, y) => x * sin(x) * y + x * cos(x) - sin(x), ['y = 1/x − cot x + C/(x sin x)', 'y = 1/x + cot x + C/(x sin x)', 'y = x − cot x + C', 'xy sin x = C'], { v: [0.2, 3, -3, 3], seeds: [[1, 0], [2, 1]], steps: [ifS(['x sin x', 'sin x', 'x cos x', 'x'], 'P = 1/x + cot x: e^(log x + log sin x).')] }),
  solQ('Ex 9.5', 'Q10', 'General solution of (x + y) dy/dx = 1', (x, y) => 1 / (x + y), (x, y) => (x + y + 1) * exp(-y), ['x + y + 1 = Ceʸ', 'x + y + 1 = Ceˣ', 'x = Ceʸ − 1', 'x + y = Ceʸ'], { v: [-4, 3, -3, 3], seeds: [[0, 1], [-2, -1]], steps: [mcqP('Treat x as the unknown:', ['dx/dy − x = y', 'dy/dx + y = x', 'dx/dy + x = y', 'dy/dx − x = y'], 'dx/dy = x + y.'), ifS(['e^(−y)', 'eʸ', 'e^(−x)', 'y'], 'P₁ = −1 in y.')] }),
  solQ('Ex 9.5', 'Q11', 'General solution of y dx + (x − y²) dy = 0', (x, y) => -y / (x - y * y), (x, y) => x * y - y ** 3 / 3, ['x = y²/3 + C/y', 'x = y²/2 + C/y', 'y = x²/3 + C/x', 'xy = y² + C'], { v: [-3, 4, -3, 3], seeds: [[1, 1], [-1, 2]], steps: [mcqP('As a linear equation in x:', ['dx/dy + x/y = y', 'dy/dx + y/x = x', 'dx/dy − x/y = y', 'dx/dy + x = y²'], 'Divide by y dy.'), ifS(['y', '1/y', 'x', 'e^y'], 'e^(∫dy/y) = y.')] }),
  solQ('Ex 9.5', 'Q12', 'General solution of (x + 3y²) dy/dx = y (y > 0)', (x, y) => y / (x + 3 * y * y), (x, y) => x / y - 3 * y, ['x = 3y² + Cy', 'x = 3y + C', 'y = 3x² + Cx', 'x = y³ + Cy'], { v: [-3, 4, 0.1, 3], seeds: [[0, 1], [2, 1]], steps: [mcqP('As a linear equation in x:', ['dx/dy − x/y = 3y', 'dx/dy + x/y = 3y', 'dy/dx − y/x = 3x', 'dx/dy − x = 3y²'], 'dx/dy = (x + 3y²)/y.'), ifS(['1/y', 'y', 'e^(−y)', '−y'])] }),
  solQ('Ex 9.5', 'Q13', 'Particular solution: dy/dx + 2y tan x = sin x; y = 0 when x = π/3', (x, y) => sin(x) - 2 * y * tan(x), (x, y) => y / cos(x) ** 2 - 1 / cos(x), ['y sec²x = sec x + C', 'y sec x = tan x + C', 'y cos²x = cos x + C', 'y = sin x + C cos²x'], { v: [-1.45, 1.45, -1.5, 1.5], ic: [PI / 3, 0], icLab: '(π/3, 0)', fx: piLab9, cq: { q: 'C = ?', a: -2, x: '0 = sec(π/3) + C = 2 + C.' }, pq: ['y = cos x − 2 cos²x', 'y = cos x + 2 cos²x', 'y = 2 cos²x − cos x', 'y = sin x − 2 cos x'], steps: [ifS(['sec²x', 'cos²x', 'e^(tan x)', 'sec x'], 'e^(2 log sec x) = sec²x.')] }),
  solQ('Ex 9.5', 'Q14', '(1 + x²) dy/dx + 2xy = 1/(1 + x²); y(1) = 0', (x, y) => (1 / (1 + x * x) - 2 * x * y) / (1 + x * x), (x, y) => y * (1 + x * x) - atan(x), ['y(1 + x²) = tan⁻¹x + C', 'y = tan⁻¹x + C', 'y(1 + x²) = log(1 + x²) + C', 'y(1 + x²) = x + C'], { v: [-3, 3, -1.5, 1.5], ic: [1, 0], icLab: '(1, 0)', cq: { q: 'C = ?', a: -PI / 4, show: '−π/4' }, pq: ['y(1 + x²) = tan⁻¹x − π/4', 'y(1 + x²) = tan⁻¹x + π/4', 'y = tan⁻¹x − π/4', 'y(1 + x²) = π/4 − tan⁻¹x'], steps: [mcqP('The left side is', ['d/dx[(1 + x²)y]', 'd/dx[y/(1 + x²)]', 'd/dx[xy]', 'not exact'], 'I.F. 1 + x² is built in.')] }),
  solQ('Ex 9.5', 'Q15', 'Particular solution: dy/dx − 3y cot x = sin 2x; y = 2 when x = π/2', (x, y) => sin(2 * x) + 3 * y / tan(x), (x, y) => y / sin(x) ** 3 + 2 / sin(x), ['y = −2 sin²x + C sin³x', 'y = 2 sin²x + C sin³x', 'y = −2 sin x + C sin²x', 'y = C sin³x'], { v: [0.2, 3, -2, 3], ic: [PI / 2, 2], icLab: '(π/2, 2)', fx: piLab9, cq: { q: 'C = ?', a: 4, x: '2 = −2 + C.' }, pq: ['y = 4 sin³x − 2 sin²x', 'y = 4 sin³x + 2 sin²x', 'y = 2 sin³x', 'y = 4 sin²x − 2 sin x'], steps: [ifS(['cosec³x', 'sin³x', 'e^(3 cot x)', 'cos³x'], 'e^(−3 log sin x).')] }),
  solQ('Ex 9.5', 'Q16', 'Curve through the origin whose slope at (x, y) equals the sum of the coordinates', (x, y) => x + y, (x, y) => (x + y + 1) * exp(-x), ['y = −x − 1 + Ceˣ', 'y = x + 1 + Ceˣ', 'y = Ceˣ', 'y = x² + C'], { v: [-3, 2, -2, 3], ic: [0, 0], icLab: '(0, 0)', cq: { q: 'C = ?', a: 1 }, pq: ['x + y + 1 = eˣ', 'x + y = eˣ', 'y = eˣ − 1', 'x + y − 1 = eˣ'], steps: [mcqP('Translate:', ['dy/dx − y = x', 'dy/dx + y = x', 'dy/dx = xy', 'dy/dx − x = y²'], 'y′ = x + y.')] }),
  solQ('Ex 9.5', 'Q17', 'Curve through (0, 2): x + y exceeds the magnitude of the slope by 5', (x, y) => x + y - 5, (x, y) => (y + x - 4) * exp(-x), ['y = 4 − x + Ceˣ', 'y = 4 + x + Ceˣ', 'y = −4 − x + Ceˣ', 'y = 5 − x + Ce⁻ˣ'], { v: [-3, 2, -3, 6], ic: [0, 2], icLab: '(0, 2)', cq: { q: 'C = ?', a: -2 }, pq: ['y = 4 − x − 2eˣ', 'y = 4 − x + 2eˣ', 'y = 5 − x − 3eˣ', 'y = 2 − x'], kim: 'At (0, 2), x + y = 2. How can it exceed |slope| by 5?',
    steps: [mcqP('The book writes the equation as', ['dy/dx = x + y − 5', 'dy/dx = 5 − x − y', '|dy/dx| = x + y', 'dy/dx = x + y + 5'], 'Treating “magnitude of the slope” as the slope itself.')],
    post: [{ k: 'tf', q: 'Taken literally, x + y − 5 = |y′| ≥ 0 cannot hold at (0, 2).', a: true, x: 'Answer-key check: at (0, 2), x + y − 5 = −3 < 0, so no curve through (0, 2) has |y′| = x + y − 5. The book\'s curve y = 4 − x − 2eˣ satisfies y′ = x + y − 5 (slope −3 there), not the “magnitude” wording.' }], w: 'y = 4 − x − 2eˣ (solves y′ = x + y − 5; the literal |y′| version is impossible at (0, 2))' }),
  boardQ('Ex 9.5', 'Q18', 'The integrating factor of x dy/dx − y = 2x² is (A) e⁻ˣ (B) e⁻ʸ (C) 1/x (D) x', [mcqP('Write it as', ['dy/dx − y/x = 2x', 'dy/dx − y = 2x²', 'dy/dx + y/x = 2x', 'dx/dy − x = 2y'], 'Divide by x.'), mcqP('Answer', ['(C) 1/x', '(A) e⁻ˣ', '(B) e⁻ʸ', '(D) x'], 'e^(−log x) = 1/x.')], '(C) 1/x'),
  boardQ('Ex 9.5', 'Q19', 'Integrating factor of (1 − y²) dx/dy + yx = ay (−1 < y < 1)?', [mcqP('P₁ = ?', ['y/(1 − y²)', 'y', '1/(1 − y²)', 'ay/(1 − y²)'], 'Divide by 1 − y².'), mcqP('Answer', ['(D) 1/√(1 − y²)', '(A) 1/(y² − 1)', '(B) 1/√(y² − 1)', '(C) 1/(1 − y²)'], '∫ y/(1 − y²) dy = −½ log(1 − y²).')], '(D) 1/√(1 − y²)'),
];

/* ===================== MISCELLANEOUS EXERCISE ===================== */
const EX9M = [
  odQ('Misc 9', 'Q1(i)', 'Order and degree of d²y/dx² + 5x(dy/dx)² − 6y = log x', 'y″ + 5x(y′)² − 6y = log x', [[2, 1, 'y″'], [1, 2, '5x(y′)²'], [0, 1, '6y']], 2, 1),
  odQ('Misc 9', 'Q1(ii)', 'Order and degree of (dy/dx)³ − 4(dy/dx)² + 7y = sin x', '(y′)³ − 4(y′)² + 7y = sin x', [[1, 3, '(y′)³'], [1, 2, '4(y′)²'], [0, 1, '7y']], 1, 3),
  odQ('Misc 9', 'Q1(iii)', 'Order and degree of d⁴y/dx⁴ − sin(d³y/dx³) = 0', 'y⁗ − sin(y‴) = 0', [[4, 1, 'y⁗'], [3, 1, 'sin(y‴)', 'sin']], 4, 'nd'),
  verQ('Misc 9', 'Q2(i)', 'Verify xy = aeˣ + be⁻ˣ + x² is a solution of x y″ + 2y′ − xy + x² − 2 = 0', { fam: (x, a) => (a * exp(x) + exp(-x) + x * x) / x, res: resid((x, a) => (a * exp(x) + exp(-x) + x * x) / x, (x, y, y1, y2) => x * y2 + 2 * y1 - x * y + x * x - 2), cs: [-1, 2, 0.5, 1], c0: 0.5, cname: 'a', v: [0.3, 3.3, -2, 7], cap: 'b = 1', steps: [mcqP('Let u = xy. Then u″ = ?', ['x y″ + 2y′', 'x y″ + y′', 'y″', 'x y″'], '(xy)′ = y + xy′, (xy)″ = 2y′ + xy″.'), mcqP('And u″ from u = aeˣ + be⁻ˣ + x² is', ['u − x² + 2', 'u + 2', 'u − x²', '2'], 'aeˣ + be⁻ˣ + 2 = (u − x²) + 2.')] }),
  verQ('Misc 9', 'Q2(ii)', 'Verify y = eˣ(a cos x + b sin x) is a solution of y″ − 2y′ + 2y = 0', { fam: (x, a) => exp(x) * (a * cos(x) + sin(x)), res: resid((x, a) => exp(x) * (a * cos(x) + sin(x)), (x, y, y1, y2) => y2 - 2 * y1 + 2 * y), cs: [-2, 2, 0.5, 1], c0: 0, cname: 'a', v: [-4, 2.2, -3, 4], cap: 'b = 1', steps: [mcqP('y′ = ?', ['y + eˣ(−a sin x + b cos x)', 'eˣ(−a sin x + b cos x)', 'y', '2y'], 'Product rule.')] }),
  verQ('Misc 9', 'Q2(iii)', 'Verify y = x sin 3x is a solution of y″ + 9y − 6 cos 3x = 0', { fam: (x) => x * sin(3 * x), res: resid((x) => x * sin(3 * x), (x, y, y1, y2) => y2 + 9 * y - 6 * cos(3 * x)), v: [-4, 4, -4, 4], steps: [mcqP('y″ = ?', ['6 cos 3x − 9x sin 3x', '3 cos 3x − 9x sin 3x', '−9x sin 3x', '6 cos 3x'], 'y′ = sin 3x + 3x cos 3x.')] }),
  verQ('Misc 9', 'Q2(iv)', 'Verify x² = 2y² log y is a solution of (x² + y²) dy/dx − xy = 0', { F: (x, y) => (x * y) / (x * x + y * y), G: (x, y) => (x * x) / (y * y) - 2 * log(y), imp: [[sqrt(8 * log(2)), 2]], onlyLevel: true, v: [-4, 4, 0.2, 4], steps: [mcqP('Differentiate x² = 2y² log y:', ['2x = (4y log y + 2y) y′', '2x = 4y log y·y′', '2x = 2y y′', 'x = y log y·y′'], 'Product rule.'), mcqP('Then (x² + y²) y′ = ?', ['xy', 'x', 'x²', 'y²'], 'x² + y² = y²(2 log y + 1).')] }),
  solQ('Misc 9', 'Q3', 'Prove x² − y² = c(x² + y²)² is the general solution of (x³ − 3xy²) dx = (y³ − 3x²y) dy', (x, y) => (x ** 3 - 3 * x * y * y) / (y ** 3 - 3 * x * x * y), (x, y) => (x * x - y * y) / (x * x + y * y) ** 2, ['x² − y² = c(x² + y²)²', 'x² + y² = c(x² − y²)²', 'x² − y² = c', 'xy = c(x² + y²)'], { v: [-3, 3, -2.5, 2.5], seeds: [[1, 0.3], [-1.2, 0.5]], mq: 'Integrating gives', steps: [vxS(['(1 − v⁴)/(v³ − 3v)', '(1 + v⁴)/(v³ − 3v)', '(1 − 3v²)/(v³ − 3v)', 'v⁴ − 1'], 'dy/dx = (1 − 3v²)/(v³ − 3v).'), mcqP('Partial fractions of (v³ − 3v)/(1 − v⁴) integrate to', ['log|(1 − v²)/(1 + v²)²| (up to sign)', 'tan⁻¹v', 'log|1 − v⁴|', 'v²/2'], 'Then put v = y/x.')] }),
  solQ('Misc 9', 'Q4', 'General solution of dy/dx + √((1 − y²)/(1 − x²)) = 0', (x, y) => -sqrt((1 - y * y) / (1 - x * x)), (x, y) => asin(x) + asin(y), ['sin⁻¹x + sin⁻¹y = C', 'sin⁻¹x − sin⁻¹y = C', 'x + y = C', 'cos⁻¹x + sin⁻¹y = C'], { v: [-1.2, 1.2, -1.2, 1.2], seeds: [[0, 0], [-0.4, 0.2]], steps: [sepS(['dy/√(1 − y²) = −dx/√(1 − x²)', '√(1 − y²) dy = √(1 − x²) dx', 'dy/(1 − y²) = dx/(1 − x²)', 'dy = −dx'])] }),
  solQ('Misc 9', 'Q5', 'Show the general solution of dy/dx + (y² + y + 1)/(x² + x + 1) = 0 is (x + y + 1) = A(1 − x − y − 2xy)', (x, y) => -(y * y + y + 1) / (x * x + x + 1), (x, y) => (x + y + 1) / (1 - x - y - 2 * x * y), ['(x + y + 1) = A(1 − x − y − 2xy)', '(x + y + 1) = A(1 + x + y + 2xy)', 'x + y = A', 'xy = A(x + y)'], { v: [-3, 3, -3, 3], seeds: [[0, 0], [1, -1.5]], mq: 'So the general solution is', steps: [mcqP('∫ dy/(y² + y + 1) = ?', ['(2/√3) tan⁻¹((2y + 1)/√3)', 'tan⁻¹(y + ½)', 'log(y² + y + 1)', '(1/√3) tan⁻¹(2y + 1)'], 'Complete the square: (y + ½)² + ¾.'), mcqP('tan⁻¹a + tan⁻¹b = constant means', ['(a + b)/(1 − ab) = constant', 'a + b = constant', 'ab = constant', 'a − b = constant'], 'Take tan of both sides.')] }),
  solQ('Misc 9', 'Q6', 'Curve through (0, π/4) with sin x cos y dx + cos x sin y dy = 0', (x, y) => -(sin(x) * cos(y)) / (cos(x) * sin(y)), (x, y) => cos(x) * cos(y), ['sec x sec y = C', 'sin x sin y = C', 'tan x + tan y = C', 'sec x + sec y = C'], { v: [-1.45, 1.45, -0.3, 2.2], ic: [0, PI / 4], icLab: '(0, π/4)', cq: { q: 'cos x cos y at (0, π/4) = ?', a: Math.SQRT1_2, show: '1/√2' }, pq: ['cos y = sec x/√2', 'cos y = cos x/√2', 'sin y = sec x/√2', 'cos y = √2 sec x'], steps: [sepS(['tan x dx + tan y dy = 0', 'sin x dx + sin y dy = 0', 'cot x dx + cot y dy = 0', 'tan x dx = tan y dy'])] }),
  solQ('Misc 9', 'Q7', 'Particular solution: (1 + e^(2x)) dy + (1 + y²) eˣ dx = 0; y = 1 when x = 0', (x, y) => -((1 + y * y) * exp(x)) / (1 + exp(2 * x)), (x, y) => atan(y) + atan(exp(x)), ['tan⁻¹y + tan⁻¹(eˣ) = C', 'tan⁻¹y − tan⁻¹(eˣ) = C', 'y + eˣ = C', 'tan⁻¹y = eˣ + C'], { v: [-3, 3, -2, 3], ic: [0, 1], icLab: '(0, 1)', cq: { q: 'C = ?', a: PI / 2, show: 'π/2' }, pq: ['tan⁻¹y + tan⁻¹(eˣ) = π/2', 'tan⁻¹y + tan⁻¹(eˣ) = π/4', 'tan⁻¹y = tan⁻¹(eˣ)', 'y = e⁻ˣ + π/2'], steps: [sepS(['dy/(1 + y²) = −eˣ dx/(1 + e^(2x))', '(1 + y²) dy = eˣ dx', 'dy = −eˣ dx', 'dy/(1 + y²) = dx/(1 + e^(2x))'])] }),
  solQ('Misc 9', 'Q8', 'Solve y e^(x/y) dx = (x e^(x/y) + y²) dy (y ≠ 0)', (x, y) => (y * exp(x / y)) / (x * exp(x / y) + y * y), (x, y) => exp(x / y) - y, ['e^(x/y) = y + C', 'e^(x/y) = x + C', 'x e^(x/y) = y + C', 'e^(y/x) = y + C'], { v: [-3, 3, 0.3, 4], seeds: [[0, 1], [-1, 2.5]], steps: [mcqP('Put x = vy. Then y dv/dy = ?', ['y e^(−v)', 'e^(−v)', 'v', 'y'], 'dx/dy = v + y e^(−v).')] }),
  solQ('Misc 9', 'Q9', 'Particular solution: (x − y)(dx + dy) = dx − dy; y = −1 when x = 0 (hint: x − y = t)', (x, y) => (1 - x + y) / (1 + x - y), (x, y) => ln(x - y) - x - y, ['x − y + log|x − y| = 2x + C', 'x + y = log|x − y| + C', 'x − y = Ce^(x + y)', 'log|x − y| = x + C'], { v: [-2, 3, -3, 2], ic: [0, -1], icLab: '(0, −1)', cq: { q: 'C = ?', a: 1, x: 't = 1 at x = 0: 1 + 0 = C.' }, pq: ['log|x − y| = x + y + 1', 'log|x − y| = x + y − 1', 'x − y = eˣ', 'log|x − y| = x − y'], steps: [mcqP('With t = x − y, dt/dx = ?', ['2t/(1 + t)', '(1 − t)/(1 + t)', 't/(1 + t)', '2t'], 'dy/dx = (1 − t)/(1 + t).')] }),
  solQ('Misc 9', 'Q10', 'Solve [e^(−2√x)/√x − y/√x] dx/dy = 1 (x ≠ 0)', (x, y) => (exp(-2 * sqrt(x)) - y) / sqrt(x), (x, y) => y * exp(2 * sqrt(x)) - 2 * sqrt(x), ['y e^(2√x) = 2√x + C', 'y e^(√x) = √x + C', 'y = e^(−2√x) + C', 'y e^(2√x) = x + C'], { v: [0.05, 4, -1, 2.5], seeds: [[1, 0.5], [0.5, -0.5]], steps: [mcqP('As dy/dx + Py = Q:', ['dy/dx + y/√x = e^(−2√x)/√x', 'dy/dx − y/√x = e^(−2√x)', 'dx/dy + x = y', 'dy/dx + y = e^(−2√x)'], 'Flip dx/dy.'), ifS(['e^(2√x)', 'e^(√x)', '√x', 'e^(−2√x)'])] }),
  solQ('Misc 9', 'Q11', 'Particular solution: dy/dx + y cot x = 4x cosec x (x ≠ 0); y = 0 when x = π/2', (x, y) => (4 * x) / sin(x) - y / tan(x), (x, y) => y * sin(x) - 2 * x * x, ['y sin x = 2x² + C', 'y sin x = 4x + C', 'y = 2x² + C', 'y cos x = 2x² + C'], { v: [0.2, 3, -4, 6], ic: [PI / 2, 0], icLab: '(π/2, 0)', fx: piLab9, cq: { q: 'C = ?', a: -(PI * PI) / 2, show: '−π²/2' }, pq: ['y sin x = 2x² − π²/2', 'y sin x = 2x² + π²/2', 'y = 2x² − π²/2', 'y sin x = 2x² − π²/4'], steps: [ifS(['sin x', 'cos x', 'cosec x', 'e^(cot x)'])] }),
  solQ('Misc 9', 'Q12', 'Particular solution: (x + 1) dy/dx = 2e⁻ʸ − 1; y = 0 when x = 0', (x, y) => (2 * exp(-y) - 1) / (x + 1), (x, y) => (2 - exp(y)) * (x + 1), ['(2 − eʸ)(x + 1) = C', '(2 + eʸ)(x + 1) = C', 'eʸ = x + C', 'y = log|x + 1| + C'], { v: [-0.9, 3, -2, 1.2], ic: [0, 0], icLab: '(0, 0)', cq: { q: 'C = ?', a: 1 }, pq: ['y = log|(2x + 1)/(x + 1)|', 'y = log|(x + 1)/(2x + 1)|', 'y = log|x + 1|', 'y = log|2x + 1|'], steps: [sepS(['eʸ dy/(2 − eʸ) = dx/(x + 1)', 'dy/(2e⁻ʸ) = dx', 'eʸ dy = dx/(x + 1)', 'dy = (2e⁻ʸ − 1) dx'], 'Multiply top and bottom by eʸ.')] }),
  solQ('Misc 9', 'Q13', 'The general solution of (y dx − x dy)/y = 0 is (A) xy = C (B) x = Cy² (C) y = Cx (D) y = Cx²', (x, y) => y / x, (x, y) => y / x, ['y = Cx', 'xy = C', 'x = Cy²', 'y = Cx²'], { v: [-4, 4, -3, 3], post: [mcqP('Answer', ['(C)', '(A)', '(B)', '(D)'], 'dy/y = dx/x.')] }),
  boardQ('Misc 9', 'Q14', 'The general solution of dx/dy + P₁x = Q₁ is (A) y e^(∫P₁dy) = ∫(Q₁e^(∫P₁dy))dy + C (B) y e^(∫P₁dx) = ∫(Q₁e^(∫P₁dx))dx + C (C) x e^(∫P₁dy) = ∫(Q₁e^(∫P₁dy))dy + C (D) x e^(∫P₁dx) = ∫(Q₁e^(∫P₁dx))dx + C', [mcqP('Answer', ['(C)', '(A)', '(B)', '(D)'], 'The unknown is x, everything is integrated in y.')], '(C)'),
  solQ('Misc 9', 'Q15', 'The general solution of eˣ dy + (y eˣ + 2x) dx = 0 is (A) x eʸ + x² = C (B) x eʸ + y² = C (C) y eˣ + x² = C (D) y eʸ + x² = C', (x, y) => -(y * exp(x) + 2 * x) / exp(x), (x, y) => y * exp(x) + x * x, ['y eˣ + x² = C', 'x eʸ + x² = C', 'x eʸ + y² = C', 'y eʸ + x² = C'], { v: [-3, 3, -3, 3], steps: [mcqP('eˣ dy + y eˣ dx is', ['d(y eˣ)', 'd(x eʸ)', 'd(eˣ⁺ʸ)', 'not exact'], 'Product rule backwards.')], post: [mcqP('Answer', ['(C)', '(A)', '(B)', '(D)'], 'd(y eˣ) + d(x²) = 0.')] }),
];
